### ISSUE TITLE
ASAN: recover option

### ISSUE THREAD

**Issue by keitee** [google/sanitizers#1011]
Hi,

Please direct me if there were topics already addressed this. 

I like to have ASAN to continue its reporting while a program runs rather than aborting it. So have looked couple of options. 

1.	recover option. 
Have tried GCC 630 and Clang and have found that both do not instrument code in output and effectively get “not-sanitized” output. Not sure it’s expected but that is what I see. No aborting but no ASAN as well. Please correct me if I am wrong.

2.	conditional compilation.
Not an option since not feasible to do in huge code bace and third party codes. 

3.	Suppressing list. 
Looks like what I’m after but it’s only for Clang. However, project is based on GCC and am afraid of many unknowns if moves it to Clang. 
So not an option. 

So question is what’s the best option to try and to use to meet this purpose? Please lead me in the right direction. Only option is to move to Clang? 

Many thanks

**Comment by yugr** [comment]
> recover option.

This is your best bet. Could you provide a repro-case which shows how it fails?

> Suppressing list

Note that this isn't supported by GCC version of Asan.

**Comment by keitee** [comment]
Thanks for the reply. Please find following snippet which is out when use recover option and as far as I see, there is no sanitised code compared to one from without it. That on GCC 630 and X86 32.

```
static char gclientname[] = "_DLRH";

void call_gbo_1()
{
  char buffer[10];
  memcpy(buffer, gclientname, 8);
  return;
}

00000786 <call_gbo_1>:
call_gbo_1():
/home/kyoupark/git/kb/asan/gbo_recover.c:143
 786:	55                   	push   ebp
 787:	89 e5                	mov    ebp,esp
 789:	83 ec 10             	sub    esp,0x10
 78c:	e8 45 01 00 00       	call   8d6 <__x86.get_pc_thunk.ax>
 791:	05 6f 18 00 00       	add    eax,0x186f
/home/kyoupark/git/kb/asan/gbo_recover.c:145
 796:	8b 90 2c 00 00 00    	mov    edx,DWORD PTR [eax+0x2c]
 79c:	8b 80 28 00 00 00    	mov    eax,DWORD PTR [eax+0x28]
 7a2:	89 45 f6             	mov    DWORD PTR [ebp-0xa],eax
 7a5:	89 55 fa             	mov    DWORD PTR [ebp-0x6],edx
/home/kyoupark/git/kb/asan/gbo_recover.c:146
 7a8:	90                   	nop
/home/kyoupark/git/kb/asan/gbo_recover.c:147
 7a9:	c9                   	leave  
 7aa:	c3                   	ret    
```

**Comment by yugr** [comment]
You are hit by an issue from [FAQ]:
```
Q: Why didn't ASan report an obviously invalid memory access in my code?

A1: If your errors is too obvious, compiler might have already optimized it out
    by the time Asan runs.
```

**Comment by keitee** [comment]
I see. However, the same code dose make sanitized output with the same
compile option other than options for ASan. Then would be okay to try
examples in Asan wiki which should be complicated enough to be sanitized?



2018년 10월 19일 (금) 오후 3:47, Yury Gribov <notifications@github.com>님이 작성:

**Comment by chefmax** [comment]
How do you compile the program? Do you use `-fsanitize=address -fsanitize-recover=address`?

**Comment by keitee** [comment]
Have checked that again and only use `-fsanitize-recover=address`

**Comment by chefmax** [comment]
That's why asan is disabled -- you need `-fsanitize=address -fsanitize-recover=address` to make it work properly.

**Comment by keitee** [comment]
You're right and many thanks @chefmax for your help.

**Comment by ParikaGoel** [comment]
Hello,

I am the same issue right now (with using the recover option).

So, the problem is that my compiler does not recognize the recover option.

I am using below flags:

ADD_COMPILE_OPTIONS(-fsanitize=address -fno-omit-frame-pointer)
SET(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address")

When I compile, I get below error:
cc1plus: error: -fsanitize-recover=address is not supported

My gcc version is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

PS: I think that might be this recover option is added in future versions of gcc but I can not find which version 
Since I am having exactly same issue, didn't open a new one

**Comment by chefmax** [comment]
You need GCC 6+.

**Comment by ParikaGoel** [comment]
@chefmax  Thank you for prompt reply.

And what about clang...what clang version is required for this ?

**Comment by chefmax** [comment]
In clang 3.8 this should be available, I guess...
