### ISSUE TITLE
cxxflags: unknown option: -fsanitize=address

### ISSUE THREAD

**Issue by BingyuLiu** [google/sanitizers#1015]
could you please help on this error?

 **cxxflags: unknown option: -fsanitize=address  -I/home/johnliu/dev/Build-omi/omi/Unix/output1/include -I../.. -I../../common  mkdep.cpp
g++: error: cxxflags:: No such file or directory
g++: error: unknown: No such file or directory
g++: error: option:: No such file or directory**

the gcc I used is :
**johnliu@osd64-ub18-02:~/dev/Build-omi/omi/Unix$ gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.**

**Comment by kcc** [comment]
Looks like you've put several options in `""` or some such. 
If you still think this is a compiler bug, please provide the exact compiler invocation command line
