### ISSUE TITLE
[Docs][TSan] Update docs with regard to `detect_deadlocks` default value

### ISSUE THREAD

**Issue by yln** [google/sanitizers#1033]
In TSan deadlock detection is enabled by default for a while now, but the docs are outdated and don't reflect that.
I tried to create a PR against the wiki/github-pages of this repository, but was unsuccessful in doing so. Here is a diff to update the docs: [docs-detect-deadlocks.diff.txt](https://github.com/google/sanitizers/files/2692348/docs-detect-deadlocks.diff.txt)

Relevant: https://reviews.llvm.org/D55846

**Comment by kcc** [comment]
Yea, PR's don't work for wiki, for no apparent reason... 
Anyway, thanks! Applied the change.
