### ISSUE TITLE
How to use simultaneously Asan and Msan? 

### ISSUE THREAD

**Issue by LifeIsStrange** [google/sanitizers#1039]
I try to replace Valgrind with Asan and Msan.
While they both work individually, I fail to make them work simultaneously.
How can I achieve this, with which combination of flags/Env?
(I'm on gcc)

**Comment by vitalybuka** [comment]
That's impossible. Instrumentations are not designed to work together and there are no plans to support it because of potential complexity of such implementation.

**Comment by vitalybuka** [comment]
Actually I am not aware of state of GCC, my previous comment is relevant to clang.
However both, clang and GCC, use same msan/asan runtime libraries, which are also mutually exclusive and cant be linked together.

**Comment by kcc** [comment]
GCC doesn't have msan at all.

**Comment by LifeIsStrange** [comment]
@vitalybuka Thanks for the fast answsering. I would like to say that google sanitizers can't compete with valgrind as long as Asan and Msan can't be used together. It's sad as both sanitizers are individually superior to valgrind. This should be the #1 priority by far. 

Naive Idea and not great performance wise but could enable asan and msan to work together without changing a lot of code:
to bypass all eventual incompatibilities with asan and msan, when you would run a binary, auto launching two different processes (thus different memory) of the binary. one for asan, one for msan. That is ths binary would run twice at the same time, one process per sanitizer (would also allow compatibility with other sanitizers like UB, Tsan or even asan and valgrind at the same time.

but to work, the terminal input would need to be copied too and piped to each processes.

**Comment by LifeIsStrange** [comment]
btw, is there a table of current compatibility between sanitizers ? for example i've been using asan together with leaksanitizer and they work well.

**Comment by ramosian-glider** [comment]
There's a reason for not using ASan and MSan together. ASan adds redzones to every local variable, global and heap allocation, which already adds quite a bit of virtual memory pressure. In fact there are applications that cannot even tolerate that. In addition ASan uses 1/8 of the available address space (which adds roughly 1/8 of the memory your app was already using).
Now, on top of that MSan needs to double or triple the amount of memory used by the program in order to track the shadow and origins of all memory in the program, including the redzones (which MSan actually doesn't need).
I'm not mentioning the slowdown caused by the instrumentation code piling up. Most certainly your program will be just timing out.

Regarding the table of compatibility, I would say it only makes sense to run ASan together with LSan. Other tools are designed to run separately.

**Comment by kcc** [comment]
asan+lsan+ubsan is fine, the rest should run separately.

**Comment by LifeIsStrange** [comment]
@ramosian-glider hi friendly ping
I have nothing really new to say but I just wanted to reinstate the importance of this issue.
I strongly believe that most developers/projects are simply NOT using msan at all... Because Asan is generally more useful and since they can't run both..
Invalid uninitialized reads errors are tricky/silent and the end result is that the whole open source ecosystem probably has regressed since they migrated from valgrind to Asan, especially for non time critical/large scale projects.
I understand your technical arguments about msan incurring a slowdown/ doubling/tripling memory use. Thats why msan should not be bundled with asan by default. But when bundled i believe it would not be slower than valgrind, and if it were it would still have benefits (log style familiarity, easier to setup for asan projects)
So when you get the time, i truly believe it would improve the quality of many software libraries at simply never using msan is not a solution.
I thought once about making a makefile that periodically (e.g one every 2 build use msan, asan otherwise) but I think this idea has not and will neher caught up in the open source world.
Feel free to answer that you have not the time to do this or that the end result would be order of magnitude slower than valgrind.

**Comment by ydroneaud** [comment]
> There's a reason for not using ASan and MSan together. [...] MSan needs to double or triple the amount of memory used by the program in order to track the shadow and origins of all memory in the program, including the redzones (which MSan actually doesn't need). I'm not mentioning the slowdown caused by the instrumentation code piling up. Most certainly your program will be just timing out.

Given the instrumentations and metadata involved, I agree we should not advocate for running ASan on top of MSan nor the other way around.

I would rather dream of a combined sanitizer which does both (MAsan). It's fantasy, as it would requires maintaining the same features in two sanitizers, to keep ASan and MSan alive + develop the combined one MASan.
