### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by RootUp** [google/sanitizers#1040]
Hi Team, 

1. clang++ pch.cpp -fsanitize=address
```
pch.cpp:1:10: fatal error: 'pch.h' file not found
#include "pch.h"
         ^~~~~~~
1 error generated.
```

I just want to compile `pch.cpp` in this case but looks like pch.h file is also required, Could someone suggest what should, I do in such case.

**Comment by kcc** [comment]
this question doesn't seem to be related to sanitizers.
