### ISSUE TITLE
unknown crash in libasan on PPC64

### ISSUE THREAD

**Issue by sachinpunadikar** [google/sanitizers#1042]
Hello,
I am using below command line to start my program (NFS Ganesha) on PPC64 (RHEL 7.3):
ASAN_OPTIONS=alloc_dealloc_mismatch=true:print_stats=true:atexit=true:start_deactivated=true:print_cmdline=true:quarantine_size_mb=1:detect_leaks=true:abort_on_error=true:disable_coredump=false:verbosity=2:log_path=/tmp/asan.log:log_exe_name=1 /usr/bin/ganesha.nfsd  -L /var/log/ganesha.log -f /etc/ganesha/ganesha.conf -N NIV_EVENT

Below crash was reported:
  1 =================================================================
  2 ==52954== ERROR: AddressSanitizer: unknown-crash on address 0x3fffe9fa6300 at pc 0x3fff8438990c     bp 0x3fffe9fa6120 sp 0x3fffe9fa6190
  3 WRITE of size 2432 at 0x3fffe9fa6300 thread T0
  4     #0 0x3fff84389908 (/usr/lib64/libasan.so.0.0.0+0x19908)
  5     #1 0x3fff838dd18c (/usr/lib64/libgcc_s-4.8.5-20150702.so.1+0xd18c)
  6     #2 0x3fff838df448 (/usr/lib64/libgcc_s-4.8.5-20150702.so.1+0xf448)
  7     #3 0x3fff8439e17c (/usr/lib64/libasan.so.0.0.0+0x2e17c)
  8     #4 0x3fff84393128 (/usr/lib64/libasan.so.0.0.0+0x23128)
  9     #5 0x3fff843931ec (/usr/lib64/libasan.so.0.0.0+0x231ec)
 10     #6 0x103f2938 (/usr/bin/ganesha.nfsd+0x103f2938)
 11 ==52954== AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_report.cc:250 "((nam    e_end)) != (0)" (0x0, 0x0)
 12     #0 0x3fff8438d438 (/usr/lib64/libasan.so.0.0.0+0x1d438)
 13     #1 0x3fff84399d18 (/usr/lib64/libasan.so.0.0.0+0x29d18)
 14     #2 0x3fff8439652c (/usr/lib64/libasan.so.0.0.0+0x2652c)
 15     #3 0x3fff84396798 (/usr/lib64/libasan.so.0.0.0+0x26798)
 16     #4 0x3fff84397818 (/usr/lib64/libasan.so.0.0.0+0x27818)
 17     #5 0x3fff84389924 (/usr/lib64/libasan.so.0.0.0+0x19924)
 18     #6 0x3fff838dd18c (/usr/lib64/libgcc_s-4.8.5-20150702.so.1+0xd18c)
 19     #7 0x3fff838df448 (/usr/lib64/libgcc_s-4.8.5-20150702.so.1+0xf448)
 20     #8 0x3fff8439e17c (/usr/lib64/libasan.so.0.0.0+0x2e17c)
 21     #9 0x3fff84393128 (/usr/lib64/libasan.so.0.0.0+0x23128)
 22     #10 0x3fff843931ec (/usr/lib64/libasan.so.0.0.0+0x231ec)
 23     #11 0x103f2938 (/usr/bin/ganesha.nfsd+0x103f2938)

May I know what is wrong here ? Is there any work-around ?

**Comment by kcc** [comment]
I'm afraid our team has zero expertise in PPC. 
You may want to ask someone who maintains the PPC port of GCC and ASAN.
