### ISSUE TITLE
Misleading wiki/AddressSanitizerLeakSanitizer

### ISSUE THREAD

**Issue by tim-janik** [google/sanitizers#1047]
The wiki page https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer states:

> If you want to run an ASan-instrumented program without leak detection, you can
> pass detect_leaks=0 in the ASAN_OPTIONS environment variable.

Which doesn't work. What works for disabling lsan however is:

LSAN_OPTIONS=detect_leaks=0

**Comment by kcc** [comment]
works for me. 
```
% cat leak.cc 
int *p = new int;
int main() {
  p = nullptr;  // leaked
}
% clang++ -fsanitize=address leak.cc && ./a.out 2>&1 | grep ERROR 
==246907==ERROR: LeakSanitizer: detected memory leaks
% ASAN_OPTIONS=detect_leaks=0 ./a.out 
% 
```

If something still doesn't work for you, please provide more details (reproducer, versions of the OS, compiler, etc)

**Comment by tim-janik** [comment]
Interesting...
Thanks for the quick response, I can reproduce your example under bionic. 
I've seen the above bug inside a dockerized CI build which is a bit involved,
I'll try to reproduce it and then get back with versions.
