### ISSUE TITLE
Dashboard does not indicate when a bot is offline

### ISSUE THREAD

**Issue by vlad902** [google/sanitizers#1054]
http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-autoconf and http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-bootstrap-msan were down for a week (buildbot7 and buildbot8 were both shut-down) and it wasn't easy to see that from the dashboard as it was green before it went down. Add a visible warning message when the last bot result is more than ~6-8 hours old.

**Comment by vitalybuka** [comment]
Maybe different timestamp color (usually purple for infrastructure errors) if build is older than threshold?
Now it's always white.
