### ISSUE TITLE
verify_asan_link_order flag does not work

### ISSUE THREAD

**Issue by vwvw** [google/sanitizers#1066]
I need to run ASAN on a binary for which I have to use LD_PRELOAD a shared library. 
I tried to set verify_asan_link_order via the ASAN_OPTIONS environment variable without success.

```
ASAN_OPTIONS=verify_asan_link_order=0 LD_PRELOAD="lib.so" ./program
```
results

```
==24101==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.==24101==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

Did I misunderstood the role of the verify_asan_link_order flag ?

**Comment by yugr** [comment]
Most likely your version of Asan is too old and does not know this flag. Can you run with `ASAN_OPTIONS=verbosity=2`? If that's the case you can still remove the load order check manually, bt editing the binary (search for "BRUTAL HACK" in https://github.com/yugr/debian_pkg_test/tree/master/examples/Asan#how-to-set-up-a-chroot).

**Comment by vwvw** [comment]
Compiling and using the latest version of llvm did the trick. The flag is indeed not registered.
