### ISSUE TITLE
Reference -fsanitize-recover=address in connection with halt_on_error=0

### ISSUE THREAD

**Issue by dilyanpalauzov** [google/sanitizers#1084]
https://github.com/google/sanitizers/wiki/AddressSanitizerFlags says “halt_on_error | is enabled by default  | Crash the program after printing the first error report (WARNING: USE AT YOUR OWN RISK!)”.

https://github.com/google/sanitizers/wiki/AddressSanitizer says “
* Q: Can AddressSanitizer continue running after reporting first error?

* A: Yes it can, AddressSanitizer has recently got continue-after-error mode. This is somewhat experimental so may not yet be as reliable as default setting (and not as timely supported). Also keep in mind that errors after the first one may actually be spurious. To enable continue-after-error, compile with -fsanitize-recover=address and then run your code with ASAN_OPTIONS=halt_on_error=0.
”

Extend the former page to reference, that halt_on_error can only be set to FALSE/0, when code is compiled with -fsanitize-recover=address.

**Comment by chefmax** [comment]
Updated info on https://github.com/google/sanitizers/wiki/AddressSanitizerFlags, thanks!
