### ISSUE TITLE
Combining gcc and clang for AddressSanitizer

### ISSUE THREAD

**Issue by dilyanpalauzov** [google/sanitizers#1085]
Where is it written, whether I can compile some DSOs with gcc, others with CLANG, all using `-fsanitize=address` and then run them in the same program?

**Comment by chefmax** [comment]
Good catch, thanks! I've updated FAQ entry (https://github.com/google/sanitizers/wiki/AddressSanitizer) with this info:

* Q: Can I mix code instrumented by Clang with code instrumented by GCC? Or can I at least compile code with Clang and link against GCC ASan runtime and vice versa?

* A: No, you cannot, Clang and GCC have completely incompatible ASan implementations, you cannot mix them in any way.
