### ISSUE TITLE
In Fedora 30 ps hangs using address sanitizer

### ISSUE THREAD

**Issue by davidjmccann** [google/sanitizers#1096]
I'm using Fedora 30 in a docker container running on a Ubuntu 16.04 or 18.04 host. The following command hangs:
LD_PRELOAD=/lib64/libasan.so.5.0.0 ps

If I take off the LD_PRELOAD, then the command completes successfully. The same works using Fedora 29.

An strace always shows it in the following:
futex(0x7f19408a0be8, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 2, NULL, FUTEX_BITSET_MATCH_ANY

**Comment by yugr** [comment]
Can you reproduce this issue with Clang? Maintainers here normally ask to file GCC-specific bugs in https://gcc.gnu.org/bugzilla/

**Comment by davidjmccann** [comment]
I tried building "ps" using gcc, and I can't get it to exhibit the same problem. So I think it unlikely I can get it to fail using clang. I'll raise a bug at the link you provided, thanks.
