### ISSUE TITLE
How to use TSan to reproduce data race cases

### ISSUE THREAD

**Issue by pratikbhd** [google/sanitizers#1107]
I'm not sure if this is the best place to ask this. 
I want to test **TSan** on a number of data race bugs on v8 and chromium using previously posted bug reports. The reason I am doing this is that I am working on a research to implement a data race detector for dynamic code such as the JIT compiler in v8. Before starting, I want to make sure to what extent TSan already solve this problem.

I have not found any documentation that says how TSan can be used to test chromium and v8 which is what I want to do. It would be great if I could be pointed to the direction that I should be looking at. Thanks!

**Comment by dvyukov** [comment]
This discussion has already started at https://groups.google.com/forum/#!topic/thread-sanitizer/UKV4ZkK333U
Let's keep it in one place.

**Comment by pratikbhd** [comment]
Oh, I did not know that question had already been answered on the forum. I sent the question through email and thought I'd receive the reply as an email as well. Thanks for directing me to the thread.
