### ISSUE TITLE
It is better to change report_objects flag from bool to int

### ISSUE THREAD

**Issue by pangqingyuan1991** [google/sanitizers#1113]
Sometimes we would like to get the address of leak objects. But if the leak number is above thousands, it is not necessary to print all of them. I think the flag report_objects can be a number, which indicates how much leak objects' address (from the same backtrace) will be printed at most.

**Comment by kcc** [comment]
I am reluctant to add a feature that will be rarely used and that has a simple other solution (e.g. use `head`)

**Comment by pangqingyuan1991** [comment]
If there are multiple backtraces, head command can only show first one.
