### ISSUE TITLE
The Asan cannot report stack-buffer-overflow error.

### ISSUE THREAD

**Issue by hccya** [google/sanitizers#1119]
$ cat testasan.cc
#include <stdio.h>
#include <string.h>
 
int main (int argc, char **argv)
{
   const char *src = "hccya"; 
   return src[strlen(src) + 2];
}

 I thought Asan would report  a stack-buffer-overflow error, but report nothing. It is strange.....

**Comment by hccya** [comment]
@ramosian-glider

**Comment by hccya** [comment]
The follow is objdump information.

0000000000000580 <.text>:
 580:	910003e0 	mov	x0, sp
 584:	14000001 	b	588 <__asan_version_mismatch_check_v8@plt+0x18>
 588:	d100c3ff 	sub	sp, sp, #0x30
 58c:	a9027bfd 	stp	x29, x30, [sp,#32]
 590:	910083fd 	add	x29, sp, #0x20
 594:	f00000e8 	adrp	x8, 1f000 <__asan_version_mismatch_check_v8@plt+0x1ea90>
 598:	91350108 	add	x8, x8, #0xd40
 59c:	f00000e9 	adrp	x9, 1f000 <__asan_version_mismatch_check_v8@plt+0x1ea90>
 5a0:	91356129 	add	x9, x9, #0xd58
 5a4:	f00000ea 	adrp	x10, 1f000 <__asan_version_mismatch_check_v8@plt+0x1ea90>
 5a8:	9e670100 	fmov	d0, x8
 5ac:	9135a14a 	add	x10, x10, #0xd68
 5b0:	4e181d20 	mov	v0.d[1], x9
 5b4:	3d8003e0 	str	q0, [sp]
 5b8:	f9000bea 	str	x10, [sp,#16]
 5bc:	f00000e2 	adrp	x2, 1f000 <__asan_version_mismatch_check_v8@plt+0x1ea90>
 5c0:	f947e042 	ldr	x2, [x2,#4032]
 5c4:	910003e3 	mov	x3, sp
 5c8:	aa1f03e1 	mov	x1, xzr
 5cc:	97ffffdd 	bl	540 <__libc_init@plt>
 5d0:	90000103 	adrp	x3, 20000 <__bss_start@@Base>
 5d4:	91000063 	add	x3, x3, #0x0
 5d8:	17ffffde 	b	550 <__register_atfork@plt>
 5dc:	2a1f03e0 	mov	w0, wzr
 5e0:	d65f03c0 	ret
 5e4:	f81f0ffe 	str	x30, [sp,#-16]!
 5e8:	97ffffde 	bl	560 <__asan_init@plt>
 5ec:	97ffffe1 	bl	570 <__asan_version_mismatch_check_v8@plt>
 5f0:	f84107fe 	ldr	x30, [sp],#16
 5f4:	d65f03c0 	ret

**Comment by kcc** [comment]
Works for me: 

```
clang -g  -fsanitize=address testasan.cc  && ./a.out 
=================================================================
==118468==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000004d6bc7 at pc 0x0000004c478d bp 0x7ffd05a9a900 sp 0x7ffd05a9a8f8
READ of size 1 at 0x0000004d6bc7 thread T0
    #0 0x4c478c in main  ... testasan.cc:7:8
0x0000004d6bc7 is located 1 bytes to the right of global variable '<string literal>' defined in 'testasan.cc:6:19' (0x4d6bc0) of size 6
  '<string literal>' is ascii string 'hccya'
```

Of course, it's a global-buffer-overflow, not stack-buffer-overflow. 

If it still doesn't work for you, what's the version of your compiler?

**Comment by hccya** [comment]
I test it on Android P.

**Comment by kcc** [comment]
On android, the detection of global-buffer-overflows is disabled by default. 
@eugenis right?

**Comment by eugenis** [comment]
Yes, in platform builds, b/137037229.
