### ISSUE TITLE
UBSAN is not crashing my app 

### ISSUE THREAD

**Issue by sarora5** [google/sanitizers#1136]
According to clang documentation "https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks"
"-fno-sanitize-recover=...: print a verbose error report and exit the program;" 

2 issues: 

1) First I tried with "-fsanitize=null" option for NULL ptr access code but my app is not crashing, it is just spitting out error message shown below , then i tried with "-fno-sanitize-recover=null" i did not see any error message with this and code just runs.

Error Message: 
```
08-21 08:51:28.226  8684  8684 I wrap.sh :/apps/samples/crashy/libcrashy.cpp:86:3: runtime error: load of null pointer of type 'int'                                   │
08-21 08:51:28.232  8684  8684 I wrap.sh :     #0 0xb1a5fd49  (/data/app/com.xxx.crashy-jxMDrGyUrDu33vadhlRpHQ==/lib/x86/libcrashy.so+0x3d49)                               │
08-21 08:51:28.232  8684  8684 I wrap.sh :     #1 0xb5da886a  (/data/app/com.xxx.crashy-jxMDrGyUrDu33vadhlRpHQ==/oat/x86/base.odex+0x2086a)                                 │
08-21 08:51:28.240  8684  8684 I wrap.sh :     #2 0xc5c0307f  (<unknown module>)                                                                                                 │
08-21 08:51:28.249  8684  8684 I wrap.sh :     #3 0xff978f07  ([stack]+0x7f9f07)
```

2) After first error if same NULL Ptr access code  executes again, UBSAN does not even complains.

**Comment by eugenis** [comment]
On Wed, Aug 21, 2019 at 9:14 AM sarora5 <notifications@github.com> wrote:

> According to clang documentation "
> https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks"
> "-fno-sanitize-recover=...: print a verbose error report and exit the
> program;"
>
> 2 issues:
>
>    1. I tried with this option for NULL ptr access code but my app is not
>    crashing, it is just spitting out error message
>
> This should not be happening. How are you building the app? Could you try
extracting the compilation command line for the source file in question,
and check that there is no -fsanitize-recover argument after the
-fno-sanitizer-recover one.


>
>    1. After first error if same NULL Ptr access code executes again,
>    UBSAN does not even complains.
>
> That's intentional. If a bad operation was in a loop, you would not want
thousands of identical reports printed out. Future reports from the same PC
address are suppressed.

**Comment by sarora5** [comment]
I am not seeing any fsanitize-recover at all in compilation flags for my lib.

**Comment by sarora5** [comment]
Which function should iubsan instrumention insert to crash the app ?

**Comment by eugenis** [comment]
You can try it with a small test case, something like int f(int x) { return
x + 1; }
With -fsanitize=undefined -c -fno-sanitize-recover=all, clang generates a
call to
  __ubsan_handle_add_overflow_abort
and without the -fno-sanitize-recover flag, it generates a call to
  __ubsan_handle_add_overflow

**Comment by sarora5** [comment]
#resolved after providing option ""-fno-sanitize-recover=all",
