### ISSUE TITLE
getline() leak not detected while calling a legit `free()` causes a crash

### ISSUE THREAD

**Issue by afjoseph** [google/sanitizers#1141]
Hey

Thanks for the great project!

I'm observing a memory leak while running ASAN on Android (I tried API 18, 22, 25, and 28) and nothing was reported. The leak is from not freeing a `getline()` usage.

[`getline()`](https://linux.die.net/man/3/getline) in Linux, FreeBSD and OpenBSD (what Bionic, Android's libc, is based on) allocates memory on the first parameter if NULL is supplied, which means that it should be free-d after usage. The following memory leak was observed and never reported by ASAN:

```
extern "C" JNIEXPORT void JNICALL
Java_com_helloworld_getline_1repro_MainActivity_stringFromJNI(
        JNIEnv* env,
        jobject /* this */) {
    FILE* fp = fopen("/proc/net/tcp", "r"); // Just an example file. Nothing special here
    if (fp == 0) {
        LOGE("bad stuff");
        return;
    }
    
    ssize_t read = 0;
    char *line = 0;
    size_t len = 0;
    while ( (read = getline(&line, &len, fp)) != -1) {
        LOGD("line: %s", line);
    }

    /* This is necessary since getline() uses
     * realloc() which allocates memory, if line == NULL
     * But ASAN WILL CRASH HERE if this line was uncommented
     *
     * if (line) {
     *  free(line);
     *}
    **/

    LOGD("Done without freeing 'line'");
}

```

I basically followed this guide to setup [ASAN on Android](https://developer.android.com/ndk/guides/asan). I do know it is working fine since calling `free()` twice on a buffer outputs an ASAN stack trace.

P.S: After running the above snippet a few times, I added a `malloc()` that is never freed and noticed a similar attitude: it is never observed by ASAN. Is this also an expected behaviour? Does ASAN only react on bad memory access rather than allocation? This is not the behaviour I saw when I ran the same code snippet above on a non-Android device (my Arch Linux box).

**Comment by afjoseph** [comment]
Thanks for the answer. I might've not been very clear in my question. I updated the code snippet and description. Regardless of if LeakSanitizer exists or not, `getline()` still creates a buffer that should be free-d but ASAN will crash with a stack trace if `free()` is used.

**Comment by unidual** [comment]
Quick guess: mismatch between an non-instrumented `malloc()` in `getline()` and the instrumented `free()` in your code.

Did you follow this step:
* Add the ASan runtime library to your app module's jniLibs.

**Comment by eugenis** [comment]
What's your Android version (not application API level, but the platform build number)?
Could you paste ASan stack trace with uncommented free() here?
