### ISSUE TITLE
issues in sancov basic block pruning 

### ISSUE THREAD

**Issue by abenkhadra** [google/sanitizers#1151]
While experimenting with the basic block pruning scheme implemented in `sancov` (current state  https://github.com/llvm-mirror/llvm/commit/f6cb5093853722a6d9f059f4e86435aa89e7491b) I noticed that the current scheme can in particular situations (1) lose precision and (2) add redundant instrumentation.

For example, consider the following CFG instances. Basic blocks that would be instrumented by `sancov` are highlightend. 

In the first instance, `A` is a full dominator while `C` is a full postdominator with more than one predecessor. Both will not be instrumented which mean that coverage information for the path `A`->`C` is lost.

In the second instance, `sancov` would make a suboptimal choice by instrumenting `D`. An optimal choice, which does not incur loss in precision, would be to instrument `E` in addition to either `A` or `C`. Note that covering `E` implies that both `B` and `D` are also covered. 

Did I understand this correctly? Any thoughts? 
![sancov-issues](https://user-images.githubusercontent.com/11852302/66741766-88316180-ee76-11e9-8649-2165be7f1447.png)

**Comment by kcc** [comment]
I believe that (1) is addressed by https://clang.llvm.org/docs/SanitizerCoverage.html#edge-coverage
I.e. when using the "edge" instrumentation mode, which is the default, the sancov pass will not see CFG like this. 

(2) is not very concerning as it's a loss of optimization, but not a loss of signal. 
Unless you think it's a major missing optimizations, I'd ignore it for the sake of simplicity.

**Comment by abenkhadra** [comment]
Thanks for the clarifications. So possible loss in signal is remedied by splitting critical edges with dummy blocks in edge coverage. 

Actually, I can report from my experience implementing probe pruning in binary-level instrumentation. In this setting, both dummy blocks and redundant instrumentation points would complicate binary-level instrumentation. We are willing to pay more in algorithm complexity to reduce instrumentation complexity. 

One data point I can provide is from `libopencv_core`. The binary has  
296567 basic blocks in 10455 functions. The `sancov` probe pruning algorithm reports that instrumentation points are needed in 42% of the basic blocks. Only 1.2% of the instrumentation points is redundant. Therefore, the main issue is the loss of signal which can be (partly?) solved by ensuring that the source or destination of critical edge is instrumented.
