### ISSUE TITLE
Strcpy() function in asan   misreport   error

### ISSUE THREAD

**Issue by wdfcc** [google/sanitizers#1156]
here is  the code:
#include <stdio.h>
#include <string.h>
int main()
{
	char buffer[64]={0};
	memcpy(buffer,"0 12",strlen("0 12"));
	char *p1=&buffer[2];
	strcpy(buffer,p1);
	return 0;
}

**Comment by yugr** [comment]
`Strcpy` [does not allow](https://linux.die.net/man/3/strcpy) overlap of source and destination buffers.

**Comment by wdfcc** [comment]
thank u
