### ISSUE TITLE
libasan_preinit.o: No such file: No such file or directory

### ISSUE THREAD

**Issue by mahmud-antor** [google/sanitizers#1159]
libubsan-7.3.1-5.16.el6.x86_64
libubsan1-8.3.1-3.1.el6.x86_64
libasan4-7.3.1-5.15.el6.x86_64
devtoolset-6-libasan-devel-6.3.1-3.1.el6.x86_64
libasan3-6.3.1-3.1.el6.x86_64

I have this packages installed for OS -
Name : kernel
Arch : x86_64
Version : 2.6.32
Release : 504.el6
Size : 124 M
Repo : installed
From repo : anaconda-CentOS-201410241409.x86_64
Summary : The Linux kernel
URL : http://www.kernel.org/
License : GPLv2
Description : The kernel package contains the Linux kernel (vmlinuz), the core of any
: Linux operating system. The kernel handles the basic functions
: of the operating system: memory allocation, process allocation, device
: input and output, etc

but every time I try to use "gcc -g -fsanitize=address test.c -o test1" I face this error

/usr/bin/ld: libasan_preinit.o: No such file: No such file or directory
collect2: error: ld returned 1 exit status

Can anyone help me please! TIA

**Comment by yugr** [comment]
@mahmud-antor You should probly redirect this question to distro maintainer to find which package includes `libasan_preinit.o`. BTW it indeed makes sense to put this file into `libasan4` so you may suggest them that.

**Comment by mahmud-antor** [comment]
I have solved this issue! This was a stupid mistake on my part. My version of GCC was older. As I have upgraded the GCC version. The problem Ended.

Thanks....
