### ISSUE TITLE
AddressSanitizer not finding an obvious memory leak after changing a printf format

### ISSUE THREAD

**Issue by mmattb** [google/sanitizers#1162]
Cross-posted from SO:
https://stackoverflow.com/questions/58721775/addresssanitizer-not-finding-an-obvious-leak-after-changing-printf

I'm scratching my head trying to figure out why ASAN isn't picking up on a simple memory leak. valgrind finds it just fine. Help?

Example that ASAN *does* find.
```
#include <stdlib.h>
#include <stdio.h>

void blah(void)
{
        int *some_int = malloc(sizeof(int));
        *some_int = 1;
        printf("hello %p\n", some_int);
        // some_int is lost here
}

int main()
{
        blah();
        return 0;
}

mbryan@remotedev-mbryan:~/git/mbryan/onefs$ clang -fsanitize=address -O0 q.c
mbryan@remotedev-mbryan:~/git/mbryan/onefs$ ./a.out
hello 0x602000000010

=================================================================
==10751==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4d9bd0 in malloc (/ifs/home/mbryan/git/mbryan/onefs/a.out+0x4d9bd0)
    #1 0x5120f3 in blah (/ifs/home/mbryan/git/mbryan/onefs/a.out+0x5120f3)
    #2 0x512183 in main (/ifs/home/mbryan/git/mbryan/onefs/a.out+0x512183)
    #3 0x7f3515000b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

So far so good. Now print the value instead of the pointer:
```
#include <stdlib.h>
#include <stdio.h>

void blah(void)
{
        int *some_int = malloc(sizeof(int));
        *some_int = 1;
        printf("hello %d\n", *some_int);  // <---------------
}

int main()
{
        blah();
        return 0;
}

mbryan@remotedev-mbryan:~/git/mbryan/onefs$ clang -fsanitize=address -O0 q.c
mbryan@remotedev-mbryan:~/git/mbryan/onefs$ ./a.out
hello 1
```

...now the leak doesn't show up.

On the latter if I recompile without the sanitizer and run valgrind, valgrind does indeed show a leak:
==10782==    definitely lost: 4 bytes in 1 blocks

Looking at the assembly: I see the optimimzer hasn't made my malloc'd variable a local or some other trickery. So: why isn't AddressSanitizer picking up this one?  Am I missing something obvious?

This is on Ubuntu18.04 using clang 6.0.0-1ubuntu2.

**Comment by vitalybuka** [comment]
Looks like issue #937 
When leak sanitizer called after the main, its stack frame (or main caller from libc) frame overlaps with dead "blah" frame and pointer is in some padding but inside of live part of stack. So it assumes it's not leaked yet.
