### ISSUE TITLE
fopen64() null pointer reference

### ISSUE THREAD

**Issue by Changochen** [google/sanitizers#1180]
We found a null pointer ref in asan. Here's the program to reproduce it:
```cpp
#include <stdio.h>

int main()
{
   FILE * f = fopen64(NULL, "ab+");
    return 0;
}
```

Compile this program with `clang -fsanitize=address -o 1 1.c`. Run it and you get a crash. While without ` -fsanitize=address` it will exit normally.

Yongheng & Rui

**Comment by eugenis** [comment]
This program has undefined behavior, see
https://stackoverflow.com/questions/12620582/posix-fopennull-r
