### ISSUE TITLE
Testing hwaddress-sanitizer on Raspberry Pi

### ISSUE THREAD

**Issue by ris3muezz** [google/sanitizers#1184]
Hi. I'm wondering is it feasible to test HWASAN on Pi 4 (Cortex-a72 processor) with the Linux kernel 5.3? Except the kernel, is there any other requirement (such as a customized allocator) that I need to have?

Currently, this is the configuration of my system and I don't see any output of a simple Hello World! program.

> ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.3.0-1014-raspi2 #16-Ubuntu SMP Tue Nov 26 11:18:23 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

> ubuntu@ubuntu:~$ lsb_release -a
LSB Version:	core-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

And I use this command to generate an executable file
> clang-9 -O2 --target=aarch64-linux -fsanitize=hwaddress -fsanitize-recover=hwaddress hello.c

And I don't see the output of printf() in the terminal. When I remove `-fsanitize=hwaddress`, I can see the output. I also, checked the output of `strace`. In the last line, I can see this output:
> write(1, 0xb400efefffffe000, 22)        = -1 EFAULT (Bad address)
exit_group(0)                           = ?
+++ exited with 0 +++

Any thought is appreciated that what's the missing part.

**Comment by eugenis** [comment]
You probably need this change:
https://reviews.llvm.org/D68794

Check strace output for calls to prctl(0x37, ...

**Comment by pcc** [comment]
Also, Linux 5.3 does not include the pointer untagging patchset, you will need 5.4 or later.

**Comment by ris3muezz** [comment]
@eugenis : I thought it is already part of `clang-9`. Do I need to compile the llvm src with this patch? or it is part of 9.0.1 /10 ?
I also can confirm that I didn't see any `prctl` in the output of `strace`

@pcc : Thanks! I hope this kernel is fine.
> Linux aa 5.4.11-1-MANJARO-ARM #1 SMP PREEMPT Wed Jan 15 18:51:57 UTC 2020 aarch64 GNU/Linux

**Comment by eugenis** [comment]
On Thu, Jan 23, 2020 at 6:16 PM ris3muezz <notifications@github.com> wrote:

> @eugenis <https://github.com/eugenis> : I thought it is already part of
> clang-9. Do I need to compile the llvm src with this patch? or it is part
> of 9.0.1 /10 ?
> I also can confirm that I didn't see any prctl in the output of strace
>
It's not in any of the tags in the github repo currently.

The kernel api for TBI support (tagged pointers in syscall arguments) was
finalized only very recently. The userspace code in clang-9 assumes that
TBI is supported from the start, w/o the prctl.

**Comment by ris3muezz** [comment]
Thanks for your help. It works fine on Linux 5.4 and clang 11.0.0 on Pi 4.

**Comment by eugenis** [comment]
Great. I've just noticed that the commit is actually in the release/10.x
branch, so that should also work.
