### ISSUE TITLE
==219342==AddressSanitizer CHECK failed: ../../../.././libsanitizer/asan/asan_thread.cc:318 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)

### ISSUE THREAD

**Issue by pzyy99** [google/sanitizers#1185]
==219342==AddressSanitizer CHECK failed: ../../../.././libsanitizer/asan/asan_thread.cc:318 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)
the gcc version is 7.3.0.
the capacity of cpu is x86_64

**Comment by kcc** [comment]
This report is not very informative. 
If you want us to do something with it, please: 
* check if this happens with the most recent clang and gcc
* provide a reproducer, as small as possible 

Assertions like this usually happen when there is a memory corruption that asan doesn't detect, e.g. coming from an assembly blob or uninstrumented library.
