### ISSUE TITLE
MSAN: use of uninitialized value with recvfrom()

### ISSUE THREAD

**Issue by ZichangG** [google/sanitizers#1201]
This has been noticed on Linux,

Call `recvfrom` with local variable `RawAddr addr`. 
```
ssize_t recvfrom(int sockfd, void *buf, size_t len, int flags,
                 struct sockaddr *src_addr, socklen_t *addrlen);
```
According to `recvfrom` man page,

> If src_addr is not NULL, and the underlying protocol provides the source address, this source address is filled in.

`addr` will be written by `recvfrom`(I added print statements, values do change after recvfrom() call). If I pass `addr` to another function, MSAN will complain `addr` is unitialized.

Note that this only happens when `recvfrom` receives a zero-length datagram.

**Comment by eugenis** [comment]
Thank you, fixed in
https://github.com/llvm/llvm-project/commit/54d6c11a6ca1fc47707d57ea7874d2cfb51ea07d
