### ISSUE TITLE
[Undefined Behavior Sanitizer]False positive on deliberately down_cast as type confusion on std::basic_streambuf

### ISSUE THREAD

**Issue by expnkx** [google/sanitizers#1203]
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/streambuf_view.h
I want to call protected methods in basic_streambuf to access its internal buffer to gain the maximum performance stream. However, the undefined behavior sanitizer complains about it. So is it impossible to correctly identify deliberate type confusion?

https://www.ginac.de/~kreckel/fileno/

![image](https://user-images.githubusercontent.com/57303909/76582455-aabeb980-64ac-11ea-96ad-7873ecb2904d.png)

**Comment by expnkx** [comment]
Also this fileno does not work either.
https://www.ginac.de/~kreckel/fileno/

https://github.com/expnkx/UBSanitizer-False-Negative/blob/master/fileno_hack.cc

![image](https://user-images.githubusercontent.com/57303909/76583305-3fc2b200-64af-11ea-865a-51c9e67342be.png)

**Comment by jwakely** [comment]
Those casts are undefined, that's why ubsan tells you they are undefined.

**Comment by expnkx** [comment]
> Those casts are undefined, that's why ubsan tells you they are undefined.

It proves that iostream is shit. REMOVE IT FROM STANDARD!

**Comment by expnkx** [comment]
iostream and stdio.h are NO 1 violator of zero-overhead principle.

**Comment by expnkx** [comment]
I have provided a new method to go bypass sanitizer for getting fd
https://github.com/expnkx/UBSanitizer-False-Positive/blob/master/fileno_hack_with_bit_cast.h
