### ISSUE TITLE
Add MSAN Dockerfile (sharing one I wrote)

### ISSUE THREAD

**Issue by Sean-Der** [google/sanitizers#1207]
I have [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.github/msan-tester.Dockerfile) Dockerfile. Would it be possible to share this on the wiki? 

It was quite a pain to get things setup to test my application, and maybe others could find something like this useful?

**Comment by Sean-Der** [comment]
I also test in travis [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L82-L91) others might find that useful as well.

**Comment by eugenis** [comment]
This is great, thank you. I've added a note near the end of https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo. Feel free to send a pull request if you want it changed.
