### ISSUE TITLE
UBSAN sanitize=integer does not work with "shorts"

### ISSUE THREAD

**Issue by caa-energid** [google/sanitizers#1214]
I am using clang++ on ubuntu.  
The following code does not generate an error with UBSAN, however if `shortie` is declared as `int32_t` and initialized with `0x7ffffff0` then I get the expected error:  
`ubsanTest.cpp:36:24: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int`  

```
   int16_t shortie = 0x7ff0;
   for (uint32_t lpcntr = 0; lpcntr != 100; lpcntr++) {
      shortie = shortie+1;
      printf("shortie = %d\r\n", shortie);
   }

```

**Comment by dvyukov** [comment]
dup of #940
