### ISSUE TITLE
MSAN does not flag obvious errors

### ISSUE THREAD

**Issue by caa-energid** [google/sanitizers#1215]
The sample program appears below; as noted, the integer math does not report a failure via MSAN:  
```
static void helper1()
{
   // Expecting MSAN to flag all of these 'addition' statements    
   int32_t shortie;
   for (uint32_t lpcntr = 0; lpcntr != 100; lpcntr++) {
      shortie = shortie+1;
   }

   int *dynInt = new int[20];
   for (uint32_t lpcntr = 0; lpcntr != 19; lpcntr++) {
      dynInt[19] += dynInt[lpcntr];
   }

   int staticInt[20];
   for (uint32_t lpcntr = 0; lpcntr != 19; lpcntr++) {
        staticInt[19] += staticInt[lpcntr];
   }
}

int main(int argc, char** argv) {
    helper1();

    // Sample code from MSAN wiki - this DOES result in an error
    int* a = new int[10];
    a[5] = 0;
    if (a[argc]) {
      printf("xx\n");
    }

    return 0;
}

```

**Comment by eugenis** [comment]
This is by design, see https://github.com/google/sanitizers/wiki/MemorySanitizerFAQ
MSan does not report memory copies, and "simple" (side effect free) operations on undefined values. Instead it propagates the undefinedness to the operation result.

**Comment by caa-energid** [comment]
Yes - after I was reading the docs carefully this AM, I noticed the comment:  

> Please keep in mind that simply reading/copying uninitialized memory will not cause an MSan report. Even simple arithmetic computations will work. To produce a report, the code has to do something significant with the uninitialized value, e.g. branch on it, pass it to a libc function or use it to index an array.
