### ISSUE TITLE
__asan_default_options has no effect on vs2019

### ISSUE THREAD

**Issue by gamearea** [google/sanitizers#1247]
const char* __asan_default_options() {
	 return "halt_on_error=false:log_path=D:\\testlog\\";
 }

this function has no effect on vs2019 。  It still crash on error and print on stderr.
operating system is win10

**Comment by vitalybuka** [comment]
I assume it's about https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/

Does it support ASAN_OPTIONS= ?

Also it should probably be should be:
extern "C" const char* __asan_default_options() {
   return "halt_on_error=false:log_path=D:\\testlog\\mylog.log";
}

**Comment by gamearea** [comment]
> I assume it's about https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/
> 
> Does it support ASAN_OPTIONS= ?
> 
> Also it should probably be:
> extern "C" const char* __asan_default_options() {
> return "halt_on_error=false:log_path=D:\testlog\mylog.log";
> }

 extern "C" const char* __asan_default_options() {
	 return "halt_on_error=false";
 }
This function can be called. but still exit on error. 
![11111111111111111](https://user-images.githubusercontent.com/34889701/81648881-00d6bb80-9462-11ea-8064-4a387dc6d0f1.png)

**Comment by gamearea** [comment]
@vitalybuka Sorry i closed issue incautionly。

**Comment by vitalybuka** [comment]
It must be related to absence of weak symbols
https://github.com/llvm/llvm-project/blob/2fdec42a167c7325f771ba340c3a5eff3d33061a/compiler-rt/lib/sanitizer_common/sanitizer_win_defs.h#L48

**Comment by gamearea** [comment]
@vitalybuka 
Sorry i didn't understand。。

Using this code in vs2019 ：
 extern "C" const char* __asan_default_options() {
	 return "halt_on_error=0:log_path=1.log";
 }

1. halt_on_error = 0, or halt_on_error = false has no effect。 Process will exit on error.
2. log_path=1.log is ok， will create a err log 1.log.pid.  but if there is folder name such lick  log_path=./tmp/1.log, log_path=/tmp/1.log will NOT create file where the folder exits or not。

__asan_default_options has been called ， but seems not act the right behaviour。

**Comment by vitalybuka** [comment]
What kind of error? Some errors can not be suppressed with this flag.
https://github.com/llvm/llvm-project/blob/445b810fbd4f1dad71fbdf96ba1c3b947417b884/compiler-rt/lib/asan/asan_report.cpp#L125

**Comment by gamearea** [comment]
@vitalybuka 
`		// 1
		char* _Leak = new char[100];
		_Leak[100] = 0;

		// 2
		void* _Del = malloc(100);
		free(_Del);
		free(_Del);`

1. The first code will not continue running while i set halt_on_error = false, but second code can.
2. log_path=./temp/1.log or log_path=/temp/1.log  will NOT create log files if there are any folders before file names above.

Thanks a lot for these replys。
