### ISSUE TITLE
asan does not compile on RHEL5 (trivial patch)

### ISSUE THREAD

**Issue by plopresti** [google/sanitizers#1253]
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95244

On the one hand, RHEL5 is EoL.

On the other hand, I still need to use it... And the patch is trivial, since the only problem is that O_CLOEXEC is missing:

```
diff --git a/libsanitizer/sanitizer_common/sanitizer_posix.cpp b/libsanitizer/sanitizer_common/sanitizer_posix.cpp
index d890a3a3177..6ba525d1811 100644
--- a/libsanitizer/sanitizer_common/sanitizer_posix.cpp
+++ b/libsanitizer/sanitizer_common/sanitizer_posix.cpp
@@ -347,8 +347,14 @@ int GetNamedMappingFd(const char *name, uptr size, int *flags) {
   CHECK(internal_strlen(name) < sizeof(shmname) - 10);
   internal_snprintf(shmname, sizeof(shmname), "/dev/shm/%zu [%s]",
                     internal_getpid(), name);
+#if defined O_CLOEXEC
   int fd = ReserveStandardFds(
       internal_open(shmname, O_RDWR | O_CREAT | O_TRUNC | O_CLOEXEC, S_IRWXU));
+#else
+  int fd = ReserveStandardFds(
+      internal_open(shmname, O_RDWR | O_CREAT | O_TRUNC, S_IRWXU));
+  fcntl(fd, F_SETFD, FD_CLOEXEC);
+#endif
```

Thank you!

**Comment by kcc** [comment]
Thanks for posting the patch. If you want it upstream, please send a code review via https://llvm.org/docs/Phabricator.html. Although frankly I would prefer to avoid an extra ifdef if that's only for a EoL-ed OS. 
But good to have the patch here, for history.

**Comment by plopresti** [comment]
Done (https://reviews.llvm.org/D80648).

Note that the #ifdef is not actually necessary; just doing open() + fcntl() works fine on any POSIX system, including older ones. So that is what I submitted as a patch.

Thanks.
