### ISSUE TITLE
How to use msan for LLVMgold.so

### ISSUE THREAD

**Issue by vzakhari** [google/sanitizers#1254]
Hello,

I wonder if it is possible to make `MemorySanitized` `LLVMgold.so` work.  I followed instructions from https://github.com/google/sanitizers/wiki/MemorySanitizerBootstrappingClang to build sanitized clang and some llvm components.  I also built sanitized LLVM gold plugin.  When I try running simple `tools/gold/X86/alias.ll` test I am getting the following error:
`ld.gold: error: llvm/test/../lib/LLVMgold.so: could not load plugin library: llvm/test/../lib/LLVMgold.so: undefined symbol: __msan_origin_tls`

Is there a way to resolve this?  `msan` library cannot be statically linked into `LLVMgold.so`, and there is no shared version of `msan` library to use with `LD_PRELOAD`, so I ran out of ideas pretty fast.

Thank you,
Slava

**Comment by kcc** [comment]
You will need the linker to also be msan-ified. 
We don't have ready to use instructions for this.
Maybe if you us lld instead of gold it would be simpler.

**Comment by vzakhari** [comment]
Thank you for the clarification.
