### ISSUE TITLE
clang+addressSanitzer and gcc+addressSanitizer mixed used

### ISSUE THREAD

**Issue by anlongfei** [google/sanitizers#1262]
i am going to replace gcc with clang for my project,which depends on deplibs. 
in debug mode, deplibs compiled with g+++-fsanitize=address,and my project compiled with clang++ -fsanitize=address, and run the binary encounters "Your application is linked against incompatible ASan runtime"(seems ASAN runtime is loaded twice,ref:https://github.com/google/sanitizers/issues/1086#issuecomment-492693405).
so what should i do except recompile the deplibs with clang++ -fsanitize=address?

**Comment by kcc** [comment]
I don't think there is any other good way.
