### ISSUE TITLE
=Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.

### ISSUE THREAD

**Issue by ravindra3** [google/sanitizers#1276]
I tried to execute Address sanitizer in  6.2.0 GCC ( ARM-64-bit) and it is simple hello world program.
the address sanitizer was linked dynamically (libasan.so) 
The below error appeared.
**=Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.**

**Comment by kcc** [comment]
Does this happen with the fresh clang? 
If yes, please specify the exact kernel & libc, as well as you exact test case and command line. 
(please reopen with details)

**Comment by yugr** [comment]
@ravindra3 this question is in [Asan FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer), please see if your case is covered.

**Comment by ravindra3** [comment]
> 
> 
> @ravindra3 this question is in [Asan FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer), please see if your case is covered.

Hi,
@yugr 
Thank you but i had already tried the below suggestion mentioned in the Asan FAQ. 
"If you are using shared ASan DSO, try LD_PRELOAD'ing Asan runtime into your program"

I still could reproduce the same issue. Did i miss anything else? Any suggestions?
