### ISSUE TITLE
ASAN incompatible with a LTTng using a dynamically loaded trace provider

### ISSUE THREAD

**Issue by ThadHouse** [google/sanitizers#1286]
Using LTTng with trace providers loaded dynamically mixed with ASAN causes ASAN to segfault with the following error. A small test project is attached.

```
Tracer caught signal 11: addr=0x0 pc=0x7f1c687ae4f0 sp=0x7f1c6334ed00
==17154==LeakSanitizer has encountered a fatal error.
==17154==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==17154==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

[AsanLttng.zip](https://github.com/google/sanitizers/files/4997749/AsanLttng.zip)

Reproduced on Ubuntu 18.04.

Steps to reproduce:
1. Extract above zip.
2. Build using cmake
3. Run `main`. Crash will occur after pressing enter.

**Comment by ThadHouse** [comment]
Forgot to mention the steps to get the lttng dev dependency installed.

sudo apt-add-repository ppa:lttng/stable-2.10
sudo apt-get install -y lttng-tools liblttng-ust-dev

**Comment by melver** [comment]
```
...
==17154==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

LTTng is a tracing framework, and the same limitations may apply when using LeakSanitizer.

Please try ASAN_OPTIONS=detect_leaks=0.

**Comment by ThadHouse** [comment]
LTTng doesn't actually use ptrace by design. Its one of its goals to not use it. This only broke when we switched to a dynamically linked tracepoint provider. Using a statically linked tracepoint provider worked without issues.

**Comment by ThadHouse** [comment]
And is that hint just generic, or is ASAN actually able to detect that its interfering with ptrace?
