### ISSUE TITLE
Mark portion of memory as read only on sanitizer runs

### ISSUE THREAD

**Issue by ebraminio** [google/sanitizers#1291]
We have [a null pool](https://github.com/harfbuzz/harfbuzz/blob/bd8aa1b/src/hb-null.hh#L77) that shouldn't be changed under any circumstances and just recently I found we are editing it in a very rare case, was wondering if is possible to mark that part of the memory as read only in sanitizer runs using some attribute or something. Thanks!

**Comment by ramosian-glider** [comment]
Will it help to align the pool on 4K and just mprotect it?

**Comment by ebraminio** [comment]
Sure! That sounds good, let me see if I can integrate it easily. Thanks
