### ISSUE TITLE
AddressSanitizer not support linux arm now ?

### ISSUE THREAD

**Issue by choujayyl** [google/sanitizers#1305]
I use gcc 4.9 with AddressSanitizer in linux arm,but test it not work.So is that so.

**Comment by kcc** [comment]
Please try the most recent clang. 
If it doesn't work, please provide the exact command lines, OS version, etc.

**Comment by choujayyl** [comment]
> Please try the most recent clang.
> If it doesn't work, please provide the exact command lines, OS version, etc.

I just want make sure sanitizer is that support linux arm ? which version support ?

**Comment by choujayyl** [comment]
![image](https://user-images.githubusercontent.com/28703422/91933825-62c27600-ed1c-11ea-80ac-8c7752df520d.png)
The map shows meaning not support,until now?

**Comment by choujayyl** [comment]
Conclusion: 32-bit gcc only supports out-of-bounds detection, not memory leaks.
Both 64 bits are supported.
llvm 32bit arm is supported and tested.
