### ISSUE TITLE
Issue with leak on gcc v2.23

### ISSUE THREAD

**Issue by tanshihaj** [google/sanitizers#1309]
Sometimes running program compiled with asan I see leaks somewhere in glibc:

```
=================================================================
==452187==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1040 byte(s) in 1 object(s) allocated from:
    #0 0x23cab06a in __interceptor_calloc .../clang/src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155:3
    #1 0x7fe2c92d41ff in __new_exitfn .../glibc-2.23/stdlib/cxa_atexit.c:101

SUMMARY: AddressSanitizer: 1040 byte(s) leaked in 1 allocation(s).
```

Is it known issue?

clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by 091530777777** [comment]
> بعضی اوقات برنامه در حال اجرا با asan وارد می شود که در جایی از glibc نشت می بینم:
> 
> ```
> =================================================================
> ==452187==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 1040 byte(s) in 1 object(s) allocated from:
>     #0 0x23cab06a in __interceptor_calloc .../clang/src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155:3
>     #1 0x7fe2c92d41ff in __new_exitfn .../glibc-2.23/stdlib/cxa_atexit.c:101
> 
> SUMMARY: AddressSanitizer: 1040 byte(s) leaked in 1 allocation(s).
> ```
> 
> آیا مسئله شناخته شده است؟
> 
> clang نسخه 7.0.0 (برچسب ها / RELEASE_700 / نهایی)
> هدف: x86_64-unknown-linux-gnu
> مدل موضوع: posix

بله

**Comment by tanshihaj** [comment]
> بله

Is it issue with asan or with glib?

**Comment by kcc** [comment]
Please check the current (fresh) version of clang, and if the problem still exists please attach a minimal reproducer.

**Comment by tanshihaj** [comment]
For some reasons I can't update quickly to the latest clang and check, I just want to know if this issue connected with glibc/clang or problem on my code.
