### ISSUE TITLE
ASAN_OPTIONS seems doesn't affect the output of asan in docker

### ISSUE THREAD

**Issue by sjc2870** [google/sanitizers#1316]
I use `export ASAN_OPTIONS=log_path=$my_path` in container and expect asan can output to specific file when I kill the process which run the container. But it failed.
And I write a simple test program and run it in docker.Its asan output can redirect to specific file.
It seems weird and is it a bug?

**Comment by kcc** [comment]
This is a bit vague, could you please provide a minimal repro and reopen? 
Also, if you kill the container before ASAN writes something `$my_path`, the file will be empty, of course.

**Comment by sjc2870** [comment]
> This is a bit vague, could you please provide a minimal repro and reopen?
> Also, if you kill the container before ASAN writes something `$my_path`, the file will be empty, of course.

sry.It's this: I build a container and run a process with asan within this container.After running this process,I added ASAN_OPTIONS env variable manually in the container,then I kill the container in host(not in container),and expect asan output to specific file. However it failed,asan not output to $my_path but to stderr. 
After this, I run a simple test process and kill it ,the all above two actions(run and kill) happened in the container, and asan output to $my_path as I expected.
At last, how to tell if the container was killed before or after asan writes?
