### ISSUE TITLE
Running ASAN over google test hanging system and failing ASAN with no reason

### ISSUE THREAD

**Issue by tejas3** [google/sanitizers#1323]
ASAN consuming 100 CPU and RAM which leads to failure of ASAN every time, seems like timeout issue.

Current configuration: 
32 GB Ram, I7 processor, 1 TB HD
OS: Ubuntu 16
ASAN Option:    "report_objects=1

**Comment by kcc** [comment]
This information is not sufficient for us to help you. 
Ideally, please provide a reproducer. 
Failing that, show the stack trace where the application is stuck and/or show the 'perf' profile.

**Comment by tejas3** [comment]
what do you mean by reproducer ? 
currently using clang compiler

**Comment by kcc** [comment]
We can not fix a problem w/o being able to reproduce it, or at least to get some idea of what's going on. 
The better and the smaller is the reproducer, the more chances are that we will be able to fix it.

**Comment by tejas3** [comment]
okay, got it.. 
Could you please help me with some pointer to look?
I think it is timeout issue.

**Comment by tejas3** [comment]
please suggest some ASAN flags by which we can track this issue

**Comment by kcc** [comment]
start with 
* run under gdb, collect several stack traces `
```
ctrl-c
bt
c
```

* run under perf
```
perf record ./a.out
# ctrl-c after some time
perf report
```

send the results here.

**Comment by tejas3** [comment]
Sure, thank you very much :)
