### ISSUE TITLE
ASAN "dynamic-stack-buffer-overflow" false positive(?) when using OpenMP reduction to std::vector

### ISSUE THREAD

**Issue by Spielix** [google/sanitizers#1326]
Minimal example:
```C++
#include <iostream>
#include <vector>

int main() {
  std::vector<int> v(10);
  auto const ptr{v.data()};
#pragma omp parallel for reduction(+ : ptr[:v.size()])
  for (int i = 0; i < 1; ++i) {}

  std::cout << v.front() << '\n';
}
```
compiled with:
`g++ -fopenmp -fsanitize=address asan_omp_test.cpp -o asan_omp_test`

Tried with gcc 8.2 and 10.2.1. I used the most recent version of libasan available on Fedora 32.
This does **not** happen when using `std::array` instead of `std::vector`. As this happens even with an empty loop body, the allocation/copy for the reduction seems to be the problem. 

Similar to this: #994

**Comment by vitalybuka** [comment]
I suspect it must be something on compiler side, not in libasan. It has more chances to be fixed if reported to GCC.

**Comment by Spielix** [comment]
I played around with it a bit more and I can't reproduce it with clang, which supports your suspicion.
Also it doesn't happen when reformulating the code in C (using calloc instead of vector).

So you say, I should put it here: [](https://gcc.gnu.org/bugzilla/)?
