### ISSUE TITLE
Asan report a crash but unknow reason.

### ISSUE THREAD

**Issue by coffeezh** [google/sanitizers#1336]
Hi,when I test a program use asan,it reports a crash :
` ==4999==ERROR: AddressSanitizer: SEGV on unknown address 0x0000001f (pc 0xb69e812e bp 0xb26f9f78 sp 0xb26f9820 T5)
 ==4999==The signal is caused by a READ memory access.
 ==4999==Hint: address points to the zero page.
   <empty stack>
    
 AddressSanitizer can not provide additional info.
 SUMMARY: AddressSanitizer: SEGV`

According to log,I think this code cause this crash.
`unsigned char mSslRecordBuf[5+0xFFFF];
......
memcpy(mSslRecordBuf, mSslRecordBuf + 5, 43);`

Array offset 5 and copy again，it will appear this crash.I change 43 to 5,this crash disappear.In my opinion,I think this code can't appear READ memory access.

Can you help me answer my questions?Thank you for your help.

**Comment by kcc** [comment]
This seems like a NULL dereference " unknown address 0x0000001f ".
There is not much ASAN can help here. 

If you suspect a bug in ASAN, please provide a minimal reproducer.
