### ISSUE TITLE
How can I protect my region for sanitizers as a library?

### ISSUE THREAD

**Issue by expnkx** [google/sanitizers#1343]
For example, I have an array which has 1024 bytes, but I want to protect the first 16 bytes.

**Comment by kcc** [comment]
Not sure I understand your request. 
Perhaps, you can provide a small test example? 
(please reopen when you have it)

**Comment by expnkx** [comment]
> Not sure I understand your request.
> Perhaps, you can provide a small test example?
> (please reopen when you have it)

I have an array

std::array<char,1000> array;

I want to protect

array.data()+0 ->array.data()+100 region. If any operations write above 100, it treats it as a memory safety violation for example.

**Comment by kcc** [comment]
This sounds like https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow
You need to use `__sanitizer_annotate_contiguous_container` from `sanitizer/common_interface_defs.h`
