### ISSUE TITLE
ASAN_OPTIONS and __asan_default_options

### ISSUE THREAD

**Issue by Bidski** [google/sanitizers#1344]
What is the behaviour of the `ASAN_OPTIONS` environment variable and the `__asan_default_options` function?

Is `ASAN_OPTIONS` appended/concatenated with whatever is returned from `__asan_default_options` or does one override the other?

**Comment by vitalybuka** [comment]
Asan first parse  __asan_default_options and then ASAN_OPTIONS. ASAN_OPTIONS overrides only options it contains, the rest of __asan_default_options is preserved.
