### ISSUE TITLE
Code works without using your software, and if I compile my stuff with this, my program fails during run time.

### ISSUE THREAD

**Issue by Xyncgas** [google/sanitizers#1351]
I can give you the entire project repo, if anyone wanna try it yourself. (only happens with release x64 though)

**Comment by kcc** [comment]
Please provide more info and a small reproducer

**Comment by Xyncgas** [comment]
It happened with my project, I can give you the link to the repository, I would invite u to come take a look and try it and I can't help you much further than that because I never ran into this problem before working on this project which I literally did nothing usual other than what I've been doing a while n works.
I can't break down my codes to debug it, because it's a lot of codes. but you can try double clicking the .sln file, and try the steps yourself, which is shown in this video (2mins): https://ewr1.vultrobjects.com/temp3/2020-12-05_08-09-32.mp4
