### ISSUE TITLE
TSAN: sanitizer/tsan_interface_atomic.h: No such file or directory

### ISSUE THREAD

**Issue by acelyc111** [google/sanitizers#1361]
I use gcc 7.4.0 to compile my project in TSAN mode, the project relies on google/protobuf as a thirdparty lib, but compile report some errors like:
```
.../thirdparty/installed/include/google/protobuf/stubs/atomicops_internals_tsan.h:40:10: fatal error: sanitizer/tsan_interface_atomic.h: No such file or directory
 #include <sanitizer/tsan_interface_atomic.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I checked file sanitizer/tsan_interface_atomic.h is not exist indeed, but I can find it in gcc code base (https://github.com/gcc-mirror/gcc/blob/master/libsanitizer/include/sanitizer/tsan_interface_atomic.h).
My question is how can I compile gcc manually with this header?
I'd appreciate for your reply, thanks!

**Comment by dvyukov** [comment]
I think it's simply not included with gcc 7. If gcc 7 is not end-of-life you may report it to gcc bug tracker.
Check out latest gcc 10 and/or declare these functions manually.
