### ISSUE TITLE
SEGV error with Address Sanitizer

### ISSUE THREAD

**Issue by anastasiyaant** [google/sanitizers#1375]
Face with this problem/ Started with ASAN_OPTIONS=halt_on_error=0 /usr/sbin/myprog

SAN:DEADLYSIGNAL
=================================================================
==75793==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x6e13c025a3a8 bp 0x7ffdb7575dd0 sp 0x7ffdb7575d60 T0)
    #0 0x6e13c025a3a7  (/usr/sbin/myprog+0x11b3a7)
    #1 0x6e13c0260de3  (/usr/sbin/myprog+0x121de3)
    #2 0x6e13c0219d1a  (/usr/sbin/myprog+0xdad1a)
    #3 0x6e13c021a376  (/usr/sbin/myprogt+0xdb376)
    #4 0x6e13c01e6093  (/usr/sbin/myprog+0xa7093)
    #5 0x7d00b32842e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #6 0x6e13c0205cc9  (/usr/sbin/myprog+0xc6cc9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/sbin/myprog+0x11b3a7) 
==75793==ABORTING

With gdb I get:

(gdb) step
std::pair<long const, Service>::pair (this=<optimized out>) at /usr/include/c++/6/bits/stl_pair.h:288
288           constexpr pair(const pair&) = default;
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x000055555566f3a8 in std::pair<long const, Service>::pair (this=<optimized out>) at /usr/include/c++/6/bits/stl_pair.h:288
288           constexpr pair(const pair&) = default;
(gdb) step
ASAN:DEADLYSIGNAL

Also can't get code text and number of string in trace. ASAN_SYMBOLIZER_PATH is set, ASAN_OPTIONS=symbolize=1 is also set, gcc option -g is set.
Function on step 0 in sanitizer code. Have no problem without sanitizer. 
Please help me with this problems.

**Comment by DavidWzh** [comment]
hello，for this “SEGV ERROR”，would you tell me how to slove .

**Comment by DavidWzh** [comment]
i met these error many times, i do not know if it is false positive。 because if i do not use Asan， my program is ok。
