### ISSUE TITLE
Thread sanitizer with Homebrew's gcc 10 on macOS

### ISSUE THREAD

**Issue by fxkaiser** [google/sanitizers#1391]
I would like to use gcc 10 from Homebrew because of its c++20 concepts STL support and the corresponding thread sanitizer in my c++ project. Using the example from 

https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual

and compiling with 'g++ simple_race.cpp -o simple_race -fsanitize=thread -g' I get the following link errors:

Undefined symbols for architecture x86_64:
  "___tsan_func_entry", referenced from:
      __Z7thread1Pv in ccHayO59.o
      __Z7thread2Pv in ccHayO59.o
      _main in ccHayO59.o
  "___tsan_func_exit", referenced from:
      __Z7thread1Pv in ccHayO59.o
      __Z7thread2Pv in ccHayO59.o
      _main in ccHayO59.o
  "___tsan_init", referenced from:
      __sub_I_00099_0 in ccHayO59.o
  "___tsan_read4", referenced from:
      __Z7thread1Pv in ccHayO59.o
      __Z7thread2Pv in ccHayO59.o
  "___tsan_read8", referenced from:
      _main in ccHayO59.o
  "___tsan_write4", referenced from:
      __Z7thread1Pv in ccHayO59.o
      __Z7thread2Pv in ccHayO59.o
ld: symbol(s) not found for architecture x86_64

Using the address sanitizer instead everything works fine. Is this a known issue or have I missed something ?

**Comment by dvyukov** [comment]
I don't remember any prior mentions of this issue.
I guess gcc does not build/link tsan runtime in such configuration. You may search for libtsan.so in the build to understand if it was even built. This should be handled in the gcc repo/issue tracker.
