### ISSUE TITLE
Address Sanitizer for Android

### ISSUE THREAD

**Issue by Nikhil1212** [google/sanitizers#1392]
I wanted to generate the instruction trace of Android Apps i.e, when I say instruction trace I want to get the address of the instructions which are getting executed.
Does Address Sanitizer support Android platform?
If yes, can I use Address Sanitizer for getting the addresses of the instruction which are getting executed? 

I am sorry, if this is the wrong platform, to discuss above type of doubts.

**Comment by eugenis** [comment]
No, this is not what ASan is for.
