### ISSUE TITLE
Is the loop instrumenting optimization implemented in ASan?

### ISSUE THREAD

**Issue by shijy16** [google/sanitizers#1393]
Thanks for the extraordinary work!
I am reading and learning the source code of ASan recently. I notice the loop instrumenting optimization is described in the wiki:
````
Instrument this loop with __asan_region_is_poisoned(a, n*sizeof(*a)) and avoid instrumenting individual accesses.

for (int i = 0; i < n; i++)
  a[i] = ...;
````
But I found no optimization code. Did I miss it? Or it hasn't been implemented yet?

**Comment by kcc** [comment]
No, it has not been implemented, IIRC.

**Comment by shijy16** [comment]
Got it, thank you very much.
