### ISSUE TITLE
Obtaining execution trace log

### ISSUE THREAD

**Issue by umangm** [google/sanitizers#1396]
Is there support for printing the entire execution trace log (sequence of all read, write, lock, unlock, fork, join operations performed in the execution) in any of the sanitizers (particularly **TSAN**)?

I am looking for something on the following lines:
```
write(tid1, memory-loc1, val1)
read(tid2, memory-loc1, val1)
lock(tid1, mutex-id1)
unlock(tid1, mutex-id1)
lock(tid2, mutex-id1)
write(tid1, memory-loc1, val2)
unlock(tid2, mutex-id1)
....
```

I see some `DPrintf` statements embedded in [the code](https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/tsan/rtl/tsan_rtl_mutex.cpp#L159) but do not see them being exercised

**Comment by dvyukov** [comment]
Hi @umangm,

Tsan supports some tracing via DPrintf[2] calls if you build runtime with -DTSAN_DEBUG_OUTPUT=1/2. The tracing was designed  only for manual debugging, it's not meant to be some parsable, structured, stable format.

**Comment by umangm** [comment]
Hi I cmaked'd llvm (latest version) using the following command:
```
cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_PROJECTS='compiler-rt' -DLLVM_BUILD_TESTS=OFF -DCOMPILER_RT_DEBUG=ON -DTSAN_DEBUG_OUTPUT=2 -DLLVM_INCLUDE_TESTS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_ENABLE_ASSERTIONS=OFF ../llvm
```

I see that this flag was unused:
```
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    TSAN_DEBUG_OUTPUT
```

AmI missing something?

**Comment by dvyukov** [comment]
Frankly I don't know how to do it officially. I am not sure it's even supported now in CMake, maybe this lost during switch to CMake. I would try just this source change to get started:

```
--- a/compiler-rt/lib/tsan/rtl/tsan_rtl.h
+++ b/compiler-rt/lib/tsan/rtl/tsan_rtl.h
-#if 1
-#if defined(TSAN_DEBUG_OUTPUT) && TSAN_DEBUG_OUTPUT >= 1
-# define DPrintf Printf
-#else
-# define DPrintf(...) do {} while(0)
-#endif
-
-#if defined(TSAN_DEBUG_OUTPUT) && TSAN_DEBUG_OUTPUT >= 2
-# define DPrintf2 Printf
-#else
-# define DPrintf2(...) do {} while(0)
-#endif
-
-#else
 # define DPrintf Printf
 # define DPrintf2 Printf
-#endif
```
