### ISSUE TITLE
Bug or Feature? I fail to suppress MSan error reporting in `memcmp()`

### ISSUE THREAD

**Issue by kuzminrobin** [google/sanitizers#1429]
Ubuntu clang version 11.0.0-2~ubuntu20.04.1

I have a suppression file that successfully suppresses a number of errors for MemorySanitizer.
But I fail to suppress an error reporting for the function `memcmp` both with this suppression line 
`fun:memcmp`, and this one 
`fun:*memcmp*`. 

Is it a bug or feature?

**Details.**
I run my binary with MSan. The MSan reports an issue in a call (I changed formatting a bit for readability):
```
1: ==1699==WARNING: MemorySanitizer: use-of-uninitialized-value
1:     #0 0x754bc8 in Catch::(anonymous namespace)::parseSpecialTag(std::__cxx11::basic_string<char, 
                                                                                               std::char_traits<char>, 
                                                                                               std::allocator<char> > const&) 
            <Removed>/src/Qir/Runtime/bin/Debug/../../../Common/externals/catch2/catch.hpp:14014:40
```
I successfully suppress this report with the following line in the suppression file:
`fun:*Catch*parseSpecialTag*`

The execution continues and _this same function_ makes a chain of calls eventually resulting in a call to `memcmp()` (I changed the output formatting for readability):
```
1: Uninitialized bytes in MemcmpInterceptorCommon at offset 0 inside [0x7fff8614fb50, 5)
1: ==3979==WARNING: MemorySanitizer: use-of-uninitialized-value
1:     #0 0x440f6e in memcmp 
            (<Removed>/src/Qir/Runtime/bin/Debug/unittests/qir-runtime-unittests+0x440f6e)
1:     #1 0x7f4c2d1f01ed in std::__cxx11::basic_string<char, 
                                                       std::char_traits<char>, 
                                                       std::allocator<char> 
                                                      >::compare(char const*) const 
            (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1451ed)
1:     #2 0x5c57e6 in bool std::operator==<char, 
                                           std::char_traits<char>, 
                                           std::allocator<char> 
                                          >(std::__cxx11::basic_string<char, 
                                                                       std::char_traits<char>, 
                                                                       std::allocator<char> > const&, 
                                            char const*) 
            /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:6177:20
1:     #3 0x754aab in Catch::(anonymous namespace)::parseSpecialTag(std::__cxx11::basic_string<char, 
                                                                                               std::char_traits<char>, 
                                                                                               std::allocator<char> > const&) 
            <Removed>/src/Qir/Runtime/bin/Debug/../../../Common/externals/catch2/catch.hpp:14015:21
```
I try to suppress this reporting by adding lines to the suppression file, 
suppression lines `fun:memcmp`, `fun:*memcmp*`. But none of these lines suppresses the reporting.
Is it a bug or feature or do I miss something?
What can I do to suppress and move forward?

See also related issue #1428

**Comment by vitalybuka** [comment]
Probably a bug.
Still not sure how practical to run msan with non-instrumented libstdc++

**Comment by kuzminrobin** [comment]
If this cannot be resolved without instrumenting libstdc++, then feel free to close this issue.

**Comment by eugenis** [comment]
That's because the check is in the interceptor ("Uninitialized bytes in
MemcmpInterceptorCommon"), those are not affected by the suppression file.
We don't have a good way of disabling interceptors - normally you don't
want to disable them globally, but only for calls from a specific function
or file or something like that.

And yes, IMHO non-instrumented libstdc++ is impractical.
