### ISSUE TITLE
Question: Why is the code in MemoryAccessImpl1 has two branches both doing the same thing?

### ISSUE THREAD

**Issue by Arslan8** [google/sanitizers#1431]
While going through the internals of tsan I happened to come across this code: 
```
  if (stored) {
#include "tsan_update_shadow_word_inl.h"
  } else {
#include "tsan_update_shadow_word_inl.h"
  }
```
I see the code is really hot that's why it is even unrolled and everything, but why the check implemented like this?
It looks like both stored==true and false run the same code, then why bother writing it this way? I am sure there is some intricate compiler optimization triggered by doing this?

**Comment by dvyukov** [comment]
It lead to a better codegen. After including tsan_update_shadow_word_inl.h compiler can eliminate all branching on `stored`. In the first case it can consider it to be `true` and execute `if (stored)` code unconditionally. In the second case it can throw away all `if (stored)` blocks.

**Comment by Arslan8** [comment]
Ah..that makes perfect sense! Thanks for the prompt response!!
