### ISSUE TITLE
Application hangs in __sanitizer::internal_sched_yield() 

### ISSUE THREAD

**Issue by getsoubl** [google/sanitizers#1449]
Hello,
We are  running an application using sanitizer . Seems that the application hangs in #0 0x00007ffff6f0ea4b in #0__sanitizer::internal_sched_yield() () from /lib64/libasan.so.5
#1 0x00007ffff6e55015 in pthread_create () from /lib64/libasan.so.5

Is  any  known bug?
Is any hint what goes wrong and this behaviour is appeared?
The g++ version is _**g++ (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)**_
Thank you 
George

**Comment by getsoubl** [comment]
Any hint ?

**Comment by mrichtarsky** [comment]
It might be helpful to see the callstacks of all threads (`thread apply all bt` in `gdb`)

**Comment by getsoubl** [comment]
I checked the thread apply all bt.  As I mentioned in my previous comment , seems that the main thread that creates working threads, hangs internal_sched_yield. I consider that it never returns.
