### ISSUE TITLE
getsockname causes asan crash if used with NULL addrlen

### ISSUE THREAD

**Issue by mvanotti** [google/sanitizers#1451]
The `getsockname` interceptor attempts to access the `addrlen` pointer. In most operating systems (linux, macos, freebsd) this would return `-EFAULT`, but when ran under AddressSanitizer, it crashes.

Sample code:
```c
#include <sys/socket.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>

int main() {
    int s = socket(PF_INET, SOCK_STREAM, 0);
    int ret = getsockname(s, NULL, NULL);
    printf("ret: %d errno: %d %s\n", ret, errno, strerror(errno));
    return 0;
}
```

```shell-session
$ clang -fsanitize=address getsockname.c -o getsockname-sanitized
$ ./getsockname-sanitized 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2471239==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000044667a bp 0x7ffd6549fa00 sp 0x7ffd6549f1c0 T0)
==2471239==The signal is caused by a READ memory access.
==2471239==Hint: address points to the zero page.
    #0 0x44667a in getsockname (/data/getsockname/getsockname-sanitized+0x44667a)
    #1 0x4c7f95 in main (/data/getsockname/getsockname-sanitized+0x4c7f95)
    #2 0x7f545fa1cd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #3 0x41e2c9 in _start (/data/getsockname/getsockname-sanitized+0x41e2c9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/data/getsockname/getsockname-sanitized+0x44667a) in getsockname
==2471239==ABORTING
```
```shell-session
$ clang getsockname.c -o getsockname-unsanitized
$ ./getsockname-unsanitized 
ret: -1 errno: 14 Bad address
```

Note that the behavior of the syscall is unspecified. But all operating systems return `-EFAULT` on an invalid pointer.

The problem seems to be that the [getsockname interceptor](https://github.com/llvm/llvm-project/blob/4ed05312a1557b2f2552298a3aac12c2e224d77e/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc#L2665) accesses the `addrlen` variable to know the size of the name buffer. If `addrlen` is not mapped, that access will cause a crash.

**Comment by dvyukov** [comment]
Do you suggest to return EFAULT instead of something else? Isn't it better to fail loudly for bug detection purposes?

**Comment by dvyukov** [comment]
> Is it documented anywhere that the kernel would return -EFAULT if an address is invalid in a system call?

See: https://man7.org/linux/man-pages/man2/getsockopt.2.html#ERRORS

> and there might be programs relying on that behavior.

Do you know any such real programs? I come up with any reasonably cases.

**Comment by tamird** [comment]
https://reviews.llvm.org/D113055

I'm not totally sure how to write a proper test for this, advice appreciated.
