### ISSUE TITLE
Tsan is broken on non-AVX processors after https://reviews.llvm.org/D113742

### ISSUE THREAD

**Issue by apinski-cavium** [google/sanitizers#1472]
https://reviews.llvm.org/D113742 introduced the instruction vmovdqu unconditionally to tsan_rtl_amd64.S.

**Comment by apinski-cavium** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103466

**Comment by dvyukov** [comment]
I guess I needed to use MOVDQU, but this code is unused since https://github.com/llvm/llvm-project/commit/66d4ce7e26a5 and will be removed in https://reviews.llvm.org/D112604
