### ISSUE TITLE
refrence doc dead link

### ISSUE THREAD

**Issue by char6ming** [google/sanitizers#1473]
refrence doc of [ThreadSanitizerAboutRaces](https://github.com/google/sanitizers/wiki/ThreadSanitizerAboutRaces#more-reading) have a dead link in  the **more-reading** section:

* Benign data races: what could possibly go wrong?   <--  can **not** get touch this doc.

**Comment by dvyukov** [comment]
I've evacuated the article to this location for now:
https://docs.google.com/document/d/e/2PACX-1vSDZFnTUNoHiBP23OqVrNBWnTPwsyAbmDnglR8osAMFZrQClPhaCv8ZBmBDCScFjAms1pReswDc3U0A/pub
Not sure what's the right place for it.

**Comment by char6ming** [comment]
nice job, love it.
