### ISSUE TITLE
[TSAN] How do I instrument seq-cst fences to make TSAN understand them?

### ISSUE THREAD

**Issue by HolyBlackCat** [google/sanitizers#1482]
I learned that TSAN doesn't understand fences yet, and I need to manually instrument acquire and/or release fences with `__tsan_acquire` and/or `__tsan_release`.

What about seq-cst fences though? How do I instrument them? I assume that acq-rel instrumentation wouldn't be enough, but I don't have an example to prove it.

**Comment by dvyukov** [comment]
Acquire-release instrumentation should be enough.
