### ISSUE TITLE
Can't seem to get instrumented MSAN to work with googletest

### ISSUE THREAD

**Issue by nmoinvaz** [google/sanitizers#1492]
I've been having difficulty trying to get googletest to compile with MSAN using instructions documented here:
https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

I have created a sample repository that just has the test from that [wiki](https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo) page:
https://github.com/nmoinvaz/googletest-msan

CI compiles LLVM using the instructions:
https://github.com/nmoinvaz/googletest-msan/blob/main/.github/workflows/cmake.yaml

CMake passes the same flags:
https://github.com/nmoinvaz/googletest-msan/blob/main/CMakeLists.txt

Linker errors:
```
/usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::OutputFlagAlsoCheckEnvVar[abi:cxx11]()':
gtest-all.cc:(.text+0x130): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/usr/bin/ld: gtest-all.cc:(.text+0x238): undefined reference to `std::__throw_length_error(char const*)'
/usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::Int32FromGTestEnv(char const*, int)':
```

Perhaps the instructions in the wiki need to be updated?

**Comment by dvyukov** [comment]
FWIW I recently used googletest with msan, here is how I built googletest:
```
CXX=clang++ cmake -GNinja -DCMAKE_CXX_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins -stdlib=libc++" ../googletest && ninja
```

and this is what I used in my CMakefile:
```
set(CXX_FLAGS "-O1 -fsanitize=memory -fsanitize-memory-track-origins -stdlib=libc++")
set(LINK_FLAGSL "-fsanitize=memory -fsanitize-memory-track-origins -stdlib=libc++ -static-libstdc++ -L${MSAN_LIBCXX}/lib  -Wl,--whole-archive ${MSAN_LIBCXX}/lib/libc++abi.a -Wl,--no-whole-archive")
```

**Comment by nmoinvaz** [comment]
I think I figured out part of my problem. The [wiki](https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo) says:
> You can verify that MSan works as expected by introducing a bug:
``` 
TEST(FooTest, Foo) {
  int uninitialized;
  EXPECT_GT(uninitialized, 5);
}
```
For me, this does not trigger a warning. And the [MemorySanitizerFAQ](https://github.com/google/sanitizers/wiki/MemorySanitizerFAQ), has this:

> Q. Why does reading an uninitialized value from memory not trigger a warning?

> A. MSan only reports errors when the uninitialized value is used in a way which could affect externally visible program behavior, like when it is used in a conditional branch, to index another memory operation, or passed to a libc function. Copying uninitialized memory as well as doing simple arithmetic operations on it is allowed, and, in fact, happens quite often in practice.

When I use something more like this then it will fail correctly:
```
TEST(FooTest, BadFoo2) {
  char *m = (char *)malloc(10);
  EXPECT_GT(m[0], 5);
  free(m);
}
```
On some of my test runs when compiling with MSAN I would get everything to compile and link correctly, but I didn't think it was working because it wasn't finding the bug that the wiki stated it should.

**Comment by nmoinvaz** [comment]
I have it working now using CMake. If anybody is interested the project is up at https://github.com/nmoinvaz/googletest-msan.
