### ISSUE TITLE
msan: regcomp() interceptor should unconditionally initialize the regex_t

### ISSUE THREAD

**Issue by tavianator** [google/sanitizers#1496]
When `regcomp()` fails, `regerror()` can be passed the same `regex_t *` to potentially get better error messages.  [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/regcomp.html) seems to imply this, and the [glibc docs](https://www.gnu.org/software/libc/manual/html_node/Regexp-Cleanup.html) state it explicitly.

But right now msan thinks it's not initialized in this case:

```
$ cat foo.c
#include <regex.h>
#include <stdio.h>

int main(void) {
        regex_t regex;
        int err = regcomp(&regex, "(", REG_EXTENDED);
        if (err) {
                char msg[1024];
                regerror(err, &regex, msg, sizeof(msg));
                fprintf(stderr, "%s\n", msg);
        }
        return 0;
}
$ clang foo.c -o foo && ./foo
Unmatched ( or \(
$ clang -fsanitize=memory foo.c -o foo && ./foo
Uninitialized bytes in __interceptor_regerror at offset 0 inside [0x7ffea46b8388, 64)
==2174958==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55a4ab5754c3 in main (/home/tavianator/code/bfs/foo+0xa44c3)
    #1 0x7fac1f96630f in __libc_start_call_main libc-start.c
    #2 0x7fac1f9663c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #3 0x55a4ab4f1144 in _start (/home/tavianator/code/bfs/foo+0x20144)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/tavianator/code/bfs/foo+0xa44c3) in main
Exiting
```

**Comment by vitalybuka** [comment]
or change regerror interceptor to assume it's initialized
however original request is probably more consistent.

Would you like to make a patch?
Here is original patch which introduced them for idea what is need to be changed https://reviews.llvm.org/D54584

**Comment by tavianator** [comment]
Patch posted: https://reviews.llvm.org/D120591
