### ISSUE TITLE
Print default options in the help

### ISSUE THREAD

**Issue by jeorsch** [google/sanitizers#1528]
It would be great to have the default of all sanitizer options in the help=1 output. This is only the case for a few options so far. It should also consider user-defined defaults by the sanitizer interface functions.

**Comment by vitalybuka** [comment]
Can you please show how do you reproduce this?

ASAN_OPTIONS=help=1 my_binary
and I see all defaults, including user redefined

**Comment by jeorsch** [comment]
I used GCC 10.3 which does not show this. However, a recent LLVM does. Sorry, my fault!
