### ISSUE TITLE
How to define suppression file to suppress a call stack frame in TSan?

### ISSUE THREAD

**Issue by xwang1** [google/sanitizers#1556]
The call stack frame looks like:
#0 fun_0
#1 fun_1
#2 fun_2

I want to ignore them all when these three functions appeared in one stack frame with this sequence, is it possible to do this?

I don't think one single function match suppression format works for my scenario:
race:fun_0
race:fun_1
race:fun_3

Please advise. Thanks.

**Comment by dvyukov** [comment]
No, it's not possible to do with suppressions.

**Comment by xwang1** [comment]
Ok got it. Thanks @dvyukov
