### ISSUE TITLE
Leak detection failed if link with SDL2

### ISSUE THREAD

**Issue by jiemojiemo** [google/sanitizers#1559]
Hi folks, recently I've been learning to use SDL2 to display image or playback audio. The following simple SDL2 code failed when LSan in on:
// empty_window.cpp
```cpp
#if defined(__cplusplus)
extern "C" {
#endif

#include <SDL.h>

#if defined(__cplusplus)
};
#endif

int main(int argc, char *argv[]) {
    int quit = 0;
    SDL_Event event;

    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window *screen = SDL_CreateWindow("My SDL Empty window",
                                          SDL_WINDOWPOS_UNDEFINED,
                                          SDL_WINDOWPOS_UNDEFINED,
                                          640, 480, 0);
    for (; !quit;) {
        SDL_WaitEvent(&event);

        switch (event.type) {
        case SDL_QUIT: {
            quit = 1;
            break;
        }
        }
    }

    SDL_Quit();
    return 0;
}
```
<img width="733" alt="企业微信截图_9dd60bc2-3b04-456f-91be-93505eb46071" src="https://user-images.githubusercontent.com/13779459/183237855-5cb826c8-fc0f-4d77-a74a-72c3bc327fe9.png">

I am sure that this simple code has no any memory leak, but lsan detected.  

so it is a lsan bug ? or SDL2 has memory leak ? or I using lsan in the wrong way?

**Comment by jiemojiemo** [comment]
more details about my system:

compiler : clang 13, -DCMAKE_CXX_COMPILER=/opt/homebrew/Cellar/llvm@13/13.0.1/bin/clang++
os: macos monterey, apple m1 pro

**Comment by vitalybuka** [comment]
According to https://wiki.libsdl.org/SDL_CreateWindow SDL_DestroyWindow(window) is expected

**Comment by jiemojiemo** [comment]
> 

oh! god！how stupid I am. very thanks for you replay.
