### ISSUE TITLE
How shadow memory mapping is chosen ?

### ISSUE THREAD

**Issue by Enna1** [google/sanitizers#1562]
The comment of compiler-rt/lib/asan/asan_mapping.h says
> // Typical shadow mapping on Linux/x86_64 with SHADOW_OFFSET == 0x00007fff8000:
// || `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
// || `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
// || `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
// || `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
// || `[0x000000000000, 0x00007fff7fff]` || LowMem     ||

According to https://www.kernel.org/doc/Documentation/x86/x86_64/mm.txt 
I learned that  the address range [0000000000000000, 00007fffffffffff] is the user-space virtual memory area.

I know once SHADOW_OFFSET is determined, the other shadow memory boundaries is determined too. i.e.
```
kHighMemEnd = 0x7fffffffffff
kLowMemEnd = ASAN_SHADOW_OFFSET - 1 = 0x00007fff7fff

kHighMemBeg = MEM_TO_SHADOW(kHighMemEnd) + 1 = 0x10007fff8000
kHighShadowEnd = MEM_TO_SHADOW(kHighMemEnd) = 0x02008fff7000
kLowShadowEnd = MEM_TO_SHADOW(kLowMemEnd) = 0x00008fff6fff
```

So my question is how SHADOW_OFFSET is determined? Is it all about performance?
Thanks!

**Comment by kcc** [comment]
7fff8000 is the largest value that fits into x86_64 small immediate constant, such that  adding 7fff8000 to a register fits into one instruction with the load. So, this choice is dictated by code size (and to some extent, by performance). 
An even better SHADOW_OFFSET would be 0, but it will have more compatibility issues.
