### ISSUE TITLE
ThreadSanitizer flakily failing to detect simple data race

### ISSUE THREAD

**Issue by diegohavenstein** [google/sanitizers#1576]
While using the following C++ program with ThreadSanitizer (Clang 15.0.1)

```
#include <thread>
int global;
__attribute__((optnone)) int main() {
   std::thread t1([](){ ++global; });
   std::thread t2([](){ --global; });
   t1.join();
   t2.join();
   return 0;
}
```

the program fails (as it should) most of the time. However, approx in 1 out of 1000 runs, it does not raise an error

Is this a known issue?

Happy to provide more details if needed

**Comment by dvyukov** [comment]
Hi @diegohavenstein,

Yes, it's a know issue. This is working-as-intended. There is an intentional trade-off between some false negatives and performance.
