### ISSUE TITLE
symbolize stack traces using code from lldb

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#16]
Originally reported on Google Code with ID 16
```
We need to symbolize error messages in process. 
Looks like we can share some code with lldb. 
See http://comments.gmane.org/gmane.comp.debugging.lldb.devel/650

Such code will be useful for other dynamic tools as well. 
```

Reported by `konstantin.s.serebryany` on 2011-12-12 23:43:41

**Comment by kcc** [comment]
We are using llvm-symbolizer by default, although out-of-process. Closing this bug. 
Using llvm-symbolizer in-process is a separate story.
