### ISSUE TITLE
Have tsan support whitelist for filter some files in specific directory?

### ISSUE THREAD

**Issue by Squirre17** [google/sanitizers#1602]
A project base on another project, but What should I do if I want only instrumentation former project.

**Comment by Enna1** [comment]
See https://github.com/llvm/llvm-project/blob/main/compiler-rt/test/tsan/ignorelist.cpp for example.

**Comment by Enna1** [comment]
BTW, if some components are tsan-instrumented, some components are not tsan-instrumented, there will be a high possibility of false positives.

**Comment by Squirre17** [comment]
> BTW, if some components are tsan-instrumented, some components are not tsan-instrumented, there will be a high possibility of false positives.

Thx for u help, I will give it a try.
