### ISSUE TITLE
Ternary operator is ignored, while if-else is correctly detected

### ISSUE THREAD

**Issue by gluk47** [google/sanitizers#1604]
This code snippet triggers no warning:
```
int main() {
    int a;
    cout << (a == 0 ? "zero" : "garbage") << endl;
}
```

whereas this one issues a warning as it should:
```
int main() {
    int a;
    const char* msg = "zero";
    if (a)
        msg = "garbage";
    cout << msg << endl;
}
```

Looks like ternary condition is not considered to be a condition enough to trigger the check.
Tested with clang 14.0.0 `-fsanitize=memory -g -Wall -O0 -fPIE -pie -fno-omit-frame-pointer`.

**Comment by eugenis** [comment]
Right. It's a bit of an implementation detail, and optimization level
dependent, too. In the first snippet a poisoned pointer will be passed to
cout.

The problem here is that cout does not catch that its argument is poisoned.
Newer clang should detect this with -fsanitize-memory-param-retval flag.

**Comment by gluk47** [comment]
Tested with `-fsanitize-memory-param-retval`, it works on clang 14.0.0, I see the warning. I suggest it become a default behavior, but, I guess, there are reasons to not do so. Thank you in any event.
