### ISSUE TITLE
App failed to mmap when running TSAN

### ISSUE THREAD

**Issue by OldChicken1** [google/sanitizers#1607]
I compiled my app with -fsanitize=thread -fPIE -pie, and the program can produce tsan reports. But when my code tries to mmap address at 0x400000000000, it failed. Then I used gdb to debug the program, and I found out mmap returned -1 by libtsan.so. So my question is that what virtual address range cannot be used to mmap? 
![image](https://user-images.githubusercontent.com/35505296/212254860-df745f6f-e35a-4264-b171-cf716d2617d5.png)
And what are the differences among low mid high app mem ranges?

**Comment by dvyukov** [comment]
> So my question is that what virtual address range cannot be used to mmap?

Only the "App" ranges (that you highlighted) are supported for the program mmaps.

> And what are the differences among low mid high app mem ranges?

No differences from this point of view.
