### ISSUE TITLE
MemorySanitizer does not detect use of uninitialized memory in dynamically allocated array

### ISSUE THREAD

**Issue by cla7aye15I4nd** [google/sanitizers#1622]
The following code example contains a use of uninitialized memory in a dynamically allocated array. However, when running the code with the MemorySanitizer (msan) tool, no errors are reported.

```c++
#include <stdio.h>
#include <stdlib.h>

__attribute__((noinline)) int* g() {
  return malloc(10 * sizeof(int));
}

int main() {
  printf("%d\n", g()[2]);
  return 0;
}
```

As can be seen, the `g()` function returns a pointer to a dynamically allocated memory block of 10 integers, but the contents of this block are not initialized. The third element of the array is then accessed using `g()[2]`, which should lead to undefined behavior due to the use of uninitialized memory.

However, when running this code with msan, no errors are reported, which indicates that msan is not detecting the use of uninitialized memory.

I am using the following configuration:

- Operating system: Ubuntu 22.04
- Compiler: Clang 15.0.6 / Clang 12.0.0
- Command used to compile and run the code: `clang -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer -g -O2 a.c && ./a.out `

Please let me know if any further information is needed to investigate this issue.

Thank you.

**Comment by vitalybuka** [comment]
https://godbolt.org/z/oz4eKhKeo

Before clang 16, msan checked only conditional branching on uninitialized variables.
With clang 16 it also check most function arguments and return values, like here for printf.

You can enabled similar behavior in older compilers with -fsanitize-memory-param-retval
Should work with clang 15, but not 12.
