### ISSUE TITLE
ASAN Increase The Memory Consumption Continually

### ISSUE THREAD

**Issue by b-altin** [google/sanitizers#1625]
We are using ASAN with the following flag and default environment variables. However, we observe that memory usage is continually increasing in the service. Like from around 200 MB to 2 GB. Besides, traffic is running on the service and which means that the service always allocates and deallocates memory. So, the ASAN always gets new memory from RAM, or deallocated memory is allocated again when it is requested? In addition to this, we know the env parameter named quarantine_size_mb. It provides a memory cache for freed memory. Let's say the default or set value is 256 Mbytes, does it mean that the memory max 256 Mbytes swell? Could you please help us with this issue?

cmake .. '-DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer" "-fsanitize=address" -DCMAKE_C_FLAGS="-fno-omit-frame-pointer" "-fsanitize=address" -DCMAKE_EXE_LINKER_FLAGS="-fno-omit-frame-pointer" "-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fno-omit-frame-pointer" "-fsanitize=address"'

**Comment by vitalybuka** [comment]
You can try to tweak these runtime options as well:
detect_stack_use_after_return or max_uar_stack_size_log
compress_stack_depot=2

**Comment by vitalybuka** [comment]
Also there is [__sanitizer_print_memory_profile() ](https://github.com/llvm/llvm-project/blob/bbaa5685b2c3460616ed799ba19cdd3aa9514c01/compiler-rt/lib/asan/asan_memory_profile.cpp#L120)
which can be called periodically from your app

**Comment by b-altin** [comment]
@vitalybuka, we suspect the ASAN lib. If the ASAN always provides new memory (instead of freed memory) when we request a memory (malloc, new, etc.). Is it possible or not?

**Comment by vitalybuka** [comment]
> @vitalybuka, we suspect the ASAN lib. If the ASAN always provides new memory (instead of freed memory) when we request a memory (malloc, new, etc.). Is it possible or not?

It has quarantine_size_mb, at some point it should start reuse feed memory.

**Comment by b-altin** [comment]
Thank you @vitalybuka, we will analyze the code with detailed. Currently, it seems that there is no issue on the ASAN side.
