### ISSUE TITLE
TSAN: atomic will cause data race undetected.

### ISSUE THREAD

**Issue by JackyWoo** [google/sanitizers#1645]
### Env
```
clang -v
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Test case

1. data race detected
```
// bad case: data race detected
void testDataRace()
{
    int32_t counter = 0;

    std::thread t1([&counter] {
        if (!counter)
            counter = 1;
    });
    std::thread t2([&counter] {
        if (!counter)
            counter = 2;
    });

    t1.join();
    t2.join();
}
```
2.  not detected when use atomic
```
// For user it is a bad case, but not detected
void testDataRaceAtomic()
{
    std::atomic<int32_t> counter = 0;

    std::thread t1([&counter] {
        if (!counter)
            counter = 1;
    });
    std::thread t2([&counter] {
        if (!counter)
            counter = 2;
    });

    t1.join();
    t2.join();
}
```

As a user's perspective  the behavior is unexpected.

**Comment by dvyukov** [comment]
Hi,

What's the definition of unexpected behavior?
Is it always a bug?
How can it be detected programmatically?

**Comment by JackyWoo** [comment]
@dvyukov Thanks for reply.  I just wonder whether case 2 should report a warning.

**Comment by dvyukov** [comment]
I don't know. Should it? Maybe the intention of the program is to produce 1 or 2 at random.

**Comment by JackyWoo** [comment]
Pls see this case, it is data condidition case. TSAN can not detect it now. I wonder whether TSAN will detect it.

```
// For user it is a bad case, but not detected
void testDataRaceAtomic()
{
    std::atomic<int32_t> counter = 0;

    std::thread t1([&counter] {
        counter = counter + 1;
    });
    std::thread t2([&counter] {
        counter = counter + 1;
    });

    t1.join();
    t2.join();
}
```

**Comment by dvyukov** [comment]
What's the definition of unexpected behavior?
Is it always a bug?
How can it be detected programmatically?

**Comment by JackyWoo** [comment]
> What's the definition of unexpected behavior?
The result of counter is not determinastic, maybe 1 or 2.  As a user's perspective it should be 2 and determinastic.

> How can it be detected programmatically?
I am new to TSAN and I have no idea.

**Comment by dvyukov** [comment]
This can be detected as data race if tsan will treat atomic variables as non-atomic.
But then it will simply report races on all atomic operations as all of them are non-deterministic (what you want to detect).
But you can achieve the same effect simply by grepping your code for atomic operations. As any static approach this won't even require good test coverage. So there is little point in adding this to tsan.

**Comment by JackyWoo** [comment]
Thank you.
