### ISSUE TITLE
Suppress leaks from <unkown module>

### ISSUE THREAD

**Issue by pfirsich** [google/sanitizers#1653]
I get a bunch of these:
```
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x5622b1e78336 in __interceptor_realloc (/home/joel/dev/c++/template_meson/build/main+0xce336) (BuildId: 6da686e190ff1e948b1e36ecb924e19d1f50c480)
    #1 0x7ff2300985a2  (<unknown module>)
```
Which last time I checked were part of my graphics driver and x11 libraries. I just want to ignore them. I know there was a [PR](https://reviews.llvm.org/D121674) that introduced "unknown module", specifically to suppress it, but none of the following lines work:
```
leak:^<unknown module>$
leak:<unknown module>
leak:unknown module
leak:unknown
```
It would be good if I could also suppress by function address, e.g. `leak:0x7ff2300985a2` for the example above, but that also doesn't work. The suppression file is used, because if give it a wrong path it errors and when I create deliberate leaks I can ignore them with that file, so I am sure that the rules just don't work.
I see this problem on GCC 11 (Ubuntu 11.3.0-1ubuntu1~22.04) and Clang 14.0.0-1ubuntu1.

**Comment by Enna1** [comment]
Hi, can you update your clang to clang-15 or newer?
As you can see in https://reviews.llvm.org/source/llvm-github/tags/main/;a63932a8152d23acf2905a1956b95b290d6703ad, this patch is landed since clang-15. I suppose clang-14 does not have this patch.

**Comment by pfirsich** [comment]
I thought I would have this patch simply because I have the "unknown module" output. It still seems to me that it was this commit that introduced it. Am I misunderstanding? I'll try clang 15 soon.

**Comment by pfirsich** [comment]
It seems I cannot reproduce these leaks at all anymore, so I can't test if clang15 fixed it. I will just assume that my compiler was probably not new enough for this to work and close this issue for now. Thank you!
