### ISSUE TITLE
Using flag -fsanitize-address-use-after-return=runtime yields Wunused-command-line-argument.

### ISSUE THREAD

**Issue by anzosasuke** [google/sanitizers#1658]
I am using clang-17 and using the flag as -fsanitize-address-use-after-return=runtime tried always too, but it seems to not work all the time, I don't know why?

**Comment by Enna1** [comment]
Did you use `-fsanitize=address` and `-fsanitize-address-use-after-return=runtime` together?

**Comment by anzosasuke** [comment]
oh.... thanks so much.
