### ISSUE TITLE
MemorySanitizer: Incorrect error 'use-of-uninitialized-value' when returning pair created using std::piecewise_construct

### ISSUE THREAD

**Issue by devzeb** [google/sanitizers#1697]
Minimal code example of the issue:
https://godbolt.org/z/7ofPK8xhx

Memory Sanitizer incorrectly reports `use-of-uninitialized-value` even though the value is initialized.

Compiler used: clang-16

(When you switch to clang-17, the function `example_working_with_clang_16()` also shows this weird behavior)

**Comment by Enna1** [comment]
MSan-instrumented C++ standard library is needed, see https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

**Comment by devzeb** [comment]
Alright, this wasn't apparent from the documentation I read on the clang website. Closing this now, sorry for the inconvenience.
