### ISSUE TITLE
hwasan can not use lsan

### ISSUE THREAD

**Issue by chengkexincccccck** [google/sanitizers#1709]
Asan defaults to enabling Lsan, which allows us to detect memory issues such as leaks and overflows. However, after Android 14, it seems that we cannot use the Lsan feature as it has been changed to Hwsan."

**Comment by vitalybuka** [comment]
Lsan for Android was incomplete, for either asan or hwasan.

**Comment by chengkexincccccck** [comment]
However, in asan, lsan can be used by default. Will this implementation be integrated into hwasan?～

**Comment by vitalybuka** [comment]
> However, in asan, lsan can be used by default. Will this implementation be integrated into hwasan?～

Yes, but neither will detect leaks on Android.

**Comment by chengkexincccccck** [comment]
Has Hwasan integrated the functionality of Lsan? This is really good news! We will do our own adaptation for Android in our project, but we just need Hwasan to have Lsan enabled by default like Asan.

**Comment by chengkexincccccck** [comment]
May I ask if hwasan has already integrated lsan or if there are plans to integrate lsan? If it is planned, can you share an expected update schedule? Thanks！

**Comment by Enna1** [comment]
> May I ask if hwasan has already integrated lsan

AFAIK, yes.
see https://reviews.llvm.org/D146098
