### ISSUE TITLE
can not be detected by asan

### ISSUE THREAD

**Issue by BigFaceBoy** [google/sanitizers#1722]
I write the demo:
```
void test_heap_buffer_overflow(){
    int *array = new int[100];
    array[0] = 0;
    int res = array[50 + 100];
    delete [] array;
}

void test_stack_buffer_overflow(){
    int stack_array[100];
    stack_array[1] = 0;
    int a = stack_array[50 + 100];
}


int global_array[100] = {-1};
int test_global_buffer_overflow(){
    return global_array[1 + 100];
}
void test_memory_leak(){
    std::cout<<"test leak"<<std::endl;
    int* array = (int*)malloc(sizeof(int) * 10);
    array[0] = 0;
}

int main(){

    //test_use_after_free();

    test_heap_buffer_overflow();

    test_stack_buffer_overflow();
    
    test_global_buffer_overflow();

    test_memory_leak();
}
```
compile with 
`set(CMAKE_CXX_FLAGS "-fsanitize=address -fno-omit-frame-pointer -O -g")`
gcc version: 10.2.1
cmake is :3.27.1
run the code, the error can not be deteced.why this happened?

**Comment by Enna1** [comment]
They were optimized out by compiler, try remove `-O` from your CMAKE_CXX_FLAGS.

**Comment by BigFaceBoy** [comment]
@Enna1 It doesn`t work

**Comment by Enna1** [comment]
See https://godbolt.org/z/fb9Mxnrd5

**Comment by BigFaceBoy** [comment]
@Enna1 I find out that if i use the value (like print it) in these overflow demo, it will be detected then. But the leak demo still can not be detected

**Comment by BigFaceBoy** [comment]
@Enna1 I find out why. I set the  CMAKE_BUILD_TYPE is Release, and -O3 is default added to CMAKE_CXX_FLAGS_RELEASE.
