### ISSUE TITLE
how environment variable split? by space or by colon ?

### ISSUE THREAD

**Issue by comicfans** [google/sanitizers#1794]
hello, I've found document

https://github.com/google/sanitizers/wiki/AddressSanitizer gives example for multi options in ASAN_OPTIONS
```
ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1
```
but on page

https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags
```
Runtime flags are passed via TSAN_OPTIONS environment variable, separate flags are separated with spaces, e.g.:

$ TSAN_OPTIONS="history_size=7 force_seq_cst_atomics=1" ./myprogram
```

does it mean ASAN_OPTIONS and TSAN_OPTIONS have different format?  or is this documentation out of date? which one should I follow if I want to pass common flags https://github.com/google/sanitizers/wiki/SanitizerCommonFlags ?

**Comment by Enna1** [comment]
> does it mean ASAN_OPTIONS and TSAN_OPTIONS have different format?

*SAN_OPTIONS share same format.
Both space and colon can be used as environment variable separator.

Personally I use colon.

**Comment by comicfans** [comment]
I hope the documents can improve a little on this, sometimes confusing.
