### ISSUE TITLE
Porting to a new target (AArch64)

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#246]
Originally reported on Google Code with ID 246
```
Hello,

I am currently working on enabling address-sanitizer in GCC for AArch64.

I am not sure if this is the right channel to ask for support?

I have made some changes necessary to have it build for this new target (GetPcSpBp,
syscalls, ...) but now I am facing runtime problems:
==15518==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504)
bytes at address 0x02008fff7000 (12)
==15518==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps
you're using ulimit -v

In my case, in asan_rtl.cc, full_shadow_is_available is false, and I guess I have to
give sensible values to kMidMemBeg and kMidMemEnd.

How do I compute the right values, and will this fix the error message above?

Thanks

```

Reported by `christophe.lyon@linaro.org` on 2013-11-22 12:14:13

**Comment by ramosian-glider** [comment]
Closing as stale.
There's some AArch64 support upstream already.

**Comment by fangqingdu** [comment]
Hello,
I have the same issue with clang address-sanitizer:
_==21786==ERROR: AddressSanitizer failed to allocate 0x400000000 (17179869184) bytes at address 67fff8000 (errno: 12)
==21786==ReserveShadowMemoryRange failed while trying to map 0x400000000 bytes. Perhaps you're using ulimit -v
Aborted (core dumped)_

Just a small case:
```
int main() {
    int *mem = new int[100];
    for (unsigned i = 0; i<=100; i++ ) {
        mem[i] = i;
    }
    return 0;
}
```
I compiled this code on redhat6.5:
fangqing@[xhdengvm155043 addr_sanitizer]$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.5 (Santiago)
fangqing@[xhdengvm155043 addr_sanitizer]$ uname -a
Linux xhdengvm155043 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 
x86_64 GNU/Linux
fangqing@[xhdengvm155043 addr_sanitizer]$ ulimit -v
unlimited

And compile command is:
clang++ -fsanitize=address -fsanitize=undefined main.cp

**However, when I compile this code on redhat5.6, It works fine:**
fangqing@[xhdvdieodvm102 addr_sanitizer]$ uname -a
Linux xhdvdieodvm102 2.6.18-371.4.1.el5 #1 SMP Wed Jan 8 18:42:07 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
fangqing@[xhdvdieodvm102 addr_sanitizer]$ cat /etc/redhat-release
Red Hat Enterprise Linux Client release 5.9 (Tikanga)

So I want to know what lead this error? And how can I resolve this?
Thanks a lot!

**Comment by kcc** [comment]
We are already discussing this on cfe-dev@lists.llvm.org.
Please don't hijack old unrelated bugs.  
A new bug here would be appropriate.

**Comment by fangqingdu** [comment]
I'm sorry for this, and I have delete my last comment.
Thanks kcc!
