### ISSUE TITLE
remove the limit of the number of ever existed threads in asan 

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#273]
Originally reported on Google Code with ID 273

```
Today asan will die after 4M threads are created, because we keep some 
small amount of metadata for every thread that ever lived. 
We should eventually remove this limitation. 
```

Reported by `konstantin.s.serebryany` on 2014-03-11 08:51:27

**Comment by Randl** [comment]
This issue is pretty annoying on big/mulithreaded projects. Ping?

**Comment by kcc** [comment]
We have no immediate plans to address this. 
The change will be very non-trivial, will add extra complexity, and will not solve any problem for the majority of users. I am sorry for that. :(

**Comment by morehouse** [comment]
@kcc:  Do we want to keep this open or not?

**Comment by brunoczim** [comment]
A different exit code for thread limit would help a lot

**Comment by cleary3** [comment]
(I know, I know: old closed thread. But, for folks that arrive here via a web search, as I did, I'm adding the context below.)

Looks like this limit has been removed in newer versions of the sanitizer. I see it removed here from LLVM: https://reviews.llvm.org/D105713. And this looks to have been merged in for GCC 12.x.
