### ISSUE TITLE
Enable malloc/delete/new/free mismatch checks on Windows

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#309]
Originally reported on Google Code with ID 309
```
This is a bug to track the progress of enabling malloc/delete/new/free mismatch checks
on Windows.

They were probably disabled because these mismatches are usually safe on Windows, so
there should be quite a few places in e.g. Chromium where these checks fire.

I think we currently don't have any way to control these checks on per-function basis,
it's either completely off or on.
```

Reported by `timurrrr@google.com` on 2014-05-12 14:01:04

**Comment by rnk** [comment]
Personally I expect this will be a huge pile of work. It is much more difficult to reliably interpose operator new / delete on Windows, and that's what's needed to implement this.

Given that this is really hard and nobody is working on it, we can close it for now.
