### ISSUE TITLE
Expose __sanitizer_symbolize_pc()

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#322]
Originally reported on Google Code with ID 322
```
I had to add this interface function today when hacking on NSS crypto code, which uses
function pointers heavily. I needed to know which function was being called by pointer
and this was the best solution I could come up with. Looks like it would require almost
zero effort to add this to our interface. Opinions?
```

Reported by `earthdok@google.com` on 2014-06-26 18:57:38

**Comment by kcc** [comment]
We also need __sanitizer_print_stack_trace in all the sanitizers.

**Comment by kcc** [comment]
__sanitizer_symbolize_pc is added
__sanitizer_print_stack_trace also seems to be in every sanitizer now.
