### ISSUE TITLE
Documentation on runtime flags

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#446]
Originally reported on Google Code with ID 39
```
ThreadSanitizer has more runtime flags than documented on
http://code.google.com/p/thread-sanitizer/wiki/Flags

Missing flags include suppress_equal_stacks, suppress_equal_addresses,
report_atomic_races, which are useful not only for those, who read
TSan's sources.

Could you, please, add documentation on missing flags to the wiki?

```

Reported by `yegor.derevenets` on 2013-11-15 20:04:55

**Comment by ramosian-glider** [comment]
Hope to update the flags pages this week as part of another activity.
Closing the bug.

**Comment by jacobsa** [comment]
@ramosian-glider It looks like you didn't actually update the documentation. Can you please reopen? (I'm here looking for docs on `report_atomic_races`.)

**Comment by ramosian-glider** [comment]
@jacobsa please see https://github.com/llvm/llvm-project/pull/205761

Overall, as stated at https://github.com/google/sanitizers, this repository is archived, and we won't be maintaining any documentation here.

Please request further changes to llvm/llvm-project if needed.

**Comment by jacobsa** [comment]
Ack, sorry for missing that.
