### ISSUE TITLE
Postpone shadow checks until function exit

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#506]
Originally reported on Google Code with ID 3

```
We can replace some or all (configurable) shadow checks with OR'ed stores to a local
temp, then add a check for this temp's value at all exits from the function.

This will make reports much less precise, but may significantly improve performance.

```

Reported by `eugenis@google.com` on 2012-08-28 09:43:08

**Comment by morehouse** [comment]
@eugenis:  Any progress on this?

**Comment by dvyukov** [comment]
I looked at a bunch of KMSAN reports lately and if anything I would suggest to _improve_ precision of reporting rather than making it worse.

**Comment by kcc** [comment]
I guess we can close this one.
