### ISSUE TITLE
Use -fsanitize=recover instead of -mllvm -msan-keep-going

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#515]
Originally reported on Google Code with ID 12

```
.
```

Reported by `eugenis@google.com` on 2013-01-22 13:41:48

**Comment by sitsofe** [comment]
It sounds like asan has grown the recovery capability (but when?) according to issue #649 ...

**Comment by kcc** [comment]
yes, it did.

**Comment by eugenis** [comment]
I don;t think this is fixed yet.

**Comment by morehouse** [comment]
Is `-msan-keep-going` still used anywhere?  I only see it as a legacy test in `test/msan/recover.cc` and `test/msan/recover-dso.cc`.

**Comment by eugenis** [comment]
I believe this is fixed.

**Comment by krytarowski** [comment]
I'm just about to give it a try as I need it for the development of a MKSANITIZER/NetBSD distribution.... init(8) dies early and I want to catch low hanging fruits checking what works.
