### ISSUE TITLE
Install a SIGSEGV handler in MSan

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#575]
Originally reported on Google Code with ID 72

```
Report null derefs properly. We can reuse ASan's handler.
```

Reported by `earthdok@google.com` on 2014-11-20 17:20:18

**Comment by morehouse** [comment]
This seems related to https://github.com/google/sanitizers/issues/262.

@vitalybuka, do we have this for MSan now?

**Comment by vitalybuka** [comment]
Yes.
