### ISSUE TITLE
"FATAL: ThreadSanitizer can not mmap the shadow memory error" during start of JVM with a java application

### ISSUE THREAD

**Issue by BhupendraThosare** [google/sanitizers#616]
Hi All,

OS: RHEL7  (x86_64 GNU/Linux)
Kernal: 3.10.0-123.8.1.el7.x86_64
Compiler: gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)
RAM: 24 GB

Our product contains shared libraries, archive libraries, java programs (jars) and many executable (c, c++, java).
Our aim is to evaluate the value of Tsan (thread sanitizer) for our product and find concurrency issues.

Therefore, we have built all shared libraries and executable (c, c++) with tsan enabled as follows:
Compile flags: -fsanitize=thread -g
Shared library linking flags: -fsanitize=thread -shared -lpthread -ldl
Executable linking flags: -fsanitize=thread -pie -lpthread -ldl
Note: We have also linked "-ltsan" wherever required.

In addition, we have built object files associated with archive library with "-fPIC" to fix following type of compilation error.
/bin/ld: something.a(something.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

When we execute our product then it causes following error:
FATAL: ThreadSanitizer can not mmap the shadow memory (something is mapped at 0x400000 < 0x7cf000000000)
FATAL: Make sure to compile with -fPIE and to link with -pie

Please note that all the executable/binaries are built with "-fsanitize=thread -pie" as mentioned above.
However, above fatal error occurs when one binary execute some script using "execvp" and script internallty tries to start JVM using following command.
$JAVA_HOME/bin/java -- -ms512m $MAX_MEMORY $FONTS -classpath $CLASSPATH \
$SYSTEM_PROPERTIES $MAIN_CLASS -port $PORT_NUMBER $*

where, $MAX_MEMORY=1855m

Please let us know your suggestion to avoid fatal error mentioned above.
Any help would be highly appreciated!

**Comment by dvyukov** [comment]
Currently tsan works only for C/C++ and Go programs.
You said you have some C/C++ executables, you can build just them with -fsanitize=thread (and any shared libraries they use). This should work.
It is always impossible to make JVM work with tsan. You would need to rebuild Java launcher with -fsanitize=thread, but even them I suspect something won't work.
If you want to test C/C++ code invoked from Java using JNI, there is a relatively simple way to do it: write a C++ test program that invokes that code roughly the same way as Java. That test will be easy to run with tsan.

**Comment by BhupendraThosare** [comment]
Thank you very much for your reply.
