### ISSUE TITLE
coverage-reset.cc flaky on android

### ISSUE THREAD

**Issue by eugenis** [google/sanitizers#618]
Both on arm and x86. Easily reproducible locally (~1 out of 20 runs).
coverage-reset.cc:29: int main(): assertion "IS_POWER_OF_TWO(main_bit)" failed
guard array at the first assert, where it is expected to contain just 1 non-zero element, contains 2 or even 3 of those.

**Comment by morehouse** [comment]
Does this still happen on Android?

**Comment by kcc** [comment]
We've killed all of sancov-for-android code.
