### ISSUE TITLE
-fsanitize-undefined-trap-on-error generates ambiguous debug locations

### ISSUE THREAD

**Issue by eugenis** [google/sanitizers#622]
Building with
-fsanitize-undefined-trap-on-error -ftrap-function=abort
all checks inside one functions are jumping to a single abort() call. This way it's impossible to tell which one has failed, and there may be dozens of checks in larger functions.

We should consider doing something similar to what ASan does to ensure that calls to __asan_report_* are not merged.

**Comment by mikea** [comment]
Moved to LLVM bug tracker: https://llvm.org/bugs/show_bug.cgi?id=25682
