### ISSUE TITLE
Data race at spinlock implemented using std:: facilities.

### ISSUE THREAD

**Issue by kevgs** [google/sanitizers#623]
Hi.

gcc --version
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

https://gist.github.com/kevgs/31a528aa442fd39f639a

Is this a false positive or a real data race?

**Comment by dvyukov** [comment]
This is a false positive caused by the fact that gcc does not seem to instrument atomic operations.
Please file a bug on gcc at:
https://gcc.gnu.org/bugzilla/
Or if you wish I can do it.

**Comment by dvyukov** [comment]
This code works fine with clang -fsanitize=thread.

**Comment by kevgs** [comment]
Done. Thanks for the quick reply.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68260
