### ISSUE TITLE
Can't get symbols in LeakSanitizer report

### ISSUE THREAD

**Issue by mark456** [google/sanitizers#635]
I get symbols from AddressSanitizer, but not from LeakSanitizer. Exporting ASAN_SYMBOLIZER_PATH in the terminal works, but exporting LSAN_SYMBOLIZER_PATH does not. What do I have to do?

**Comment by kcc** [comment]
Please give the exact reproduction steps and your version of the compiler -- then reopen.

**Comment by vonosmas** [comment]
(note that you can just add directory with llvm-symbolizer binary to your PATH, then you won't need to set any env variables).
