### ISSUE TITLE
 Can't get symbols in LeakSanitizer report

### ISSUE THREAD

**Issue by mark456** [google/sanitizers#636]
#635

I get symbols from AddressSanitizer, but not from LeakSanitizer. Exporting ASAN_SYMBOLIZER_PATH in the terminal works, but exporting LSAN_SYMBOLIZER_PATH does not. What do I have to do?

Reproduction steps are more or less these:

Install Ubuntu 15.10 64-bit on an Intel core i3 machine

$ sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
$ sudo apt-get update
$ sudo apt-get -y install build-essential
$ sudo apt-get -y install clang-3.6
$ sudo apt-get -y install libc++-dev

$ export ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.6/bin/llvm-symbolizer
$ export LSAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.6/bin/llvm-symbolizer

$ export PATH=$PATH:/usr/lib/llvm-3.6/bin

$ clang-3.6 -g -fsanitize=leak -stdlib=libc++ -pthread -std=c++14 -osomething something.cpp -lc++
$ ./something

When the application exits LeakSanitizer prints:

==24164==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 280 byte(s) in 7 object(s) allocated from:
    #0 0x456100 in calloc (/home/mark456/Desktop/something/something+0x456100)
    #1 0x7f8ddfcbb8e1 in _init (/usr/lib/x86_64-linux-gnu/dri/i965_dri.so+0x2a78e1)

etc.

And I think instead of 0x456100 there should be a symbol like when AddressSanitizer prints its report.

**Comment by kcc** [comment]
One potential problem here is 15.10: sadly we don't test lsan on such a new system. 
Another problem is clang-3.6. Does the same reproduce with the most recent clang (from trunk)?

Just in case, please also attach something.cpp

**Comment by vonosmas** [comment]
Please provide the output of
```
echo 0x456100 | /usr/lib/llvm-3.6/bin/llvm-symbolizer -obj=/home/mark456/Desktop/something/something
```

It's possible that calloc() just doesn't have debug info (file-line info) associated with it.

**Comment by mark456** [comment]
echo 0x456100 | /usr/lib/llvm-3.6/bin/llvm-symbolizer -obj=/home/mark456/Desktop/something/something

prints

calloc
??:0:0

**Comment by kcc** [comment]
That's fine. Calloc just resides in the stripped part of the binary (that comes from asan/lsan run-time). 
What is strange is why we have this report in the first place. 
Can you attach something.cpp?

**Comment by mark456** [comment]
@kcc

Using the trunk version will take me some time, I've so far relied on installing Ubuntu packages. :) And clang-3.7 from Ubuntu has some problem https://llvm.org/bugs/show_bug.cgi?id=22757

I'll add something.cpp or a test.cpp, I need to strip it down to something readable, it's a a bit too chaotic.

**Comment by kcc** [comment]
I've just tried a simple test on a fresh 15.10 VM. 
As long as you do `export PATH=/usr/lib/llvm-3.6/bin/:$PATH` everything seems to work fine. 
So, this is something about your particular test. 
Please reopen when you have a reproducer (test.cpp, whatever)

**Comment by vonosmas** [comment]
It's pretty clear the problem is not with symbolization: it's just the stack trace is too short - it contains two entries and both functions don't have file/line info associated, one from LSan runtime (calloc), and one from _init from i965_dri.so.

It's also likely a false positive. If calloc() is called very early (before __lsan_init), then LSan's calloc will allocate memory from special buffer, which is (probably) not added to root regions during leak detection
(also see https://github.com/google/sanitizers/issues/626)

**Comment by vonosmas** [comment]
Another request:
could you run
$ gdb ./something
$ br __lsan_init
$ br calloc
$ r
$ c (until the program exits)

**Comment by mark456** [comment]
(gdb) br __Isan_init
Function "__Isan_init" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (__Isan_init) pending.
(gdb) br calloc
Breakpoint 2 at 0x456004
(gdb) r
Starting program: /home/mark456/Desktop/something/something

Breakpoint 2, calloc (nmemb=1425, size=1) at dl-minimal.c:102
102	dl-minimal.c: No such file or directory.
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1169, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1178, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1181, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1179, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1183, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1180, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1180, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c
Continuing.

Breakpoint 2, calloc (nmemb=1184, size=1) at dl-minimal.c:102
102	in dl-minimal.c
(gdb) c

..goes on and on..

**Comment by vonosmas** [comment]
That's weird, you should have __lsan_init if you've actually linked your executable with -fsanitize=leak: try
$ nm ./something | grep __lsan

Could you print backtraces of calloc() invocations and find the one (or ones) originating from i965_dri.so?

**Comment by kcc** [comment]
... or just attach a small reproducer, we can take it from there.

**Comment by mark456** [comment]
I should mention that I actually (that's why I wrote "more or less") use GL, GLUT, alsa etc. I think I might leak a texture, some GL driver (965something?) consequently leaks an calloc, and that I've chosen to link statically, so basically I'm supposed to see something+0x12345678 because there's the statically linked calloc. And backtracing would fail because I don't really debug symbols or the complete trace from the GL driver.

**Comment by mark456** [comment]
@vonosmas 
Yes, although I've compiled with "-fsanitize=leak", "nm ./something | grep __lsan" will not print anything.

**Comment by vonosmas** [comment]
This is weird: if you have no LSan symbols, LSan will not run a leak detection :) Make sure you've also linked with -fsanitize=leak, not just compiled. Anyway, it seems to be tricky to figure out what the problem is remotely, w/o the standalone reproducer.
