### ISSUE TITLE
unify handle_segv/handle_abort/handle_sigill/handle_sigfpe across sanitizers

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#637]
asan/tsan/msan/ubsan should support handle_segv/handle_abort/handle_sigill/handle_sigfpe
in the same way, with the same defaults. 

Error reports should print the signal name properly (today, we print SEGV for ABRT)

Also check what should be done with SIGBUS, if anything

**Comment by inferno-chromium** [comment]
and cfi as well.

can this be prioritized ? we cannot enable --disable-in-process-stacktraces on chromium for ubsan/msan/tsan/cfi since they wont catch the sigabrt.

**Comment by eugenis** [comment]
Could you elaborate? Cfi in chromium does not have a runtime library at
all. There is no way for it to handle sigabrt.

**Comment by inferno-chromium** [comment]
Checkout https://bugs.chromium.org/p/chromium/issues/detail?id=716235
Basically we have added a flag --disable-in-process-stack-traces in chromium that makes sure that chromium does not catch sigabrt and instead passes it to sanitizer. with sanitizer, we get good stack frames to work upon and they can be symbolized properly (with line number). chromium sigabrt handler does not give line numbers, also, does not ignore inline frames which we use for testcase deduplication.

**Comment by eugenis** [comment]
Oh right, sorry about that. Of course cfi has a runtime library - it uses
ubsan_standalone in diagnostics mode.

**Comment by inferno-chromium** [comment]
I don't think this works on mac, can you please take a look.
E.g.
https://clusterfuzz.com/v2/testcase-detail/5992945101832192

**Comment by vitalybuka** [comment]
Could you please clarify what is wrong with report. Mac CHECK error looks similar to Linux one https://clusterfuzz.com/v2/testcase-detail/6312664245731328.

Also for different signal works as expected on mac: https://clusterfuzz.com/v2/testcase-detail/6541624137220096

**Comment by inferno-chromium** [comment]
Check failures should result in SIGABRT stack at end. E.g. see on that linux testcase link, you will see this. We are not seeing this on Mac, it could be chromium side issue as well. Didn't know Sigill was catching fine, thanks for link.

=================================================================
--
  | ==1==ERROR: AddressSanitizer: ABRT on unknown address 0x03e900000001 (pc 0x7f370e8a4c37 bp 0x7ffc097a0970 sp 0x7ffc097a0838 T0)
  | SCARINESS: 10 (signal)
  | ==1==WARNING: invalid path to external symbolizer!

**Comment by vitalybuka** [comment]
It looks like Mac uses "#define DEBUG_BREAK_ASM() asm("int3") instead of abort 
https://cs.chromium.org/chromium/src/base/debug/debugger_posix.cc?sq=package:chromium&l=228&ssfr=1
