### ISSUE TITLE
ASan fails with internal CHECK on double free in recovery mode.

### ISSUE THREAD

**Issue by chefmax** [google/sanitizers#639]
$ cat test.c

```
#include <stdlib.h>
int main() {
  int i = 0;
  void *p = malloc(10);
  free(p);
  free(p);
  return 0;
}
```
$ clang -fsanitize=address -fsanitize-recover=address -g test.c
$ ASAN_OPTIONS=halt_on_error=false ./a.out
```
=================================================================
==13154==ERROR: AddressSanitizer: attempting double-free on 0x60200000eff0 in thread T0:
    #0 0x4af86b in free /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:38:3
    #1 0x4d9ae7 in main /tmp/2.c:8:3
    #2 0x7f5d828b0ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #3 0x418585 in _start (/tmp/a.out+0x418585)

0x60200000eff0 is located 0 bytes inside of 10-byte region [0x60200000eff0,0x60200000effa)
freed by thread T0 here:
    #0 0x4af86b in free /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:38:3
    #1 0x4d9ade in main /tmp/2.c:7:3
    #2 0x7f5d828b0ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287

previously allocated by thread T0 here:
    #0 0x4afb8b in __interceptor_malloc /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52:3
    #1 0x4d9ad1 in main /tmp/2.c:6:13
    #2 0x7f5d828b0ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: double-free /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:38:3 in free
==13154==AddressSanitizer CHECK failed: /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:467 "((CHUNK_ALLOCATED)) == ((old_chunk_state))" (0x2, 0x3)
    #0 0x4b8c5d in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:67:3
    #1 0x4bc321 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/max/src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:159:5
    #2 0x418ca4 in AtomicallySetQuarantineFlag /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:467:5
    #3 0x418ca4 in Deallocate /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:525
    #4 0x418ca4 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:709
    #5 0x4af93f in free /home/max/src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:41:3
    #6 0x4d9ae7 in main /tmp/2.c:8:3
    #7 0x7f5d828b0ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #8 0x418585 in _start (/tmp/a.out+0x418585)
```
There are may be some other checks that may fail in recover mode.
I'm wondering what should we do in such cases, perhaps use flags()->halt_on_error guard?

**Comment by chefmax** [comment]
Or just add a return statement just after printing report?

**Comment by ygribov-samsung** [comment]
The second option looks more natural to me.

**Comment by vonosmas** [comment]
I don't see reasonable "expected behavior" for double-free error. Producing a CHECK-failure is bad, but probably crashing the program is fine.

**Comment by eugenis** [comment]
I don't see why double free is any worse than say oob-read. Assuming that
such reads return zero (is that what we are doing? or just undef?) is
completely arbitrary.

**Comment by yugr** [comment]
This is all about recovery mode (-fsanitize-recover=address) in which we try to continue execution to possibly uncover more errors. E.g. in this case it'll probably make sense to early exit deallocation as soon as we detect double-free (rather than hack around CHECK).

@chefmax : an idea - in recovery mode we could skip invalid writes which are detected by Asan (both in user code and in interceptors) to hopefully reduce chances of crash.

**Comment by chefmax** [comment]
Yes, this is all about recovery mode. We indeed don't have reasonable behavior after double free, but still want continue execution in hope to find more bugs. I think adding return after double free report should be OK, since it doesn't affect default ASan behavior at all and removes CHECK failure in recovery mode.

@yugr: Frankly, I don't think we need to be too smart here. I'm not sure that such a strategy would be profitable enough.

**Comment by vonosmas** [comment]
How does program behave for double free w/o ASan instrumentation? If libc malloc crashes, it's perfectly fine for us to crash too.

**Comment by yugr** [comment]
I think it'll crash all right and so t's absolutely fine for ASan to crash. We're simply talking about best effort to recover after fault so that more errors get detected afterwards.

**Comment by chefmax** [comment]
Should be fixed by http://reviews.llvm.org/rL259473.
