### ISSUE TITLE
link error in iOS device

### ISSUE THREAD

**Issue by waleyzheng** [google/sanitizers#641]
in xCode7 build setting tap, i add flag as below
other c flags: -fsanitize=address
other linker flags:-fsanitize=address
But,when launched app, the app crash.
 the  information is : 
dyld: Library not loaded: @rpath/libclang_rt.asan_ios_dynamic.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/6DFB6F58-A283-4F82-A4B5-903E12B7D0CA/EduLayout.app/EduLayout
  Reason: image not found。
so how to fix it？

**Comment by AnnaZaks** [comment]
Xcode needs to copy the library onto the device, so only setting the compile and link flags is not sufficient. Please, remove "-fsanitize=address" from other flags and enable AddressSanitizer from the Diagnostics tab in the Run Scheme:
https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html
https://developer.apple.com/videos/play/wwdc2015-413/

**Comment by kcc** [comment]
Closing, please reopen if the above comment does not help. 
(Thanks Anna!)
