### ISSUE TITLE
wiki: AddressSanitizerHowToBuild outdated

### ISSUE THREAD

**Issue by tamird** [google/sanitizers#642]
The bottom of this article has some formatting issues (things that should be code are plaintext, and things that should be plain are code). Also, the one-liner for using the chrome team's script should be changed from:
```
mkdir -p tools/clang cd tools/clang
svn co http://src.chromium.org/svn/trunk/src/tools/clang/scripts
cd ../../
tools/clang/scripts/update.sh
```

to:
```
git clone --depth 1 https://chromium.googlesource.com/chromium/src/tools/clang
clang/scripts/update.py
```

**Comment by kcc** [comment]
Thanks, should be better now.

**Comment by tamird** [comment]
@kcc sorry, I updated the snippet by editing; chromium has moved from svn to git, so we need a git checkout to get a reasonable version of clang out of this.

**Comment by kcc** [comment]
Can you provide the correct snippet?

**Comment by tamird** [comment]
Yeah, it's up above now, but here it is again:

```
git clone --depth 1 https://chromium.googlesource.com/chromium/src/tools/clang
clang/scripts/update.py
```

Your comment `# Now use third_party/llvm-build/Release+Asserts/bin/clang++` will need to change to `# Now use ../third_party/llvm-build/Release+Asserts/bin/clang++`

**Comment by kcc** [comment]
ok now?

**Comment by tamird** [comment]
Yep, thanks for being so quick!
