### ISSUE TITLE
Asan false positive when long jumping from a signal handler on Mac OSX 10.11.2 (15C50)

### ISSUE THREAD

**Issue by hbowden** [google/sanitizers#645]
Why I try to use `longjmp` from within a signal handler, ASAN returns the error below.

```
ASAN:DEADLYSIGNAL
=================================================================
==27283==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010162fe32 bp 0x7fff5e62e990 sp 0x7fff5e62e108 T0)
    #0 0x10162fe31 in __sanitizer::internal_memmove(void*, void const*, unsigned long) (/usr/local/lib/clang/3.8.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x5be31)
    #1 0x1015d1a7b in main (/Users/nah/Desktop/./test+0x100000a7b)
    #2 0x7fff958cb5ac in start (/usr/lib/system/libdyld.dylib+0x35ac)
    #3 0x0  (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/clang/3.8.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x5be31) in __sanitizer::internal_memmove(void*, void const*, unsigned long)
==27283==ABORTING
==27283==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fff5e62f000; bottom 0x0001027b0000; size: 0x7ffe5be7f000 (140730440347648)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
ASAN:DEADLYSIGNAL
=================================================================
==27283==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010162fe32 bp 0x7fff5e62e990 sp 0x7fff5e62e108 T0)
    #0 0x10162fe31 in __sanitizer::internal_memmove(void*, void const*, unsigned long) (/usr/local/lib/clang/3.8.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x5be31)
    #1 0x1015d1a7b in main (/Users/nah/Desktop/./test+0x100000a7b)
    #2 0x7fff958cb5ac in start (/usr/lib/system/libdyld.dylib+0x35ac)
    #3 0x0  (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/clang/3.8.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x5be31) in __sanitizer::internal_memmove(void*, void const*, unsigned long)
==27283==ABORTING
^CASAN:DEADLYSIGNAL
=================================================================
==27283==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010162fe32 bp 0x7fff5e62e990 sp 0x7fff5e62e108 T0)
==27283==WARNING: Can't read from symbolizer at fd 3
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

Here's the output from `clang --version`.

```
clang version 3.8.0 (trunk 257526)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
InstalledDir: /usr/local/bin
```

Finally here is a test case that reproduces the issue on  Mac OSX 10.11.2 (15C50), I ran the test case on FreeBSD 10.2-RELEASE  r286666, but ASAN does the right thing on FreeBSD.

``` c
#include <setjmp.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>

static jmp_buf return_jump;

static void signal_handler(int sig)
{
    longjmp(return_jump, 1);
}

static void setup_test_sig_handler(void)
{
    struct sigaction sa;
    sigset_t ss;
    unsigned int i;

    for(i = 1; i < 512; i++)
    {
        (void)sigfillset(&ss);
        sa.sa_flags = SA_RESTART;
        sa.sa_handler = signal_handler;
        sa.sa_mask = ss;
        (void)sigaction((int)i, &sa, NULL);
    }

    return;
}

int main(void)
{
    int rtrn = setjmp(return_jump);
    if(rtrn < 0)
    {
        perror("setjmp");
        return (-1);
    }

    setup_test_sig_handler();

    /* Cause signal. */
    memmove(NULL, "123456789", 9);

    return (0);
}
```

**Comment by kcc** [comment]
On Linux, I see just the SEGV report, nothing else. 
Let me summon Mac experts here. 


But what exactly is your test doing? 
Do you expect it to catch the signal? 
By default, asan installs it's own SEGV handler and disallows to change it. 
You may use ASAN_OPTIONS=handle_segv=0:allow_user_segv_handler=1 to override this default.
But then the app just dies with SEGV on my *linux* machine after reaching memmove call 2 times. 
Same happens w/o asan.

**Comment by yogurfrul** [comment]
I got the same error when run at the second time
`INFO: Seed: 211892240
INFO: -max_len is not provided, using 64
INFO: A corpus is not provided, starting from an empty corpus
#0      READ   units: 1 exec/s: 0
Successfuly enter LLVMFuzzerTestOneInput!
Construct MyClass,myData = 0
Successfuly! data = 0
ASAN:DEADLYSIGNAL
=================================================================
==173072==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x000000000001 sp 0x7fff67a10498 T0)
==173072==Hint: pc points to the zero page.
==173072==The signal is caused by a READ memory access.
==173072==Hint: address points to the zero page.

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==173072==ABORTING

`

**Comment by kcc** [comment]
The above comment is not helpful, please file a separate bug and provide more details.

**Comment by hbowden** [comment]
@kcc I'm going to just close this as I was that was making a mistake not address sanitizer.

**Comment by ayushkh** [comment]
Hey, @hbowden  what caued this problem can you please tell if you remember it now :P . I'm facing the same issue and not able to find the cause
