### ISSUE TITLE
memory sanitizers do not work with googletest - or instructions outdated

### ISSUE THREAD

**Issue by hal88** [google/sanitizers#648]
Compiling both libc++ and googleltest to be instrumented with memory sanitization. Following these instructions as closely as possible:
https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

I'm getting exactly the same results from centos7, clang-3.6.1 built from source using a fedora rpm specfile. Ubuntu 14.04, clang-3.4 distro packaged

The one divergence from the instructions:
suggested googlest revision 613 is still using tr1 - which fails to compile - updated to tip (746) and googletest successfully compiles.

The trivial suggested test case from that page to ensure things are working didn't get picked up by msan - this is not expected behaviour.

`TEST(FooTest, Foo) {
  std::string foo("foo");
  EXPECT_EQ('z', foo[4]);
}`

Yet without gtest msan reports the problem just as it should.
`if(foo[4] == 'z') std::cout << "it is z" << std::endl;`

dup of this.
http://stackoverflow.com/questions/34667242/cant-get-even-basic-clang-memory-sanitization-wiki-example-working

**Comment by vonosmas** [comment]
First of all, can you reproduce it with tip-of-trunk Clang built from sources (http://clang.llvm.org/get_started.html)?

It is possible that the comparison in EXPECT_EQ gets optimized away in
this trivial example. You can try to defeat optimizations and trigger the error
by using smth. like
volatile char c = foo[4];
EXPECT_EQ('z', c);

**Comment by hal88** [comment]
I will try building clang with the tip of trunk and using that when I get the chance. In the meantime can the wikipage be marked as experimental only and definitely not working with any version you're likely to have packaged from a distro? Seems like the polite thing to do.


```
#include "gtest/gtest.h"
#include <string>
#include <vector>

TEST(FooTest, Foo) {
    std::string foo("foo");
    volatile char c = foo[4];
    EXPECT_EQ('z', foo[4]);
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```


```
clang++  -fsanitize=memory -fsanitize-memory-track-origins -fPIE -pie -fno-omit-frame-pointer -g -O2  -std=c++11 -stdlib=libc++ -L/home/hal/libcxx_msan/lib -lc++abi -I/home/hal/libcxx_msan/include -I/home/hal/libcxx_msan/include/c++/v1 test1.cc -I/home/hal/googletest/include/ /home/hal/gtest-msan/libgtest.a -lpthread -Wl,-rpath,/home/hal/libcxx_msan/lib -o test1

```
```
➜ [hal@davis 10:39 ~/test-gtest-msan] ./test1 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from FooTest
[ RUN      ] FooTest.Foo
test1.cc:8: Failure
Value of: foo[4]
  Actual: '\0'
Expected: 'z'
Which is: 'z' (122, 0x7A)
[  FAILED  ] FooTest.Foo (5 ms)
[----------] 1 test from FooTest (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (6 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FooTest.Foo

 1 FAILED TEST
```

**Comment by vonosmas** [comment]
Let's first figure out where the problem is.

In your example, consider replacing
EXPECT_EQ('z', foo[4]);
with
EXPECT_EQ('z', c);

**Comment by hal88** [comment]
My apologies.

```
➜ [hal@davis 10:57 ~/test-gtest-msan] ./test1 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from FooTest
[ RUN      ] FooTest.Foo
test1.cc:8: Failure
Value of: c
  Actual: '\0'
Expected: 'z'
Which is: 'z' (122, 0x7A)
[  FAILED  ] FooTest.Foo (4 ms)
[----------] 1 test from FooTest (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FooTest.Foo

 1 FAILED TEST
```

**Comment by hal88** [comment]
Regardless of what's going on, definitely time to update the wiki page.

**Comment by vonosmas** [comment]
Reproduced this locally, issue confirmed. I guess that libc++ sources have changed and their implementation of small-string optimization explicitly initializes bytes which technically don't belong to user-provided string ("foo", in our example). I have yet to confirm this guess, though.

I will update the wiki page shortly.

**Comment by vonosmas** [comment]
I've updated the instructions - inability to detect out-of-bounds access to std::string from libc++ is a different problem, and we plan to do work that will allow us to solve it in the future.

Thanks for the report!
