### ISSUE TITLE
halt_on_error for ASan: is it effective?

### ISSUE THREAD

**Issue by androm3da** [google/sanitizers#649]
`halt_on_error` is described in `sanitizers/wiki/AddressSanitizerFlags`, but its presence appears to conflict with `sanitizers/wiki/AddressSanitizer#faq`: 

> Q: Can AddressSanitizer continue running after reporting first error?
> A1: No, sorry. AddressSanitizer errors are fatal. This design choice allows the tool to be faster and simpler.

**Comment by chefmax** [comment]
Well, actually ASan can run in continue-after-error mode (see A2). But I agree, having two conflicting answers is confusing, so perhaps we should merge A1 and A2 to something like this:

* Yes it can, AddressSanitizer has recently got -fsanitize-recover=address which enables continue-after-error mode. But this is somewhat experimental so may not yet be as reliable as default mode (and not as timely supported). Also keep in mind that errors after the first one may actually be spurious.

**Comment by androm3da** [comment]
Ok, thanks for clarifying.  When you say " -fsanitize-recover=address which enables continue-after-error mode" -- do you still meant `halt_on_error` or some other option?

**Comment by chefmax** [comment]
To run your sanitized code in continue-after-error mode, you need:

1) Compile your code with " -fsanitize=address  -fsanitize-recover=address" flags.
2) Run your binary with ASAN_OPTIONS=halt_on_error=false environment option.

You can find a simple example here: https://github.com/google/sanitizers/issues/639.

**Comment by ygribov-samsung** [comment]
Fixed as suggested in https://github.com/google/sanitizers/wiki/AddressSanitizer
