### ISSUE TITLE
Missing __vacopy

### ISSUE THREAD

**Issue by adrianN** [google/sanitizers#651]
Hi,

I'm trying to build a project with -fsanitize=address and clang-cl with MSVC 2010. I use /MT and specify "clang_rt.asan-i386.lib; libcmt.lib" as "Additional Dependencies" and "libcmt.lib" as "Ignore Specific Default Libraries". Unfortunately I get the following error

   1>clang_rt.asan-i386.lib(sanitizer_printf.cc.obj) : error LNK2019: unresolved external symbol __vacopy referenced in function "void __cdecl __sanitizer::SharedPrintfCode(bool,char const *,char *)" (?SharedPrintfCode@__sanitizer@@YAX_NPBDPAD@Z)

I'm using clang 3.7.

I tried googling, but didn't find anything related to vacopy and address sanitizer, so I suppose that I'm doing something wrong.

**Comment by vonosmas** [comment]
Can you try MSVC 2013 or above? It's listed as a minimum supported version for LLVM projects:
http://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library

**Comment by adrianN** [comment]
I was afraid you were going to say something like that. Unfortunately my employer only recently upgraded from VS 6, so a further upgrade is probably out of the question. Can you maybe think of some workaround to make it work with the older version? Couldn't I add my own version of __vacopy?

**Comment by adrianN** [comment]
After some begging I got VS 2013. This links successfully.
