### ISSUE TITLE
improve/extend san_cov 

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#655]
Few things to improve in san_cov
- make -strip_path_prefix behave the same way as in sanitizers (-strip_path_prefix=foo strips ".*foo")
- filter out coverage from  /usr/include and other system paths
- make -dump-html print extended summary ([not-]covered files and functions, number of [not]covered  edges, etc)

**Comment by mikea** [comment]
- strip_path_prevyx is already like this (https://cs.corp.google.com/#piper///depot/google3/third_party/llvm/llvm/tools/sancov/sancov.cc&rcl=114393542&l=164). Let me know if it doesn't work as expected.

**Comment by kcc** [comment]
* do not crash when the source files are not present. Instead, just print a single line saying "some of the source files were not found"

**Comment by kcc** [comment]
More stuff: 
* add a flag to allow the user to specify which files they are interested in
* somehow mark the functions that are partially covered in terms of BBs (i.e. that were entered, but that have some uncovered BBs (not edges). Not 100% sure how this is going to look like. This is a poor-man's coverage frontier

**Comment by mikea** [comment]
We already have -blacklist to filter out unnecessary stuff. Do you think we need whitelist as well?

**Comment by kcc** [comment]
Dunno, maybe. Let's keep this in mind.

**Comment by kcc** [comment]
By default, I'd prefer if we strip the common prefix from the file names.

**Comment by kcc** [comment]
@vitalybuka

**Comment by kcc** [comment]
make non-covered functions easier to search in browser. 
Right now we can see this: 
```
0% Foo
30% Bar
```
Right now I don't know how to search for 0% in the browser w/o also finding 30%
Maybe replace 0% with e.g. `zero%` (something easy to search)

**Comment by mikea** [comment]
How about 00%?

**Comment by kcc** [comment]
000% then (to distinguish from 100%)

**Comment by kcc** [comment]
One comment from users: unclear what do the different colors mean. 
I think we should at least add a legend in the output, something like this:
```
red = bad (not covered)
greed = good (covered)
yellow = goog/bad (more than one edge in the line, only some covered)
white = no data. 
Note that due to optimizations the data may not be 100% precise. 
```

**Comment by morehouse** [comment]
For most use cases, SanCov has been deprecated in favor of [Clang Coverage](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html).

@kcc, please re-open if you still want to make these improvements.
