### ISSUE TITLE
ASan false positive on unaligned access

### ISSUE THREAD

**Issue by eugenis** [google/sanitizers#656]
See AddressSanitizer::instrumentUnusualSizeOrAlignment.
Unaligned access is handled by
 (a) 8-byte check at the first byte of the access range
 (b) 8-byte check at the last byte of the access range

This is totally wrong. Check (a) is OK if the size of the access is at least 8. Check (b) is never OK, it should be replaced with a 1-byte check.
Test case: 32-bit access aligned by 4 bytes.

**Comment by yugr** [comment]
AFAIR GCC just checks one byte for both.

**Comment by eugenis** [comment]
Nope, I misread ASan code. LLVM also checks just one byte for both.

FTR, the real problem is in LLVM vectorizer:
https://llvm.org/bugs/show_bug.cgi?id=26600
