### ISSUE TITLE
asan_poisoning check failed

### ISSUE THREAD

**Issue by danra** [google/sanitizers#657]
I'm getting CHECK failed with Xcode 7.2.1, only when compiling with libc++:
==32554==AddressSanitizer CHECK failed: /Library/Caches/com.apple.xbs/Sources/clang/clang-700.1.81/src/projects/compiler-rt/lib/asan/asan_poisoning.cc:361 "(((u8)MemToShadow(a))) == ((0))" (0xfc, 0x0)

Stack trace:
#0 0x000000015eace170 in __asan::AsanDie() ()
#1 0x000000015ead1a9d in __sanitizer::Die() ()
#2 0x000000015eace36a in __asan::AsanCheckFailed(char const, int, char const, unsigned long long, unsigned long long) ()
#3 0x000000015ead1c32 in __sanitizer::CheckFailed(char const, int, char const, unsigned long long, unsigned long long) ()
#4 0x000000015eac8552 in __sanitizer_annotate_contiguous_container ()
#5 0x000000015c46a01f in std::__1::vector, std::__1::allocator > >::__annotate_contiguous_container(void const, void const, void const, void const) const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:842
#6 0x000000015c46c337 in std::__1::vector, std::__1::allocator > >::__annotate_new(unsigned long) const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:848
#7 0x000000015c479de8 in std::__1::vector, std::__1::allocator > >::allocate(unsigned long) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:938
#8 0x000000015c4790c2 in std::__1::enable_if<(__is_forward_iterator>::value) && (is_constructible, std::__1::iterator_traits>::reference>::value), void>::type std::__1::vector, std::__1::allocator > >::assign>(std::__1::pair, std::__1::pair*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1413
#9 0x000000015c475338 in std::__1::vector, std::__1::allocator > >::operator=(std::__1::vector, std::__1::allocator > > const&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1358
#10 my own code, assigning std::vector < std::pair < int, in t> > to another vector

Also commented in issue #258 which may be related.

**Comment by kcc** [comment]
I would guess that this happens because some of the code (e.g. libc++ itself) 
is not instrumented. This is specific for container overflow detection feature, which you can disable. 
https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow

(Let me summon the Apple folks since we discussed this problem recently).

**Comment by morehouse** [comment]
@kcc:  It would appear the Apple folks were not summoned.

**Comment by kcc** [comment]
too old to be actionable. please reopen if the problem exists.
