### ISSUE TITLE
Undefined symbol clarification

### ISSUE THREAD

**Issue by jpakkane** [google/sanitizers#660]
The FAQ says the following:

    Q: When I link my shared library with -fsanitize=address, it fails due to some
    undefined ASan symbols (e.g. asan_init_v4)?

    A: Most probably you link with -Wl,-z,defs or -Wl,--no-undefined.
    These flags don't work with ASan.

However some people use `-Wl,--no-undefined` with `-lasan` and this seems to work. Is this an officially supported way of using no-undefined or does it work only by accident and the reliable way is to not use `-Wl,--no-undefined`.

**Comment by kcc** [comment]
Passing -lasan manually is not supported -- you are on your own.
Same goes for -Wl,--no-undefined, I guess.

**Comment by eugenis** [comment]
-Wl,--no-undefined works with -static-libasan.
This is the default mode for GCC.

**Comment by eugenis** [comment]
I meant -shared-libasan.

**Comment by jpakkane** [comment]
It would be cool if you updated the FAQ to explicitly mention this.

Thanks,

**Comment by eugenis** [comment]
Done.
