### ISSUE TITLE
sancov -not-covered-functions doesn't work on shared objects

### ISSUE THREAD

**Issue by toddlipcon** [google/sanitizers#661]
It seems that the implementation works by iterating over the symbols in the target object in order to find the address of __sanitizer_cov. However, in the case of a shared library, this is an undefined symbol:

todd@todd-ThinkPad-T540p:~/git/kudu$ nm build/asan/lib/libgutil.so | grep sanitiz
                 U __sanitizer_cov
                 U __sanitizer_cov_module_init

and the calls will be through the PLT:

e.g:
   6a7e4:   e8 c7 7b ff ff          callq  623b0 __sanitizer_cov@plt

It seems like sancov should either handle this, or print some reasonable error if it finds that the __sanitizer_cov function is an undefined symbol in the target object.

**Comment by kcc** [comment]
We'll need to print a warning for now...

**Comment by mikea** [comment]
Warning was added as well during -obj refactoring. Here's the message it prints now:

Ignoring out/fuzzer/./libc++.so and its coverage because  __sanitizer_cov* functions were not found.

Todd, you are right. PLT is precisely the reason why it doesn't work now.

**Comment by morehouse** [comment]
We have a warning and are not planning major updates to SanCov.  Please see https://clang.llvm.org/docs/SourceBasedCodeCoverage.html for an alternative tool.
