### ISSUE TITLE
sancov -print should not require a -obj flag

### ISSUE THREAD

**Issue by toddlipcon** [google/sanitizers#662]
sancov -print is just doing format conversion from binary to text, so shouldn't require -obj to be passed. Passing /bin/true has the same effect as passing the correct binary:

todd@todd-ThinkPad-T540p:~/git/kudu/build/cov$ sancov -print coverage/callback_bind-test/callback_bind-test.1261.sancov -obj bin/callback_bind-test | md5sum -
ae8b00facf16a66193942cd88d7d93e2  -
todd@todd-ThinkPad-T540p:~/git/kudu/build/cov$ sancov -print coverage/callback_bind-test/callback_bind-test.1261.sancov -obj /bin/true | md5sum -
ae8b00facf16a66193942cd88d7d93e2  -
todd@todd-ThinkPad-T540p:~/git/kudu/build/cov$ sancov -print coverage/callback_bind-test/callback_bind-test.1261.sancov  | md5sum -
sancov: for the -obj option: must be specified at least once!

**Comment by kcc** [comment]
agreed

**Comment by mikea** [comment]
It doesn't. I have rewritten it a while back and there's no -obj parameter anymore. You just pass binaries / coverage files as positional arguments. For -print it shouldn't complain.
