### ISSUE TITLE
unnoticed invalid dereference when using address sanitizer

### ISSUE THREAD

**Issue by cwarlich** [google/sanitizers#666]
The code below has been compiled with GCC 5.3:

$ gcc -fsanitize=address -fno-omit-frame-pointer -g sanitize.c

When executing the result, the sanitizer only complains about the
invalid dereference of the second printf statement, while the first
one is executed unnoticed.

#include <stdlib.h>
#include <stdio.h>

struct Simple {
    int value;
};
int f(struct Simple simple) {
    return simple.value;
}

int g(int value) {
    return value;
}

int main() {

    struct Simple *psimple = (struct Simple *) malloc(sizeof(struct Simple));
    psimple->value = 42;
    free(psimple);
    printf("%d\n", f(*psimple));

    int *pint = (int *) malloc(sizeof(int));
    *pint = 24;
    free(pint);
    printf("%d\n", g(*pint));

    return 0;
}

**Comment by ygribov-samsung** [comment]
This seems to be GCC-specific error so could you file it in https://gcc.gnu.org/bugzilla ?

**Comment by cwarlich** [comment]
Ok, done: Bug report 70541.

Yes, using clang (Version 3.6), the address sanitizer works fine.
