### ISSUE TITLE
How to disable asan's global objects check ?

### ISSUE THREAD

**Issue by etaf** [google/sanitizers#667]
Is there a easy way to disable Instrument for global variables if we don't need global variables address check ?

**Comment by yugr** [comment]
AFAIR it's  --param asan-globals=0 for GCC and  -mllvm -asan-globals=0 for LLVM. But why don't you want to check globals? Have you faced some false positive from ASan?

**Comment by etaf** [comment]
Thank you!

**Comment by etaf** [comment]
Thank you! 
With this flag, asan would not check the shadow memory of global objects ?

**Comment by eugenis** [comment]
With flag ASan would not poison the shadow for global objects, so all
checks will pass. It also would not add redzones around globals, so you'll
have slightly smaller .data and .bss.
