### ISSUE TITLE
Several hundred asan failures with 6.0 on x86_64-apple-darwin10.8

### ISSUE THREAD

**Issue by DominiquedHumieres** [google/sanitizers#669]
On x86_64-apple-darwin10.8 I get several hundred asan failures with 6.0 (see
https://gcc.gnu.org/ml/gcc-testresults/2016-04/msg01013.html). Most (if not
all) of them are of the kind

dyld: Symbol not found: _dyldVersionNumber
  Referenced from:
/opt/gcc/build_c/x86_64-apple-darwin10.8.0/i386/libsanitizer/asan/.libs/libasan.3.dylib
  Expected in: flat namespace
 in
/opt/gcc/build_c/x86_64-apple-darwin10.8.0/i386/libsanitizer/asan/.libs/libasan.3.dylib

AFAICT they are related to revision r229111

+bool DyldNeedsEnvVariable() {
+  // If running on OS X 10.11+ or iOS 9.0+, dyld will interpose even if
+  // DYLD_INSERT_LIBRARIES is not set. However, checking OS version via
+  // GetMacosVersion() doesn't work for the simulator. Let's instead check
+  // `dyldVersionNumber`, which is exported by dyld, against a known version
+  // number from the first OS release where this appeared.
+  return dyldVersionNumber < kMinDyldVersionWithAutoInterposition;
+}
+

**Comment by chefmax** [comment]
Could it be that your dyld simply doesn't contain **_dyldVersionNumber** symbol (although this would be quite strange)? Could you check this?

**Comment by DominiquedHumieres** [comment]
> Le 11 avr. 2016 à 19:20, chefmax <notifications@github.com> a écrit :
> 
> Could it be that your dyld simply doesn't contain _dyldVersionNumber symbol (although this would be quite strange)?

I think so.

> Could you check this?

How?

**Comment by jwhowarth** [comment]
$ nm /usr/lib/dyld | grep dyldVersionNumber
00007fff5fc2d6b8 S _dyldVersionNumber

**Comment by kubabrecka** [comment]
How about the ASan dylib, does it properly import the symbol?  Here's what it looks like on a recent OS X  with a LLVM built ASan (libSystem re-exports libdyld):

```
$ nm -gm .../libclang_rt.asan_osx_dynamic.dylib | grep dyldVersion
                 (undefined) external _dyldVersionNumber (from libSystem)
$ otool -l /usr/lib/libSystem.dylib | grep -C3 dyld
Load command 17
          cmd LC_REEXPORT_DYLIB
      cmdsize 56
         name /usr/lib/system/libdyld.dylib (offset 24)
$ nm -gm /usr/lib/system/libdyld.dylib | grep dyldVersion
0000000000003ea8 (__TEXT,__const) external _dyldVersionNumber
0000000000003e80 (__TEXT,__const) external _dyldVersionString

```

**Comment by DominiquedHumieres** [comment]
On x86_64-apple-darwin10.8, Xcode 3.2.6, I see

[macbook] gcc/build_c% otool -l /usr/lib/libSystem.dylib | grep -C3 dyld
 reserved1 1685 (index into indirect symbol table)
 reserved2 0
Section
  sectname __dyld
   segname __DATA
      addr 0x00000000001c54b0
      size 0x0000000000000010
[macbook] gcc/build_c% nm -gm /usr/lib/system/libdyld.dylib | grep dyldVersion
nm: can't open file: /usr/lib/system/libdyld.dylib (No such file or directory)
[macbook] gcc/build_c% nm /opt/gcc/gcc6c/lib/libasan.dylib | grep dyldVersion
                 U _dyldVersionNumber

On x86_64-apple-darwin15.4, Xcode 7.3, I see

[Book15] f90/bug% otool -l /usr/lib/libSystem.dylib | grep -C3 dyld
Load command 17
          cmd LC_REEXPORT_DYLIB
      cmdsize 56
         name /usr/lib/system/libdyld.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 360.21.0
compatibility version 1.0.0
[Book15] f90/bug% nm /opt/gcc/gcc6c/lib/libasan.dylib | grep dyldVersion
                 U _dyldVersionNumber

**Comment by jwhowarth** [comment]
It looks like you have some local filesystem damage then as your copy of /usr/lib/system/libdyld.dylib has gone missing.

**Comment by kubabrecka** [comment]
Please send the output of

```
$ nm /opt/gcc/gcc6c/lib/libasan.dylib | grep dyldVersion
```

to see what library are we expecting `_dyldVersionNumber` to be in.  Then `nm` that library.

**Comment by jwhowarth** [comment]
From his previous observation of...

[macbook] gcc/build_c% nm -gm /usr/lib/system/libdyld.dylib | grep dyldVersion
nm: can't open file: /usr/lib/system/libdyld.dylib (No such file or directory)

the /usr/lib/system/libdyld.dylib has been lost on his filesystem.

**Comment by kubabrecka** [comment]
I don't think so.  He's on x86_64-apple-darwin10.8, which is very old, and the library structure is probably different there.

**Comment by jwhowarth** [comment]
I don't have 10.8 handy but https://discussions.apple.com/thread/6836792?start=0&tstart=0 shows that 10.8.5 should have that file present.

**Comment by kubabrecka** [comment]
x86_64-apple-darwin10.8 is not OS X 10.8.  It's 10.6.8.

**Comment by jwhowarth** [comment]
Okay, https://feedback.techsmith.com/techsmith/topics/snagit_2_1_5_on_mac_10_7_5_not_working shows that  /usr/lib/system/libdyld.dylib goes as far back as 10.7.

**Comment by jwhowarth** [comment]
Does recent llvm even build on 10.6? I thought the requirement that the llvm build compiler support c++-11 pretty much limited the OS X support to releases which provide libc++ for the c++-11 support (which I think limits the builds to 10.7 or later).

**Comment by kubabrecka** [comment]
The failure is with GCC.  But still, ASan is only supported on 10.7+.

**Comment by jwhowarth** [comment]
I double checked the fink llvm packaging and indeed since llvm 3.6, builds of llvm on 10.6 require a local installation of llvm 3.4/3.5 (including libc++).

**Comment by chefmax** [comment]
Can't we use something like this:
```
diff --git a/lib/sanitizer_common/sanitizer_mac.cc b/lib/sanitizer_common/sanitizer_mac.cc
index 25c1c68..d079e01 100644
--- a/lib/sanitizer_common/sanitizer_mac.cc
+++ b/lib/sanitizer_common/sanitizer_mac.cc
@@ -560,7 +560,10 @@ void DisableReexec() {
   reexec_disabled = true;
 }
 
-extern "C" double dyldVersionNumber;
+extern "C" {
+  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber = MACOS_VERSION_UNKNOWN;
+}
+
```
?
Although ASan is only supported on 10.7+, applying patches directly to GCC source tree is really undesirable, it would be nice to apply the fix to upstream repo.

**Comment by DominiquedHumieres** [comment]
> Le 14 avr. 2016 à 09:44, chefmax <notifications@github.com> a écrit :
> 
> +extern "C" {
> +  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber = MACOS_VERSION_UNKNOWN;
> +}
> +
> 

This look like a step in the right direction. Preliminary tests with patch

--- ../_clean/libsanitizer/asan/asan_mac.cc	2015-11-23 10:17:05.000000000 +0100
+++ libsanitizer/asan/asan_mac.cc	2016-04-14 11:16:18.000000000 +0200
@@ -97,7 +97,10 @@ void DisableReexec() {
   reexec_disabled = true;
 }
 
-extern "C" double dyldVersionNumber;
+extern "C" {
+  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber = MACOS_VERSION_UNKNOWN;
+}
+
 static const double kMinDyldVersionWithAutoInterposition = 360.0;
 
 bool DyldNeedsEnvVariable() {

gives on x86_64-apple-darwin10

[macbook] build_c/gcc% tail testsuite/g++/g++.sum

# of expected passes		1087
# of unsupported tests		185

		=== g++ Summary ===

# of expected passes		2174
# of unsupported tests		370
/opt/gcc/build_c/gcc/testsuite/g++/../../xg++  version 6.0.0 20160410 (experimental) [trunk revision 234869] (GCC) 


[macbook] build_c/gcc% tail testsuite/gcc/gcc.sum
# of unexpected failures	7
# of unsupported tests		164

		=== gcc Summary ===

# of expected passes		1952
# of unexpected failures	14
# of unsupported tests		328
/opt/gcc/build_c/gcc/xgcc  version 6.0.0 20160410 (experimental) [trunk revision 234869] (GCC) 

I don’t know why the test

FAIL: c-c++-common/asan/strncpy-overflow-1.c   -O*  output pattern test, is 

fails with gcc, but not with g++.

However on x86_64-apple-darwin15, I see a lot of (expected?) failures of the kind asan_init_is_running

[Book15] build_w/gcc% grep "asan_init_is_running" testsuite/g++/g++.log | wc -l
     806
[Book15] build_w/gcc% tail testsuite/g++/g++.sum
# of unexpected failures	224
# of unsupported tests		192

		=== g++ Summary ===

# of expected passes		1642
# of unexpected failures	448
# of unsupported tests		384
/opt/gcc/build_w/gcc/testsuite/g++/../../xg++  version 6.0.0 20160414 (experimental) [trunk revision 234970p25] (GCC) 
[Book15] build_w/gcc% grep "asan_init_is_running" testsuite/gcc/gcc.log | wc -l
     634
[Book15] build_w/gcc% tail testsuite/gcc/gcc.sum
# of unexpected failures	171
# of unsupported tests		171

		=== gcc Summary ===

# of expected passes		1568
# of unexpected failures	342
# of unsupported tests		342
/opt/gcc/build_w/gcc/xgcc  version 6.0.0 20160414 (experimental) [trunk revision 234970p25] (GCC) 

Dominique

**Comment by chefmax** [comment]
No, these failures are unexpected. Could you try to remove MACOS_VERSION_UNKNOWN initializer from dyldVersionNumber and check it again?

**Comment by DominiquedHumieres** [comment]
> Le 14 avr. 2016 à 18:43, chefmax <notifications@github.com> a écrit :
> 
> No, these failures are unexpected. Could you try to remove MACOS_VERSION_UNKNOWN initializer from dyldVersionNumber and check it again?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

As in

--- ../_clean/libsanitizer/asan/asan_mac.cc	2015-11-23 10:17:05.000000000 +0100
+++ libsanitizer/asan/asan_mac.cc	2016-04-14 11:16:18.000000000 +0200
@@ -97,7 +97,10 @@ void DisableReexec() {
  reexec_disabled = true;
}

-extern "C" double dyldVersionNumber;
+extern "C" {
+  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber = ;
+}
+
static const double kMinDyldVersionWithAutoInterposition = ;

bool DyldNeedsEnvVariable() {

?

Dominique

**Comment by chefmax** [comment]
Just like this:
```
-extern "C" double dyldVersionNumber;
+extern "C" {
+  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
+}
+
```

**Comment by DominiquedHumieres** [comment]
On x86_64-apple-darwin15 I have bootstrapped with the following patch applied on top of revision r234982

diff -up ../_clean/libsanitizer/asan/asan_mac.cc libsanitizer/asan/asan_mac.cc
--- ../_clean/libsanitizer/asan/asan_mac.cc	2015-11-23 10:17:05.000000000 +0100
+++ libsanitizer/asan/asan_mac.cc	2016-04-14 19:54:05.000000000 +0200
@@ -97,7 +97,10 @@ void DisableReexec() {
   reexec_disabled = true;
 }
 
-extern "C" double dyldVersionNumber;
+extern "C" {
+  SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
+}
+
 static const double kMinDyldVersionWithAutoInterposition = 360.0;
 
 bool DyldNeedsEnvVariable() {

but I still get

[Book15] build_w/gcc% tail testsuite/g++/g++.sum
# of unexpected failures	224
# of unsupported tests		192

		=== g++ Summary ===

# of expected passes		1642
# of unexpected failures	448
# of unsupported tests		384
/opt/gcc/build_w/gcc/testsuite/g++/../../xg++  version 6.0.0 20160414 (experimental) [trunk revision 234982p26] (GCC) 

[Book15] build_w/gcc% grep "asan_init_is_running" testsuite/g++/g++.log | wc -l
     806

**Comment by chefmax** [comment]
Dominique, sorry bothering, could you check this one:
```
diff --git a/lib/sanitizer_common/sanitizer_mac.cc b/lib/sanitizer_common/sanitizer_mac.cc
index 25c1c68..d8ec798 100644
--- a/lib/sanitizer_common/sanitizer_mac.cc
+++ b/lib/sanitizer_common/sanitizer_mac.cc
@@ -560,10 +560,14 @@ void DisableReexec() {
   reexec_disabled = true;
 }

-extern "C" double dyldVersionNumber;
+extern "C" SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
 static const double kMinDyldVersionWithAutoInterposition = 360.0;

 bool DyldNeedsEnvVariable() {
+  // Although sanitizer support was added to LLVM on Darwin 10.7+, GCC users
+  // still may want use them on older systems. On older Darwin platforms, dyld
+  // doesn't export dyldVersionNumber symbol and we simply can return false.
+  if (!&dyldVersionNumber) return false;
   // If running on OS X 10.11+ or iOS 9.0+, dyld will interpose even if
   // DYLD_INSERT_LIBRARIES is not set. However, checking OS version via
   // GetMacosVersion() doesn't work for the simulator. Let's instead check
```
?  I've tested it with dummy testcase on my Linux machine and it worked for me.

**Comment by kubabrecka** [comment]
> ```
> +  // Although sanitizer support was added to LLVM on Darwin 10.7+, GCC users
> +  // still may want use them on older systems. On older Darwin platforms, dyld
> +  // doesn't export dyldVersionNumber symbol and we simply can return false.
> +  if (!&dyldVersionNumber) return false;
> ```

You need to return `true` if `dyldVersionNumber` si not present.

**Comment by chefmax** [comment]
> You need to return true if dyldVersionNumber si not present.

Of course, thank you! Here the patch to be tested:
```
diff --git a/lib/sanitizer_common/sanitizer_mac.cc b/lib/sanitizer_common/sanitizer_mac.cc
index 25c1c68..d8ec798 100644
--- a/lib/sanitizer_common/sanitizer_mac.cc
+++ b/lib/sanitizer_common/sanitizer_mac.cc
@@ -560,10 +560,14 @@ void DisableReexec() {
   reexec_disabled = true;
 }

-extern "C" double dyldVersionNumber;
+extern "C" SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
 static const double kMinDyldVersionWithAutoInterposition = 360.0;

 bool DyldNeedsEnvVariable() {
+  // Although sanitizer support was added to LLVM on Darwin 10.7+, GCC users
+  // still may want use them on older systems. On older Darwin platforms, dyld
+  // doesn't export dyldVersionNumber symbol and we simply can return true.
+  if (!&dyldVersionNumber) return true;
   // If running on OS X 10.11+ or iOS 9.0+, dyld will interpose even if
   // DYLD_INSERT_LIBRARIES is not set. However, checking OS version via
   // GetMacosVersion() doesn't work for the simulator. Let's instead check
```

**Comment by DominiquedHumieres** [comment]
The patch

--- ../_clean/libsanitizer/asan/asan_mac.cc	2015-11-23 10:17:05.000000000 +0100
+++ libsanitizer/asan/asan_mac.cc	2016-04-15 13:22:01.000000000 +0200
@@ -97,10 +97,14 @@ void DisableReexec() {
   reexec_disabled = true;
 }
 
-extern "C" double dyldVersionNumber;
+extern "C" SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
 static const double kMinDyldVersionWithAutoInterposition = 360.0;
 
 bool DyldNeedsEnvVariable() {
+  // Although sanitizer support was added to LLVM on Darwin 10.7+, GCC users
+  // still may want use them on older systems. On older Darwin platforms, dyld
+  // doesn't export dyldVersionNumber symbol and we simply can return false.
+  if (!&dyldVersionNumber) return true;
   // If running on OS X 10.11+ or iOS 9.0+, dyld will interpose even if
   // DYLD_INSERT_LIBRARIES is not set. However, checking OS version via
   // GetMacosVersion() doesn't work for the simulator. Let's instead check

works well on x86_64-apple-darwin15:

		=== g++ Summary ===

# of expected passes		2174
# of unsupported tests		370

		=== gcc Summary ===

# of expected passes		1966
# of unsupported tests		328

Allow for five more hours for x86_64-apple-darwin10.

**Comment by DominiquedHumieres** [comment]
> Le 15 avr. 2016 à 15:20, Dominique d'Humières <dominiq@lps.ens.fr> a écrit :
> 
> The patch
> 
> --- ../_clean/libsanitizer/asan/asan_mac.cc	2015-11-23 10:17:05.000000000 +0100
> +++ libsanitizer/asan/asan_mac.cc	2016-04-15 13:22:01.000000000 +0200
> @@ -97,10 +97,14 @@ void DisableReexec() {
>   reexec_disabled = true;
> }
> 
> -extern "C" double dyldVersionNumber;
> +extern "C" SANITIZER_WEAK_ATTRIBUTE double dyldVersionNumber;
> static const double kMinDyldVersionWithAutoInterposition = 360.0;
> 
> bool DyldNeedsEnvVariable() {
> +  // Although sanitizer support was added to LLVM on Darwin 10.7+, GCC users
> +  // still may want use them on older systems. On older Darwin platforms, dyld
> +  // doesn't export dyldVersionNumber symbol and we simply can return false.
> +  if (!&dyldVersionNumber) return true;
>   // If running on OS X 10.11+ or iOS 9.0+, dyld will interpose even if
>   // DYLD_INSERT_LIBRARIES is not set. However, checking OS version via
>   // GetMacosVersion() doesn't work for the simulator. Let's instead check
> 
> works well on x86_64-apple-darwin15:
> 
> 		=== g++ Summary ===
> 
> # of expected passes		2174
> # of unsupported tests		370
> 
> 		=== gcc Summary ===
> 
> # of expected passes		1966
> # of unsupported tests		328
> 
> Allow for five more hours for x86_64-apple-darwin10.

It took slightly longer, but the patch works. Thanks.

**Comment by iains** [comment]
(same comment as from the GCC PR70264) - this works for me and looks good.

BTW there are folks using Darwin10 for "day job" things (both LLVM and GCC), so there's definitely a real interest in making sure it's functioning well.

**Comment by chefmax** [comment]
Should be fixed on trunk now by http://reviews.llvm.org/rL266868.
