### ISSUE TITLE
kasan_symbolize: move to kernel tree

### ISSUE THREAD

**Issue by dvyukov** [google/sanitizers#674]
It turns out kernel tree contains a similar script in scripts/decode_stacktrace.sh. But it is less advanced than kasan_symbolize.py. It makes sense to move kasan_symbolize.py to kernel tree instead of scripts/decode_stacktrace.sh.
Proposed by Andrey Ryabinin here:
https://groups.google.com/d/msg/syzkaller/XvxH3cBQ134/St81wUn0AAAJ

**Comment by dvyukov** [comment]
@xairy @ramosian-glider

**Comment by ramosian-glider** [comment]
Fixed by bf3fc6c4071e9bcdce5ba14119dbd8cf58b1b4d1

**Comment by ramosian-glider** [comment]
Sent the script for upstream review: https://groups.google.com/forum/#!topic/kasan-dev/-eBU8ipBO3w

**Comment by morehouse** [comment]
@ramosian-glider: Status?

**Comment by dvyukov** [comment]
syzkaller has own symbolization logic, which is used for all syzbot reports. It's also provided as syz-symbolize command line utility. So I think we don't need kasan_symbolize.py anymore.
