### ISSUE TITLE
fix out-of-tree tsan tests and ./test_tsan.sh, make them part of CMake build in-tree

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#677]
LLVM's r267755 disables the old tsan tests because they are red. 
Besides, the tests are using http://data-race-test.googlecode.com/svn/trunk/
which will be dead soon. 
If we still need to run those tests we need to migrate them into the llvm tree.

**Comment by dvyukov** [comment]
What was the failure?

**Comment by dvyukov** [comment]
Mailed http://reviews.llvm.org/D19868

**Comment by dvyukov** [comment]
The previously failing bot now green on check_analyze:

http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-autoconf/builds/18884/steps/tsan%20analyze/logs/stdio
