### ISSUE TITLE
ASan runtime does not come first in initial library list

### ISSUE THREAD

**Issue by chshaob1** [google/sanitizers#679]
hi, sanitizers, 

I was trying to use the asan in gcc-5.2.0 (the tool chain is from poky jethro) with some embedded codebase. My makefile was quite straight forward: 
`EXTRA_CCFLAGS  +=  -fsanitize=address -fno-omit-frame-pointer`
Then also add `"-lasan"` along with `"-lpthread"` etc.
It compiles. However, when I start to run the program, the following errors come out. 

> processA   : ==559==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
> end session 'processA' (1), failing
> processB     : ==560==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
> end session 'processB' (1), failing
> ...

I tried several things but nothing works yet. Any idea how this can be solved?

**Comment by ygribov-samsung** [comment]
You should add -fsanitize=address to LDFLAGS as well.

**Comment by kcc** [comment]
>> Then also add "-lasan"
Is there any piece of documentation that mentions -lasan? 
This question keeps popping up despite the fact that we do not support manual usage of -lasan

**Comment by ygribov-samsung** [comment]
+1

**Comment by yugr** [comment]
It seems that tons of blogs mention -lasan. It may make sense to add a special compiler check for this.

**Comment by yogurfrul** [comment]
yes,it auto link libasan.so without -lasan.I use fresh gcc version is gcc (GCC) 6.3.0
and I got the same error:
==236083==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

then I export  LD_PRELOAD=/path/libasan.so.3, it works~
But,still don't know why. ldd command show that my output file linked with libasan.so.3

**Comment by chefmax** [comment]
Is your output file an executable, or it's a shared library? Also, do you have non-empty /etc/ld.so.preload file on your system?

**Comment by yogurfrul** [comment]
my output is  an executable.
my  /etc/ld.so.preload is not empty, but not contains  libasan.so I need.
Need I add libasan.so to  /etc/ld.so.preload?
Why not  something do it auto?

**Comment by kcc** [comment]
Probably your gcc installation is broken somehow. 
What if you try -static-libasan (to link asan statically)?

**Comment by yogurfrul** [comment]
maybe,becaese I install gcc in my own workspace for making my code can work independently with machine environment 。
 -static-libasan fix it~
 thank you very much~

**Comment by chefmax** [comment]
FWIW non-empty /etc/ld.so.preload was an exact reason why GCC 6 didn't work (ASan runtime indeed wasn't first in initial library list). GCC 4.9 works just because it's too old and doesn't have this sanity check.

**Comment by daixtrose** [comment]
@kcc Why exactly was this issue closed? We have major headaches in cross-compiling with gcc-7.3.1 for Raspi.

**Comment by yugr** [comment]
@daixtrose Basically libasan can not guarantee correct work if it's not the first loaded library (which is e.g. the case when `/etc/ld.so.preload` is not empty). We saw several cases when preloaded libraries caused Asan misbehaviors and decided to add this check to prevent them in future. _Maybe_ we should add a flag for users who are willing to take the risk.

**Comment by daixtrose** [comment]
AFAICS there is no chance to have libasan be loaded first. At least cross compilers have that issue. 

My current workaround is using -l:libasan I.e.have libasan linked statically. Some sanitizers yield false positives otherwise (on Raspberry Pi).

**Comment by yugr** [comment]
> AFAICS there is no chance to have libasan be loaded first. At least cross compilers have that issue.

Note that many people were able to sanitize and successfully boot complete Linux distros without issues so it's not that bad.

> My current workaround is using -l:libasan I.e.have libasan linked statically.

This is hardly an ideal solution though (it will at least cause false negatives).
