### ISSUE TITLE
AddressSanitizer fails on simple programs due to 'calling itself'

### ISSUE THREAD

**Issue by rspanton** [google/sanitizers#682]
If I compile a very simple Hello World program, with gcc, and the `-fsanitize=address` option, I get the following error when running the resulting program:
~~~~
$ ./test
==6987==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_rtl.cc:556 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)
    <empty stack>
~~~~

The code I'm compiling is:
~~~~
#include <stdio.h>

int main(void)
{
	printf("Hi\n");
	return 0;
}
~~~~

And the command I used to compile is:
~~~~
gcc test.c -fsanitize=address -o test
~~~~

Package versions installed:
 * gcc 5.3.1
 * libasan 5.3.1

**Comment by chefmax** [comment]
Strange error. Could you provide more details, what platform do you use?

**Comment by rspanton** [comment]
This is running on an up-to-date Fedora 23, on x86_64.

**Comment by chefmax** [comment]
I cannot reproduce this on my x86_64 Ubuntu 14.04:

```
$ ~/install/gcc/bin/gcc test.c -fsanitize=address -o test.x
$ LD_LIBRARY_PATH=/home/max/install/gcc/lib64 ./test.x
Hi
```
Could you run the test case like this:
```
ASAN_OPTIONS=debug=1:verbosity=3 ./test.x 
```

**Comment by rspanton** [comment]
No real change in output:
~~~
$ ASAN_OPTIONS='debug=1:verbosity=3' ./test
==10566==Parsed ASAN_OPTIONS: debug=1:verbosity=3
==10566==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_rtl.cc:556 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)
    <empty stack>
~~~

To check it wasn't specific to this machine, I have also just testing this on another Fedora 23 x86_64 box, and get the same result.

**Comment by ygribov-samsung** [comment]
Rob, could you run this under gdb and print backtrace on error?

**Comment by rspanton** [comment]
Sure.  Unfortunately gdb didn't seem to want to give me a stack trace once the program had terminated (is there a knack to persuading it to play well with AddressSanitizer?)  

So I set a breakpoint at the line of the failing assertion, and grabbed a backtrace before it failed.  A copy of the output from that is here: https://gist.github.com/rspanton/c0f6b6acb68f6b80a458a6b290345316

**Comment by yugr** [comment]
I guess it's https://llvm.org/bugs/show_bug.cgi?id=27310 ...

**Comment by fweimer** [comment]
A workaround for Fedora 23 is on its way: https://bugzilla.redhat.com/show_bug.cgi?id=1335011

We would really prefer a proper fix in ASAN, though.

**Comment by ygribov-samsung** [comment]
> Unfortunately gdb didn't seem to want to give me a stack trace once the program had terminated
> (is there a knack to persuading it to play well with AddressSanitizer?) 

Most probably ASAN_OPTIONS=abort_on_error=1 should do the trick (without it ASan would just exit(1) which won't be caught by debuggers).

**Comment by chefmax** [comment]
Should be fixed by http://reviews.llvm.org/rL269633. Closing.

**Comment by DaanDeMeyer** [comment]
I'm encountering this issue on trivial programs on Windows compiled using clang-cl and clang++. I'm using the latest stable version of all tools used (LLVM 8.0.1, Visual C++ Build Tools 16.2, Windows 10 May 2019 update)

main.cpp:

```cpp
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << "Hello, World" << std::endl;
  return 0;
}
```

`clang++ -fsanitize=address main.cpp` or `clang-cl -fsanitize=address main.cpp`

Output:

```
==8244==AddressSanitizer CHECK failed: C:\src\llvm_package_801-final\llvm\projects\compiler-rt\lib\asan\asan_rtl.cc:402 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)       
==8244==AddressSanitizer CHECK failed: C:\src\llvm_package_801-final\llvm\projects\compiler-rt\lib\asan\asan_poisoning.cc:37 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
```

**Comment by AhmedAshrafHamza** [comment]
> I'm encountering this issue on trivial programs on Windows compiled using clang-cl and clang++. I'm using the latest stable version of all tools used (LLVM 8.0.1, Visual C++ Build Tools 16.2, Windows 10 May 2019 update)
> 
> main.cpp:
> 
> ```c++
> #include <iostream>
> 
> int main(int argc, char *argv[])
> {
>   std::cout << "Hello, World" << std::endl;
>   return 0;
> }
> ```
> 
> `clang++ -fsanitize=address main.cpp` or `clang-cl -fsanitize=address main.cpp`
> 
> Output:
> 
> ```
> ==8244==AddressSanitizer CHECK failed: C:\src\llvm_package_801-final\llvm\projects\compiler-rt\lib\asan\asan_rtl.cc:402 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)       
> ==8244==AddressSanitizer CHECK failed: C:\src\llvm_package_801-final\llvm\projects\compiler-rt\lib\asan\asan_poisoning.cc:37 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
> ```
I have the same issue
Did you solve this issue and how? if you do.

**Comment by DaanDeMeyer** [comment]
@AhmedAshrafHamza I stopped having the issue once LLVM 9 was released. I'm on the latest Visual Studio Build Tools version as well (not sure if that makes a difference or not).

**Comment by victorstewart** [comment]
hey i'm having this issue today. using Clang 12.0.1 and glibc 2.34. any guidance on how to address it?
