### ISSUE TITLE
LeakSanitizer for Windows

### ISSUE THREAD

**Issue by Trass3r** [google/sanitizers#686]
Is there any information on the status of LeakSanitizer Windows (x64) support?

**Comment by kcc** [comment]
Nobody has worked on implementing it. Volunteers are welcome :) 
Feel free to re-open if you want to work on it.

**Comment by Trass3r** [comment]
Ok. Though there's a stub @ https://github.com/llvm-mirror/compiler-rt/blob/master/lib/tsan/rtl/tsan_platform_windows.cc

I wonder what would need to be done given that asan seems to support Windows.

**Comment by kcc** [comment]
tsan_platform_windows.cc is tsan, totally unrelated to LeakSanitizer (lsan)
To support lsan on windows the biggest (or the only?) part is to implement StopTheWorld():

From lib/sanitizer_common/sanitizer_stoptheworld.h
```
// Suspend all threads in the current process and run the callback on the list
// of suspended threads. This function will resume the threads before returning.
// The callback should not call any libc functions. The callback must not call
// exit() nor _exit() and instead return to the caller.
// This function should NOT be called from multiple threads simultaneously.
void StopTheWorld(StopTheWorldCallback callback, void *argument);
```

**Comment by Trass3r** [comment]
Somehow I read the t as l :laughing:

**Comment by dvyukov** [comment]
Should be easy with CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD)/SuspendThread/ResumeThread.

**Comment by clemenswasser** [comment]
@kcc, @dvyukov Is there some up-to-date information, on what needs to be done here?
@Trass3r are you still interested in implementing this?
I am also interested in implementing this 😄

**Comment by Trass3r** [comment]
No I'm on Linux now.
Afaik Microsoft implemented asan for Windows
https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/asan/asan_win.cpp
but not lsan.
https://github.com/llvm/llvm-project/tree/main/compiler-rt/lib/lsan
