### ISSUE TITLE
cannot find libasan_preinit.o and -lasan

### ISSUE THREAD

**Issue by yyh-graphsql** [google/sanitizers#695]
When I use -fsanitize=address to link some object into a binary, g++ said the two lib in the title are not exist. 
My g++ version is:

```
$ /opt/rh/devtoolset-2/root/usr/bin/g++ -v
Using built-in specs.
COLLECT_GCC=/opt/rh/devtoolset-2/root/usr/bin/g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --with-mpc=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
```

Do I need to manually compile the libasan if I use g++?

**Comment by noloader** [comment]
This is intentional, but I've never quite understood the reasoning. Also see [Issue 1303766: GCC missing libasan and libubsan after installing gcc and gcc-c++](http://bugzilla.redhat.com/show_bug.cgi?id=1303766).

**Comment by morehouse** [comment]
Please re-open if still an issue.

**Comment by mahmud-antor** [comment]
libubsan-7.3.1-5.16.el6.x86_64
libubsan1-8.3.1-3.1.el6.x86_64
libasan4-7.3.1-5.15.el6.x86_64
devtoolset-6-libasan-devel-6.3.1-3.1.el6.x86_64
libasan3-6.3.1-3.1.el6.x86_64

I have this packages installed for OS -
Name        : kernel
Arch        : x86_64
Version     : 2.6.32
Release     : 504.el6
Size        : 124 M
Repo        : installed
From repo   : anaconda-CentOS-201410241409.x86_64
Summary     : The Linux kernel
URL         : http://www.kernel.org/
License     : GPLv2
Description : The kernel package contains the Linux kernel (vmlinuz), the core of any
            : Linux operating system.  The kernel handles the basic functions
            : of the operating system: memory allocation, process allocation, device
            : input and output, etc

but every time I try to use "gcc -g -fsanitize=address test.c -o test1" I face this error

/usr/bin/ld: libasan_preinit.o: No such file: No such file or directory
collect2: error: ld returned 1 exit status

Can anyone help me please! TIA

**Comment by NanXiao** [comment]
@mahmud-antor I guess your can use `-static-libasan`:
```
gcc -g -static-libasan -fsanitize=address test.c -o test1
```

**Comment by NanXiao** [comment]
@mahmud-antor : Could you show me the output of "`gcc -v`" and "`gcc -v -g -fsanitize=address test.c -o test1`"?

**Comment by Aitinkle** [comment]
`yum install devtoolset-8-libasan-devel` try it.

**Comment by Aitinkle** [comment]
My SDE:  gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
