### ISSUE TITLE
GNU version of strerror_r interceptor counts as a write to static storage

### ISSUE THREAD

**Issue by toddlipcon** [google/sanitizers#696]
In the strerror_r interceptor, for the GNU case, 'res' is a pointer to either the user-provided buffer, or to some static storage owned by the library. The interceptor currently handles it as:

```
  } else {
    // GNU version.
    COMMON_INTERCEPTOR_WRITE_RANGE(ctx, res, REAL(strlen)(res) + 1);
  }
```

which is incorrect if 'res' is not a pointer to 'buf'. I think there should be an additional 'if (res == buf)' condition here.

**Comment by toddlipcon** [comment]
I verified that glibc returns a pointer to existing const storage, see http://repo.or.cz/glibc.git/blob/HEAD:/string/_strerror.c#l71

So this is definitely incorrect behavior.

**Comment by toddlipcon** [comment]
Put up a fix here: https://reviews.llvm.org/D27062

**Comment by morehouse** [comment]
https://reviews.llvm.org/D27062 landed 1 year ago.
