### ISSUE TITLE
LargeMmapAllocator problem

### ISSUE THREAD

**Issue by daliands** [google/sanitizers#697]
I get the log as belows:
07-08 08:41:08.741: I/(11150): ==11150==ERROR: AddressSanitizer failed to allocate 0x20e4000 (34488320) bytes of LargeMmapAllocator (error code: 12)
07-08 08:41:08.891: I/(11150): ==11150==Process memory map follows:
........
07-08 08:41:09.431: I/(11150): ==11150==End of process memory map.
07-08 08:41:09.431: I/(11150): ==11150==AddressSanitizer CHECK failed: external/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common.cc:183 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
07-08 08:41:09.541: I/(11150):     #0 0x400a6bdb  (/system/lib/libclang_rt.asan-arm-android.so+0x7fbdb)
07-08 08:41:09.541: I/(11150):     #1 0x400abb13  (/system/lib/libclang_rt.asan-arm-android.so+0x84b13)
07-08 08:41:09.541: I/(11150):     #2 0x400b4063  (/system/lib/libclang_rt.asan-arm-android.so+0x8d063)
07-08 08:41:09.541: I/(11150):     #3 0x40042543  (/system/lib/libclang_rt.asan-arm-android.so+0x1b543)
07-08 08:41:09.541: I/(11150):     #4 0x4004218b  (/system/lib/libclang_rt.asan-arm-android.so+0x1b18b)
07-08 08:41:09.541: I/(11150):     #5 0x4003efeb  (/system/lib/libclang_rt.asan-arm-android.so+0x17feb)
07-08 08:41:09.541: I/(11150):     #6 0x4003fa37  (/system/lib/libclang_rt.asan-arm-android.so+0x18a37)
07-08 08:41:09.541: I/(11150):     #7 0x4009c0d7  (/system/lib/libclang_rt.asan-arm-android.so+0x750d7)
07-08 08:41:09.541: I/(11150):     #8 0x405aa26f  (/system/lib/libcutils.so+0x426f)
07-08 08:41:09.541: I/(11150):     #9 0x4054edc9  (/system/lib/libc.so+0x25dc9)
07-08 08:41:09.541: I/(11150):     #10 0x4053db81  (/system/lib/libc.so+0x14b81)
07-08 08:41:09.541: I/(11150):     #11 0x43f5facb  (/system/lib/libdvm.so+0x5facb)
07-08 08:41:09.541: I/(11150):     #12 0x43f5fb1d  (/system/lib/libdvm.so+0x5fb1d)
07-08 08:41:09.541: I/(11150):     #13 0x43f5f4af  (/system/lib/libdvm.so+0x5f4af)
07-08 08:41:09.541: I/(11150):     #14 0x43f28e83  (/system/lib/libdvm.so+0x28e83)
07-08 08:41:09.541: I/(11150):     #15 0x43f5f1df  (/system/lib/libdvm.so+0x5f1df)
07-08 08:41:09.541: I/(11150):     #16 0x43f65807  (/system/lib/libdvm.so+0x65807)
07-08 08:41:09.541: I/(11150):     #17 0x43f26fe3  (/system/lib/libdvm.so+0x26fe3)
07-08 08:41:09.541: I/(11150):     #18 0x43f2dfa3  (/system/lib/libdvm.so+0x2dfa3)
07-08 08:41:09.541: I/(11150):     #19 0x43f2b63b  (/system/lib/libdvm.so+0x2b63b)
07-08 08:41:09.541: I/(11150):     #20 0x43f6057f  (/system/lib/libdvm.so+0x6057f)
07-08 08:41:09.541: I/(11150):     #21 0x43f605a3  (/system/lib/libdvm.so+0x605a3)
07-08 08:41:09.541: I/(11150):     #22 0x43f55289  (/system/lib/libdvm.so+0x55289)
07-08 08:41:09.541: I/(11150):     #23 0x40536173  (/system/lib/libc.so+0xd173)
07-08 08:41:09.541: I/(11150):     #24 0x4053630b  (/system/lib/libc.so+0xd30b)

I can't make sure it's a problem of OOM or a problem of AddressSanitizer.And I can't find where my code alloces a large memory.

**Comment by chefmax** [comment]
> I can't make sure it's a problem of OOM or a problem of AddressSanitize

This is most likely an OOM. Do you use **ulimit -v** or something like this?

> And I can't find where my code alloces a large memory.

Look at frame #11 in backtrace, most likely you call malloc from here. To get more information, you'll probably want to symbolize the backtrace (e.g. by using **asan_symbolize.py** script or rebulding your libraries with debug info available).

**Comment by yugr** [comment]
> And I can't find where my code alloces a large memory.

Note that ASan's allocator may mmap N times more than your app requested.

**Comment by yugr** [comment]
> Note that ASan's allocator may mmap N times more than your app requested.

(to proactively allocate memory for future requests)

**Comment by morehouse** [comment]
Please re-open if still an issue.
