### ISSUE TITLE
LeakSanitizer not working in gcc 4.8.2

### ISSUE THREAD

**Issue by yyh-graphsql** [google/sanitizers#699]
First I just hard code a memory leak in the program. After I compiled the binary with -fsanitize=address. It showed nothing. Is it normal situation or Did I miss something?

**Comment by yugr** [comment]
It's hard to say without an example. Note that leak detector is disabled on 32-bit platforms as it's considered to not be reliable there.

**Comment by yyh-graphsql** [comment]
@yugr  The platform of our system is 64bits. It's centos 7.1.（Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux）. And the hacked leak code is just "int *a = new int (4);" in a function definitely will invoked

**Comment by yugr** [comment]
Just to check, could you try with
```
volatile int *a = new int (4);
a = 0;
```
?

**Comment by yyh-graphsql** [comment]
The code:
#include <cstdio>
int main() {
volatile int *a = new int(3);
a = 0;
return 0;
}

compile: g++ -fsanitize=address -o 1 /tmp/1.cpp
run: ASAN_OPTIONS='detect_leaks=1' ./1
output: 'nothing'

**Comment by yyh-graphsql** [comment]
Is it related to the libasan's version ?

**Comment by chefmax** [comment]
Yes,  AFAIK LSan is available in GCC 4.9+.

**Comment by chefmax** [comment]
gcc-4_8-branch doesn't even contain libsanitizer/lsan/ directory. Please try more recent GCC versions.

**Comment by yyh-graphsql** [comment]
Let me try gcc 4.9. Thanks a lot!

**Comment by chefmax** [comment]
Closing than.

**Comment by rootkea** [comment]
I'm using `gcc 4.9.2` and no. `-fsanitizer=address` doesn't report memory leak. You need `-fsanitizer=leak` for that.

Here is an interesting bit (bug?) with gcc 4.9.2 though. `-fsanitizer=leak` doesn't work with `-fsanitizer=address`. Yes! Weird!

**Comment by kcc** [comment]
@rootkea lsan is enabled as part of asan, so if you have `-fsanitizer=address` leak detection is enabled. 
(not sure about 4.9.2, maybe it's too old). 
`-fsanitizer=leak` is a way to enable *just* lsan, w/o asan. 
You can not pass both `-fsanitizer=leak` and `-fsanitizer=address`

**Comment by chefmax** [comment]
Hm, it seems that for gcc 4.9 LSan is disabled by default when using with ASan. Use `ASAN_OPTIONS=detect_leaks=1` to enable leak detection.

**Comment by rootkea** [comment]
> Use ASAN_OPTIONS=detect_leaks=1 to enable leak detection

I did `ASAN_OPTIONS=detect_leaks=1`. Then `gcc foo.c -fsanitize=address -o foo`. After which `./foo` gets executed smoothly. It's only when  I use `-fsanitize=leak` it shows memory leak.

**Comment by hyyeah** [comment]
I  have the same problem with rootkea
