### ISSUE TITLE
unrecognized command line option '-fsanitize-recover=all'

### ISSUE THREAD

**Issue by 0chunhui** [google/sanitizers#700]
when compile with -fsanize-recover=all, g++ report this error.
How to resolve it?

**Comment by chefmax** [comment]
What GCC version do you use?

**Comment by 0chunhui** [comment]
4.8.5

**Comment by yugr** [comment]
I think it's not available until GCC 5 (or even 6?).

**Comment by chefmax** [comment]
Yeah,  -fsanitize-recover=all was added to GCC 5.

**Comment by 0chunhui** [comment]
Well, it goes to fast....
