### ISSUE TITLE
Address Sanitizer take two much virtual memory

### ISSUE THREAD

**Issue by 0chunhui** [google/sanitizers#704]
When I run a program compiled and linked with -fsanitize=address, it takes 17.001t virtual memory, and the PC became much slower. Is this a bug? Why does it take so much virtual memory?

**Comment by wang0109** [comment]
Are you running windows 64-bit?

**Comment by 0chunhui** [comment]
No, on linux x86-64

**Comment by wang0109** [comment]
To my understanding, 1/8 of total virtual space is reserved for shadow memory, which is likely 128TB/8 = 16TB. That's fine since it's not actually backed by physical memory until your program use it. Perhaps your program's resident memory is high enough to cause swapping to hard disk.

**Comment by kcc** [comment]
> When I run a program compiled and linked with -fsanitize=address, it takes 17.001t virtual memory,

You are using a pretty old version. 
The newer one consumes 20t. 
And that is normal, see https://github.com/google/sanitizers/wiki/AddressSanitizerAlgorithm

>  and the PC became much slower. 

This is not normal. 
asan usually has 2x slowdown and should not affect the whole system, unless you have too little *physical* memory and asan's extra memory consumption causes swapping

**Comment by 0chunhui** [comment]
If I compile and link the program with both tcmalloc and -fsanitizer=address, which one will replace malloc at last?

**Comment by kcc** [comment]
That's up to the linker. I don't know who will win. Don't do this.

**Comment by yugr** [comment]
This depends on how you link. Generally if you build your main executable with ASan, it will win (i.e. ASan malloc will be the first one to be called and will call tcmalloc afterwards).

**Comment by charliegracie** [comment]
Related to the huge amount of virtual memory consumed. Is it possible to force this reservation to a much higher address range? On some versions of Linux this memory is being consumed at a very low range and consuming an address range our application requires.
