### ISSUE TITLE
LSAN_OPTIONS=print_reachable

### ISSUE THREAD

**Issue by basinilya** [google/sanitizers#705]
A program may have a global map or vector (a cache, for example), and forget to remove objects from there, when they're no longer needed. LSan is unable to detect them, because they're formally reachable.

I assume that if a program runs long enough, such lost objects will constitute the greater part of allocated memory and it would be easy for the developer to tell what's wrong, if only LSan could print such objects in its usual manner - grouped by unique backtrace, sorted by number of bytes.

**Comment by kcc** [comment]
If you build with asan you may try using __sanitizer_print_memory_profile
(`#include <sanitizer/common_interface_defs.h>`), see here: 
https://llvm.org/svn/llvm-project/compiler-rt/trunk/include/sanitizer/common_interface_defs.h

Another option is to overwrite all elements on you map/vector/cache and exit(0), which will cause the usual lsan logic to kick in.

**Comment by basinilya** [comment]
Which versions of clang/gcc have it? Even on Archlinux with clang 3.8 and gcc 6.1.1 it's missing.

**Comment by kcc** [comment]
__sanitizer_print_memory_profile was added recently, you may only find it in Clang trunk. 
Its functionality is pretty simple, but should do what you are asking for.

**Comment by morehouse** [comment]
Looks resolved, please re-open if not.
