### ISSUE TITLE
Sancov support on AArch64

### ISSUE THREAD

**Issue by mikea** [google/sanitizers#706]
@eugenis 

sancov doesn't work on AArch64 due to LLVM disassembler limitations.

Discovered problems:
- `MCInstrAnalysis::evaluateBranch` doesn't work for AArch64. This seems to be incomplete instruction definition. It doesn't specify arguments as offsets:

``` c
static const MCOperandInfo OperandInfo2[] = { { -1, 0, MCOI::OPERAND_UNKNOWN, 0 }, };

  { 147,        1,      0,      4,      117,    0|(1ULL<<MCID::Call), 0x0ULL, ImplicitList2, ImplicitList3, OperandInfo2, -1 ,nullptr },  // Inst #147 = BL
```

**Comment by mikea** [comment]
https://reviews.llvm.org/rL278560 enables dummy MCInstrAnalysis.

**Comment by morehouse** [comment]
@kcc:  Do we still care about SanCov on AArch64?

**Comment by kcc** [comment]
nope
