### ISSUE TITLE
Issues with ASAN in Windows 10 Ubuntu subsystem

### ISSUE THREAD

**Issue by ztdwu** [google/sanitizers#708]
The output of a C++ program built with `-fsanitize=address` in the new Windows 10 Ubuntu subsystem: 

> ==6089==Sanitizer CHECK failed: /build/llvm-toolchain-3.8-mC_dbv/llvm-toolchain-3.8-3.8/projects/compiler-rt/lib/sanitizer_common/sanitizer_procmaps_linux.cc:57 ((IsOneOf(*current_, 's', 'p'))) != (0) (0, 0)

The program:

``` c++
int main() { }
```

Tested with gcc4.8, gcc5, gcc6, clang3.7, clang3.8

**Comment by kcc** [comment]
Ouch. I am sorry for that.
You are the first asan user I know who cares about the "Windows 10 Ubuntu subsystem".
This particular assertion tells us that procmaps on Windows10/Ubuntu are not as good as on the real Ubuntu.

**Comment by kasper93** [comment]
Some information about the issue. ASAN expects procmaps to be formatted as follows 
```08048000-08056000 r-xp 00000000 03:0c 64593   /foo/bar```
It fails on the last char of permissions part. It expects either `s` or `p`. On Windows information whether mapping is shared or private is not available and `-` is shown instead which triggers assert here https://github.com/llvm-mirror/compiler-rt/blob/74c8f498fa128f0cd4eb97d603c017f250dd3694/lib/sanitizer_common/sanitizer_procmaps_linux.cc#L59

**Comment by kcc** [comment]
The problem seems pretty minor and we could accept, but we have no way to test it :(

**Comment by eugenis** [comment]
We can totally test it. Just give MemoryMappingLayout a test-only
constructor that accepts a text buffer, and pass a saved copy of
/proc/self/maps from Windows.

On Thu, Apr 20, 2017 at 4:31 PM, Kostya Serebryany <notifications@github.com

**Comment by kasper93** [comment]
Not worth until they fix performance issues with large memory mappings. It is just so slow that I can't even run empty main, because it takes forever to init everything. I left it for an hour and it was still in asan init code. ASAN maps 20TB and it kills current WSL. See https://github.com/Microsoft/BashOnWindows/issues/1671 which seems to be the same issue with large mmap.

**Comment by kcc** [comment]
> performance issues with large memory mappings

Sounds like the same problem that we have with native asan-on-windows, where we can't mmap the shadow properly and instead need to mmap it partially in SEGV handler. This sucks utterly. @rnk FYI

**Comment by rnk** [comment]
Makes sense. I think we need to investigate how control flow guard maps massive amounts of virtual memory efficiently.

I agree with @kcc, if your app is portable, for now you'll get better mileage running it natively on Windows or Linux, and not using the Windows subsystem for Linux.

**Comment by MikeGitb** [comment]
Just wanted to drop by to say that I'm also very interested in running thread sanitizer on WSL. But from the comments it sounds as if there is not a lot you can do about it.

**Comment by retep998** [comment]
@kcc How exactly is the memory being mapped in the native windows version? Are you memory mapping an actual file, are you creating a shared mapping to be shared with other processes, or are you just allocating virtual memory? If it is the third option, then the efficient option is to use `VirtualAlloc`. According to some local benchmarks, reserving 16TB of address space with `VirtualAlloc` only takes 10 milliseconds.

**Comment by rnk** [comment]
@retep998 Yes, we use VirtualAlloc to reserve 1/8 the address space. However, if we try to *commit* that much address space, the kernel usually returns an error. Instead, on Windows, we effectively do our own page fault handling for shadow memory with a vectored exception handler.

I suspect that the Windows subsystem for Linux will also fail or perform poorly if you ask it to mmap 1/8 the address space.

**Comment by DarthSpock** [comment]
See [Release Notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063) You "may" be able to further increase interop and performance now. Also see [WSL/121](https://github.com/Microsoft/WSL/issues/121)

**Comment by DarthSpock** [comment]
ASAN should work now as of Insider build 17093, see above link for Release Notes and WSL issue for more details. If there are any failings, perform an strace and provide in WSL/121 as linked above. 

@rnk 

> we effectively do our own page fault handling for shadow memory with a vectored exception handler

With AF_Unix on Windows and now has interop with WSL, are you able to take advantage of this capability to change your current page fault handling configuration? If so, I'd recommend making the change but still make the current implementation available in case it proves too buggy until there's more support in AF_Unix for Windows.

**Comment by DarthSpock** [comment]
Confirmed as fixed as of 17093 by another person so this can be marked closed.

**Comment by morehouse** [comment]
Sounds fixed.  Please re-open if not.
