### ISSUE TITLE
ASAN_OPTIONS log_path log file opened without O_APPEND

### ISSUE THREAD

**Issue by basinilya** [google/sanitizers#709]
I periodically call `__sanitizer_print_memory_profile()` and `__lsan_do_recoverable_leak_check()`. Before each call I copy/truncate the log file. After the truncation the new data is written with an offset. 

It appears that the log file is opened without O_APPEND, which is untraditional.

    [il@reallin log]$ xxd "sanitizer-rap - Copy.log-1" | tail
    00191830: 3520 696e 2052 6170 5365 7276 6963 6544  5 in RapServiceD
    00191840: 4247 6574 436f 6e74 6578 7420 2f68 6f6d  BGetContext /hom
    00191850: 652f 696c 2f77 6f72 6b73 7061 6365 2f72  e/il/workspace/r
    00191860: 6170 6d61 7374 6572 2f63 2f72 6170 2f72  apmaster/c/rap/r
    00191870: 6170 5f70 7062 5f64 622e 7063 3a32 3235  ap_ppb_db.pc:225
    00191880: 3a32 300a 0a53 554d 4d41 5259 3a20 4164  :20..SUMMARY: Ad
    00191890: 6472 6573 7353 616e 6974 697a 6572 3a20  dressSanitizer:
    001918a0: 3134 3335 3532 2062 7974 6528 7329 206c  143552 byte(s) l
    001918b0: 6561 6b65 6420 696e 2032 3930 3720 616c  eaked in 2907 al
    001918c0: 6c6f 6361 7469 6f6e 2873 292e 0a         location(s)..

    [il@reallin log]$ xxd "sanitizer-rap.log-1" | grep -C10 ^001918c0
    00191820: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191830: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191840: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191850: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191860: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191870: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191880: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00191890: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    001918a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    001918b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    001918c0: 0000 0000 0000 0000 0000 0000 004c 6976  .............Liv
    001918d0: 6520 4865 6170 2041 6c6c 6f63 6174 696f  e Heap Allocatio
    001918e0: 6e73 3a20 3230 3230 3432 3935 2062 7974  ns: 20204295 byt
    001918f0: 6573 2066 726f 6d20 3136 3035 3020 616c  es from 16050 al
    00191900: 6c6f 6361 7469 6f6e 733b 2073 686f 7769  locations; showi
    00191910: 6e67 2074 6f70 2031 3030 250a 3236 3438  ng top 100%.2648
    00191920: 3230 3020 6279 7465 2873 2920 2831 3325  200 byte(s) (13%
    00191930: 2920 696e 2035 2061 6c6c 6f63 6174 696f  ) in 5 allocatio
    00191940: 6e28 7329 0a20 2020 2023 3020 3078 3463  n(s).    #0 0x4c
    00191950: 6439 3438 2069 6e20 5f5f 696e 7465 7263  d948 in __interc
    00191960: 6570 746f 725f 6d61 6c6c 6f63 202f 746d  eptor_malloc /tm

**Comment by kcc** [comment]
Why would we open the log file with O_APPEND? 
We don't want to append the log to an existing file.

**Comment by basinilya** [comment]
When disk full, you either stop a program producing the log file or rotate the log. A cheap form of log rotation to truncate it. O_APPEND helps in this case. Most loggers use this flag. One example of a logger not supporting real rotation was in IBM db2 9.5 and earlier.

**Comment by basinilya** [comment]
> We don't want to append the log to an existing file. 
Then combine O_APPEND with O_TRUNC. That's what `tee` does.

**Comment by kcc** [comment]
Not convinced so far that this is worth extra complexity. 
In most cases the sanitizers don't produce huge logs. 
Having O_APPEND will complicate the regular logic (where we currently expect to overwrite the existing file on disk, not append)

For your use case you may report to stderr instead of a file and then pipe it to something

**Comment by basinilya** [comment]
Ask other people what they think

**Comment by kcc** [comment]
Well, let "other people" comment here and lets reopen if there is a high demand.
