### ISSUE TITLE
MSAN is saying std::cout is uninitialized .. 

### ISSUE THREAD

**Issue by ehzShelter** [google/sanitizers#712]
![hell](https://cloud.githubusercontent.com/assets/12381692/17703782/c3fb300c-63f4-11e6-8878-a4077e115d26.png)

I have got this several times...

Confusing ...
Is that issue with libc++abi of Clang or Google Sanitizer?

**Comment by kcc** [comment]
Did you follow https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo ?

**Comment by ehzShelter** [comment]
Yeah .. I have followed that..

**Comment by kcc** [comment]
@eugenis

**Comment by ehzShelter** [comment]
In my .bash_profile

**alias cxx="clang++ -ggdb3 -O0 -std=c++14 -stdlib=libc++ -lc++abi -ldl -Werror -Wself-assign -Wall -pedantic-errors -Wextra-tokens -Wambiguous-member-template -Wbind-to-temporary-copy -fdiagnostics-print-source-range-info -fcolor-diagnostics -fdiagnostics-show-template-tree -ferror-limit=33 -ftemplate-backtrace-limit=13 -lpthread -l:libmagic.so.1"

alias MSanCC='cxx -fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer'**

this is how I build my program..

Address sanitizer works properly..

Maybe, I am missing something.. Actually, I didn't build libc++abi from scratch rather I am using official prebuild binaries of Clang 3.8.1 (http://llvm.org/releases/download.html) 

Disclaimer : I am noob....maybe, I am missing something :/ @kcc

**Comment by eugenis** [comment]
You are probably running against the system libc++.
Try adding RPATH to the binary, or setting LD_LIBRARY_PATH environment variable.

Non-instrumented libc++abi could also be a problem.

**Comment by ehzShelter** [comment]
How can I check that "it is Non-instrumented libc++abi or NOT?"

PATH is set properly, I think.

**# clang LLVM
export LLVMCLANG=~/.myClang
export PATH=$LLVMCLANG/bin:$PATH
export CPATH=$LLVMCLANG/include
# On Mac OS X, replace LD_LIBRARY_PATH with DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/.myClang/lib
export LIBRARY_PATH=~/.myClang/lib
export CPLUS_INCLUDE_PATH="$LLVMCLANG/include/c++/v1"
unset MANPATH
export MANPATH="$LLVMCLANG/share/man:$(manpath)"**

Is there need anything else?
Need to mention that, I am using Ubuntu 16.04.1

**Comment by eugenis** [comment]
Look at /proc/$PID/maps for your program. If it loads libc++ or libc++abi library that you did not build with MSan, then it's not instrumented.

**Comment by ehzShelter** [comment]
Sorry to say, I am not familiar with that command ..After googling get confused... little bit details
![hell](https://cloud.githubusercontent.com/assets/12381692/17712955/49790496-641a-11e6-9693-0dabd821a12d.png)

**Comment by eugenis** [comment]
ldd should tell you the library path to libc++

**Comment by ehzShelter** [comment]
looks like.. I have no MSan-ified libc++... So I have to build MSan-ified libc++.
