### ISSUE TITLE
c++11 standard regex support (Crappy Situation)(Two scenerio)

### ISSUE THREAD

**Issue by ehzShelter** [google/sanitizers#713]
Actually, when I compile -std=c++14 -stdlib=libc++ -fsanitize=memory, it throws error(Unitilized Value) of iostream header (REGEX header is ok this time)

Then , I use -std=c++14 -lc++abi -fsanitize=memory, it throws error(Unitilized Value) of regex header (ref http://en.cppreference.com/w/cpp/regex) but iostream header is ok now, REGEX does not support here beacuse It really needs -stdlib=libc++ FLAG for MSAN not for trivial compilation.

But, Otherwise It is good for catching memory related bug....

THREE situation : screenshot added for visualizing the issue.. 
Maybe, I am missing something .. may be or not :/ :/

![shit](https://cloud.githubusercontent.com/assets/12381692/17738118/c8d72fe6-64b1-11e6-98f4-8967d16dc4c2.png)
![right](https://cloud.githubusercontent.com/assets/12381692/17738122/cead2fc4-64b1-11e6-8d82-243eb1ef8236.png)

**Comment by Bu11etmagnet** [comment]
Please don't post screenshots of text. You can select, copy and paste text from a terminal window.

**Comment by ehzShelter** [comment]
Tools are promising, but documentation are frustrating for newbie.. Issue resolved !! :-1:  :+1: :
