### ISSUE TITLE
question: does anyone know which gcc supports AddressSanitizer for MIPS?

### ISSUE THREAD

**Issue by keitee** [google/sanitizers#720]
Hello,

Considering to use AddressSanitizer for MIPS embedded platform but it is difficult to find if GCC supports it for MIPS. Anyone knows this please?

Many thanks

**Comment by chefmax** [comment]
I'm afraid GCC doesn't support ASan for MIPS even now on trunk:
```
$ cat libsanitizer/configure.tgt

case "${target}" in
  x86_64-*-linux* | i?86-*-linux*)
        if test x$ac_cv_sizeof_void_p = x8; then
                TSAN_SUPPORTED=yes
                LSAN_SUPPORTED=yes
                TSAN_TARGET_DEPENDENT_OBJECTS=tsan_rtl_amd64.lo
        fi
        ;;
  powerpc*-*-linux*)
        ;;
  sparc*-*-linux*)
        ;;
  arm*-*-linux*)
        ;;
  aarch64*-*-linux*)
        if test x$ac_cv_sizeof_void_p = x8; then
                TSAN_SUPPORTED=yes
                LSAN_SUPPORTED=yes
                TSAN_TARGET_DEPENDENT_OBJECTS=tsan_rtl_aarch64.lo
        fi
        ;;
  x86_64-*-darwin[1]* | i?86-*-darwin[1]*)
        TSAN_SUPPORTED=no
        ;;
  *)
        UNSUPPORTED=1
        ;;
esac

```

**Comment by dvyukov** [comment]
clang should support mips. At least I see multiple mentions of mips in code
and tests. No idea what version, I would use the latest one.

**Comment by dvyukov** [comment]
clang should support mips. At least I see multiple mentions of mips in code and tests. No idea what version, I would use the latest one.

Please direct non-issue questions to address-sanitizer@googlegroups.com

**Comment by keitee** [comment]
Many thanks @chefmax and @dvyukov

**Comment by TXTT2016** [comment]
I have seen sanitizer support MIPS, does sanitizer which gcc built support support fo MIPS?
And which gcc version support?
