### ISSUE TITLE
keep going when runtime errors are being found ?

### ISSUE THREAD

**Issue by ghost** [google/sanitizers#725]
I have small project with qt5 framework especially on qtcore module. compiling simple hello world with qcoreapplication class was producing memory error from qt5 side instead of mine simple main.cpp test app. was it possible to skip exiting program after -fsanitize=memory errors were being found? I wasn't interested in fixing huge qt5 sources memory bugs.
thanks

**Comment by kangjoni76** [comment]
PS: I was doing  dynamic linking with self debug build qt5.

**Comment by sitsofe** [comment]
Does using `-fsanitize=recover` work (see http://clang.llvm.org/docs/UsersManual.html )?

**Comment by sitsofe** [comment]
Looking further you might been to use set the appropriate environment variable before running your program e.g. `MSAN_OPTIONS=halt_on_error=0 program` (assuming your version on the sanitizers is new enough)...

**Comment by eugenis** [comment]
It appears that -fsanitize=recover is not doing anything for MSan. You
could use -mllvm -msan-keep-going=1, along
with MSAN_OPTIONS=halt_on_error=0 at runtime.

Did you read
http://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code ? To
get anything useful out of MSan, you'll need to build QT libraries with it.

**Comment by kangjoni76** [comment]
ah sorry for late answer, yes ````-fsanitize=recover```` solve the problem , memory sanitation is hard to achieve, both undefined and address sanitizer may be what I was looking for atm. Thanks

**Comment by marxin** [comment]
Can you @ghost please close this issue?
