### ISSUE TITLE
Unable to disable asan-stack with clang

### ISSUE THREAD

**Issue by kcwu** [google/sanitizers#726]
My code is at https://github.com/kcwu/oss-fuzz/tree/add-boehmgc/boehmgc

I want to write fuzzer for boehmgc. Since it is a GC library and will scan the stack, I'd like to disable ASAN stack check. So I added `-mllvm -asan-stack=0` to CFLAGS.

However,  ASAN still report stack-buffer-overflow error
```
SUMMARY: AddressSanitizer: stack-buffer-underflow (/out/boehmgc/boehmgc_fuzzer+0x679c29)
```

How to reproduce
```
git clone https://github.com/kcwu/oss-fuzz.git
cd oss-fuzz
git checkout origin/add-boehmgc
python scripts/helper.py build_image boehmgc
python scripts/helper.py build_fuzzers boehmgc
python scripts/helper.py run_fuzzer boehmgc boehmgc_fuzzer
```

clang version 
```
clang version 4.0.0 (http://llvm.org/git/clang.git ce09b185b48ab28a787951c1047980fb0d543f3a) (http://llvm.org/git/llvm.git f98f3575ee34efdab29f304f37cf5ec626d78a1a)
```

I can disable asan-stack with gcc, btw.

**Comment by kcc** [comment]
Can you reproduce the problem on something smaller?

**Comment by kcwu** [comment]
I found I cannot reproduce with dummy fuzzer.
```
#include <stddef.h>
#include <stdint.h>
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  int a[10], b[10], c[10];
  b[15] = 1;
  return 0;
}
```

Now my question is, how does `-mllvm -asan-stack=0` work? Is it compile time option? or link time?
How can I tell stack-check is enabled via objdump? by existence of call  __asan_report_load8 ?

**Comment by kcc** [comment]
The above test case is bad, it compiles with warnings and the compiler optimizes it away. 
Simpler example:
```
int foo(int a, int b) {
  int x[10];
  x[b] = 1;
  return x[a];
}
```

```
% clang -fsanitize=address   a.c -O -c  && nm a.o | grep asan_stack_malloc
                 U __asan_stack_malloc_1
% clang -fsanitize=address   a.c -O -c -mllvm -asan-stack=0 && nm a.o | grep asan_stack_malloc
% 
```
So, the option works on this case.

The option is compile-time. 
You can tell if it worked by the absence of calls to `*asan_stack_malloc` in the binary.

Closing. Please provide a buildable runnable example where it does not work to reopen. 

Also note that `-mllvm -asan-stack=0` is not strictly supported, this option is mostly for our own experiments

**Comment by eugenis** [comment]
It's better to add a no_sanitize_address attribute to the function(s) that
scan the stack, and keep asan stack checking on for the rest of the code.

On Mon, Oct 3, 2016 at 10:20 AM, Kostya Serebryany <notifications@github.com
