### ISSUE TITLE
alloc-dealloc-mismatch error when overloading the operator new

### ISSUE THREAD

**Issue by phelippeneveu** [google/sanitizers#727]
Hi,

I get a alloc-dealloc-mismatch error when overloading the operator new. My operator new overload is simply using malloc() and memset() to make sure the memory is initialized to 0. I cannot use the "new Vertex_t()" syntax to initialize the memory because my structure might define a constructor that doesn't initialize all the members. Is there a way around this problem? How can I flag the address to be allocated using new instead of malloc()?

I'm using GCC 4.8 on CentOS 7 and compiled the following example with this command:

g++ -fsanitize=address -o test test.cpp

test.cpp
```
#include <new>
#include <cstdlib>
#include <cstring>

struct zeromemory_t { };

void * operator new(size_t nSize, const zeromemory_t &)
{
    void * p = malloc(nSize);

    memset(p, 0, nSize);

    return p;
}

struct Vertex_t
{
    double x;
    double y;
    double z;

    Vertex_t(void)
        : x(0),
          y(0)
    {
    }
};

int main(void)
{
    Vertex_t * zero = new(zeromemory_t()) Vertex_t;

    delete zero;

    return 0;
}
```

Thanks,

Phelippe Neveu

**Comment by yugr** [comment]
I'm not sure why you reported this as ASan bug as your code obviously contains several bugs.

> How can I flag the address to be allocated using new instead of malloc()?

I suggest
  p = new char[nSize];
and later
  delete [] p;

**Comment by phelippeneveu** [comment]
This is simply sample code to expose my problem. The original code uses a template method to allocate a class of type T which might not initialize all the members in its constructor. I was looking for a solution that didn't require me to change the calls to the delete operator since there are many throughout our source code. Thanks for your suggestion anyway.

My bad for posting this as a ASan issue.

**Comment by yugr** [comment]
> My bad for posting this as a ASan issue.

Np but it's better to post questions to ASan Google group (you'll get help from many more ASan users whereas here you'll only find maintainers, sometimes).
