### ISSUE TITLE
Detect Use after destruction (but before free) 

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#73]
Originally reported on Google Code with ID 73
```
We may want to poison memory on a call to a destructor so that 
a use of destructed (but not yet deleted) object is detected. 
The tricky part here is how to handle placement new followed by an explicit 
call to a DTOR. 
```

Reported by `konstantin.s.serebryany` on 2012-05-22 13:08:44

**Comment by kcc** [comment]
This is implemented in msan as -fsanitize-memory-use-after-dtor. 
Closing this bug. 
Making this flag on by default is another story.
