### ISSUE TITLE
Why does the address sanitizer cost quite a lot memory sometimes?

### ISSUE THREAD

**Issue by 0chunhui** [google/sanitizers#731]
When I compile my program with the Address Sanitizer, my program cost 1.8G memory in run time(600M without the AS. However, recently I find that it cost about 10+G or even 100+G !!!! 
I don't know whether it is a problem of my program, or it is the bug of AS.

**Comment by yugr** [comment]
@0chunhui how do you measure memory consumption?

**Comment by kcc** [comment]
On Sun, Oct 23, 2016 at 7:56 PM, 0chunhui <notifications@github.com> wrote:

> When I compile my program with the Address Sanitizer, my program cost 1.8G
> memory in run time(600M without the AS.
>
3x is not unheard of.


> However, recently I find that it cost about 10+G or even 100+G !!!!
>

I will need more info.
Also, make sure you are measuring real memory (RSS) and not virtual.
asan consumes 20Tb of virtual memory and that is perfectly normal.

--kcc

**Comment by 0chunhui** [comment]
@yugr I use command 'top'

**Comment by 0chunhui** [comment]
@kcc  I'm sure it is real memory.  It costs 600M without asan, and 8-9G with asan.

**Comment by yugr** [comment]
@0chunhui how do you measure memory consumption?

**Comment by 0chunhui** [comment]
@yugr Input the command "top" in the console, it will show the memory cosumption of each progress.
The RSS colomn indicates the real memory cosumption.

**Comment by 0chunhui** [comment]
@kcc what other information do you need?

**Comment by yugr** [comment]
Yes, rss should be fine. You can do some initial analysis based on /proc/maps (e.g. see how much rss is taken by shadow, stack(s) and anon maps). But to dive deeper you probably need to do profiling inside libasan to detect the offending data structures.

**Comment by 0chunhui** [comment]
@yugr How can I profiling inside libasan?

**Comment by yugr** [comment]
I just added printfs in various places when I had to investigate memory consumption. Maybe @kcc has better suggestions.

**Comment by chefmax** [comment]
@0chunhui You could call **__sanitizer_print_memory_profile** from various places to check ASan memory consumption.

**Comment by 0chunhui** [comment]
@chefmax My project contains 6000,000+ lines code with multi-threads, I have no idea where to put it..
but thanks, I would have a try.

**Comment by yugr** [comment]
@0chunhui You can attach with gdb during peak consumption and examine the stacktrace.

**Comment by yugr** [comment]
@0chunhui Let us know if you find anything, it may be something we'll want to fix in Asan.

**Comment by 0chunhui** [comment]
@yugr Sorry, I have not find anything. I just stop using asan, because I don't have enough time to debug.
I will let you know if find it out.

**Comment by xiangzhai** [comment]
Hi @0chunhui 

please try [it](https://github.com/llvm-mirror/compiler-rt/blob/master/test/asan/TestCases/Linux/print_memory_profile_test.cc#L26) in your real project.

Regards,
Leslie Zhai - a [LLVM developer](https://reviews.llvm.org/p/xiangzhai/)

**Comment by morehouse** [comment]
Not enough information to investigate.

**Comment by Hi-Angel** [comment]
@chefmax the `__sanitizer_print_memory_profile` *(which I see defined [here](https://github.com/gcc-mirror/gcc/blob/1a1abec1d618cde709c585fcce89330bb33b07ac/libsanitizer/include/sanitizer/common_interface_defs.h#L381))* doesn't seem to do anything at all:

```haskell
 λ cat -n test.c
     1  #include <stdlib.h>
     2  #include <stdio.h>
     3
     4  int main() {
     5      char *a = malloc(256);
     6      puts("here");
     7      free(a);
     8  }
 λ gcc test.c -o a -g3 -O0 -fsanitize=address,undefined
 λ gdb ./a
Reading symbols from ./a...
gdb λ br 6
Breakpoint 1 at 0x11af: file test.c, line 6.
gdb λ r
Starting program: /tmp/a
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, main () at test.c:6
6           puts("here");
gdb λ p __sanitizer_print_memory_profile(1, 10)
$1 = void
```
