### ISSUE TITLE
Why from asan build (with gcc4.8.5) test was crashed, but with gcc6.2 don't get crash?

### ISSUE THREAD

**Issue by martin00001313** [google/sanitizers#735]
Hi all.

When I run program with asan_build(gcc4.8.5),test was crashed, but in gcc6.2 don't crashed.
Why?

Regards,
Martin.

**Comment by yugr** [comment]
It's hard to say w/o more info (e.g. error message and/or reprocase). One option is that Asan adds some instrumentation code into your program which results in different assembly code generated and this may code some latent bugs to pop-up.

**Comment by martin00001313** [comment]
What you mean,can I do something for get some result? (e.g change some options in make file)

Thank's.

**Comment by yugr** [comment]
As I said, it's hard to say with more details (how you enabled Asan, error message and ideally a repro case).

**Comment by martin00001313** [comment]
Ok.

Can I run asan with gcc4.4.7?

**Comment by chefmax** [comment]
@martin00001313 Nope, the oldest supported version is 4.8.

**Comment by martin00001313** [comment]
Thanks.

**Comment by martin00001313** [comment]
Can I run UBSAN and ASAN together?(what write in makefile (e.g. -fsanitize = address???))
