### ISSUE TITLE
Correction to first FAQ on sanitizers/wiki/AddressSanitizer

### ISSUE THREAD

**Issue by octoploid** [google/sanitizers#739]
It currently reads:

»Q: Can AddressSanitizer continue running after reporting first error?
A: Yes it can, AddressSanitizer has recently got continue-after-error mode. This is somewhat experimental so may not yet be as reliable as default setting (and not as timely supported). Also keep in mind that errors after the first one may actually be spurious. To enable continue-after-error, compile with -fsanitize-recover and then run your code with ASAN_OPTIONS=halt_on_error=0.«

But -fsanitize-recover doesn't work. One needs to use -fsanitize-recover=address.

**Comment by chefmax** [comment]
Fixed, thanks for noticing.

**Comment by octoploid** [comment]
Thanks.
