### ISSUE TITLE
False Negative in Structs with Bitfields?

### ISSUE THREAD

**Issue by mrigger** [google/sanitizers#742]
Hi,

I used Clang with MemorySanitizer to compile the following program:

```c
#include <stdlib.h>
#include <stdio.h>

struct s1 { int v : 3; };
struct s2 { int v : 4; };

int main() {
	struct s2 t;
	((struct s1*) &t)->v = -1;
	printf("%d\n", t.v);
}
```

I expected to get an error, since I did not initialize the most significant bit of `t.v`. Instead, the program runs without errors and prints `7`. Could it not have printed `-1` instead, if the most significant bit was initialized to `1`, instead of `0`? Does the C standard specify that it is implicitly initialized with `0`?

It would make sense from a machine perspective do not print an error, since it is not possible (on most architectures) to only write 3 or 4 bits to the memory. However, https://github.com/google/sanitizers/wiki/MemorySanitizer states that the sanitizer is bit-exact.

```
clang --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by kcc** [comment]
same as #718?

**Comment by mrigger** [comment]
Is this issue platform-specific or is this use case generally not supported?

**Comment by kcc** [comment]
it's just a missing logic in the msan's printf interceptor, has nothing to do with the platform, see #718
