### ISSUE TITLE
ERROR: AddressSanitizer: SEGV on unknown address - no backtrace

### ISSUE THREAD

**Issue by minfrin** [google/sanitizers#744]
While attempting to run -fsanitize=address on gstreamer on a Raspbian RPi3 machine running gcc (Raspbian 4.9.2-10) 4.9.2, the following segfault is reported as below.

No segfault is reported in the code or in gdb when run without sanitizer.

The segfault is logged without a backtrace, making it impossible to see where the segfault is occurring.

Gstreamer is built with debugging symbols and optimisation removed, and other issues are reported with backtraces and include symbols as expected.

Is this an AddressSanitizer bug?

`ASAN:SIGSEGV
=================================================================
==5516==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x00000000 sp 0x6be79ab8 bp 0x6be79adc T6)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
Thread T6 (multiqueue0:src) created by T5 (rtpjitterbuffer) here:
    #0 0x76a13f43 in __interceptor_pthread_create (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ff43)

Thread T5 (rtpjitterbuffer) created by T1 (udpsrc0:src) here:
    #0 0x76a13f43 in __interceptor_pthread_create (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ff43)

Thread T1 (udpsrc0:src) created by T0 here:
    #0 0x76a13f43 in __interceptor_pthread_create (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ff43)

==5516==ABORTING
`

**Comment by yugr** [comment]
This indeed looks like a sanitizer bug. Notice that current pc is NULL, meaning that probably one of libasan interceptors has failed and you got call to NULL. Can you attach with gdb and examine LR to understand from which function it jumped? This would help to pinpoint the error.

@chefmax May make sense to dump LR on ARMs as well, would help to quickly analyze issues like this.

**Comment by chefmax** [comment]
I'm not sure whether this dups #297? 
In any case, could you try more recent GCC and Clang?

**Comment by minfrin** [comment]
Dumb question - is there a particular commit that fixed #297? I'd like to report this to Debian/Raspbian to get them to fix it formally.

**Comment by chefmax** [comment]
@minfrin Probably this one: https://reviews.llvm.org/rL206423

**Comment by morehouse** [comment]
Please re-open if not fixed in more recent Clang.
