### ISSUE TITLE
 undefined reference to `__tsan_read8'

### ISSUE THREAD

**Issue by martin00001313** [google/sanitizers#745]
Hi guys.
Can you say,what I should be done,for avoid from this. (compiler gccc6.2.0)

Thanks.

**Comment by dvyukov** [comment]
On Tue, Nov 22, 2016 at 1:45 PM, martin00001313 <notifications@github.com>
wrote:

> Hi guys.
> Can you say,what I should be done,for avoid from this. (compiler gccc6.2.0)
>
>
>

Hi,

add -ltsan flag when linking

**Comment by martin00001313** [comment]
In makefiles I add follow:
                CXXFLAGS	+= -fsanitize=thread -f -fno-omit-frame-pointer  -ltsan

but get some problem

**Comment by dvyukov** [comment]
Try LDFLAGS=-ltsan

**Comment by martin00001313** [comment]
Thank's.
