### ISSUE TITLE
No UBSAN_SYMBOLIZER_PATH ?

### ISSUE THREAD

**Issue by kcwu** [google/sanitizers#747]
I found we have ASAN_SYMBOLIZER_PATH and MSAN_SYMBOLIZER_PATH but no UBSAN_SYMBOLIZER_PATH. The only way to specify symbolizer is using UBSAN_OPTIONS. Is this inconsistency intended?

BTW, I found 
https://chromium.googlesource.com/chromium/src/+/lkgr/testing/libfuzzer/reproducing.md
mentioned UBSAN_SYMBOLIZER_PATH.

**Comment by kcc** [comment]
See https://reviews.llvm.org/D27375

**Comment by morehouse** [comment]
https://reviews.llvm.org/D27375 landed 1 year ago.
