### ISSUE TITLE
allocator_may_return_null=1 breaks C++ operator new

### ISSUE THREAD

**Issue by ngg** [google/sanitizers#748]
https://github.com/llvm-mirror/compiler-rt/blob/master/lib/asan/asan_new_delete.cc#L82

If asan_memalign can return nullptr then the overriden operator new functions will return nullptrs as well instead of throwing an exception. This breaks lots of C++ codes including libc++ itself.

**Comment by kcc** [comment]
same as #295?

**Comment by ngg** [comment]
Yes it is the same, sorry for the duplicate
