### ISSUE TITLE
ASan didn't intercept bcopy()

### ISSUE THREAD

**Issue by kcwu** [google/sanitizers#750]
I found ASan cannot detect overflow inside bcopy().

```
$ cat b.c
#include <strings.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
  int n = atoi(argv[1]);
  char *a = malloc(n);
  char *b = malloc(n);
  bcopy(a, b, n+1); // overflow 1 byte
  free(a);
  free(b);
  return 0;
}
$ clang -fsanitize=address -o b b.c
$ ./b 1
```
I have checked `bcopy` is not in https://llvm.org/svn/llvm-project/compiler-rt/trunk/lib/sanitizer_common/sanitizer_common_interceptors.inc.

**Comment by kcwu** [comment]
BTW, msan did.
https://llvm.org/svn/llvm-project/compiler-rt/trunk/lib/msan/msan_interceptors.cc

**Comment by kcc** [comment]
Yep... bcopy is deprecated so we did not bother... (in msan we had to, to avoid false positives). 
Thanks for reminding, it's worth adding to asan too.

(Feel free to send a patch via http://llvm.org/docs/Phabricator.html if you feel urgency)

**Comment by yugr** [comment]
bcopy is quite popular in legacy codes.

**Comment by kcwu** [comment]
ok, I will send a patch tomorrow.

**Comment by kcc** [comment]
probably the best way is to move the interceptor from msan to sanitizer_common, so that tsan benefits too.

**Comment by yugr** [comment]
@kcwu could you add bzero and bcmp as well?

**Comment by kcwu** [comment]
I will add bcmp.
bzero seems not intercepted but ASan can detect it. I haven't studied why.

**Comment by kcc** [comment]
I would guess that bzero is implemented via memset, which *is* intercepted

**Comment by kcwu** [comment]
Yes, clang default work in GNU mode, which `bzero` is builtin and implemented via `memset`. If build with flags like `-std=c99`, `bzero` is not builttin and is still compiled as unintercepted `bzero`.

**Comment by kcwu** [comment]
FYI, my patch https://reviews.llvm.org/D27659

**Comment by kcwu** [comment]
The patch is landed.
Just curious. Will it be merged to branches?

**Comment by kcc** [comment]
We usually don't do this.
