### ISSUE TITLE
Will AddressSanitizer mess up when catching exceptions?

### ISSUE THREAD

**Issue by yyh-graphsql** [google/sanitizers#751]
I found AS will report stack over flow after I caught an exception.
But cannot found any overflows, each time I comments the overflowed function. There will report a new over flow. I am confused.

**Comment by rnk** [comment]
What platform? If Windows, this is not yet supported: https://github.com/google/sanitizers/issues/749#issuecomment-265004717

**Comment by yyh-graphsql** [comment]
@rnk  I'm on centos 7 and The gcc version is 4.8.2

**Comment by yugr** [comment]
Exceptions should work. Can you try with newer GCC? If it still fails, I suggest to provide a minimal repro.

**Comment by morehouse** [comment]
Please re-open with more information if still an issue.
