### ISSUE TITLE
Feature request: "read is not fatal" mode

### ISSUE THREAD

**Issue by kcwu** [google/sanitizers#752]
Sometimes I want to assess whether a bug could lead to WRITE access or not. I'd like ASan recover from read access violation if possible and only abort for write access violation.

Does it make sense to add this feature to ASan? I already have a local hack. I can upload it for review if you are interested. If not, feel free to close this issue.

**Comment by yugr** [comment]
GCC has `--param asan-instrument-reads=0`, Clang has `-mllvm -asan-instrument-reads=false`. Or you could just use `-fsanitizer-recover=address` and `ASAN_OPTIONS=halt_on_error=0`.

**Comment by kcc** [comment]
there is an internal flag that will cause asan to not instrument the reads.
`-mllvm -asan-instrument-reads=0`
We don't recommend it to anyone and have it mostly for testing. 
And no, I don't want to have such mode to be easily accessible and advertised. 
There is a large risk that people will be misusing it and getting false sense of safety
("hey, my writes are safe, ignore the reads, they are not as bad")

**Comment by kcwu** [comment]
I see. Thanks.
