### ISSUE TITLE
Please update MSDN multithreaded apps link

### ISSUE THREAD

**Issue by sitsofe** [google/sanitizers#753]
At the bottom of https://github.com/google/sanitizers/wiki/ThreadSanitizerAboutRaces there is a link "What Every Dev Must Know About Multithreaded Apps" which goes to http://msdn.microsoft.com/en-us/magazine/cc163744.aspx . Unfortunately that now lands at a generic page but on https://blogs.msdn.microsoft.com/vancem/2016/02/27/encore-presentation-what-every-dev-must-know-about-multithreaded-apps/ the author gives a link to a direct PDF version of the document - https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/67/06/52/MultiThreading.pdf . Could the wiki link be updated to go to the direct PDF version?

**Comment by dvyukov** [comment]
done

**Comment by sitsofe** [comment]
@dvyukov Thank you!

**Comment by Uzume** [comment]
@dvyukov apparently it has moved again. It can still be found at the Internet Archive Wayback Machine though:
- [What Every Dev Must Know About Multithreaded Apps](https://web.archive.org/web/20200720080110/https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/67/06/52/MultiThreading.pdf)

I hope this helps.
