### ISSUE TITLE
How to add support to other malloc like function, like rte_malloc

### ISSUE THREAD

**Issue by littletiny** [google/sanitizers#754]
I want to use address-sanitizer to find bugs in our project, but our project use rte_malloc* alloc memory. How can I use address-sanitizer with these function?

**Comment by kcc** [comment]
I am not familiar with rte_malloc. 
If you can disable it during testing and use asan's malloc -- that's the best option. 
And that's pretty much your only option unless you want to write quite a bit of code either inside 
rte_malloc or inside asan. 
asan has an API to mark memory as addressable/unaddressable, so if you can arrange for redzones
and quarantine with rte_malloc -- you can use that.
See https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/asan_interface.h
 redzones are relatively easy, quarantine is easy only if you have one thread.
