### ISSUE TITLE
ASAN and LSAN

### ISSUE THREAD

**Issue by martin00001313** [google/sanitizers#755]
What I should be done for run asan  without  LSAN (for ex. ASAN_OPTIONS=detect_leaks=0, but this only for current run. I need a permanent disconnect).
Thank's.

**Comment by martin00001313** [comment]
In gcc62

**Comment by yugr** [comment]
@martin00001313 you should be able to overload __lsan_is_turned_off in your app (see sanitizer/lsan_interface.h for details).

Probably makes sense to describe this in wiki.

**Comment by kcc** [comment]
you may also use __asan_default_options from
 https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/asan_interface.h
Make it return  "detect_leaks=0" and it will have the same effect as passing ASAN_OPTIONS=...
