### ISSUE TITLE
SIGSEGV is not always deadly

### ISSUE THREAD

**Issue by richardweinberger** [google/sanitizers#756]
asan seems to have no way to ignore SIGSEGV. This makes it impossible to use asan for programs
that catch SIGSEGV and fix up the fault manually. A prominent example is UserModeLinux.

Can you please add an option to ignore SIGSEGV?

**Comment by yugr** [comment]
@richardweinberger how about ASAN_OPTIONS=handle_segv=0 ?

**Comment by richardweinberger** [comment]
Thanks, I oversaw that option. ;-\

**Comment by eugenis** [comment]
There is also allow_user_segv_handler which lets the application to replace
asan's handler and delegate to it as appropriate.
