### ISSUE TITLE
Compiling with TSan produces incorrect program

### ISSUE THREAD

**Issue by xaqq** [google/sanitizers#758]
Hello,

I'm new to using sanitizers. I wanted to try tsan so I made a simple test program.

````
#include <iostream>
#include <thread>
#include <atomic>

std::atomic<int> c;

void count()
{
  for (int i = 0 ; i < 100000; ++i)
    c++;
}

int main()
{
  std::thread t(count);
  std::thread t2(count);

  c.store(0);

  t.join();
  t2.join();
  std::cout << "C = " << c.load()  << std::endl;
}
````

As expected, tsan doesn't report an error. However, when compiling with tsan, the result of the program is invalid. Obviously, `200000` is expected, but it always returns less.

I compile like this `g++ test.cpp -fsanitize=thread -ltsan -no-pie && ./a.out` (have gcc-6 and linux 4.8 so i need `-no-pie` for now, AFAIK)

When compiling this program normally (ie no tsan) it works as expected, returning `200000` as expected.

Note that I've also tried with clang++3-9 and the same issue is present.

**Comment by dvyukov** [comment]
Initialize c to 0 _before_ starting threads.

**Comment by xaqq** [comment]
Oh god I'm dumb.
