### ISSUE TITLE
How can I determine if UBSAN has been compiled in using clang or gcc?

### ISSUE THREAD

**Issue by hptabster** [google/sanitizers#765]
2
down vote
favorite
	

We use the following code to determine if _-fsanitize=address_ has been specified at compile time for clang and gcc. How do we determine if _-fsanitize=undefined_ has been specified?
```

    bool isSanitized = false;
#if defined(__has_feature)
#if __has_feature(address_sanitizer)
    isSanitized = true;
#endif
#elif defined(__SANITIZE_ADDRESS__)
    isSanitized = true;
#endif

```

**Comment by chefmax** [comment]
I'm not sure about clang, but AFAIK GCC doesn't have such a mechanism for UBSan (mainly because as opposed to other sanitizers, UBSan is not a monolithic checker but set of independent UB checkers).

**Comment by kcc** [comment]
yes, I don't think we have such. 
What is your use case?

**Comment by hptabster** [comment]
We would like to be able to determine at run time if the application will be instrumented with UBSan. We plan to use a macro at compile time to accomplish this.

**Comment by morehouse** [comment]
@kcc:  Yea or nay on this?

**Comment by kcc** [comment]
No plans here. 
It's certainly possible to implement `__has_feature(undefined_behavior_sanitizer)` and even all possible subsets, e.g. `__has_feature(signed-integer-overflow)`, but why? 

We have seen a few cases for asan/msan/tsan, but no cases for ubsan. 
For those users who really need it please tell us why. 
(and you can always use your own macro)

**Comment by krytarowski** [comment]
This is needed in the NetBSD kernel. We need this to change alignment logic, namely disable relaxed alignment operations under UBSan.

**Comment by krytarowski** [comment]
Anyway.. this is now supported in Clang/LLVM. I will patch GCC and submit it to review to GCC people.

**Comment by noloader** [comment]
This is also needed for [Gnulib](https://www.gnu.org/software/gnulib/manual/html_node/index.html). The library has a test like [the following](https://github.com/noloader/Build-Scripts/blob/master/patch/gettext.patch#L76):

```
--- gettext-tools/gnulib-tests/test-canonicalize-lgpl.c
+++ gettext-tools/gnulib-tests/test-canonicalize-lgpl.c
@@ -70,10 +70,14 @@
     result = canonicalize_file_name ("");
     ASSERT (result == NULL);
     ASSERT (errno == ENOENT);
+
+#if 0
+    /* Disabled due to UBsan finding */
     errno = 0;
     result = canonicalize_file_name (null_ptr ());
     ASSERT (result == NULL);
     ASSERT (errno == EINVAL);
+#endif
   }
```

I really need something like, which ensures `canonicalize_file_name` handles `NULL` properly without producing the finding when testing under UBsan.

```
+#ifndef __UBSAN__
     errno = 0;
     result = canonicalize_file_name (null_ptr ());
     ASSERT (result == NULL);
     ASSERT (errno == EINVAL);
+#endif
```

**Comment by krytarowski** [comment]
I proposed a patch to GCC to support `SANITIZE_UNDEFINED` but the upstream was unconvinced..... and my use-case was 'useless'.

In NetBSD we patch GCC and use code like:

```
#if !__has_feature(undefined_behavior_sanitizer) && \
	!defined(__SANITIZE_UNDEFINED__)
/* The amd64 does not have strict alignment requirements. */
#define	__NO_STRICT_ALIGNMENT
#endif
```

There is similar local support for LSan. Clang supports it with ifdef, upstream GCC rejected.

https://nxr.netbsd.org/xref/src/sys/arch/amd64/include/types.h#78

**Comment by craigbarnes** [comment]
> For those users who really need it please tell us why

@kcc it'd be useful to use such a check to guard `#include <sanitizer/common_interface_defs.h>` when using UBSan alone.

**Comment by Cons-Cat** [comment]
Using UBsan with a `__builtin_unreachable()` in my `_start` function caused 8 bytes of stack to be subtracted from `%rsp` before  I could load argc and argv. I need to be able to `#ifdef __SANITIZER_UNDEFINED` or something to solve this elegantly.

**Comment by ecatmur** [comment]
This would be useful to workaround bugs like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71962

**Comment by LewisPringle** [comment]
Not sure if this is compelling, but I find it helpful cuz UBSAN is sometimes buggy/wrong, and you have to workaround the bugs.

**Comment by eric-riff-simplisafe** [comment]
> This would be useful to workaround bugs like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71962

I came here looking for a workaround for exactly this same problem. So +1 on this being a nice addition
