### ISSUE TITLE
Asan does not detect ouf-of-bounds read in strtok

### ISSUE THREAD

**Issue by mrigger** [google/sanitizers#766]
Consider the following example:

```c
#include <string.h>

int main() {
   char str[] = "Hello world";
   char s[2] = {' ', '\n'};
   char *token = strtok(str, s);
}
```

This example produces an out-of-bounds read in `strtok`. I expected that Asan (`clang-3.9 -fsanitize=address`) can find this out-of-bounds access, similar to an out-of-bounds read in `strcpy`:

```c
#include <string.h>

int main() {
   char str[20];
   char s[2] = {' ', '\n'};
   char *token = strcpy(str, s);
}
```

However, the program executes without errors.

I found the issue while executing a dictionary implementation with [Safe Sulong](https://github.com/graalvm/sulong/blob/master/docs/SAFE-SULONG.md). Safe Sulong detected the error and aborted the program (see [PR](https://github.com/roecrew/BB_Dictionary/pull/3)).

**Comment by yugr** [comment]
@chefmax

**Comment by chefmax** [comment]
Yeah, sanitizers miss strtok interceptor... perhaps it makes sense to add it.

**Comment by kcc** [comment]
Yep, strtok interceptor is clearly missing. Volunteers?

**Comment by mrigger** [comment]
If it is not too late I would like to try in two weeks (after my vacation).

**Comment by kcc** [comment]
Unless someone claims this bug, it's yours! :) 
Please use http://llvm.org/docs/Phabricator.html for code review.

**Comment by mrigger** [comment]
Fixed by https://reviews.llvm.org/rL298650.
