### ISSUE TITLE
Feature request: the ability to start gdb where issue is detected by asan or tsan

### ISSUE THREAD

**Issue by gaojx** [google/sanitizers#771]
It is very helpful sometimes if the asan/tsan can start gdb instead of exit the program when an issue is detected.

In xstack, an ASAN_OPTION is used: RUN_TOOL='gdb -ex r --args'  to start gdb.
  https://xstack.exascale-tech.com/wiki/index.php/Debugging_with_AddressSanitizer

**Comment by chefmax** [comment]
You can use `ASAN_OPTIONS=sleep_before_dying=...` and attach via `gdb -p`. Is that what you are looking for?

**Comment by gaojx** [comment]
That is similar. I tried that and to be honest, it is quite hard to use:
 - there is no indication that an issue is found. I usually redirect the asan/tsan output to an file using log_path option. Since the output file name changes (the thread id is appended), we can't monitor this by file name. 
 
So if this is currently possible, this request will be a more convenient way to start gdb.

**Comment by yugr** [comment]
Has been suggested [in group](https://groups.google.com/forum/#!msg/address-sanitizer/mwHL4-zN_d4/NwKtBazyi4kJ) too, with "patch welcome" reply.

**Comment by StephanDollberg** [comment]
I created a patch for a `run_before_dying` option once which would have allowed doing this. 

https://reviews.llvm.org/D27470

It was rejected though.

**Comment by morehouse** [comment]
Won't fix as described in https://reviews.llvm.org/D27470.
