### ISSUE TITLE
ASAN slowdown gradually increases from ~3x to ~50x

### ISSUE THREAD

**Issue by Alomir** [google/sanitizers#775]
I have a reasonably large multi-threaded program for which ASAN has been tremendously helpful in finding memory issues. However, I have a serious issue - the ASAN build starts off well enough, at about ~3x slowdown, but then continues to slow down over the course of a day or so, eventually getting to upwards of 50x slower. If anyone has any pointers of what/how to investigate this, it would be much appreciated.

More details: there are two main threads in the application (lots of transient ones too); thread A does a lot of initialization work at the beginning (typically 6-7 minutes, close to 25 in the ASAN build - typical slowdown numbers), while thread B does very little waiting for A to finish. Timings seem constant in this period.

As soon as A finishes its initialization and B starts working in ernest, the slowdown starts. Thread A's cycle time ramps up, gradually but continuously, from ~1 minute up to ~15 minutes over the course of a day or so. (the non-ASAN version's cycle time is a constant ~18-20 seconds). Thread B also gradually slows down, but not nearly to the same extent.

Memory use seems to be inline with expectations; non-ASAN version uses about 5GB, ASAN starts at about 10GB and gradually increases to about 17GB after a day (this is on a machine with 32GB, and no other processes using large amounts).

I'm building and running without any extra ASAN options; -fsanitize=address, -fno-omit-frame-pointer, -O2 on build, and only log path and symbolize in ASAN_OPTIONS.

**Comment by yugr** [comment]
One simple option would be to attach with debugger and collect backtraces few dozen times (could even be done automatically).

**Comment by Alomir** [comment]
@yugr - would you mind saying a bit more about collecting backtraces, and what I'd be looking for?

**Comment by kcc** [comment]
or, better, `perf report` then `perf record`. 
Two guesses so far: 

1. Something wrong in the allocator. We actually know a serious problem in long running processes: try ASAN_OPTIONS=quarantine_size_mb=1

2. Something is wrong with synchronization inside asan. (this is more typical for tsan, and we haven't seen it in asan, but who knows). 

Anyway, give us the `perf` profile, and we'll give more advice.

**Comment by Alomir** [comment]
We're having unrelated issues in our system right now (of course); I'll collect the data as soon as I can and report back when I can. Thanks!

**Comment by morehouse** [comment]
No response for over a year.  Please re-open with perf data if still an issue.
