### ISSUE TITLE
allocator_may_return_null does not always work. Test case is broken.

### ISSUE THREAD

**Issue by LebedevRI** [google/sanitizers#779]
The vanilla test case, https://github.com/llvm-mirror/compiler-rt/blob/master/test/asan/TestCases/allocator_returns_null.cc works.
But unfortunately, if i change `volatile size_t size = std::numeric_limits<size_t>::max() - 10000;` to some lower value, in my case `32202304176`, it does not work.
Meaning, it crashes regardless of the value of `ASAN_OPTIONS=allocator_may_return_null=1`.

I have found this while fuzzing one image-processing library, where it is okay to alloc huge buffers.

**Comment by chefmax** [comment]
Dup of issue #740?

**Comment by LebedevRI** [comment]
Ugh, right, sorry, should have posted this as a comment there.
