### ISSUE TITLE
asan needs more libc interceptors. 

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#78]
Originally reported on Google Code with ID 78
```
asan needs more libc interceptors. 

Alexey, please implement strncat and then all those functions intercepted by tsan.


```

Reported by `konstantin.s.serebryany` on 2012-06-08 12:04:04

**Comment by kcc** [comment]
Done lots here. Let's open separate bugs if we need more interceptors. (or just implement them)
