### ISSUE TITLE
How to do memory leak detection for a program keeps running

### ISSUE THREAD

**Issue by sanjosh** [google/sanitizers#780]
Is there an option to gradually print memory leak errors while the program keeps running ?
I don't want to wait until the program exits in order to find all the leak errors.

I am looking for an API where I can call "start_profile" and "end_profile" between which all leak detection can take place.

**Comment by kcc** [comment]
Yes. 
https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/lsan_interface.h
```
  // Check for leaks now. Returns zero if no leaks have been found or if leak
  // detection is disabled, non-zero otherwise.
  // This function may be called repeatedly, e.g. to periodically check a
  // long-running process. It prints a leak report if appropriate, but does not
  // terminate the process. It does not affect the behavior of
  // __lsan_do_leak_check() or the end-of-process leak check, and is not
  // affected by them.
  int __lsan_do_recoverable_leak_check();
```

> I am looking for an API where I can call "start_profile" and "end_profile" between which all leak detection can take place.

I am not sure about this part.

**Comment by sanjosh** [comment]
Do I have to use clang/llvm to use this API ?  I am currently running gcc on Ubuntu and cannot find a package which exposes this header file

**Comment by chefmax** [comment]
What GCC version do you use? GCC 5 has it on my Ubuntu 16.04 box.

**Comment by sanjosh** [comment]
I am running the same (gcc 5.4 on Ubuntu 16.04).  
I cant find any header file which declares "int __lsan_do_recoverable_leak_check()" or any library which has the symbol.  What header file or package should I look for ?

$ dpkg -L liblsan0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/liblsan.so.0.0.0
/usr/share
/usr/share/doc
/usr/lib/x86_64-linux-gnu/liblsan.so.0
/usr/share/doc/liblsan0

$ dpkg -L libasan2
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0
/usr/share
/usr/share/doc
/usr/lib/x86_64-linux-gnu/libasan.so.2
/usr/share/doc/libasan2

$ nm -AC /usr/lib/gcc/x86_64-linux-gnu/5/libasan.a | grep leak
shows one symbol
libasan.a:lsan_common.o:00000000000027c0 T __lsan_do_leak_check

$ nm -AC /usr/lib/gcc/x86_64-linux-gnu/5/liblsan.a  |grep leak
liblsan.a:lsan_common.o:00000000000027c0 T __lsan_do_leak_check

**Comment by AlexisWilke** [comment]
For those interested, the headers for the asan/lsan features are found with the compiler specific headers:

    /usr/lib/gcc/x86_64-linux-gnu/7/include/sanitizer/

Make sure to change the version (`7` in my example on Ubuntu 18.04) and you'll see the headers. To include, just use the following:

    #include <sanitizer/asan_interface.h>
    #include <sanitizer/common_interface_defs.h>
    #include <sanitizer/lsan_interface.h>

There are 3 files in the directory on Ubuntu 18.04. You probably don't need to include them all.

**Comment by Hi-Angel** [comment]
@kcc does not seem to work for me. When I call `__lsan_do_recoverable_leak_check()` in gdb, even though the report is correctly created, it exits the process.

```haskell
gdb λ p (int)__lsan_do_recoverable_leak_check()
[Inferior 1 (process 6277) exited with code 01]
The program being debugged exited while in a function called from GDB.
Evaluation of the expression containing the function
(__lsan_do_recoverable_leak_check) will be abandoned.
```

**Comment by Hi-Angel** [comment]
Actually, I stand corrected, `__lsan_do_recoverable_leak_check()` does work most of the times, i.e. prints report without existing the process. I don't know why sometimes it doesn't.

**Comment by Hi-Angel** [comment]
> Hello, how are you building your application? What compiler and version are you using? My lsan_interface.h file does not include __lsan_do_recoverable_leak_check().

I presume you are asking to be able to call the function. I do not know in what header it's declared. You can search trough the installed files of your compiler, or if you want a quick hack, you can just declare the function yourself, and build the application *(if you want to call it from the code)*. To call it from gdb header file is not needed.

**Comment by AlexisWilke** [comment]
On Ubuntu 22.04, it looks like it's here:

    /usr/lib/gcc/x86_64-linux-gnu/12/include/sanitizer/lsan_interface.h:  int __lsan_do_recoverable_leak_check(void);

(I have multiple versions, really, 9 through 12).

So the include would look like:

    #include <sanitizer/lsan_interface.h>

Note that functions that start with one or more `_` are special to your system so not likely to work on another OS. Although in this case, it's probably specific to gcc rather than the OS.

Here is a minimal example of how that works:

    #include    <stdlib.h>
    #include    <sanitizer/lsan_interface.h>

    int main(int argc, char * argv[])
    {
        void * ptr = malloc(100);

        __lsan_do_recoverable_leak_check();

        return 0;
    }

**Comment by Hi-Angel** [comment]
> @kcc does not seem to work for me. When I call `__lsan_do_recoverable_leak_check()` in gdb, even though the report is correctly created, it exits the process.
> 
> ```haskell
> gdb λ p (int)__lsan_do_recoverable_leak_check()
> [Inferior 1 (process 6277) exited with code 01]
> The program being debugged exited while in a function called from GDB.
> Evaluation of the expression containing the function
> (__lsan_do_recoverable_leak_check) will be abandoned.
> ```

To answer my question: it turns out LeakSanitizer won't work properly under a debugger, so calling a leak sanitizer function while being attached to a process may result in a weird behavior such as the one I met.
