### ISSUE TITLE
Huge memory usage in case of a high allocation/deallocation pressure.

### ISSUE THREAD

**Issue by tau0** [google/sanitizers#782]
[This ](https://gist.github.com/tau0/ce3ba7e62461d97ef95b7417dbedbc87)simple program consumes:
[Maximum resident set size (kbytes): 1002636](https://gist.github.com/tau0/e9467efcb445c556e238a92a0c2f953e) - with enabled address sanitizer. 

If I understand docs correctly quarantine size should be only 256mb by default.

But: `Maximum resident set size (kbytes): 980` - without.
LLVM: r297967
FLAGS: -fsanitize=address
OS: Ubuntu 14.04.5 LTS

**Comment by kcc** [comment]
Aleksey, you've touched this part most recently. 
If I run with `ASAN_OPTIONS=heap_profile=1` the last I get is: 
```
HEAP PROFILE at RSS 902Mb
Live Heap Allocations: 41 bytes in 1 chunks; quarantined: 82267169 bytes in 20566783 chunks;
```
Something is pretty weird here. 
We think we keep 82267169 (82Mb) bytes in quarantine, but RSS is 902Mb

Nickolay, thanks for report!

**Comment by morehouse** [comment]
@alekseyshl:  Any progress on this?

**Comment by alekseyshl** [comment]
Running the test program with ASAN_OPTIONS=atexit=1 ... tells us that 850 MB are mapped in the allocator, out of those 20788 * 8192 = 162MB used for quarantine batches (the inevitable overhead), those 162+80MB of actual quarantined data fills up almost entire 256MB total quarantine capacity. Almost all the allocations in the 8192 bucket are those quarantine batches.

Now, 21000320 of 32 bytes chunks are used, that is, they are in the quarantine, all those ints pushed into vectors, they take 21000320 * 4 = 80MB of user memory (note the quarantined size), but with all the ASan metadata added on top, they fall into 32 bytes bucket and use up 640MB of RSS + some overhead of free list, pages not fully occupied by used chunks etc. takes us to 678MB of RSS in that bucket.

Hope this sheds some light on why ASan uses that much of memory.

Here's the relevant excerpt from the output:

Stats: SizeClassAllocator64: 850M mapped (849M rss) in 100092665 allocations; remains 21021393
  02 (    32): mapped: 694336K allocs: 99993728 frees: 78993408 inuse: 21000320 num_freed_chunks 1218432 avail: 22218752 rss: 693528K releases:     23 last released:    808K region: 0x602000000000
  04 (    64): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     896 avail:   1024 rss:      4K releases:      0 last released:      0K region: 0x604000000000
  11 (   176): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     244 avail:    372 rss:      4K releases:      0 last released:      0K region: 0x60b000000000
  36 (  8192): mapped: 176128K allocs:   98680 frees:   77864 inuse:  20816 num_freed_chunks    1200 avail:  22016 rss: 175924K releases:     23 last released:    256K region: 0x624000000000
  49 ( 81920): mapped:    128K allocs:       1 frees:       0 inuse:      1 num_freed_chunks       0 avail:      1 rss:      8K releases:      0 last released:      0K region: 0x631000000000
Stats: LargeMmapAllocator: allocated 0 times, remains 0 (0 K) max 0 M; by size logs: 
Quarantine limits: global: 256Mb; thread local: 1024Kb
Global quarantine stats: batches: 20788; bytes: 254206128 (user: 83910832); chunks: 20977708 (capacity: 21224548); 98% chunks used; 202% memory overhead
