### ISSUE TITLE
Missing coverage instrumentation with trace-pc-guard option

### ISSUE THREAD

**Issue by nikdmt** [google/sanitizers#783]
While trying to get a coverage for sanitizers for my library compiled with Clang 5.0.0 I have encountered a problem that some calls to `__sanitizer_coverage_trace_pc_guards` are missing in several basic blocks. I made a reduced reprocase for this and built it with `-gline-tables-only -O0 -fsanitize=address -fsanitize-coverage=trace-pc-guard` flags:

`clang -gline-tables-only -O0 -fsanitize=address -fsanitize-coverage=trace-pc-guard -S reduced.c`

```c
extern void clobber1(int *state_ptr);
extern void clobber2(int *state_ptr);
extern void clobber3(int *state_ptr);

int foo(char c, int state, int threshold) {
   while (state < threshold) {
     switch (state) {
     case 1:
       clobber1(&state);
       if (c == '*') {
         state++;
       } else if (c == '/') {
         state--;                 <============== missing __sanitizer_cov_trace_pc_guard call
       } else {
         clobber1(&state);
         goto out;
       }
       clobber2(&state);
       break;
     case 2:
       clobber3(&state);
       break;
     }
   }
out:
   return state;
}

int main(int argc, char **argv) {
   return foo(argv[1][2], argc + 4, 255) > 100;
}
```

After examination of dumped LLVM IR (-print-after-all) I have found that there are no calls of `__sanitizer_coverage_trace_pc_guard` in `if.then6` basic block that corresponds to `else if (c == '/')` fall through case:

```
sw.bb:                                            ; preds = %while.body
   call void @clobber1(i32* %state.addr), !dbg !15
   %3 = load i8, i8* %c.addr, align 1, !dbg !16
   %conv = sext i8 %3 to i32, !dbg !16
   %cmp1 = icmp eq i32 %conv, 42, !dbg !17
   br i1 %cmp1, label %if.then, label %if.else, !dbg !16

if.then:                                          ; preds = %sw.bb
   call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 8) to i32*)), !dbg !18
   call void asm sideeffect "", ""(), !dbg !18
   %4 = load i32, i32* %state.addr, align 4, !dbg !18
   %inc = add nsw i32 %4, 1, !dbg !18
   store i32 %inc, i32* %state.addr, align 4, !dbg !18
   br label %if.end8, !dbg !19

if.else:                                          ; preds = %sw.bb
   %5 = load i8, i8* %c.addr, align 1, !dbg !20
   %conv3 = sext i8 %5 to i32, !dbg !20
   %cmp4 = icmp eq i32 %conv3, 47, !dbg !21
   br i1 %cmp4, label %if.then6, label %if.else7, !dbg !20

if.then6:                                         ; preds = %if.else       <======= no __sanitizer_cov_trace_pc_guard
   %6 = load i32, i32* %state.addr, align 4, !dbg !22
   %dec = add nsw i32 %6, -1, !dbg !22
   store i32 %dec, i32* %state.addr, align 4, !dbg !22
   br label %if.end, !dbg !23

if.else7:                                         ; preds = %if.else
   call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 12) to i32*)), !dbg !24
   call void asm sideeffect "", ""(), !dbg !24
   call void @clobber1(i32* %state.addr), !dbg !24
   br label %out, !dbg !25

if.end:                                           ; preds = %if.then6
   br label %if.end8

if.end8:                                          ; preds = %if.end, %if.then
   call void @clobber2(i32* %state.addr), !dbg !26
   br label %sw.epilog, !dbg !27
```

But, if I remove the `goto out` instruction, then `__sanitizer_cov_trace_pc_guard` call appears in all `if` clauses as expected.

I also reported this issue to llvm-dev@lists.llvm.org but haven't got any reply yet:
http://lists.llvm.org/pipermail/llvm-dev/2017-March/111209.html

**Comment by mikea** [comment]
By default the sanitizer-coverage-prune-blocks option (lib/Transforms/Instrumentation/SanitizerCoverage.cpp) removes instrumentation from blocks that are full pre/post dominators. I guess this is what is at play here because of 'goto'.

Can you retry with the option off? (`-mllvm -sanitizer-coverage-prune-blocks=0`)

We've implemented this option because it doesn't change the coverage precision, but generates up to 1/3 less of instrumentation.

**Comment by chefmax** [comment]
> We've implemented this option because it doesn't change the coverage precision, but generates up to 1/3 less of instrumentation. 

But don't we miss precision here? One can I see, we can't distinguish between single hit of (c == '/') when loop executes only once and (state > threshold) when loop doesn't execute at all because in both cases we hit the same set of guards. Or perhaps I miss something?

**Comment by mikea** [comment]
With different values of c the following guards will be set:

- `c=='*'` - {if.then, if.end}
- `c=='/'` - {if.end}
- others - {if.else7}

All cases have different sets of coverage points, so there's no precision lost. Given the original CFG it is possible to fully recover the set of blocks that were executed, but I agree it doesn't seem trivial. Especially if you compile code with optimizations turned on.

**Comment by chefmax** [comment]
> With different values of c the following guards will be set:
> 
> c=='*' - {if.then, if.end}
> c=='/' - {if.end}
> others - {if.else7}

But according to attached IR if.end isn't instrumented. How can we distinguish it from the case when we don't even enter the loop?

**Comment by mikea** [comment]
You are right, I made a mistake because yours doesn't seem to be a full listing. There should be more instrumentation for the loop and for the switch.

In my case (ToT clang): https://gist.github.com/anonymous/304677463ebb5e65fb8386d154999d24

There are following guards:

- [a] function entrance
- [b] switch entrance
- [c] c=='*' (if.then, line 11)
- [d] other cs (line 15)
- [e] case 2 (line 21)
- [f] while.end

These 6 seem to be enough to describe all code paths. 
Can you paste full assembly output from your clang? I also wonder why is it so different. I did ` clang -gline-tables-only -O0 -fsanitize=address -fsanitize-coverage=trace-pc-guard -S ~/tmp/reduced.c`

**Comment by chefmax** [comment]
> These 6 seem to be enough to describe all code paths.

I'm sorry, still can't get this :(. Is that enough? How can we then distinguish between this sequence:
```
1) [b] switch entrance
2) `if (c == '/')`
3) [b] switch entrance
4) [c] c=='*' (if.then, line 11)
5) [f] while.end
```
and this:
```
1) [b] switch entrance
2) [c] c=='*' (if.then, line 11)
3) [b] switch entrance
4) [c] c=='*' (if.then, line 11)
5) [f] while.end
```
?  By number of hits of [c] guard? AFAIK we can write `__sanitizer_cov_trace_pc_guard` to remember only first hit...

**Comment by chefmax** [comment]
Mike, it seems that for this particular testcase this coverage is indeed sufficient. But for slightly modified testcase:
```
extern void clobber0(int *state_ptr, char *cp);
extern void clobber1(int *state_ptr, char *cp);
extern void clobber2(int *state_ptr, char *cp);
extern void clobber3(int *state_ptr, char *cp);

int foo(char c, int state, int threshold) {
   while (state < threshold) {
     switch (state) {
     clobber0(&state, &c);
     case 1:
       clobber1(&state, &c);
       if (c == '*') {
         clobber1(&state, &c);
         state++;
       } else if (c == '/') {
         clobber1(&state, &c);
         state--;               
       } else {
         clobber1(&state, &c);
         goto out;
       }
       clobber2(&state, &c);
       break;
     case 2:
       clobber3(&state, &c);
       break;
     }
   }
out:
   return state;
}

int main(int argc, char **argv) {
   return foo(argv[1][2], argc + 4, 255) > 100;
}
``` 
IR looks like this (same coverage points):
```
define i32 @foo(i8 signext %c, i32 %state, i32 %threshold) #0 !dbg !6 {
entry:
  %c.addr = alloca i8, align 1
  %state.addr = alloca i32, align 4
  %threshold.addr = alloca i32, align 4
  call void @__sanitizer_cov_trace_pc_guard(i32* getelementptr inbounds ([6 x i32], [6 x i32]* @__sancov_gen_, i32 0, i32 0)), !dbg !8
  call void asm sideeffect "", ""(), !dbg !8
  store i8 %c, i8* %c.addr, align 1
  store i32 %state, i32* %state.addr, align 4
  store i32 %threshold, i32* %threshold.addr, align 4
  br label %while.cond, !dbg !9

while.cond:                                       ; preds = %sw.epilog, %entry
  %0 = load i32, i32* %state.addr, align 4, !dbg !10
  %1 = load i32, i32* %threshold.addr, align 4, !dbg !11
  %cmp = icmp slt i32 %0, %1, !dbg !12
  br i1 %cmp, label %while.body, label %while.end, !dbg !9

while.body:                                       ; preds = %while.cond
  %2 = load i32, i32* %state.addr, align 4, !dbg !13
  switch i32 %2, label %while.body.sw.epilog_crit_edge [
    i32 1, label %sw.bb
    i32 2, label %sw.bb9
  ], !dbg !14

while.body.sw.epilog_crit_edge:                   ; preds = %while.body
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 4) to i32*)), !dbg !14
  call void asm sideeffect "", ""(), !dbg !14
  br label %sw.epilog, !dbg !14

sw.bb:                                            ; preds = %while.body
  call void @clobber1(i32* %state.addr, i8* %c.addr), !dbg !15
  %3 = load i8, i8* %c.addr, align 1, !dbg !16
  %conv = sext i8 %3 to i32, !dbg !16
  %cmp1 = icmp eq i32 %conv, 42, !dbg !17
  br i1 %cmp1, label %if.then, label %if.else, !dbg !16

if.then:                                          ; preds = %sw.bb
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 8) to i32*)), !dbg !18
  call void asm sideeffect "", ""(), !dbg !18
  call void @clobber1(i32* %state.addr, i8* %c.addr), !dbg !18
  %4 = load i32, i32* %state.addr, align 4, !dbg !19
  %inc = add nsw i32 %4, 1, !dbg !19
  store i32 %inc, i32* %state.addr, align 4, !dbg !19
  br label %if.end8, !dbg !20

if.else:                                          ; preds = %sw.bb
  %5 = load i8, i8* %c.addr, align 1, !dbg !21
  %conv3 = sext i8 %5 to i32, !dbg !21
  %cmp4 = icmp eq i32 %conv3, 47, !dbg !22
  br i1 %cmp4, label %if.then6, label %if.else7, !dbg !21

if.then6:                                         ; preds = %if.else
  call void @clobber1(i32* %state.addr, i8* %c.addr), !dbg !23
  %6 = load i32, i32* %state.addr, align 4, !dbg !24
  %dec = add nsw i32 %6, -1, !dbg !24
  store i32 %dec, i32* %state.addr, align 4, !dbg !24
  br label %if.end, !dbg !25

if.else7:                                         ; preds = %if.else
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 12) to i32*)), !dbg !26
  call void asm sideeffect "", ""(), !dbg !26
  call void @clobber1(i32* %state.addr, i8* %c.addr), !dbg !26
  br label %out, !dbg !27

if.end:                                           ; preds = %if.then6
  br label %if.end8

if.end8:                                          ; preds = %if.end, %if.then
  call void @clobber2(i32* %state.addr, i8* %c.addr), !dbg !28
  br label %sw.epilog, !dbg !29

sw.bb9:                                           ; preds = %while.body
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 16) to i32*)), !dbg !30
  call void asm sideeffect "", ""(), !dbg !30
  call void @clobber3(i32* %state.addr, i8* %c.addr), !dbg !30
  br label %sw.epilog, !dbg !31

sw.epilog:                                        ; preds = %while.body.sw.epilog_crit_edge, %sw.bb9, %if.end8
  br label %while.cond, !dbg !9, !llvm.loop !32

while.end:                                        ; preds = %while.cond
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([6 x i32]* @__sancov_gen_ to i64), i64 20) to i32*)), !dbg !9
  call void asm sideeffect "", ""(), !dbg !9
  br label %out, !dbg !9

out:                                              ; preds = %while.end, %if.else7
  %7 = load i32, i32* %state.addr, align 4, !dbg !34
  ret i32 %7, !dbg !35
}
```
How can we distinguish between
```
1) [b] switch entrance
2) `if (c == '/')`
3) [b] switch entrance
4) [c] c=='*' (if.then, line 11)
5) [f] while.end
```
and
```
1) [b] switch entrance
2) [c] c=='*' (if.then, line 11)
3) [b] switch entrance
4) [c] c=='*' (if.then, line 11)
5) [f] while.end
```
since we don't have a guard for `if (c == '/')`?

**Comment by dvyukov** [comment]
I may be missing something, but why are we talking about complex path analysis? We don't require fuzzers to do some kind of complex global trace analysis to restore missing redundant bits of information (and in the end it would require knowledge of CFG which we don't expose anyway). So it seems to me that all if/switch blocks should contain callbacks.

**Comment by chefmax** [comment]
> I may be missing something, but why are we talking about complex path analysis? We don't require fuzzers to do some kind of complex global trace analysis to restore missing redundant bits of information (and in the end it would require knowledge of CFG which we don't expose anyway). So it seems to me that all if/switch blocks should contain callbacks.

There is a `-fsanitize-coverage=trace-cmp` option that would instrument all if/switch blocks, perhaps it's somewhat we are looking for. But this still doesn't help us with coverage analysis (`-mllvm -sanitizer-coverage-prune-blocks=0` helps). Perhaps we can mention `-mllvm -sanitizer-coverage-prune-blocks=0` somewhere in documentation? This would help people who want to inspect coverage produced by their fuzzer?

**Comment by dvyukov** [comment]
I am confused. How is `-fsanitize-coverage=trace-cmp` related to this? It solves a different problem and (1) if does not necessary contain any arithmetic comparison (it can just check an existing bool), (2) it does not allow to calculate result of comparison (don't know the operator and signedness).
If we have `if {} else if {} else {}` I think we need callback in each of the blocks. Not just for people manually inspecting coverage, but as fuzzer guidance signal.

**Comment by chefmax** [comment]
> I am confused. How is -fsanitize-coverage=trace-cmp related to this?

I'm sorry, just ignore this (I've misread `-fsanitize-coverage=trace-cmp`). So yeah, we cannot understand in fuzzer that we visited `if (c == '/')` fall through block with current instrumentation.

**Comment by nikdmt** [comment]
I have checked coverage and LibFuzzer results with `-mllvm -sanitizer-coverage-prune-blocks=0`: the number of covered branches has increased and I was able to find another bug in my library with LibFuzzer, that wasn't discovered without this option.

**Comment by kcc** [comment]
> the number of covered branches has increased 

You mean, `cov: NNN` in the the libFuzzer's has increased? That would be expected because you have more instrumentation points. 

>  I was able to find another bug in my library with LibFuzzer, that wasn't discovered without this option.
Interesting. Are you sure this is not a coincidence? I.e. can you reliably repeat this experiment? 
(Run libFuzzer in two modes ~10 independent times each)

(And I still need to look at your comments to verify if we indeed miss some instrumentation now...)

**Comment by nikdmt** [comment]
> You mean, cov: NNN in the the libFuzzer's has increased? That would be expected because you have more instrumentation points.

No, `cov: NNN` is indeed increased in about twice, but I was looking specifically for branches (like that `else if` clause from reduced.c) that were not instrumented at all without this option.

> Interesting. Are you sure this is not a coincidence?

I guess it is a coincedence. Sorry for misinformation. I am still confused why, but now both with and without this option I can catch this bug. Until now I was pretty sure that it wasn't discovered after hours of fuzzing and now fuzzer finds it in instant starting with empty corpus.

**Comment by mikea** [comment]
I've debugged this problem further and there indeed is a subtle bug, thank you.
If you take a look at the attached CFG, then if.then6 won't be instrumented because it is full dominator of if.end and if.end won't be instrumented because it is a full postdominator of if.then6.

Looks like this happens when there are linear sequences of basic blocks. I have to think a bit about the best way to fix this.


![graph](https://cloud.githubusercontent.com/assets/3236/24123231/eeef3624-0d7b-11e7-9389-71d362f21c86.png)

**Comment by mikea** [comment]
Proposed fix is here: https://reviews.llvm.org/D31266

**Comment by kcc** [comment]
Vitaly, please take over this bug (and the patch above). 
It may need to be simplified further

**Comment by mguseva** [comment]
Hello! Do you have any plans to submit the fix? It seems the initial patch has been already implemented and it needs only to be updated after the review. Thank you in advance!

**Comment by kcc** [comment]
We hope to do it soon-ish, but I don't like the current patch -- it needs to be simplified. 
Vitaly, do you have ETA?

**Comment by vitalybuka** [comment]
I'll try this week.

**Comment by cheshire** [comment]
I'm hitting this (or a very similar) when fuzzing Swift code, due to a peculiar shape of emitted IR for `&&` constructs.

**Comment by cheshire** [comment]
For me, the fuzzer doesn't find anything, unless the coverage optimization is disabled.

**Comment by kcc** [comment]
@cheshire, mind attaching the LLVM IR repro?

**Comment by cheshire** [comment]
@kcc maybe a bit later, currently it looks like the fact that critical edges are somehow not being split is at fault.
I've added a comment at the phabricator revision, I think a simpler and more obvious fix would be to disable the optimization which does not instrument full post-dominators to prevent problematic circular reasoning.

**Comment by kcc** [comment]
@cheshire, @vitalybuka I guess this is fixed now? Can we close?

**Comment by cheshire** [comment]
@kcc I think we should close, fixed in https://github.com/llvm-mirror/llvm/commit/f6cb5093853722a6d9f059f4e86435aa89e7491b

**Comment by kcc** [comment]
@cheshire , thanks again!
