### ISSUE TITLE
ASan/UBSan does not detect illegal input to the ctype.h macros

### ISSUE THREAD

**Issue by mrigger** [google/sanitizers#785]
Consider the following example:

```c
#include <ctype.h>

int main() {
    int a = isdigit(12345678);
    printf("%d\n", a);
}
```

Contrary to my expectations, no error is printed when executing the program with ASan or UBSan. The C specification (see [C99 7.4.1](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)) specifies the following for the `ctype.h` functions:

> In all cases the argument is an int, the value of which shall be representable as an unsigned char or shall equal the value of the macro EOF. If the argument has any other value, the behavior is undefined.

In the glibc, the `ctype.h` functions are mapped to a call to `ctype_b_loc` which returns a lookup table. According to this function's specification, values from -128 to 255 are allowed as input parameters (see [here](https://refspecs.linuxfoundation.org/LSB_2.0.1/LSB-Core/LSB-Core/baselib---ctype-b-loc.html)). On my system, the above program produces an out-of-bound access that results in a `SegmentationFault`.

Probably, interceptors are missing for `ctype_b_loc` and the `ctype.h` functions. If interceptors are the way to go, I could try to implement them.

I found this issue while writing a test case for Safe Sulong, which has its own libc implementation and detected the error.

**Comment by kcc** [comment]
I'd say this should be done in libc.

**Comment by mrigger** [comment]
Why? Passing values exceeding this range is undefined behavior, so libc implementations are not required to check for such values.

**Comment by kcc** [comment]
Because a libc code would be the easiest place to implement this.

**Comment by mrigger** [comment]
I doubt we can convince glibc and other C standard implementations to insert checks that are not required. Related to this topic, I remember the discussion about `memcpy` and `memmove` in the [Friendly C proposal](https://blog.regehr.org/archives/1287):
> To get a taste of this, notice that in the comments for the Friendly C post, several people disagree with what I would consider an extremely non-controversial design choice for Friendly C: memcpy() should have memmove() semantics.

**Comment by kcc** [comment]
> I doubt we can convince glibc

Well, maybe you should try? 
They already have fortify, which is kind-of-similar.
