### ISSUE TITLE
Get rid of "ASan runtime does not come first in initial library list" assertion

### ISSUE THREAD

**Issue by yugr** [google/sanitizers#786]
The said check (in `AsanCheckDynamicRTPrereqs` in asan_linux.cc) is overly agressive. It prevents ASan from running in many important environments e.g. cowbuilder and fakeroot (which use symbol interposition too). I suggest to convert it into a warning (hidden under `verbosity=2`) or at least provide a flag to suppress it.

**Comment by yugr** [comment]
@chefmax

**Comment by eugenis** [comment]
The issue is with LD_PRELOAD, right?
The check could be relaxed to "first after the main executable".

**Comment by yugr** [comment]
> The check could be relaxed to "first after the main executable".

Hm but all libraries (even preloaded ones) should go after main executable. I've just verified that with a simpel test for `dl_iterate_phdr`.

**Comment by eugenis** [comment]
Right. Yeah, a flag sounds fine.

**Comment by chefmax** [comment]
https://reviews.llvm.org/rL299188
