### ISSUE TITLE
Textdomain interceptors intercepts on NULL

### ISSUE THREAD

**Issue by yugr** [google/sanitizers#787]
`COMMON_INTERCEPTOR_READ_STRING` call should be protected with `if (domain)` in textdomain interceptor, otherwise we'll get segfault in `strlen` when `strict_string_checks` is enabled:

    COMMON_INTERCEPTOR_READ_STRING(ctx, domainname, 0);
    char *domain = REAL(textdomain)(domainname);
    if (domain) {
      COMMON_INTERCEPTOR_INITIALIZE_RANGE(domain, REAL(strlen)(domain) + 1);
    }

Sample crash (detected when building Debian packages under Asan via [debian_pkg_test](https://github.com/yugr/debian_pkg_test)):

    ==19841==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ffff65c8b96 bp 0x7fffffffd960 sp 0x7fffffffd0e8 T0)
    #0 0x7ffff65c8b95 in strlen (/lib/x86_64-linux-gnu/libc.so.6+0x8ab95)
    #1 0x7ffff6e7182b in __interceptor_textdomain (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x3c82b)
    #2 0x7ffff693e830  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x37830)
    #3 0x7ffff693e9a5 in g_dgettext (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x379a5)
    #4 0x7ffff693bb8f in g_dir_open (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x34b8f)
    #5 0x402db6  (/usr/bin/pkg-config+0x402db6)
    #6 0x7ffff694d51c in g_list_foreach (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4651c)
    #7 0x4024a0  (/usr/bin/pkg-config+0x4024a0)
    #8 0x7ffff655e82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x402b58  (/usr/bin/pkg-config+0x402b58)

**Comment by Lekensteyn** [comment]
Proposed patch: https://reviews.llvm.org/D32318
(tests fail without the fix, tests pass with the fix)

**Comment by Lekensteyn** [comment]
Should be fixed now in LLVM trunk, it is worth backporting this change to other GCC/LLVM branches?

**Comment by yugr** [comment]
@Lekensteyn Probly not, strict strings is not widely used.

**Comment by morehouse** [comment]
Looks like this was resolved.
