### ISSUE TITLE
libFuzzer: Crash resistant merge hangs after timeout and oom combo

### ISSUE THREAD

**Issue by attekett** [google/sanitizers#788]
Tested on: 

OS: Ubuntu 16.04
Clang: clang version 5.0.0-svn297872-1 exp1 (trunk)
libFuzzer: libfuzzer-5.0-dev - 1:5.0 svn297872-1 exp1

I'm running corpus merge for huge data set that contains some badly behaving inputs.

libFuzzer run command: ./fuzzer -workers=1 -merge=1 -timeout=1 <corpus-dirs>

Sometimes libFuzzer hangs after first reporting, "ALARM: working on the last Unit for 1 seconds", then in the middle of the timeout output libFuzzer reports OOM: "ERROR: libFuzzer: out-of-memory (used: 2060Mb; limit: 2048Mb)"

Example output:

	#64	pulse  cov: 2638 exec/s: 16 rss: 1215Mb
	ALARM: working on the last Unit for 1 seconds
	       and the timeout value is 1 (use -timeout=N to change)
	MS: 0 ; base unit: 0000000000000000000000000000000000000000
	<content>
	==10925== ERROR: libFuzzer: out-of-memory (used: 2060Mb; limit: 2048Mb)
	   To change the out-of-memory limit use -rss_limit_mb=<N>

	artifact_prefix='./'; Test unit written to ./timeout-<hash>
	Base64: <base64>
	==10925== ERROR: libFuzzer: timeout after 1 seconds
	Live Heap Allocations: 1669308551 bytes in 2482645 chunks; quarantined: 253234514 bytes in 139668 chunks; 103842 other chunks; total chunks: 2726155; showing top 95%
	1207984704 byte(s) (72%) in 1 allocation(s)

FWIW, I can find and kill the fuzzer instance that has hanged and merge continues normally.

**Comment by kcc** [comment]
> libFuzzer: libfuzzer-5.0-dev - 1:5.0 svn297872-1 exp1

This looks fresh enough, but still, please try to use the most recent version

> ./fuzzer -workers=1 -merge=1 -timeout=1

-workers=1 is redundant. 

Interesting. Looks like timeout and oom handlers block each other somehow.
Will need to think. The workaround is probably to use e.g. -timeout=10

**Comment by morehouse** [comment]
I'm hitting a similar (the same?) bug during fuzzing of PCRE.  ASan is in the middle of reporting a bug when OOM hits and a deadlock ensues.

Fuzzing thread:
```
#0  atomic_exchange<__sanitizer::atomic_uint32_t> () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_atomic_clang.h:68
#1  Lock () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cc:639
#2  0x000000000056a1c2 in GenericScopedLock () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_mutex.h:189
#3  SymbolizePC () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:76
#4  0x0000000000568c59 in Print () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cc:35
#5  0x00000000005509ca in __sanitizer_print_stack_trace () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_stack.cc:38
#6  0x000000000044530a in AlarmCallback () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:292
#7  <signal handler called>
#8  internal_iserror () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_syscall_linux_x86_64.inc:88
#9  internal_read () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cc:210
#10 0x000000000055f8b0 in __sanitizer::ReadFromFile(int, void*, unsigned long, unsigned long*, int*) ()
    at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:175
#11 0x000000000056b11f in __sanitizer::SymbolizerProcess::ReadFromSymbolizer(char*, unsigned long) ()
    at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:464
#12 0x000000000056ae95 in SendCommandImpl () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:445
#13 SendCommand () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:429
#14 0x000000000056abeb in __sanitizer::LLVMSymbolizer::SymbolizePC(unsigned long, __sanitizer::SymbolizedStack*) ()
    at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:354
#15 0x000000000056a229 in SymbolizePC () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:88
#16 0x0000000000568c59 in Print () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cc:35
#17 0x00000000004afa42 in Print () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_errors.cc:470
#18 0x000000000054c875 in ~ScopedInErrorReport () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_report.cc:138
#19 0x000000000054d8c3 in ReportGenericError () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_report.cc:404
#20 0x000000000054dfeb in __asan_report_load1 () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_rtl.cc:111
#21 0x0000000000606f70 in match (eptr=<optimized out>, ecode=0x60e000073e07 "\036\f\036\322\242\036 8\n\036-x", mstart=0x7ffe92bf4d10 ".+\\C+\f\322\242 \n+-", offset_top=2, 
    mb=0x7ffe92bf4820, eptrb=0x7ffe92bf3ba0, rdepth=<optimized out>) at src/pcre2_match.c:5968
#22 0x00000000005f179c in match (eptr=0x7ffe92bf4d16 "\322\242 \n+-", ecode=0x60e000073e05 "W\016\036\f\036\322\242\036 8\n\036-x", mstart=0x7ffe92bf4d10 ".+\\C+\f\322\242 \n+-", 
    offset_top=2, mb=0x7ffe92bf4820, eptrb=0x7ffe92bf4200, rdepth=<optimized out>) at src/pcre2_match.c:5965
#23 0x00000000005c5c4c in pcre2_match_8 (code=<optimized out>, subject=0x7ffe92bf4d10 ".+\\C+\f\322\242 \n+-", length=12, start_offset=0, options=<optimized out>, 
    match_data=0x60b0000a20d0, mcontext=0x7ffe92bf490c) at src/pcre2_match.c:6876
#24 0x000000000061a2e1 in regexec (preg=<optimized out>, string=0x7ffe92bf4d10 ".+\\C+\f\322\242 \n+-", nmatch=0, pmatch=0x7ffe92bf4d80, eflags=<optimized out>) at src/pcre2posix.c:291
#25 0x0000000000578b62 in LLVMFuzzerTestOneInput (data=<optimized out>, size=12) at /work/FTS/pcre2-10.00/target.cc:17
#26 0x000000000044662d in ExecuteCallback () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:515
#27 0x0000000000445fac in RunOne () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:440
#28 0x0000000000447d14 in MutateAndTestOne () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:648
#29 0x0000000000448716 in Loop () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:779
#30 0x000000000043ed09 in FuzzerDriver () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:754
#31 0x0000000000465863 in main () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20
```

Memory Profile thread:
```
#0  atomic_exchange<__sanitizer::atomic_uint32_t> () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_atomic_clang.h:68
#1  Lock () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cc:639
#2  0x000000000056a1c2 in GenericScopedLock () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_mutex.h:189
#3  SymbolizePC () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cc:76
#4  0x0000000000568c59 in Print () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cc:35
#5  0x00000000005496f1 in Print () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_memory_profile.cc:71
#6  0x00000000005495a8 in MemoryProfileCB () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/asan/asan_memory_profile.cc:109
#7  0x0000000000569b24 in TracerThread () at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:320
#8  0x000000000055efe2 in __sanitizer::internal_clone(int (*)(void*), void*, int, void*, int*, void*, int*) ()
    at /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cc:1159
```

Looks like the deadlock is happening on lock `mu` inside `SymbolizePC`.

1. **Fuzzing thread** - ASan detects error and enters `SymbolizePC` to print a stack trace.  Acquires lock `mu`.
2. **Memory profile thread** - OOM detected.  Sends `SIGALRM` to fuzzing thread.
3. **Fuzzing thread** - Enters `Fuzzer::AlarmCallback`, proceeds to `SymbolizePC` to print stack trace.  Deadlocks on `mu`.

**Comment by morehouse** [comment]
On further investigation, this deadlock looks slightly more complicated.  We also have a timeout mixed in there.

1. **Fuzzing thread** - ASan detects error and enters `SymbolizePC` to print a stack trace.  Acquires lock `mu`.
2. **Fuzzing thread** - Timeout reached and `SIGALRM` received.  Enters `Fuzzer::AlarmCallback`, proceeds to `SymbolizePC` and deadlocks on `mu`.
3. **RSS monitor thread** - OOM detected.  Calls `StopTheWorld` and suspends **fuzzing thread** (which is already deadlocked).  Continues to `MemoryProfileCB` and `SymbolizePC`.  Deadlocks on `mu`.

So there's actually 2 deadlocks here.  The one in step 2 is probably what @attekett ran into, but the one in step 3 is also a problem.

Maybe we want to block signals in `SymbolizePC` before acquiring `mu`.

**Comment by morehouse** [comment]
I've come up with a few ideas to address the deadlock, but none seem ideal, and some only partially fix the problem.  @kcc, let me know what you think.

1. Disable symbolization for TO/OOM crashes.
    - Makes TO/OOM reports less actionable.
    - Not sure if there's an easy way to do this currently.
2. Block signals before acquiring `Symbolizer` lock.
    - Only fixes the TO deadlock.  OOM handler can still stop a thread inside `Symbolizer` methods since we can't block `SIGSTOP`.
2. Implement `Symbolizer::TrySymbolizePC()` method that returns `nullptr` if the lock is held.
    - Either requires `Symbolizer` to switch to a `SpinMutex` or implementation of `BlockingMutex::TryLock()` for all platforms.
    - Probably also requires implementation of `__sanitizer_try_print_stack_trace()`, `StackTrace::TryPrint()`, `__sanitizer_try_print_memory_profile()`, `TryMemoryProfileCB`, `HeapProfile::TryPrint()`.
3. Implement `Symbolizer::UnsafeSymbolizePC()` method that attempts symbolization even if the lock is held.
    - Since we're already crashing, we don't care as much about doing things that could cause a crash.
    - Probably also requires implementation of `__sanitizer_unsafe_print_stack_trace()`, `StackTrace::UnsafePrint()`, `__sanitizer_unsafe_print_memory_profile()`, `UnsafeMemoryProfileCB`, `HeapProfile::UnsafePrint()`.
4. Implement a kill timer for TO/OOM handlers that kills the process if a deadlock happens.
    - Only fixes the TO deadlock.  OOM handler pauses all threads, and `SIGALRM` does not unpause them.

**Comment by kcc** [comment]
I would try some way to block all variants of report-and-die once one of them is initiated. 
One way to do so is to implement `bool __sanitizer_acquire_report_bug_and_die_state()` (or some such)
as an atomic exchange of a boolean. Every part of asan/libFuzzer that is trying to report-and-die should call this function and return immediately if the result is false.

This won't work well with asan in recovery mode, but we should not be using that with libFuzzer anyway.

**Comment by morehouse** [comment]
Fixed by https://reviews.llvm.org/D46277.

**Comment by savannahsafari** [comment]
![email_privacy](https://user-images.githubusercontent.com/35204255/39680771-5c731d6a-5172-11e8-8581-f0ea0a562d05.png)
