### ISSUE TITLE
If set "coverage_bitset=1:coverage_direct=1", the bit_set file cannot be generate.

### ISSUE THREAD

**Issue by MayfeelYang** [google/sanitizers#790]
If I set "coverage=1", "coverage_bitset=1" and "coverage_direct=1" at the same time, the bitset file can't be generate.
And I set "coverage=1" and "coverage_bitset=1", the bitset file can be generate successfully
How can I get the bitset file when I set "coverage_direct=1"?

**Comment by kcc** [comment]
I am going to deprecate these flags, sorry. 

The supported part is described here: 
https://clang.llvm.org/docs/SanitizerCoverage.html#tracing-pcs-with-guards
You will need to implement two tiny callbacks yourself and then dump the coverage in the format(s) you prefer.
