### ISSUE TITLE
sancov: -symbolize does not work on linux kernel

### ISSUE THREAD

**Issue by dvyukov** [google/sanitizers#791]
Reported here:
https://groups.google.com/d/msg/syzkaller/6ZYQjkHCIeo/HnW64qn8CAAJ

`sancov -symbolize vmlinux.sancov vmlinux` says:
`Ignoring vmlinux and its coverage because  __sanitizer_cov* functions were not found.`

Kernel objdump looks as follows:
```
ffffffff81002060 <try_to_run_init_process>:
ffffffff81002060:       55                      push   %rbp
ffffffff81002061:       48 89 e5                mov    %rsp,%rbp
ffffffff81002064:       41 54                   push   %r12
ffffffff81002066:       53                      push   %rbx
ffffffff81002067:       49 89 fc                mov    %rdi,%r12
ffffffff8100206a:       e8 91 e9 6c 00          callq  ffffffff816d0a00 <__sanitizer_cov_trace_pc>
ffffffff8100206f:       4c 89 e7                mov    %r12,%rdi
ffffffff81002072:       e8 a9 ff ff ff          callq  ffffffff81002020 <run_init_process>
ffffffff81002077:       89 c3                   mov    %eax,%ebx
ffffffff81002079:       83 c0 02                add    $0x2,%eax
ffffffff8100207c:       83 e0 fd                and    $0xfffffffd,%eax
ffffffff8100207f:       75 0c                   jne    ffffffff8100208d <try_to_run_init_process+0x2d>
ffffffff81002081:       e8 7a e9 6c 00          callq  ffffffff816d0a00 <__sanitizer_cov_trace_pc>
ffffffff81002086:       89 d8                   mov    %ebx,%eax
ffffffff81002088:       5b                      pop    %rbx
ffffffff81002089:       41 5c                   pop    %r12
ffffffff8100208b:       5d                      pop    %rbp
ffffffff8100208c:       c3                      retq   
ffffffff8100208d:       e8 6e e9 6c 00          callq  ffffffff816d0a00 <__sanitizer_cov_trace_pc>
ffffffff81002092:       89 da                   mov    %ebx,%edx
ffffffff81002094:       4c 89 e6                mov    %r12,%rsi
ffffffff81002097:       48 c7 c7 00 01 40 84    mov    $0xffffffff84400100,%rdi
ffffffff8100209e:       e8 80 02 81 00          callq  ffffffff81812323 <printk>
ffffffff810020a3:       eb dc                   jmp    ffffffff81002081 <try_to_run_init_process+0x21>
```

**Comment by yogurfrul** [comment]
I'working on Android , I have likely problem .
Then I debug the sancov.cc source code ,I found that the tool can only read the symbols of host linux PC ,failed when the object is Android  target ,like arm.

**Comment by eugenis** [comment]
I think the problem on Android was that the tool, using llvm disassembler,
could not recognize calls to __sanitizer_cov* functions through PLT. Doing
this requires platform-specific knowledge (PLT entry format at the least)
which was not readily available in the disassembler.

I don't know what the kernel problem is.

**Comment by yogurfrul** [comment]
It seems that the kernel is Android kernel :(
$LLVM/projects/compiler-rt/lib/sanitizer_common/scripts/sancov.py works for me ,why the tool don't disassembler as the same way?
I want to use the tool to generate the coverage report of library on Android .
I have got the .sancov files ,  do you have any  suggestion？ or other ways？

**Comment by lietdai** [comment]
I have the same   problem with running libfuzz target on  android.

**Comment by kcc** [comment]
@lietdai, please open a separate issue with details (what exactly is happening and what versions of everything are used)

**Comment by morehouse** [comment]
Workaround provided in https://groups.google.com/d/msg/syzkaller/6ZYQjkHCIeo/HnW64qn8CAAJ, and no major SanCov updates are expected in the future.
