### ISSUE TITLE
Asan should intercept stdio APIs

### ISSUE THREAD

**Issue by yugr** [google/sanitizers#793]
Asan will be able to report overflow for plain `write` is used but not for `fwrite` (i.e. when `-DSTDIO`):

    #include <unistd.h>
    #include <stdio.h>
    int main() {
      char buf[1];
      volatile char *p = buf;
    #ifdef STDIO
      fwrite(p, 1, 10, stdout);
    #else
      write(1, p, 10);
    #endif
      return 0;
    }

This is probly caused by the fact that Glibc calls it's own functions directly, not through a PLT (this is achieved via hidden aliases).

The same issue obviously applies to `fread` and others.

**Comment by chefmax** [comment]
TSan and MSan have fread and fwrite interceptors, I think it's not a big deal to move them to sanitizer_common.

**Comment by yugr** [comment]
https://reviews.llvm.org/D31456

**Comment by chefmax** [comment]
Can close this?

**Comment by yugr** [comment]
Yes, thanks!
