### ISSUE TITLE
Why there is no 32bit liblsan.so?

### ISSUE THREAD

**Issue by yangluoshen** [google/sanitizers#794]
First of all, my target is to compile a 32bit program(but my machine is 64bit, so -32m is essential(I think)), and I only want to detect memory leak( so I should use  -fsanitize=leak(I told by the document))
while I do compile following , I got a link error:
    
    #  /opt/gcc-6.1.0/bin/gcc -fsanitize=leak  -m32 main.cpp -o main
    /usr/bin/ld: cannot find -llsan
    collect2: error: ld returned 1 exit status

Then I found there is no 32bit liblsan.so .

    # find /opt/ -name liblsan.so
    /opt/gcc-6.1.0/lib64/liblsan.so

The LD_LIBRARY_PATH:

    # echo $LD_LIBRARY_PATH
    /opt/gmp-6.1.1/lib/:/opt/mpfr-3.1.5/lib/:/opt/mpc-1.0.3/lib/:/opt/gcc-6.1.0/lib/:/opt/gcc-6.1.0/lib64/

I compile gcc-6.1.0 in this way ( I don't enable "--disable-multilib", so I suppose it would support  32 bit):

    # /opt/gcc-6.1.0/bin/gcc -v
    Using built-in specs.
    COLLECT_GCC=/opt/gcc-6.1.0/bin/gcc
    COLLECT_LTO_WRAPPER=/opt/gcc-6.1.0/libexec/gcc/x86_64-pc-linux-gnu/6.1.0/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: ../configure --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,objc -with-gnu-as --with-gnu-ld --with-cpu=generic --disable-dssi --enable-plugin --prefix=/opt/gcc-6.1.0 --enable-linux-futex --with-gmp=/opt/gmp-6.1.1/ --with-mpfr=/opt/mpfr-3.1.5/ --with-mpc=/opt/mpc-1.0.3/ --program-suffix=-6.1.0
    Thread model: posix
    gcc version 6.1.0 (GCC)

I don't know how to achieve my target. Can anybody give me a hand?

**Comment by chefmax** [comment]
GCC doesn't support 32-bit LSan so far, only recent Clang does (see https://reviews.llvm.org/rL293610).
This probably can be merged to GCC 8. But I must warn you that LSan on 32-bit architectures might have huge ratio of false negatives, see https://code.google.com/archive/p/valgrind-variant/wikis/LeakCheckingOn32bits.wiki for explanation.

**Comment by yangluoshen** [comment]
Thanks.
