### ISSUE TITLE
[documentation] Why not `-fsanitize-address-use-after-scope` by default?

### ISSUE THREAD

**Issue by lbrandy** [google/sanitizers#795]
I'm sure there is a good reason this is a separate compiler option but I don't know what it is and I don't see it in the docs. 

https://github.com/google/sanitizers/wiki/AddressSanitizerUseAfterScope says "AddressSanitizer currently does not enable detection of these bugs by default. " but not why :(

**Comment by eugenis** [comment]
This was, in fact, fixed last week in https://reviews.llvm.org/D31479.
Use-after-scope detection is now on by default. I've fixed the wiki.

**Comment by lbrandy** [comment]
Thanks great. We'll turn this on internally by default. 

As for the wiki, as written now, it might be more clear to say at which version of llvm/etc it becomes enabled by default. Because had I read that this morning (that it was enabled by default), I might have been even more confused. 

At any rate, close this as you see fit.

**Comment by moberhuber** [comment]
I agree, it is hard to see which sanitizers are available in which compilers, and how to actually run all available sanitizers. I understand that -fsanitize=address and -fsanitize=thread can not run in parallel. Now if I do 2 runs with those 2 options, will it run everything available? What about -fsanitize=leak, -fsanitize=undefined?

As a user, I'd ideally want to set up my CI system to automatically run all available sanitizers. Any pointer to what options are needed for this in (a) clang6-trunk or (b) gcc7.2 would be appreciated. Similar to https://github.com/google/sanitizers/wiki/AddressSanitizerClangVsGCC-(5.0-vs-7.1) but ideally more hilevel (not quite so detailed)...

**Comment by moberhuber** [comment]
PS the -fsanitize-address-use-after-scope flag should perhaps be removed from the table on https://github.com/google/sanitizers/wiki/AddressSanitizerFlags , if it is now on by default?

**Comment by morehouse** [comment]
> PS the -fsanitize-address-use-after-scope flag should perhaps be removed from the table on https://github.com/google/sanitizers/wiki/AddressSanitizerFlags , if it is now on by default?

Done.
