### ISSUE TITLE
ASAN fails to detect alignment mismatched delete calls

### ISSUE THREAD

**Issue by ahh** [google/sanitizers#799]
class alignas(64) Foo {
  char buf[64];
};

class Bar {
  char buf[64];
};

  Foo *f = new Foo;
  Bar *b = new Bar;
  volatile Foo *nf = reinterpret_cast<Foo *>(b);
  volatile Bar *nb = reinterpret_cast<Bar *>(f);
  DoNotOptimize(nf);  // prevent new/delete elision somehow
  DoNotOptimize(nb); 
  delete nf;
  delete nb;

This does not error out.  At least as of C++17, I believe it should be able to make it do so (and that it is important to in fact do so)--becuase the "delete nf" call should invoke a aligned delete operator (3 or 7 here http://en.cppreference.com/w/cpp/memory/new/operator_delete) and the delete nb call should not.

**Comment by kcc** [comment]
we will need to intercept operator new/delete with the alignment argument and then store
the alignment in asan's ChunkHeader. 
3 bits should be enough to represent 8 different alignment values:  none, 8, 16, 32, 64, 128, 256, 512+.
We can steal 3 bits from `u32 user_requested_size`

**Comment by kcc** [comment]
@alekseyshl can we close this?

**Comment by alekseyshl** [comment]
Yes, we can
