### ISSUE TITLE
[ASAN] Check for large malloc request?

### ISSUE THREAD

**Issue by Lekensteyn** [google/sanitizers#802]
In order to catch issues like `malloc((unsigned)-1)`, it would be nice if ASAN could warn about it.

At the moment, ASAN will only do this for 32-bit systems:
```c
struct Allocator {
  static const uptr kMaxAllowedMallocSize =
      FIRST_32_SECOND_64(3UL << 30, 1ULL << 40);
```

What do you think about the addition of an `alloc_max_size_mb` option that makes this value configurable? (And if this is to be added, should it still enforce the previous platform-dependent `kMaxAllowedMallocSize` to avoid internal consistency (integer overflows)?)

**Comment by kcc** [comment]
Hmm. On a 64-bit system `malloc(-1)` turns into `malloc(0xffffffffffffffff)` and asan barks on it: 
```
==26728==WARNING: AddressSanitizer failed to allocate 0xffffffffffffffff bytes
```
So, not sure what's the problem.

**Comment by Lekensteyn** [comment]
Sorry, `malloc(-1)` should have been `malloc((unsigned)-1)` (i.e. "-1" stored in a 32-bit unsigned number rather than a 64-bit one). That case is currently not detected.

**Comment by yugr** [comment]
You may get a lot of FPs if you warn on 4G allocations on 64-bit systems.

**Comment by Lekensteyn** [comment]
@yugr True, but that is why it is an option (which defaults to `3ULL << 30` for 32-bit and `1ULL << 40` for 64-bit).

The motivation for this request is an out-of-memory oss-fuzz report which I could not reproduce. It turns out that a `malloc(0xffffffff)` request was involved, but this was not caught on my system. While accounting the memory consumption via allocations could work, I imagine it would involve some overhead since the memory size for deallocations is not known (see `__asan::Allocator::Deallocate()`). So putting a maximum limit on `malloc` would be simple and sufficient to catch this case.

**Comment by yugr** [comment]
@Lekensteyn "So putting a maximum limit on malloc would be simple and sufficient to catch this case" - only if it does not introduce too many false positives in other projects. I wonder if simply checking for `(unsigned)-1` on 64-bit platforms would be sufficient?

**Comment by Lekensteyn** [comment]
@yugr It would not be sufficient. Consider size allocation requests like:
```c
int size = end - (offset - begin);
void *buffer = malloc(size);
```
if for some reason size ends up to be negative (be it -1, -2 or -10), then it would still be desirable to fail.

I'd like to emphasize that the proposed option still has high limits by default. Similar to how you can set `hard_rss_limit_mb=2048`, this option should be able to limit the maximum malloc request.

**Comment by kcc** [comment]
I am reluctant to introduce a flag that will turn a perfectly valid code into a crash (even if not by default). 
If anything, we have too many flags already. 
However, you may get what you need using an asan's malloc hook
(which is what libFuzzer does to catch allocations larger than rss_limit_mb). 
https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/allocator_interface.h#L75
https://github.com/llvm-mirror/llvm/blob/master/lib/Fuzzer/FuzzerLoop.cpp#L126

**Comment by Lekensteyn** [comment]
Yes, using ASAN alloc hooks works and for the timeout check there is already a `LD_PRELOAD` library that uses `SIGALRM` so I guess that is a sufficient compromise.

Btw, is it true that the `*_rss_limit_mb` can miss cases when the program is short-lived due to its 100ms interval in a separate thread?

**Comment by kcc** [comment]
Yes, libFuzzer's rss_limit_mb is not perfect. 
It will always catch a single huge malloc, but it may miss a short-lived spike in RAM usage due to several large-but-not-huge mallocs. 

If running libFuzzer w/o asan you can achieve a more reliable OOM detection with 'ulimit -v 2048000' or some such.

**Comment by morehouse** [comment]
Solution is to use malloc hooks.
