### ISSUE TITLE
__sanitizer_cov* functions were not found when I sancov my executable

### ISSUE THREAD

**Issue by yogurfrul** [google/sanitizers#808]
I'm doing some  libFuzzer test  on Android ,whose llvm version is 4.0.285906, so I use sancov tool to get coverage report as 
http://releases.llvm.org/4.0.0/tools/clang/docs/SanitizerCoverage.html#coverage-reports-experimental

then I got the error as blow:
`Ignoring out/target/product/XXX/data/nativetest64/fuzzers/fuzz_me/fuzz_me and its coverage because  __sanitizer_cov* functions were not found.`
my executable is compiled with  LOCAL_CFLAGS += -fsanitize-coverage=edge,indirect-calls,8bit-counters,trace-cmp
then I nm the executable：

`nm -D out/target/product/XXX/data/nativetest64/fuzzers/fuzz_me/fuzz_me | grep -s sanitizer_cov                    U __sanitizer_cov
                 U __sanitizer_cov_indir_call16
                 U __sanitizer_cov_module_init
000000000000a850 T __sanitizer_cov_trace_cmp1
000000000000a7c0 T __sanitizer_cov_trace_cmp2
000000000000a728 T __sanitizer_cov_trace_cmp4
000000000000a690 T __sanitizer_cov_trace_cmp8
000000000000a9a4 T __sanitizer_cov_trace_div4
000000000000aa3c T __sanitizer_cov_trace_div8
000000000000aa3c T __sanitizer_cov_trace_gep
000000000000a560 T __sanitizer_cov_trace_pc_guard
000000000000a5a4 T __sanitizer_cov_trace_pc_guard_init
000000000000a620 T __sanitizer_cov_trace_pc_indir
000000000000a8e0 T __sanitizer_cov_trace_switch`

**Comment by kcc** [comment]
You should stop using old clang, old libFuzzer, and old sanitize coverage flags -- we can't support them, sorry. 
Meanwhile, **on Android**, with the new stuff you are also on your own -- we don't officially support it yet.  
Sorry again. 

BTW, my usual question wrt libFuzzer on Android: why can't you fuzz the same code on Linux?

**Comment by yogurfrul** [comment]
I  really understand what you said.

All of our work are based on Android, and  I can easily call the  function to test under Android.mk which define the compile options of all of targets. 
And the vast majority of shared libraries are made for running on arm ,not no host linux.
I have do some small test to fuzz some simply functions on linux, it works fine~However  it's a huge work to reconstructe the compile option and I want to apply libFuzzer to more source codes.

In fact, Android has introduced libfuzzeras as libLLVMfuzzer, so I just use it~
so ,as you see, I have to work base on old clang/libfuzzer/sancov which Android offers.
do you know dan albert ？I see he is also member of libfuzzer of groups.google.He introduced libfuzzer from llvm to android.Maybe ，he could help me~

Anyway,thank you for your reply~
