### ISSUE TITLE
Coverage pass creates critical edges, which ironically stop coverage from working properly

### ISSUE THREAD

**Issue by cheshire** [google/sanitizers#809]
For the input LLVM IR file http://metaworld.me/swift.ll (visualization http://metaworld.me/uninstrumented.pdf) applying coverage (`opt swift.ll -sancov -sanitizer-coverage-level=3 -sanitizer-coverage-trace-pc-guard`) produces the output http://metaworld.me/swift_instrumented.ll (visualization http://metaworld.me/instrumented.pdf), which contains critical edges, and thus for which the coverage is not working properly.

**Comment by kcc** [comment]
Can you make this happen while compiling a C code?

**Comment by cheshire** [comment]
@kcc actually it seems that this is not a bug, and the created (albeit critical) branch simply increments the coverage only if it is zero.
My actual bug is indeed #783, patch coming shortly, sorry for the nuisance.
