### ISSUE TITLE
valgrind + AddressSanitizer: ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

### ISSUE THREAD

**Issue by minfrin** [google/sanitizers#810]
When attempting to run a program linked against AddressSanitizer under valgrind, AddressSanitizer crashes with the message "ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD."

The message is accurate - valgrind has inserted it's own LD_PRELOAD.

It looks like the LD_PRELOAD hack to make AddressSanitizer work clashes with the LD_PRELOAD hack to make valgrind work.

Any chance to get AddressSanitizer to work without hacks?

minfrin@towerofpi9:/var/www/html/stream$ GST_LEAKS_TRACER_STACK_TRACE=1 GST_LEAKS_TRACER_SIG=1 ASAN_OPTIONS=atexit=1 GST_TRACERS="leaks(stack-traces-flags=full,filters=GstMemory,check-refs=true)" GST_DEBUG_DUMP_DOT_DIR=. G_DEBUG="fatal-warnings" LD_LIBRARY_PATH=/usr/local/lib:/usr/local/gcc-6.2.0/lib /tmp/valgrind/bin/valgrind gst-launch-1.0 --gst-debug-no-color --gst-debug=1,GST_TRACER:7,GST_REFCOUNTING:0,GST_PADS:1,GST_STATES:5,tdttsparse:5,tsdemux:1,omx:1,omxvideo:1,omxvideodec:1,omxh264dec:1,omxvideoenc:1,omxh264enc:1,videoencoder:1,videorate:1,videoscale:1,mpegtsmux:4,decodebin:1,encodebin:1,h264parse:1,transcoder:5,hlssink:5 udpsrc multicast-iface=eth0 uri=udp://239.106.0.0:1234 "caps=application/x-rtp,media=(string)video,clock-rate=(int)90000" ! rtpbin ! rtpmp2tdepay ! progressreport update-freq=5 ! transcoder name=transcoder ! capsfilter caps=audio/x-raw ! fakesink   transcoder. ! capsfilter caps=video/mpegts ! hlssink target-duration=0    transcoder. ! capsfilter caps=audio/x-raw ! fakesink
==20184== Memcheck, a memory error detector
==20184== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==20184== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==20184== Command: gst-launch-1.0 --gst-debug-no-color --gst-debug=1,GST_TRACER:7,GST_REFCOUNTING:0,GST_PADS:1,GST_STATES:5,tdttsparse:5,tsdemux:1,omx:1,omxvideo:1,omxvideodec:1,omxh264dec:1,omxvideoenc:1,omxh264enc:1,videoencoder:1,videorate:1,videoscale:1,mpegtsmux:4,decodebin:1,encodebin:1,h264parse:1,transcoder:5,hlssink:5 udpsrc multicast-iface=eth0 uri=udp://239.106.0.0:1234 caps=application/x-rtp,media=(string)video,clock-rate=(int)90000 ! rtpbin ! rtpmp2tdepay ! progressreport update-freq=5 ! transcoder name=transcoder ! capsfilter caps=audio/x-raw ! fakesink transcoder. ! capsfilter caps=video/mpegts ! hlssink target-duration=0 transcoder. ! capsfilter caps=audio/x-raw ! fakesink
==20184== 
==20184==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
==20184== Jump to the invalid address stated on the next line
==20184==    at 0x0: ???
==20184==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==20184== 
==20184== 
==20184== Process terminating with default action of signal 11 (SIGSEGV)
==20184==  Bad permissions for mapped region at address 0x0
==20184==    at 0x0: ???
==20184== 
==20184== HEAP SUMMARY:
==20184==     in use at exit: 0 bytes in 0 blocks
==20184==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==20184== 
==20184== All heap blocks were freed -- no leaks are possible
==20184== 
==20184== For counts of detected and suppressed errors, rerun with: -v
==20184== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

(Also raised this with the valgrind people at https://bugs.kde.org/show_bug.cgi?id=380037)

**Comment by eugenis** [comment]
Valgrind people are right, even though this could be made to work in
theory, it does not out of the box, for multiple reasons. And there is very
little motivation to support this mode.

**Comment by minfrin** [comment]
Currently it seems impossible to turn off AddressSanitizer as described in https://github.com/google/sanitizers/issues/811, and thus it remains impossible to run valgrind even with AddressSanitizer not enabled.

Would it be possible to fix this so that AddressSanitizer can at very least be switched off?

Right now AddressSanitizer's DoSes valgrind completely.

**Comment by morehouse** [comment]
Solution is don't run ASan+Valgrind.
