### ISSUE TITLE
Mention quarantine_size_mb in libFuzzer documentation

### ISSUE THREAD

**Issue by nwellnhof** [google/sanitizers#812]
It would have saved me a few hours of head-scratching if the libFuzzer docs mentioned that you should set the `quarantine_size_mb` ASan option if you plan longer runs. Otherwise, RSS seems to keep growing, resulting in an OOM eventually.

**Comment by kcc** [comment]
I am reluctant to mention it in the libFuzzer docs since we are about to actually fix this in asan... 
@alekseyshl 
But you are right, that's not a perfect users experience, sorry. 
I'll probably add some warning in libFuzzer output on OOMs.

**Comment by nwellnhof** [comment]
On 25/05/2017 04:51, Kostya Serebryany wrote:
> I'll probably add some warning in libFuzzer output on OOMs.

That's an even better idea.

**Comment by kcc** [comment]
I think the problem is finally solved (fully? partially?) byt the recent libFuzzer patches by @alekseyshl
