### ISSUE TITLE
Is address sanitizer suppose to work with 64bit binaries on Windows? 

### ISSUE THREAD

**Issue by kasper93** [google/sanitizers#818]
Hi,

I have not looked at the issue in details yet, but ASAN doesn't seem to work with x86_64 on Windows. 

It seem to fail to init 
```
==11096==AddressSanitizer CHECK failed: ..\projects\compiler-rt\lib\asan\asan_rtl.cc:505 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)
==11096==AddressSanitizer CHECK failed: ..\projects\compiler-rt\lib\asan\asan_poisoning.cc:37 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
```

You have build-bot set up for 32-bit builds only (and those indeed works) http://lab.llvm.org:8011/builders/sanitizer-windows so I suspect x64 is not supported? Or I'm missing something here? I couldn't find any info about actual status on Windows. It is not mentioned at all here https://github.com/google/sanitizers/wiki/AddressSanitizer. Yet official distribution ships with Windows ASAN libs. Also for not working x64. 

Regards,
Kacper

**Comment by rnk** [comment]
Win64 is supposed to work at this point, but we haven't set up bots for it yet. I've been waiting for some other buildbot changes to land before expanding our testing.

Windows has proven to be a much more complicated environment than Windows (AV, diverse versions, hard to interpose malloc & CRT, etc), so ASan seems to be more fragile. If you can get a stack trace for that CHECK failure, that would be helpful.

**Comment by kasper93** [comment]
Actually it failed in `GetInstructionSize()` when processing `strnlen` function. And after fixing this case everything seem to work fine.

``` diff
diff --git a/lib/interception/interception_win.cc b/lib/interception/interception_win.cc
index e4f3d358f..f7777a302 100644
--- a/lib/interception/interception_win.cc
+++ b/lib/interception/interception_win.cc
@@ -497,6 +497,11 @@ static size_t GetInstructionSize(uptr address, size_t* rel_offset = nullptr) {
       return 2;
   }
 
+  switch (0x0000FFFF & *(u32*)address) {
+    case 0x058B: // 8b 05 XX XX XX XX : mov eax, dword ptr [__isa_available (...)]
+      return 6;
+  }
+
   switch (0x00FFFFFF & *(u32*)address) {
     case 0xe58948:    // 48 8b c4 : mov rbp, rsp
     case 0xc18b48:    // 48 8b c1 : mov rax, rcx
```

It is little unfortunate that there is no error message when it fails here, but I have seen this fixme comment, so it seems to be known issue  :)

**Comment by rnk** [comment]
Should be fixed after r305581. Mozilla reported this as https://bugs.llvm.org/show_bug.cgi?id=32895

**Comment by kinke** [comment]
I'm having this issue on Win64 with ASan from LLVM v5.0.1 and VS 2017 v15.5.5.

**Comment by Oldes** [comment]
Me too..
```
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\SDKs\LLVM\bin
```
with error:
```
x:\>hello-asan.exe
==24616==AddressSanitizer CHECK failed: C:\src\llvm_package_501-final\llvm\projects\compiler-rt\lib\asan\asan_rtl.cc:497 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)
==24616==AddressSanitizer CHECK failed: C:\src\llvm_package_501-final\llvm\projects\compiler-rt\lib\asan\asan_poisoning.cc:37 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
```

**Comment by PIlin** [comment]
@Oldes I have similar issue. I used the hint from https://bugs.llvm.org/show_bug.cgi?id=35343#c3 to list and manually link against required ASAN libs.
