### ISSUE TITLE
[ASAN]Only detect one problem 

### ISSUE THREAD

**Issue by dxm5118118** [google/sanitizers#821]
hello,
I have a question,I have set make rule"-fsanitize-recover=address,all",system environment is "export ASAN_OPTIONS=halt_on_error=0",gcc version is 6.1.0,but detect one problem,is over,it can not continue.why ?
Thank you

**Comment by yugr** [comment]
It's hard to say w/o repro but it may be that error is so bad that program simply crashes afterwards.

**Comment by dxm5118118** [comment]
Oh,Thank you
Now I have found it can record log file,only not display
Thank you again.
