### ISSUE TITLE
AddressSanitizer CHECK failed when free unsigned char point

### ISSUE THREAD

**Issue by yogurfrul** [google/sanitizers#825]
I'm doing some libfuzzer test on Android O,I got the error as blow:

`==7687==AddressSanitizer CHECK failed: external/compiler-rt/lib/asan/asan_allocator.cc:147 "((alloc_magic[0])) == ((kAllocBegMagic))" (0xc0c000cc6e96b9, 0xcc6e96b9)
    #0 0x7776c5abdf  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x7cbdf)

    #1 0x7776c6e533  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x90533)

    #2 0x7776bfd123  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x1f123)

    #3 0x7776bfce0b  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x1ee0b)

    #4 0x7776bfccab  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x1ecab)

    #5 0x7776c52b97  (/system/lib64/libclang_rt.asan-aarch64-android.so+0x74b97)

    #6 0x5c2dd056cb  (/data/nativetest64/fuzzers/hi_omx_fuzzer/hi_omx_fuzzer+0x1a6cb)`

the error point to the code : 

`typedef unsigned char           HI_U8;

HI_U8* u32TmpData = (HI_U8*)malloc(framesize);

//some other codes

free(u32TmpData );`

**Comment by yogurfrul** [comment]
however when I run the fuzzer on the crash reproducer ,it come through, no crash
and 
when I add use_counters=0 runtime flags  to disable 8bit-counters to guide fuzzer, it works ok

any idea?~

**Comment by morehouse** [comment]
Please post a repro if still an issue.
