### ISSUE TITLE
Sanitizer CHECK failed

### ISSUE THREAD

**Issue by dxm5118118** [google/sanitizers#826]
Hello,
I have an error,Environment: gcc 6.1.0   x86_64   8U8G

c file:
#include <stdlib.h>
int main() {
  char *x = (char*)malloc(100);
  x[1] = '0';
  return 0;
}

error:
==119295==Sanitizer CHECK failed: ../../../../gcc-6.1.0/libsanitizer/sanitizer_common/sanitizer_allocator.h:324 ((kSpaceBeg)) == ((reinterpret_cast<uptr>(MmapNoAccess(kSpaceBeg, kSpaceSize)))) (105553116266496, -12)

gcc code:
void Init() {
    CHECK_EQ(kSpaceBeg,
             reinterpret_cast<uptr>(MmapNoAccess(kSpaceBeg, kSpaceSize)));
    MapWithCallback(kSpaceEnd, AdditionalSize());
  }

Thank you

**Comment by chefmax** [comment]
```
char x = (char)malloc(100);
```
This looks completely broken and doesn't even compile on my box. If I replace it with `char *x = (char*)malloc(100);` everything works fine for me.

**Comment by chefmax** [comment]
Also, please provide compilation flags you used to trigger the issue.

**Comment by dvyukov** [comment]
On Fri, Jun 23, 2017 at 11:37 AM, dxm5118118 <notifications@github.com> wrote:
>
> Hello,
> I have an error,Environment: gcc 6.1.0 x86_64 8U8G
>
> c file:
> #include <stdlib.h>
> int main() {
> char x = (char)malloc(100);
> x[1] = '0';
> return 0;
> }
>
> error:
> ==119295==Sanitizer CHECK failed: ../../../../gcc-6.1.0/libsanitizer/sanitizer_common/sanitizer_allocator.h:324 ((kSpaceBeg)) == ((reinterpret_cast(MmapNoAccess(kSpaceBeg, kSpaceSize)))) (105553116266496, -12)

Do you have ulimit -v set? If so, remove it. Sanitizers need lot of
virtual memory.

> gcc code:
> void Init() {
> CHECK_EQ(kSpaceBeg,
> reinterpret_cast(MmapNoAccess(kSpaceBeg, kSpaceSize)));
> MapWithCallback(kSpaceEnd, AdditionalSize());
> }
>
> Thank you

**Comment by dxm5118118** [comment]
@chefmax 
I write error on 1tip,right is:  
char *x = (char*)malloc(100);

compile ：
1、gcc a.c -o a -fsanitize=leak -O0 -fno-omit-frame-pointer -Wl,-rpath -Wl,/usr/local/lib64 
2、./a

**Comment by dxm5118118** [comment]
@dvyukov 
I don't have ulimit -v set,now I don't kown the error

**Comment by dvyukov** [comment]
It seems that you kernel restricts mmap of multi-TB regions. You can test this separately without asan by trying to mmap, say, 16TB and see if it fails. If that fails, there is nothing we can do on asan side.

**Comment by dxm5118118** [comment]
@dvyukov 
If I can modify code,it's size,don't restrict mmap of multi-TB regions
I can't find the limit code，can you help me find it?

Thank you

**Comment by dvyukov** [comment]
> I can't find the limit code，can you help me find it?

No idea what it is if not ulimit -v. Probably some kernel settings.

**Comment by dxm5118118** [comment]
@dvyukov   @chefmax 
I  try to set environment: “ulimit -v unlimited”，it's OK.
Result is:
```
==54874==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 100 byte(s) in 1 object(s) allocated from:
    #0 0x7f9f496ab44f in __interceptor_malloc ../../../../gcc-6.1.0/libsanitizer/lsan/lsan_interceptors.cc:51
    #1 0x400749 in main (/usr1/duxiaomiao/b+0x400749)
    #2 0x7f9f4935ebc5 in __libc_start_main (/lib64/libc.so.6+0x1ebc5)
```

Thank You
