### ISSUE TITLE
odr-violation disable?

### ISSUE THREAD

**Issue by qhdwns123** [google/sanitizers#831]
Hi.

Is there any way to disable odr-violation?

I can check the results using the command below, but this is inconvenient.

ASAN_OPTIONS = detect_odr_violation = 0 ./a.out

Thanks.

**Comment by kcc** [comment]
Not sure I understand the question. 
```
ASAN_OPTIONS=detect_odr_violation=0 ./a.out
```
*is* the way to disable the odr checking.

**Comment by yugr** [comment]
@qhdwns123 You can also implement `__asan_default_options` function as described in https://github.com/google/sanitizers/wiki/AddressSanitizerFlags
