### ISSUE TITLE
Instrumented/uninstrumented symbol collision with unoptimized libFuzzer build

### ISSUE THREAD

**Issue by cheshire** [google/sanitizers#832]
Hi,

When `libFuzzer` is compiled without optimizations, I sometimes have symbol collision issues, resulting in counterintuitive crashes.
For now, I can only reliably reproduce the issue on a mac, but I do recall seeing similar linking issues on Linux as well, so I don't think the issue is inherently platform specific.

To reproduce on a mac:

 * Compile `libLLVMFuzzer.a` without optimizations.
 * Create a file `blah.cc` which uses a `uint8_t` constructor on a vector:

```
#include<vector>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* buffer, size_t length) {
    std::vector<uint8_t> bb(100 * 10);
    return 0;
}
```
 * Drop `libLLVMFuzzer.a` into a toolchain for the freshly built compiler:

```
cp libLLVMFuzzer.a build/lib/libLLVMFuzzer.a
```

 * Compile the result with ASAN:

```
./build/bin/clang++ -fsanitize=address,fuzzer blah.cc
```

 * Observe a container overflow false positive resulting from the collision of instrumented and uninstrumented symbols from `vector` when running `./a.out`.

**Comment by kcc** [comment]
Yea... the container overflow checking may produce false positives like this, it's even part of docs:
https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow

There isn't much we can do easily. 
Less trivial approaches: 
  * get rid of all of STL in libFuzzer
  * privateize the STL in libFuzzer
  * build libFuzzer with the same sanitizer as used for the target (this is what we do in most cases)

**Comment by yugr** [comment]
TBH enabling container sanitization by default is questionable as it effectively breaks separate sanitization (which is much more important in practice). It's default disabled in GCC for that reason (https://gcc.gnu.org/ml/gcc-patches/2017-07/msg00295.html).

**Comment by cheshire** [comment]
@kubamracek Adding Kuba

@yugr I am not sure whether we are talking about the same issue: your email mentions passing `std::vector` from one application part to the other, whereas here the issue happens as linker gets confused and mixes calls to instrumented and uninstrumented parts of `std::vector`.

@kcc 
Apparently, it's possible to circumvent the problem by using `ld -r` to merge the object file and explicitly specifying the symbols which should be exported.
I guess that would come down to "privatize the STL in libFuzzer".

I am not a linker expert, but it seems very surprising that it is so difficult to say "always prefer the symbols from the archive for all calls emanating from the archive", as it seems a natural constraint.

**Comment by cheshire** [comment]
To elaborate on the previous comment: apparently, if we do `ld -r --export-symbols-list <FILE_WITH_ALL_EXPORTED_SYMBOL_NAMES>` on a generated archive, we would get a `.o` file where the visibility of all non-exported symbols was changed to `static`, which would force their usage, preventing collisions such as this one.

Additionally, the problem might not even appear if we were to change libFuzzer from an archive to a shared object/dylib, as the linker rules are different for those (or we can build both, and prefer a dynamic library when linking using `-fsanitize=fuzzer`).

**Comment by yugr** [comment]
> I am not sure whether we are talking about the same issue

Sry, I was answering kcc - false positives that _he_ mentioned are the same.

**Comment by cheshire** [comment]
@kcc FWIW I've solved the issue on Darwin by using `--export-symbols-list`. I'll see whether it can be integrated in CMake nicely.

**Comment by cheshire** [comment]
This _particular_ issue should be fixed with https://reviews.llvm.org/D37086.
Of course, there are many more related issues on instrumented/uninstrumented ODR violation collisions.
