### ISSUE TITLE
ASAN can't  detect  mem leak

### ISSUE THREAD

**Issue by dxm5118118** [google/sanitizers#833]
my thread is not over，it can run on the device，unless the device is abnormal，so ASAN can‘t  detect the mem leak，because thread is not over，what can I do？
Thank You

**Comment by yugr** [comment]
There's a public API to trigger leak checker `__lsan_do_leak_check`. Surprisingly it does not seem to be documented anywhere...

**Comment by dxm5118118** [comment]
@yugr 
when can I trigger leak checker `__lsan_do_leak_check`，thread is over or begin?

**Comment by yugr** [comment]
From what you said before it seems that your app runs for unlimited amount of time. In that case maybe you can call `__lsan_do_leak_check` periodically?

**Comment by morehouse** [comment]
`__lsan_do_leak_check()` seems like the simplest solution.
