### ISSUE TITLE
More debugging opportunities

### ISSUE THREAD

**Issue by marxin** [google/sanitizers#834]
Similar to #31 I would like to introduce sleep_after_init which is a good place to attach gdb to process that can eventually trigger a sanitizer issue. I know one can add sleep to a source base, but debugging complex scenario can be easier with that.

Will it be accepted by community?

**Comment by kcc** [comment]
why can't you start the process under gdb?

**Comment by marxin** [comment]
Sometimes make check is quite complicated stuff where e.g. a server is launched and then set of tests is done against the server.

**Comment by eugenis** [comment]
I think it would be a nice feature. Sometimes starting under gdb is very
hard or even impossible - imagine a program that needs to inherit a pipe
from some long running process for correct operation.

This option should also apply during asan activation to be useful on
Android.

**Comment by marxin** [comment]
I've just done a review request:
https://reviews.llvm.org/D35409

**Comment by marxin** [comment]
Done.
