### ISSUE TITLE
[libFuzzer] treat exit() as a failure

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#835]
When executing LLVMFuzzerTestOneInput libFuzzer should treat exit() as a failure and report it. 
(under a flag, true by default). 

Please add a flag, a test, and implement it (probably via atexit hook). 
It would be nice to handle _exit this way as well, but it's a bit more involved (no at_exit)

**Comment by morehouse** [comment]
Many of the tests in the libFuzzer suite call exit() inside LLVMFuzzerTestOneInput and would therefore fail after this change.  Should I add a "not" in front of the RUN commands for those tests?

**Comment by kcc** [comment]
yep

**Comment by morehouse** [comment]
Implemented in LLVM r308669.
