### ISSUE TITLE
Asan libs fail to load on Android

### ISSUE THREAD

**Issue by nathpete-msft** [google/sanitizers#845]
I'm currently trying to run an Android app with Asan, but am getting warnings when the libraries are being loaded:

```
08-08 15:54:20.920 3967-3967/? W/linker: could not load library "libclang_rt.asan-i686-android.so" from LD_PRELOAD for "/system/bin/sh-from-zygote"; caused by empty/missing DT_HASH in "libclang_rt.asan-i686-android.so" (built with --hash-style=gnu?)
08-08 15:54:20.920 3967-3967/? W/linker: could not load library "libclang_rt.asan-i686-android.so" from LD_PRELOAD for "/system/bin/app_process32"; caused by empty/missing DT_HASH in "libclang_rt.asan-i686-android.so" (built with --hash-style=gnu?)
08-08 15:54:20.920 3967-3967/? W/linker: could not load library "symlink-to-libclang_rt.asan" from LD_PRELOAD for "/system/bin/app_process32"; caused by empty/missing DT_HASH in "symlink-to-libclang_rt.asan" (built with --hash-style=gnu?)
```

I'm compiling using the latest NDK with `clang`, the `c++_shared` STL, and the following flags:
C/CXX flags: 
```
-Wall -Wextra -Wno-unused-command-line-argument -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-comment -Werror -pthread -fsanitize=address -fno-omit-frame-pointer -funwind-tables -std=c++14 -fexceptions -frtti -g -gdwarf-4 -DANDROID -DDEBUG
```
Link flags:
```
-Wl,--gc-sections -O3 -fsanitize=address -shared-libasan
```

The deploy target is an API19 x86 Android emulator, set up for Asan with these steps:
```
asan_device_setup
adb root
adb shell setenforce 0
adb shell setprop wrap.com.myappname LD_PRELOAD=libclang_rt.asan-i686-android.so
```

If I instead change the prop to use `asanwrapper` via: `adb shell setprop wrap.com.myappname "asanwrapper"`, I get the following:
```
08-08 16:39:14.795 3991-3991/? W/linker: could not load library "symlink-to-libclang_rt.asan" from LD_PRELOAD for "/system/bin/sh"; caused by empty/missing DT_HASH in "symlink-to-libclang_rt.asan" (built with --hash-style=gnu?)
08-08 16:39:14.795 3991-3991/? W/linker: could not load library "symlink-to-libclang_rt.asan" from LD_PRELOAD for "/system/bin/sh-from-zygote"; caused by empty/missing DT_HASH in "symlink-to-libclang_rt.asan" (built with --hash-style=gnu?)
08-08 16:39:14.795 3991-3991/? W/linker: could not load library "symlink-to-libclang_rt.asan" from LD_PRELOAD for "/system/bin/app_process32"; caused by empty/missing DT_HASH in "symlink-to-libclang_rt.asan" (built with --hash-style=gnu?)
08-08 16:39:14.795 3991-3991/? W/linker: could not load library "symlink-to-libclang_rt.asan" from LD_PRELOAD for "/system/bin/app_process32"; caused by empty/missing DT_HASH in "symlink-to-libclang_rt.asan" (built with --hash-style=gnu?)
```

**Comment by eugenis** [comment]
Interesting. ASan runtime library in NDK r15 is indeed built with --hash-style=gnu, which makes it incompatible with Android L and below. Thank you for reporting this! @DanAlbert 

Unrelated comments: 
setprop wrap.com.myappname is unnecessary after asan_device_setup.
-shared-libasan is the default on Android

**Comment by DanAlbert** [comment]
It looks like ASAN got moved to the new AOSP build system at some point (long ago, actually) and the new build system doesn't have logic to not use gnu-hash for old API levels.

Can you confirm that this is broken with other NDK versions as well? It looks to me like it shouldn't work on KitKat beginning with r12, but it's hard to be sure from the git history and I don't have a device available.

**Comment by eugenis** [comment]
r12 and r13 are fine.
r14 and r15 are broken.

r10 has only ELF hash
r12, r13 have both ELF and GNU hashes
r14, r15 have only GNU hash

mips and mips64 are a strange exception - they have only ELF hash in all builds.

**Comment by DanAlbert** [comment]
> r12 and r13 are fine.

Interesting. I could take a closer look, but I don't think it's worth doing since we know what the problem is already. It's probably just that the fairly old CL to move ASAN to soong didn't land in the toolchain branch until the r14 time frame.

> mips and mips64 are a strange exception - they have only ELF hash in all builds.

MIPS doesn't support GNU hash, aiui

**Comment by DanAlbert** [comment]
http://b/64608507 is the soong bug

**Comment by DanAlbert** [comment]
I've refiled this in the NDK since this isn't really an ASAN issue, just an issue in our build. Can probably close this.
