### ISSUE TITLE
ASan detection question

### ISSUE THREAD

**Issue by neox123** [google/sanitizers#846]
Hello,

I will output FPE at build time.

Is there a way to disable ASan?

I want to skip FPE errors and build ASan.

Thanks.

**Comment by kcc** [comment]
You may want to provide more details (examples, command lines, version of the software, etc).
Please reopen once you have those.

**Comment by yugr** [comment]
I think you need to run with `ASAN_OPTIONS=handle_sigfpe=false`. See full list of flags [here](https://github.com/google/sanitizers/wiki/SanitizerCommonFlags) and [here](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags).
