### ISSUE TITLE
how to run asan on android after i have finished build config in Android.mk and have run asan_device_setup into phone

### ISSUE THREAD

**Issue by smartjing** [google/sanitizers#848]
i do not know what to do when i have finished the following in my ndk+JNI project:
1. in Android.mk i hava adding
 LOCAL_CFLAGS    := -fsanitize=address -fno-omit-frame-pointer
 LOCAL_LDFLAGS   := -fsanitize=address
 LOCAL_ARM_MODE := arm
2.then i have ran the asan_device_setup into my phone
3.my apk including .so lib have installed on my phone
4. I write a merrory leak error in my C++ code,

then what will i do for using asan to see my leak log? thank for your help.

**Comment by eugenis** [comment]
Run the application as usual and look in logcat.

**Comment by smartjing** [comment]
now i cannot see memory leak which i write manually。
when my phone not install the libclang.xxxx.so，my apk cannot be installed into my android phone。
when my phone install the libclang.xxx.so，the apk is installed ok。but in the logcat i cannot see the error log。

**Comment by smartjing** [comment]
so how i can set the extra_option in the shell script 'asan_device_setup'? currently i set it nothing

**Comment by eugenis** [comment]
Ah, right, LeakSanitizer is not enabled on Android. Sorry.

https://github.com/google/sanitizers/issues/379
https://github.com/android-ndk/ndk/issues/431

**Comment by smartjing** [comment]
thank you, eugenis.
i hope very much LeakSanitizer can be suppored for Android quickly.

**Comment by kcc** [comment]
dup of #379
