### ISSUE TITLE
asan shared libraries question

### ISSUE THREAD

**Issue by memojedi** [google/sanitizers#850]
I've currently followed all the instructions and I'm able to see asan msgs on logCat, for example:

=================================================================
==24389==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x2e519a60 at pc 0xb6a79d94 bp 0x475e0bb8 sp 0x475e0788
READ of size 56 at 0x2e519a60 thread T11095 (pool-6-thread-1)

My current project consists of 5 shared libraries, but only one of them was built with the flags:

LOCAL_CFLAGS    := -fsanitize=address -fno-omit-frame-pointer
LOCAL_LDFLAGS   := -fsanitize=address
LOCAL_ARM_MODE := arm

do I have to build the other four with the same flags?

**Comment by eugenis** [comment]
You don't have to, but the more you build with ASan, the more bugs you'll
find.

Also, there is one known case where not building everything can produce
false reports:
https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives
.

**Comment by morehouse** [comment]
No further responses, closing.
