### ISSUE TITLE
fatal error of asan when executable has no issues

### ISSUE THREAD

**Issue by hadibeere** [google/sanitizers#857]
Since using gcc 7.1.1/clang 4.0.1 ASAN sometimes exits with the following error:

```
==12203==LeakSanitizer has encountered a fatal error.
==12203==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==12203==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

The error occurs always when the executable is run within gdb (8) and sometimes if just started on command line.

```
#include <vector>
#include <iostream>

int main () {
	return (0);
}
```

The above snippet always fails with the described error (tested on 2 systems with same gcc/gdb version).
Where as the following will produce the expected ASAN behaviour:

```
#include <vector>
#include <iostream>

int main () {
	std::vector<int> short_vec{1,2};
	for (size_t i=0; i<=short_vec.size();++i) {
		std::cout<<short_vec[i]<<std::endl;
	}
	return (0);
}
```

For more complex programs the error appears sporadically.

**Comment by kcc** [comment]
As the warning message tells you, LeakSanitizer does not work with gdb. 
When running it under gdb you may disable it using `ASAN_OPTIONS=detect_leaks=0`

(feel free to reopen if you have more questions)

**Comment by kcc** [comment]
> For more complex programs the error appears sporadically.

For this we will need more info.

**Comment by fencekicker** [comment]
Hi,

Sorry for commenting on a closed bug, hope that won't seem antisocial - that's not the intention. I have 2 questions here:

- this worked fine in Ubuntu 16.04 (gcc 5.4 and gdb 7.11.1 I think). What changed? As a developer, I realize some features are brittle and can't be supported, but when something worked in the past and is not working anymore, at least an explanation would be nice
- I guess the program crashing right after the lsan error message is not expected? That's what I'm getting with my project executable.

In the past, my workflow was to build with -fsanitize=address and -O0 -g, run the program with gdb through script, so I could save the whole session, and then I'd also get the leak report at the end as a bonus. Now I guess I need to choose whether I want to debug or check for leaks.

**Comment by Lekensteyn** [comment]
If I may make any guess, I suspect it has something to do with improved signal handling.
https://github.com/llvm-mirror/compiler-rt/commit/c6bb9a490b0ac8e0357df9868f49f043eda48536

**Comment by kcc** [comment]
>> hat won't seem antisocial 
no worries. 

Yea, I am afraid this is the case of a "brittle" feature. 
It might have seemed to work, but it was leading to very weird failures.

**Comment by flaphoschi** [comment]
Shouldn't the documentation changed therefore?
https://github.com/google/sanitizers/wiki/AddressSanitizerAndDebugger

> You can use gdb with binaries built by AddressSanitizer in a usual way...
