### ISSUE TITLE
ASAN backtrace too short for allocate and free when detecting UAF bug.

### ISSUE THREAD

**Issue by sleicasper** [google/sanitizers#860]

**Comment by mrichtarsky** [comment]
Make sure you are compiling with -fno-omit-frame-pointer.

**Comment by sleicasper** [comment]
Thanks :)

**Comment by sleicasper** [comment]
No, it doesn't work...

**Comment by chefmax** [comment]
Please provide more info. What system do you have (OS, target platform, compilation flags, run command etc)

**Comment by sleicasper** [comment]
Ubuntu16.04.1 

this is from .mozconfig when building firefox

export CFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC -mllvm -asan-stack=0 -g -Wl,--no-keep-memory -fno-omit-frame-pointer"
export CXXFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC -mllvm -asan-stack=0 -g -Wl,--no-keep-memory -fno-omit-frame-pointer"
export LDFLAGS="-fsanitize=address -g -Wl,--no-keep-memory -fno-omit-frame-pointer"

**Comment by morehouse** [comment]
Closing.  @sleicasper, please provide a repro if issue still exists.
