### ISSUE TITLE
Use-after-dtor emits superfluous shadow updates for __sanitizer_dtor_callback

### ISSUE THREAD

**Issue by morehouse** [google/sanitizers#861]
Because use-after-dtor instrumentation is emitted in clang CodeGen rather than the LLVM MemorySanitizer pass, calls to `__sanitizer_dtor_callback` are instrumented with stores to `__msan_param_tls` to mark the arguments as initialized.  But `__sanitizer_dtor_callback` never actually checks the shadow in `__msan_param_tls`, so the stores are unnecessary.

**Comment by morehouse** [comment]
@eugenis What was the original reason for emitting the instrumentation in clang CodeGen?  It looks like the easiest solution would be check for `__sanitizer_dtor_callback` in MemorySanitizer.cpp and not emit the stores.  However, the cleaner solution might be to move the instrumentation to MemorySanitizer.cpp.

**Comment by kcc** [comment]
My guess: 
* make clang emit no-sanitize metadata on the call sites 
* make msan honor this metadata

**Comment by eugenis** [comment]
MemorySanitizer.cpp has no idea what a destructor is, especially as it runs after inlining. Default destructors often do not emit any code at all, but we want to make corresponding parts of the objects inaccessible.

Let's do what kcc@ says.

**Comment by morehouse** [comment]
Fixed in r313831.
