### ISSUE TITLE
is there any other sanitizer tools except address sanitizer can be  integrated into android apk ?

### ISSUE THREAD

**Issue by newjorchen** [google/sanitizers#862]
hi all, I want to integrate sanitizer tools into android apk to check native code. Currently i can run the app that intergrated ASAN on android Oreo phone. But, for other sanitizer tools, such as USAN or TSAN..., I can not catch any any crached info that trapped by sanitizer. Besides, the info about android sanitizer are varied. So could you pls. tell me is there any other sanitizer tools supported on android? and how to integrate them? Thx!

BRs,
newjor

**Comment by eugenis** [comment]
I've replied in https://github.com/android-ndk/ndk/issues/527
