### ISSUE TITLE
any suggestion on msvcr100.dll interception support ?

### ISSUE THREAD

**Issue by comicfans** [google/sanitizers#864]
I've found that interception_win.cc line 835:

"msvcr110.dll"  //VS2012
"msvcr120.dll" //VS2013

interception is supported by  commit 916b81 3 years ago ,
currently I'm build project with msvc100 , application will crash in un-intercepted free. adding msvcr100.dll to this list make it runs without problems (yet),  currently compiler rt itself can't built with vs2010,  if I want to support msvcr100.dll interception , how should I test it can pass the tests ? or any comments on the differences between msvcr100 / msvcr110  ?

**Comment by rnk** [comment]
I went ahead and added the DLL to the list in r316929. I'm taking your word that it works, though. :)
