### ISSUE TITLE
Static linking on GCC 7.2.0

### ISSUE THREAD

**Issue by elfarouk** [google/sanitizers#871]
Hello, 

Is the separated static compilation supported on GCC 7.2.0 + CentOS7 ? 

To activate ASAN i use use some things like that on my configure.ac : 
CFLAGS="$CFLAGS -static-libasan -fsanitize=address" 
LDFLAGS="$LDFLAGS -Wl,--no-undefined -static-libasan -fsanitize=address"

But i get this error every where i execute binaries
"Your application is linked against incompatible ASan runtimes."

What means this error? Is the ASAN runtime started by GCC or early ?
Thanks a lot

**Comment by yugr** [comment]
It should be supported but is second-class in GCC (contrary to Clang, where dynamic runtime is second class). Could you provide details about the application you try to sanitize? E.g. do you sanitize main executable or shared library?

**Comment by elfarouk** [comment]
Yes, my application uses severals shared libraries (which are compiled and constructed with other GCC 4.8). 

Is is possible to have more control on ASAN runtime or more info ? which runtime is executed on the system right now ?

**Comment by yugr** [comment]
> Yes, my application uses severals shared libraries (which are compiled and constructed with other GCC 4.8).

So sanitized executable is compiled with GCC 7.2 and sanitized libraries with GCC 4.8? I'm afraid this isn't going to work, you can't have several different versions of Asan runtime in the same process (they are binary incompatible so would crash at runtime).

**Comment by elfarouk** [comment]
Ok of course, is see. What if libraries are not compiled with ASAN, only the application it is ? I guess no interaction between ASAN and libraries ?

**Comment by yugr** [comment]
> What if libraries are not compiled with ASAN, only the application it is ?
> I guess no interaction between ASAN and libraries ?

Exactly, if there's a bug in library code it won't be detected.

**Comment by morehouse** [comment]
Seems resolved.
