### ISSUE TITLE
clang does not to link C++ part of Asan runtime

### ISSUE THREAD

**Issue by cupper** [google/sanitizers#872]
Example of code
```
#include <iostream>
int main() {
    std::cout << "Started Program\n";
    int* i = new int(); 
    *i = 42;
    std::cout << "Expected i: " << *i << std::endl;
}
```
Build with clang++3-8:
`clang++-3.8 -o memory-leak++ memory_leak.cpp -fsanitize=address -fno-omit-frame-pointer -g`
Output:
```
tarted Program
Expected i: 42

=================================================================
==14891==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4f2040 in operator new(unsigned long) (memory-leak+++0x4f2040)
    #1 0x4f4f00 in main memory_leak.cpp:4:11
    #2 0x7fae13ce6f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

Build with clang-3.8
`clang-3.8 -o memory-leak memory_leak.cpp -std=c++11 -fsanitize=address -fno-omit-frame-pointer -g -lstdc++`

Output:
```
Started Program
Expected i: 42

=================================================================
==14922==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4c3bc8 in malloc (memory-leak+0x4c3bc8)
    #1 0x7f024a8e4dac in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x5edac)
    #2 0x7f0249998f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

Verbose clang's output shows that clang++ linked against this library:
`-whole-archive,/usr/lib/llvm-3.8/lib/clang/3.8.0/lib/linux/libclang_rt.asan_cxx-x86_64.a -no-whole-archive`

when original clang doesn't do that.

Current workaround: `-fsanitize-link-c++-runtime`

Original discussion: https://stackoverflow.com/questions/46836809/clang-and-clang-with-asan-generate-different-output/46844114#46844114

Someone has mentioned that it's already fixed in clang-5.0. The bug is reproduced for at least clang-3.8 and clang-4.0.

**Comment by eugenis** [comment]
I don't see it as a bug. Clang (without ++) does not link libstdc++, too.
If you link C++ code in C mode, you have to provide your own C++ runtime
libraries.

**Comment by kcc** [comment]
Yep. use clang++
