### ISSUE TITLE
Unsupported argument 'fuzzer' to option 'fsanitize='

### ISSUE THREAD

**Issue by niteshnarayanlal** [google/sanitizers#873]
Hi,

I am using the fuzzer option with clang 4.0.1 but every time it says unsupported option. I am using //github.com/llvm-mirror/compiler-rt to build libFuzzer.a.
Error message:
clang-4.0: error: unsupported argument 'fuzzer' to option 'fsanitize='
It may be possible that the option is changed as I was not able to find the fuzzer keyword in the released notes for version 4.0.1.
I am not sure what's the issue here.
Command:Downloads/clang+llvm-4.0.1-x86_64-linux-gnu-Fedora-25/bin/clang -fsanitize=fuzzer,address test.c
I also tried passing it libFuzzer.a but nothing changed.

**Comment by kcc** [comment]
-fsanitize=fuzzer is a recent flag, present only in 6.0 (trunk). 
Please try a freshly built clang

**Comment by niteshnarayanlal** [comment]
Hey Hi,
Thanks for the quick response. So is it not possible to use fuzzer option with the prior versions?

**Comment by morehouse** [comment]
`-fsanitize=fuzzer` only works with a recent clang.  With an older clang you have to manually specify the coverage instrumentation you want to use.  See http://releases.llvm.org/3.8.0/docs/LibFuzzer.html.

**Comment by niteshnarayanlal** [comment]
Thanks :)

**Comment by niteshnarayanlal** [comment]
Hi, 
A quick quesiton:
I have a simple program which actually does nothing but I wanted to try fuzzer-no-link 
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
extern int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size)
{
        return 0;
}

void b(char *a)
{
        printf("\nfuzzed:%s\n", a);
}
void testing()
{
        char a[20];
        printf("\nenter a input\n");
        scanf("%s", a);
        LLVMFuzzerTestOneInput(a, sizeof(a));
        b(a);
}
This is working just fine if I don't have a main() (fuzzing is getting initiated).
But as I add a main() to this and use fuzzer-no-link it gets compiled just fine but fuzzing doesn't initiate when I run the program. 
Commands:
llvm-build/Release+Asserts/bin/clang -fsanitize=fuzzer,address main.c ./libFuzzer.a -o main.out
llvm-build/Release+Asserts/bin/clang -fsanitize=fuzzer-no-link ,address main.c ./libFuzzer.a -o main.out

**Comment by kcc** [comment]
> But as I add a main() 

I'm not sure what you want to achieve. libFuzzer provides its own main. If you provide your main, lbiFuzzer is not in charge any more.

**Comment by niteshnarayanlal** [comment]
I was reading this information provided on https://llvm.org/docs/LibFuzzer.html.
This will perform the necessary instrumentation, as well as linking in libFuzzer library. Note that linking in libFuzzer defines the main symbol. If modifying CFLAGS of a large project, which also compiles executables requiring their own main symbol, it may be desirable to request just the instrumentation without linking:

clang -fsanitize=fuzzer-no-link mytarget.c

I thought it is possible to use fuzzer-no-link if a project already has its main.
I am just trying to figure how exactly I can use the fuzzer option if the project with which I am using this already has a main.

Thanks
Nitesh

**Comment by kcc** [comment]
libFuzzer is not suitable for fuzzing something that has its own main. 
You need to turn the code into a library (without main) and then follow the libFuzzer documentation.

**Comment by niteshnarayanlal** [comment]
I see, thanks :+1:
