### ISSUE TITLE
Getting stacktraces of all threads on failures

### ISSUE THREAD

**Issue by bilboed** [google/sanitizers#881]
Hi all,

  When debugging multi-threaded apps/libraries, it would be great to be able to get the stacktraces of all threads present when a failure arises.

  Right now we only get:
  * The stacktrace of the thread that caused the failure
  * (optionally) The stacktrace of where some allocation occured
  * Teh stacktrace of *where* all threads were created

  The rationale is that it gives more context on what other threads were doing, and therefore help pinpoint what caused the failure.

**Comment by kcc** [comment]
You can get this today, manually, with gdb: just run the program under gdb (https://github.com/google/sanitizers/wiki/AddressSanitizerAndDebugger) then when the report happens and gdb stops, type `thread apply all bt` or some such. 

We could do this in asan with StopTheWorld (the one used by lsan) 
and then printing all stack traces. But that's some work, and given that there is a simple solution with gdb, probably not a high priority.

**Comment by morehouse** [comment]
@kcc:  Will we ever implement this?

**Comment by kcc** [comment]
no plans
