### ISSUE TITLE
LSAN_OPTIONS=log_path=xxx is ignored

### ISSUE THREAD

**Issue by llunak** [google/sanitizers#886]
Using LSAN_OPTIONS=log_path=xxx is ignored when code is compiled with -fsanitize=leak. This is because the code for liblsan lacks the call to __sanitizer_set_report_path() and needs something like below. This is broken both in Clang and Gcc.

Is it sufficient to report this here both both Clang and Gcc, or should I report this elsewhere?

--- compiler-rt-5.0.0.src/lib/lsan/lsan.cc.sav	2017-04-11 22:05:02.000000000 +0200
+++ compiler-rt-5.0.0.src/lib/lsan/lsan.cc	2017-11-25 11:12:04.915580893 +0100
@@ -63,6 +63,8 @@ static void InitializeFlags() {
   if (Verbosity()) ReportUnrecognizedFlags();
 
   if (common_flags()->help) parser.PrintFlagDescriptions();
+
+  __sanitizer_set_report_path(common_flags()->log_path);
 }
 
 extern "C" void __lsan_init() {

**Comment by kcc** [comment]
Feel free to send a patch (with a test) via https://reviews.llvm.org

**Comment by morehouse** [comment]
@alekseyshl:  Any progress?

**Comment by alekseyshl** [comment]
No, I haven't got to work on this issue

**Comment by sciencemanx** [comment]
Is anyone going to work on this? What do you estimate the extent of work involved would be?

**Comment by sciencemanx** [comment]
Actually this appears to be fixed as of https://reviews.llvm.org/rL323083. I recommend closing this issue.
