### ISSUE TITLE
"allocator is terminating the process instead of returning 0" does not provide enough info

### ISSUE THREAD

**Issue by eugenis** [google/sanitizers#887]
This error can have multiple reasons, we should expose them to the users.
 * malloc argument too large
 * calloc overflow
 * memalign alignment not power of 2
and that is just in asan.

Also, exiting with CHECK(0) makes it look like an internal issue in the sanitizer.

**Comment by morehouse** [comment]
I believe this was fixed in https://reviews.llvm.org/D44404.
