### ISSUE TITLE
detect_container_overflow=0 not working

### ISSUE THREAD

**Issue by greensky01** [google/sanitizers#888]
Previously this runtime flag worked well for me, but suddenly it's not working anymore. I am sorry I cannot provide any more info because I really have no idea about this at all. 

I suspect it might be 
- clang version. Mine is clang-900.0.38, comes with Xcode 9.1
- Env variable collision. Just guess, I do not know which one

Any hint?

**Comment by kcc** [comment]
Please provide a reproducer. 
What happens if you compile and run https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow ?

**Comment by greensky01** [comment]
I've tried a lot and it seems like a bug of Xcode. I start up Xcode from terminal, but it cannot get the ASAN_OPTIONS variable. If I edit project's scheme Arguments tab and set ASAN_OPTIONS=detect_container_overflow=0 inside, then Asan would stop report container overflow issue.

**Comment by kcc** [comment]
Closing then. Let us know if there is anything else actionable on our side.
