### ISSUE TITLE
On Windows with Visual Studio 2017 I cant enable the following sanitizers.

### ISSUE THREAD

**Issue by AraHaan** [google/sanitizers#895]
```
1>clang.exe : error : unsupported option '-fsanitize=safe-stack' for target 'i686-pc-windows-msvc'
1>clang.exe : error : unsupported option '-fsanitize=dataflow' for target 'i686-pc-windows-msvc'
1>clang.exe : error : unsupported option '-fsanitize=memory' for target 'i686-pc-windows-msvc'
1>clang.exe : error : unsupported option '-fsanitize=thread' for target 'i686-pc-windows-msvc'
```
This is with the system installed clang 5.0.0 binaries. I would like to system install the latest master commits of clang but it seems an little difficult.

I want these options so I can have an better check than old dummy valgrind being an annoying pest itself. And being only debug only (I dont have an debug configuration and plan to not have one anytime soon either).

Also the clang documentations says I can use those options and does not do an warning about them not being available on Windows.

I am trying to make clang only compile in 32 bit mode on my 64 bit system.

**Comment by kcc** [comment]
I don't think we have any of these on windows. @rnk

**Comment by rnk** [comment]
Nope, none of these are supported on Windows. The sanitizer wiki has information on this for MSan and TSan, but it could use updating. SafeStack is documented to work on Linux, FreeBSD, and MacOS. The ASan OS/Arch support grid is missing Windows completely, that could use a fix. DFSan I couldn't speak for.

**Comment by AraHaan** [comment]
😕 Why cant they be implemented on Windows? is it hard to do or nearly impossible? I hate valgrind because of the debug build limitation on it.

**Comment by kcc** [comment]
for asan/dfsan -- nearly impossible w/o help from Microsoft (they will need to provide instrumented runtimes)

for tsan/safe-stack -- just quite a bit of work

>  all inclusive -fsanitize=all

I wish we could, but we currently consider this impossible
