### ISSUE TITLE
BUG: -fsanitize=address on Mac - can not see locals in debugger

### ISSUE THREAD

**Issue by Natris** [google/sanitizers#896]
Hello,
I am not sure whether this is the correct place but I was not able to find a better one. I have found out that when using sanitizer, in some cases I can not see local variables in debugger. Tested on Mac with Apple LLVM version 9.0.0 (clang-900.0.39.2) and lldb-900.0.64 but I had this problem for a while with older xcode and also with lldb in CLion.

The issue only occurs when there are multiple variables on the stack; in the example below if only 'whatever' string is there, the debugger works fine:
```
#include <string>
#include <stdio.h>
#include <vector>

void fill(std::string & s)
{
    s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}

int main(void)
{
    std::string a,b,c,d,q,w,e,r,t,y,u,i,o,p;
    std::string whatever;
    fill(whatever);
    printf("%s", whatever.c_str());
    return 0;
}
```
run clang++ -g  -fsanitize=address test.cc
lldb a.out
b main
r
n until at printf
p whatever - this will display garbage.
```
(lldb) n
Process 69462 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step over
    frame #0: 0x00000001000021d9 a.out`main at test.cc:15
   12  	    std::string a,b,c,d,q,w,e,r,t,y,u,i,o,p;
   13  	    std::string whatever;
   14  	    fill(whatever);
-> 15  	    printf("%s", whatever.c_str());
   16  	    return 0;
   17  	}
Target 0: (a.out) stopped.
(lldb) p whatever
(std::__1::string) $0 = "���\x7f\0\0\x80���\x7f\0\0@���\x7f\0\0\0pA���\x7f\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10@���\x7f\0\0\0ar, std�����\x7f\0\0\x0far_trai\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
(lldb)
```

Without -fsanitize=address the debugger works fine.

Please note that there is quite a lot of stuff broken when sanitizer is used, eg.:
```
(lldb) fr v
(std::__1::string) a = ""
(std::__1::string) b = ""
(std::__1::string) c = ""
(std::__1::string) d = ""
(std::__1::string) q = "���\x7f\0\0 ���\x7f\0\0 ���\x7f\0\0\0\0\0\0\0\0\0\0\0"
(std::__1::string) w = "���\x7f\0\0@���\x7f\0\0 ���\x7f\0\0 ���\x7f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
(std::__1::string) e = "���\x7f\0\0\x80���\x7f\0\0@���\x7f\0\0 ���\x7f\0\0 ���\x7f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0@���\x7f\0\0@���\x7f\0\0@"
(std::__1::string) r = ""
(std::__1::string) t = "���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@"
(std::__1::string) y = "���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@���\x7f\0\0 ���\x7f\0\0 ���\x7f\0\0\0"
(std::__1::string) u = "���\x7f\0\0\x80���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@���\x7f\0\0 ���\x7f\0\0 ���\x7f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
(std::__1::string) i = ""
(std::__1::string) o = "���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@"
(std::__1::string) p = "���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80"
(std::__1::string) whatever = "���\x7f\0\0\x80���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@���\x7f\0\0\0���\x7f\0\0����\0\0\x80���\x7f\0\0@���\x7f\0\0 ���\x7f\0\0 "
(lldb) p **(string**)&whatever
(std::__1::string) $6 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
(lldb) fr v
(const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > *) this = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
(lldb) p whatever
error: use of undeclared identifier 'whatever'
```
This is extremly annoying as address sanitizer is a great tool and you usually want to run it in debug configuration!
Kind regards,
Ondrej Kolacek

**Comment by kcc** [comment]
On Linux with fresh clang I get reasonable output (with gdb). 
```
(gdb) 
15	    printf("%s", whatever.c_str());
(gdb) p whatever
$1 = 'a' <repeats 90 times>
(gdb) 
```

So, either the Xcode's clang is much older and does not have some fixes (although I am not sure if we've fixed anything related to debug info in the last year), or this is Mac-specific (will need to summon Apple folks). 

>> address sanitizer is a great tool and you usually want to run it with debug configuration!

We hear this periodically from our users, which is why we try to keep the debug info with ASAN usable. 
But we never truly understood why one needs a debugger when running with ASAN. 
What's your use case?

**Comment by Natris** [comment]
kcc: It is probable that it is a mac specific issue; I would expect this to be long known and fixed otherwise.
Regarding debugger/asan: it is common to have a debug and a release configurations; the debug configuration is used for development and initial basic testing of changes by the developers. And this is also often the phase where issues show up and debugger is a good way to diagnose stuff, especially in legacy parts without sufficient logging. Our release configuration does not include address sanitizer as we can not afford to test everything twice - once with and once without. Poor man's choice.

**Comment by eugenis** [comment]
How old is your clang?
http://llvm.org/viewvc/llvm-project?rev=320415&view=rev (very recent) is
supposed to fix some things around debug info for local variables.

**Comment by morehouse** [comment]
No response in 6 months.  Please comment if issue persists.
