### ISSUE TITLE
Memory leak reported when compiling with address sanitizer

### ISSUE THREAD

**Issue by singku** [google/sanitizers#904]
I have a program with my own memory manager.
This manager will report memory leak status in the end when program ends.
While this manager will report there is no leak when program is compiled without -fsanitize=address.
But will report leak when compiled with -fsanitize=address, together with sanitizer's report.
Sanitizer's report shows that the leaked memory was malloced through my own memory manager, which will call interceptor_malloc from Address Sanitizer.
And that happened with a std::map assignment.

Since my own memory manager report and the same time with Address Sanitizer. It means this memory manager can correctly track memory allocation. Then when I compile the program without Address Sanitizer, it should also track memory correctly, means, If it reports no leak then there is no leak in my program. 

I am not sure if Address sanitizer will malloc some memory inside interceptor_malloc call and forget to free.

**Comment by kcc** [comment]
I am not sure how we can help you here w/o a reproducer. 
Please provide a minimized test case -- only then we'll be able to assist.
