### ISSUE TITLE
add breakpoint at free, when using debugger

### ISSUE THREAD

**Issue by sleicasper** [google/sanitizers#905]
add a condition at |free| function. 
some code like below, g_breakaddr can be modified in debuggers. so debugger can pause at specific address when calling |free|.

void *g_breakaddr = 0;
int free(void *addr)
{
  if( g_breakaddr && g_breakaddr == addr ){
    //send int 3 signal, so debugger would pause
  }
 ......
}

**Comment by kcc** [comment]
I'm pretty sure you can do it with gdb now: https://sourceware.org/gdb/onlinedocs/gdb/Conditions.html
