### ISSUE TITLE
Allow object annotations to prevent use-after-dtor poisoning.

### ISSUE THREAD

**Issue by morehouse** [google/sanitizers#910]
Some types are designed for safe use after destruction when instantiated as globals.  We normally blacklist their destructors to prevent use-after-dtor poisoning, but this isn't safe when an instance is not a global.

For these cases, it would be helpful if we could annotate the object definition to not poison the object in its destructor.

**Comment by eugenis** [comment]
By not safe, do you mean false-negative, i.e. you want to catch use-after-dtor for stack and heap instances of such types, but not for global instances?

This could be done by instrumenting their destructors with a different use-after-dtor callback which would check a thread-local flag set in the __cxa_atexit() interceptor, but that may catch some unrelated objects, too.

Another option is to emit a special variant of the destructor to use for global instances.

Both options look like a terrible mess.

**Comment by morehouse** [comment]
> By not safe, do you mean false-negative, i.e. you want to catch use-after-dtor for stack and heap instances of such types, but not for global instances?

Yes, this was requested by ahh@google.com to address an internal use-after-dtor.  He wanted to be able to mark an object as "do not poison" rather than blacklisting destructors for the whole type.

**Comment by morehouse** [comment]
After today's discussion, closing this as infeasible.
