### ISSUE TITLE
MSAN Suppressing Reports in External Libraries

### ISSUE THREAD

**Issue by akddv** [google/sanitizers#915]
I am running the Memory Sanitizer on a small binary using an external library. I cannot modify or recompile the code of the library. I am getting an error report which looks like the following:

> Uninitialized bytes in __interceptor_memcmp at offset 0 inside [0x7020000004a0, 4)
> ==14299==WARNING: MemorySanitizer: use-of-uninitialized-value
>     #0 0x7f64e669795c  (/lib64/libextern.so+0x1395c)
> ...

Being part of a test suite which runs automatically I would like to be able to suppress this specific report.
What is the best way of doing so?

Thanks.

**Comment by kcc** [comment]
msan does not support mixing instrumented and non-instrumented code, sorry. 
See https://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code
