### ISSUE TITLE
Detect if ptrace not available and gracefully disable LeakSanitizer

### ISSUE THREAD

**Issue by ezyang** [google/sanitizers#916]
If I understand correctly, the following situation:

```
jenkins@ff742997f986:~$ echo "int main() { return 0; }" > test.c
jenkins@ff742997f986:~$ clang-5.0 -fsanitize=address test.c
jenkins@ff742997f986:~$ ./a.out 
==4821==LeakSanitizer has encountered a fatal error.
==4821==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==4821==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

occurs whenever you don't have ptrace rights, e.g., if ptrace is disabled or you're working inside a Docker image. It would be much better if LeakSanitizer could detect if this is the trace, and turn itself off automatically (maybe with a warning.) Or, if not that, mention this as another possible explanation. Or also suggest how to turn off LeakSanitizer manually with ASAN_OPTIONS.

**Comment by kcc** [comment]
> if ptrace is disabled or you're working inside a Docker image. 

yes

> It would be much better if LeakSanitizer could detect if this is the trace, and turn itself off automatically (maybe with a warning.) 

That's counter productive, imho

> Or, if not that, mention this as another possible explanation. 


This is somewhat reasonable. But such change won't affect users of older versions. 
Mieanwhile, it is also very easy to find solutions in the internet. 
For docker, the solution is to use `--cap-add SYS_PTRACE`

> Or also suggest how to turn off LeakSanitizer manually with ASAN_OPTIONS.
This is part of the documentation. 
https://clang.llvm.org/docs/AddressSanitizer.html#memory-leak-detection

**Comment by arc4313** [comment]
Can this be disabled in compile-time? For the case when we can't affect program env while perform tests.

**Comment by martinvonwittich** [comment]
> Can this be disabled in compile-time? For the case when we can't affect program env while perform tests.

I am looking for the same thing, but for a different reason. I'm trying to track down a PHP-FPM "zend_mm_heap corrupted" error that occurs rarely on our production servers. Unfortunately PHP seems to leak memory be default:

<details>

```
martin.mein-iserv.de ~ # php -r 'echo "hello";'          
hello
=================================================================
==821199==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4800 byte(s) in 1 object(s) allocated from:
    #0 0x5605def651d7 in __interceptor_calloc (/usr/bin/php8.2+0x3cf1d7)
    #1 0x7ff724e3d1f7  (<unknown module>)

Direct leak of 144 byte(s) in 6 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff72a06ca4d  (<unknown module>)
    #2 0xc4e7822dfa4f43ff  (<unknown module>)

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff73039a045 in gaih_inet ../sysdeps/posix/getaddrinfo.c:1058
    #2 0x7ff73039b7a4 in __GI_getaddrinfo ../sysdeps/posix/getaddrinfo.c:2256
    #3 0x5605def40029  (/usr/bin/php8.2+0x3aa029)
    #4 0x7ff72808bb74  (<unknown module>)
    #5 0x7ff72808e025  (<unknown module>)
    #6 0x7ff72808e162  (<unknown module>)
    #7 0x7ff72808e19b  (<unknown module>)
    #8 0x7ff7280a4f96  (<unknown module>)
    #9 0x7ff7281a46b7  (<unknown module>)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff72808954b  (<unknown module>)
    #2 0x7ff72808bc89  (<unknown module>)
    #3 0x7ff72808e025  (<unknown module>)
    #4 0x7ff72808e162  (<unknown module>)
    #5 0x7ff72808e19b  (<unknown module>)
    #6 0x7ff7280a4f96  (<unknown module>)
    #7 0x7ff7281a46b7  (<unknown module>)

Direct leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff72808954b  (<unknown module>)
    #2 0x7ff7280a54df  (<unknown module>)
    #3 0x7ff72808e16a  (<unknown module>)
    #4 0x7ff72808e19b  (<unknown module>)
    #5 0x7ff7280a4f96  (<unknown module>)
    #6 0x7ff7281a46b7  (<unknown module>)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff7282bf0f8  (<unknown module>)

Indirect leak of 48 byte(s) in 6 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff72a06ca4d  (<unknown module>)
    #2 0xc4e7822dfa4f43ff  (<unknown module>)

Indirect leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x5605def6502f in __interceptor_malloc (/usr/bin/php8.2+0x3cf02f)
    #1 0x7ff730340bba in __GI___strdup string/strdup.c:42

SUMMARY: AddressSanitizer: 5166 byte(s) leaked in 18 allocation(s).
```
</details>

We use PHP-CLI at a lot of places in our scripts, and now all these commands print leak reports on STDERR, thereby breaking a lot of stuff that expects STDERR to be empty. I am only interested in AddressSanitizer errors, and don't care for these leak reports. I know that I can disable LeakSanitizer at runtime with `ASAN_OPTIONS`, but then I would have to set this variable globally and hope that it reaches any single PHP script that we call, and there are bound to be some places where the environment gets cleared. A compile time option to disable LeakSanitizer therefore seems very useful to me.
