### ISSUE TITLE
Output full backtrace in UAF

### ISSUE THREAD

**Issue by sleicasper** [google/sanitizers#920]
When detect a UAF bug, if there are many functions in stack backtrace, not all functions are displayed, especially in free section.  Thus, output all backtrace.

**Comment by kcc** [comment]
you may use ASAN_OPTIONS=malloc_context_size=128
See https://github.com/google/sanitizers/wiki/SanitizerCommonFlags
If this doesn't help, please reopen with a small reproducer, command line, clang (or gcc) version, OS version, libc version, etc.
