### ISSUE TITLE
whitelisting a memory range

### ISSUE THREAD

**Issue by alveko** [google/sanitizers#927]
I'm looking for possible ways to catch memory bugs in a single-threaded C program. The critical piece of the program operates mainly on heap memory pool with heavy use of tricky pointer type casting and nested interlinked data structures (which are also a part of the same code base).

My goal is to restrict somehow all read/write memory access through pointers to addresses only within the bounds of the dedicated memory pool.
ASan seems to have some properties that can be controlled dynamically at runtime. So I'm hoping it may be possible to extend it to support my use case which would look something like this:

```
    // restrict use of addresses only within the dedicated range
    asan_set_allowed_address_range(mempool->start, mempool->end);
    
    // this will call a bunch of other functions with some
    // use of local stack variables, but no pointers to the stack
    // and no stack read/write using pointer dereferencing
    do_stuff(mempool);
    
    // the below should raise an error _even_if_ the dereferenced
    // address points to normally accessible memory (like another allocated mempool)
    uchar x = *((uchar *)(mempool->start - 100)); // boom!
    
    // allow use of any addresses
    asan_set_allowed_address_range(0, 0);
```

I have little to no knowledge about whether something like this is feasible by extending clang/asan, but willing to invest time into extending it given it is achievable and makes sense.

It's running on Linux x86_64.

ASan poisoning is close but not ideal; it's backlisting of the memory regions as opposed to whitelisting only allowed ones which gives less security/safety confidence and also requires memset-ing lots of shadow memory on frequent allowed range bounds switching.

Ideally, I would like to instrument every memory access through a pointer and ensure the pointer is within the whitelisted address range. This way, it would be possible to still allow some variables on the stack like "int a;" (with exceptions of arrays perhaps), but disallow pointer dereferencing if it points anywhere outside of the whitelisted range. For example:
```
// set whitelisted region on the heap
void foo (char *p) {
    int a = 0; // ok, as a is on the stack
    *p = 1; // ok, if p is within the whitelisted range
    p = &a;
    *p = 2; // boom, pointer access outside of the whitelisted heap region
            // (even if it's on the stack which is a read/write memory page)
}
```

Q1: How much of it is achievable today and with possible extensions to ASan or other sanitizers?
Q2: At the time of instrumentation, can we distinguish memory access via a variable name (like "int a; a = 0;" vs. memory access via pointer dereferencing (like "*p = 0")? 

Thank you in advance!

**Comment by eugenis** [comment]
It may sound crazy, but mprotect()ing parts of the shadow that correspond to the rest of the heap is fast and will crash the program on first access.
Poisoning large regions of memory does not have to be expensive. It is in the current implementation, but with page mapping tricks you could paint a lot of memory with 0xFF (or any other value) cheaply.

**Comment by alveko** [comment]
This approach has multiple downsides:
1) it's harder to reason what to poison and how; the use of this won't be easy in the source as compared to the snipped above where you just specify the range
2) it's still blacklisting as opposed to more secure and easier to reason about whitelisting
3) it doesn't solve issue with variables on stack - if I poison the stack page/region, I won't be able to create/modify any local variables, right?

**Comment by eugenis** [comment]
You probably want to whitelist the entire stack, and globals, too. It can be hard to ensure that a program does not access either. Consider string literals, for example. If you want a pure whitelisting approach - disallowing everything except for explicitly specified memory ranges - you'd need to locate data segments for all shared libraries in the process.

Take a look at ThreadSanitizer instrumentation. It does not do any inline checks, so you could implement your own runtime library and do any checking you want in __tsan_read and __tsan_write. It will be quite a bit slower than ASan, of course.

**Comment by alveko** [comment]
> Take a look at ThreadSanitizer instrumentation. It does not do any inline checks, so you could implement your own runtime library and do any checking you want in __tsan_read and __tsan_write.

This is exactly what I just did. Seems good so far, but I need to understand a couple of details:

1) when exactly the read/write are called? Per memory operation in the origin source code, per memory operation at some intermediate code representation in the compiler, or per memory operation in the resulting assembly code?
For example, a number of such read/write callback invocations differ for the same source code/input depending on the compiler optimization level. Why?

2) is there any case when such callback can be missed? I.e. a memory operation happens, but callback is not invoked?

Given the memory range check is quick in the read/write callbacks, why would it be much slower than Asan? As per my understanding, Asan also has similar load/store interceptors, see [1], (though for some reason I don't see them exposed in the runtime library; why?), which check the shadow memory bits. Is it just because of the shadow bit lookup is much faster than an address range check or something else?

[1] https://github.com/llvm-mirror/compiler-rt/blob/master/lib/asan/asan_interface_internal.h#L190

**Comment by eugenis** [comment]
(1) Intermediate representation. Callbacks are inserted after inlining and most SSA optimizations to reduce overhead.

(2) External function calls. That's what interceptors are for. Also, looking at the source, ThreadSanitizer::chooseInstructionsToInstrument, some instructions can be omitted due to data-race-related reasons.

ASan checks are normally inlined, that's a lot faster than a function call. These callbacks are for special cases, like huge functions where inline instrumentation slows down compilation too much, or linux kernel where early accesses need to be ignored. There are -mllvm flags in AddressSanitizer.cpp that can force-enable the callbacks.

**Comment by alveko** [comment]
> (1) Intermediate representation. Callbacks are inserted after inlining and most SSA optimizations to reduce overhead.

What would be the best resource to get more information on how the instrumentation (inline/callbacks) works, perhaps explaining the internals of clang/llvm?

**Comment by eugenis** [comment]
There is a paper, https://www.usenix.org/system/files/conference/atc12/atc12-final39.pdf
It is quite high level. You can read the source:
http://llvm-cs.pcc.me.uk/lib/Transforms/Instrumentation/AddressSanitizer.cpp
It used to be small and simple, but has grown to >3000 lines.

As for LLVM internals, there are lots of docs at llvm.org/docs, one of the most useful is the IR specification at http://llvm.org/docs/LangRef.html.

Tests under http://llvm-cs.pcc.me.uk/test/Instrumentation/AddressSanitizer show instrumentation of small snippets of IR.

**Comment by kcc** [comment]
Also: https://github.com/google/sanitizers/wiki/AddressSanitizerAlgorithm

**Comment by morehouse** [comment]
Closing this.  @alveko, feel free to continue the discussion.
