### ISSUE TITLE
asan doesn't report error when code has exception catched.

### ISSUE THREAD

**Issue by cyyever** [google/sanitizers#929]
I tried the following code on gcc  7.3.0:

> 

#include<stdexcept>
#include<stdio.h>

int main(int argc, char **argv) {

  try {
    throw std::runtime_error("aa");
  }catch(...) {

  }
  int stack_array[100];
  stack_array[1] = 0;
  return stack_array[argc + 100];  // BOOM
}

> 

and no warning was generated.
But then I removed the try...catch block, then asan generated  a warning of  

> 
==8959==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe2fc942d4 at pc 0x55a9f4509bed bp 0x7ffe2fc94100 sp 0x7ffe2fc940f0
READ of size 4 at 0x7ffe2fc942d4 thread T0
    #0 0x55a9f4509bec in main (/home/cyy/a.out+0xbec)
    #1 0x7fd710984b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #2 0x55a9f45099d9 in _start (/home/cyy/a.out+0x9d9)

Address 0x7ffe2fc942d4 is located in stack of thread T0 at offset 436 in frame
    #0 0x55a9f4509ac9 in main (/home/cyy/a.out+0xac9)

  This frame has 1 object(s):
    [32, 432) 'stack_array' <== Memory access at offset 436 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/cyy/a.out+0xbec) in main
Shadow bytes around the buggy address:
  0x100045f8a800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a820: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
  0x100045f8a830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100045f8a850: 00 00 00 00 00 00 00 00 00 00[f2]f2 00 00 00 00
  0x100045f8a860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100045f8a8a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==8959==ABORTING

>

**Comment by kcc** [comment]
Yes, I'm afraid this is expected. 
When asan sees an exception thrown, it behaves very conservatively and clears the shadow for the entire stack. Otherwise it's very hard to avoid false positives. 

This *is* a problem in asan that we may be able to fix eventually, leaving this report open.

**Comment by cyyever** [comment]
Could Asan provide some option to deal with exceptions,even at the cost of false positives?

**Comment by kcc** [comment]
I can't see an obvious way. 
The problem is that the false positives will become so prevalent that the tool will likely become unusable.

**Comment by eugenis** [comment]
This would be tricky, but we could try instrumenting landing pads.
