### ISSUE TITLE
Moving instrumentation data to memory mapped files

### ISSUE THREAD

**Issue by willemneal** [google/sanitizers#938]
I'm interested in fuzzing multi-process applications with state, particularly server applications.  

For example, I want a client process that delivers the data to the server, waits until it gets a response and then can read the instrumentation data from the server.  Although it is clearly possible to do this from within the same process, the idea is to just wrap around the server application and attach with the client.

From what I've gathered from reading the code, the instrumentation data are global so that inlined writes can reference it at runtime without any indirection.   Is there an easy to move these globals to a memory-mapped location?  If so does indirection become necessary and degrade runtime performance?

**Comment by kcc** [comment]
It's clearly possible, but libFuzzer was not designed for such kind of heavy targets, so YMMV. 
If you want to prototype something like this today, I would suggest you to use the callback-style
instrumentation (https://clang.llvm.org/docs/SanitizerCoverage.html#tracing-pcs-with-guards)
where you would implement the callbacks yourself (shared memory, whatever), 
and then pass the coverage back to libfuzzer (running in a separate process) via e.g. 
the extra counters (see https://github.com/llvm-mirror/compiler-rt/blob/0c8339c8aab25f1156558e9e2082b4b124dc2327/test/fuzzer/TableLookupTest.cpp)

This is not something I'd be very interested in adding directly to libFuzzer today though. 

> it is clearly possible to do this from within the same process

This is much more preferable IMHO.

**Comment by morehouse** [comment]
Initial questions answered, so closing this.  @willemneal, feel free to continue discussion here.
