### ISSUE TITLE
add suffix to report file name

### ISSUE THREAD

**Issue by WallStProg** [google/sanitizers#951]
For those using a GUI, it can be very helpful to have a particular suffix appended to the report file name, so it can be opened with a double-click.

**Comment by WallStProg** [comment]
The attached patch appears to do the trick.  Pls. let me know if there's a better way to submit this -- there are a bunch of different instructions out there, not sure which is preferred, if any.  


[log-suffix.patch.txt](https://github.com/google/sanitizers/files/1977984/log-suffix.patch.txt)

**Comment by kcc** [comment]
Hi. 

We accept patches via https://reviews.llvm.org
Although I doubt I want any extra complexity around log file names. 
I am sure this can be solved outside tsan.

**Comment by WallStProg** [comment]
Your point re: complexity is well-taken, and I've simplified the patch with that in mind.

I've submitted the updated patch to: https://reviews.llvm.org/D46546

I hope you'll consider this -- it's certainly been a big time-saver for me.

Thanks!

**Comment by mrichtarsky** [comment]
Thanks, will allow to remove a similar patch we have internally.
