### ISSUE TITLE
libfuzzer integration with the NetBSD userland

### ISSUE THREAD

**Issue by krytarowski** [google/sanitizers#955]
I'm mentoring (together with @zoulasc) a project for Google Summer of Code that aims to integrate libfuzzer with the NetBSD basesystem.

The general readmap is to:

 - Import compiler-rt into basesystem together with upgraded Clang and LLVM (from 5.x to likely 7svn).
 - Build and install compiler-rt features, basically everything, except rescheduled for later: LSan, ESan, DFSan, HWSan. Right now we ship ASan and UBSan for the GCC-style distribution.
 - Add support for a global switch option like MKSANITIZER (Memory, Thread, MemoryWithOrigins etc) to rebuild the whole userland (with an exception of libc, libpthread, ...) with a dedicated sanitizer option.
 - Integrate libfuzzer with userland programs and perform fuzzing. We have good userland candidates for fuzzing like file(1), as it has been already ported for libfuzzer and used with oss-fuzz.(@zoulasc is the upstream maintainer).

http://wiki.netbsd.org/projects/project/libfuzzer/

https://summerofcode.withgoogle.com/projects/#6417656001855488

Our student is @plusun / @tomsun7 (hmm, it looks like 2 accounts?).

We are in the process of performing the final clean up of the code before importing compiler-rt into src/.

I'm opening this ticket to aggregate our questions for upstream developers in a single place.

CC: people who helped to review the already upstreamed NetBSD code: @kcc @vitalybuka @dvyukov @jsonn @morehouse 

Yes, I know, that the ported compiler-rt code is work in progress, we still keep local patches and there are pending cleanups for the upstream code. Thought, the overall state as of today is decent.

```
check-ubsan:
  Expected Passes    : 229
  Expected Failures  : 1
  Unsupported Tests  : 32
  Unexpected Failures: 2

check-sanitizer:
  Expected Passes    : 576
  Expected Failures  : 13
  Unsupported Tests  : 206
  Unexpected Failures: 31

check-asan:
  Expected Passes    : 852
  Expected Failures  : 4
  Unsupported Tests  : 440
  Unexpected Failures: 16

check-tsan:
  Expected Passes    : 288
  Expected Failures  : 1
  Unsupported Tests  : 84
  Unexpected Failures: 8

check-msan:
  Expected Passes    : 102
  Expected Failures  : 1
  Unsupported Tests  : 30
  Unexpected Failures: 4
```

Last but not the least, formal coding timeline: May 14, 2018 - August 6, 2018

**Comment by krytarowski** [comment]
The current state of `check-fuzzer`:

```
********************
Testing Time: 153.86s
********************
Failing Tests (17):
    LLVMFuzzer :: cxxstring.test
    LLVMFuzzer :: fuzzer-timeout.test
    LLVMFuzzer :: memcmp.test
    LLVMFuzzer :: memcmp64.test
    LLVMFuzzer :: merge-posix.test
    LLVMFuzzer :: recommended-dictionary.test
    LLVMFuzzer :: strcmp.test
    LLVMFuzzer :: strncmp.test
    LLVMFuzzer :: strstr.test
    LLVMFuzzer :: trace-malloc-threaded.test
    LLVMFuzzer :: trace-malloc-unbalanced.test
    LLVMFuzzer :: value-profile-cmp.test
    LLVMFuzzer :: value-profile-load.test
    LLVMFuzzer :: value-profile-mem.test
    LLVMFuzzer :: value-profile-set.test
    LLVMFuzzer :: value-profile-strcmp.test
    LLVMFuzzer :: value-profile-strncmp.test

  Expected Passes    : 90
  Unsupported Tests  : 8
  Unexpected Failures: 17
```

1. I've narrowed down fuzzer-timeout.test to this workaround:

```
diff --git a/lib/fuzzer/FuzzerLoop.cpp b/lib/fuzzer/FuzzerLoop.cpp
index 6cc220d97..a67431c71 100644
--- a/lib/fuzzer/FuzzerLoop.cpp
+++ b/lib/fuzzer/FuzzerLoop.cpp
@@ -274,7 +274,7 @@ NO_SANITIZE_MEMORY
 void Fuzzer::AlarmCallback() {
   assert(Options.UnitTimeoutSec > 0);
   // In Windows Alarm callback is executed by a different thread.
-#if !LIBFUZZER_WINDOWS
+#if !LIBFUZZER_WINDOWS && !LIBFUZZER_NETBSD
   if (!InFuzzingThread())
     return;
 #endif
```

I still don't understand what's going wrong and I'm investigating. I need to determine why Windows needs this switch.

2. The remaining failures seem to share the same reason of failure. It appears that handling SanitizerCoverage isn't fully functional and libfuzzer cannot make sense of it.

I ask for suggestions how to debug it as I don't have enough comprehension of this feature. Please help.

3. We have fixed some local libfuzzer issues and we will keep submitting patches through reviews.llvm.org.

**Comment by kcc** [comment]
1. The windows port of libFuzzer is dead. I don't know much about it. 
2. Let's start a separate bug and discuss there, in order to not pollute this umbrella bug.

**Comment by krytarowski** [comment]
OK, I will submit a new bug and link it here!

**Comment by krytarowski** [comment]
We are down to:

```
********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 56.25s
********************
Failing Tests (2):
    LLVMFuzzer :: merge-posix.test
    LLVMFuzzer :: trace-malloc-threaded.test

  Expected Passes    : 105
  Unsupported Tests  : 8
  Unexpected Failures: 2
```

I will submit a part of local patches to LLVM review.

The failing tests seem to be some environment mismatch... and false positives. If there is interest to check them, I can share output from them in a dedicated bug entry.

For now, I skip them myself. I will keep a local kludge for the timeout patch in `Fuzzer::AlarmCallback()`. I think we are ready for GSoC.

**Comment by krytarowski** [comment]
For the record, we have managed to build a distribution with Clang/LLVM 7svn + compiler-rt. Our plans had to be changed and we use now EXTERNAL_TOOLCHAIN functionality of our build framework (./build.sh).

We have prepared new regression tests in our distribution (ATF - Automatic Test Framework) for: TSan, MSan and libFuzzer (ASan and UBSan were already ready).

We are actively working on MKSANITIZER option, that will allow us to build the whole userland (with not applicable exceptions) with a dedicated sanitizer option. We have got first success of building a subset of it and we have caught real bugs in top(1):

https://github.com/NetBSD/src/commit/524f47bae4ce78a90f2e7b797212757f1da804b8
https://github.com/NetBSD/src/commit/18f2adcb99a25fa61ffa1912a358aebd2fbfe54b

Next milestone is to get a basic MSanitized userland ready to be chroot(8)ed into it. We are struggling now with sh(1) and ls(1) issues.

**Comment by krytarowski** [comment]
http://blog.netbsd.org/tnf/entry/gsoc_2018_reports_integrate_libfuzzer Part 1 done

We are planning now to integrate libfuzzer into a selection of programs, @plusun might have some questions here regarding the strategy how to perform efficiency fuzzing in some of them.

**Comment by krytarowski** [comment]
In general we would prefer to perform fuzzing of programs as they are more interesting than our userland libraries. The libraries could be put into categories that make it not worth fuzzing them.

I've changed few changes with LLVM developers and the proposed approach for programs like sed(1) is:
 - coarse grained: change main() to sed_main(), pass argc/argv and wrap stdin,
 - fine grained: try to detect interesting functions in the codebase like regex handling and insert there libfuzzer functions.

The first approach is catch them all, and the second one should have a good performance.

**Comment by krytarowski** [comment]
Update: We keep researching the usage of libfuzzer and keep integrating it with a selection of programs. We have caught the first real bug in expr(1):
http://netbsd.org/~kamil/libfuzzer/0001-expr-perform_arith_op.txt

Out of the GSoC context, I've successfully booted fully ASanitized userland:
http://netbsd.org/~kamil/mksanitizer-reports/asan-first-login-prompt.png
http://netbsd.org/~kamil/mksanitizer-reports/asan-first-shell-prompt.txt

**Comment by krytarowski** [comment]
Update.

MKSANITIZER report: http://blog.netbsd.org/tnf/entry/mksanitizer_bug_detector_software_integration

We are now comparing userland integration pros and cons of AFL, libFuzzer, radamsa and honggfuzz and checking which one is the best match for our userland programs in what use-cases.

We will follow up with the same process against routines in libraries in coding phase 3.

Personally, I'm joined the NetBSD kernel sanitization department (for start KUBSAN and KASAN).. and we have already managed to catch the first bugs with Undefined Behavior Sanitizer http://netbsd.org/~kamil/kubsan/0002-second-boot.txt

**Comment by kcc** [comment]
Great progress! Thanks for the update, and for the blog post.

**Comment by krytarowski** [comment]
GSoC 2018 Reports: Integrate libFuzzer with the Basesystem, Part 2
http://blog.netbsd.org/tnf/entry/gsoc_2018_reports_integrate_libfuzzer1

**Comment by krytarowski** [comment]
Today finished the coding period and we work on summaries.

Personally, I've finished the Undefined Behavior Sanitizer in the kernel.. so we are heading for kernel fuzzing too.

Introduction to µUBSan - a clean-room reimplementation of the Undefined Behavior Sanitizer runtime
http://blog.netbsd.org/tnf/entry/introduction_to_%C2%B5ubsan_a_clean

**Comment by krytarowski** [comment]
GSoC 2018 Reports: Integrate libFuzzer with the Basesystem, Part 3
http://blog.netbsd.org/tnf/entry/gsoc_2018_reports_integrate_libfuzzer2

GSoC is done, thank you for the support!

There will be a work on the fuzzers and NetBSD quality beyond GSoC, but it was a great start and research!
