### ISSUE TITLE
tsan: support compare_exchange failure ordering

### ISSUE THREAD

**Issue by dvyukov** [google/sanitizers#970]
Tsan wholesale ignores compare_exchange failure ordering. Instrumentation pass now passes it to runtime. We need to respect it and use instead of success ordering on failure. Note: in C++17 failure ordering can be stronger than success ordering.

**Comment by dvyukov** [comment]
FTR another related discussion on the mailing list:
https://groups.google.com/d/msg/thread-sanitizer/bTOVyLAo8p4/Y-2yks6ZLAAJ

**Comment by bcardosolopes** [comment]
I gave this a shot, lemme know if the patch makes sense: https://reviews.llvm.org/D99434

**Comment by bcardosolopes** [comment]
Implemented and landed upstream!

**Comment by dvyukov** [comment]
Thanks!
