### ISSUE TITLE
sancov's "pc-table" + UBSan's "vptr" cause "undefined symbol: typeinfo for %CLASS_NAME%" link error 

### ISSUE THREAD

**Issue by Dor1s** [google/sanitizers#971]
Local reproducer: [typeinfo.zip](https://github.com/google/sanitizers/files/2081059/typeinfo.zip)

This issue is blocking migration to `fsanitize=fuzzer-no-link` in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=764514

Please pay attention to the comments in `build.sh` file to understand what's going on.

I've been able to find a workaround (see comments in `Interface.h`), and uploaded two CLs fixing such issues in Chromium:

1) https://chromium-review.googlesource.com/c/webm/libwebm/+/1089372
2) https://chromium-review.googlesource.com/c/chromium/src/+/1089381

But the second CL doesn't look good to the code owners and they raise a good point, I think. Here is a quote ([link to comment](https://chromium-review.googlesource.com/c/chromium/src/+/1089381#message-8d66855ea3fe6bce9c8aa98a113de50055d39eba)):

> I am not a super fan of this change. Do we understand why the compiler/linker doesn't accept valid c++? The vtable and typeinfo is normally associated with the "key method" (i.e. typically first virtual method implementation, see https://gcc.gnu.org/onlinedocs/gcc/Vague-Linkage.html). Do we understand why that is not happening in this mode?  Could we fix that?
> 
> If not, could we start a thread on cxx@chromium.org to discuss the constraints this imposes and whether the tradeoffs are acceptable? This might limit third_party code and other various constructs we might use in the codebase. It also goes against the style guide (no virtual method implementation in headers)

//cc @kcc @morehouse + @inferno-chromium as FYI

**Comment by Dor1s** [comment]
Btw, it seems like issue is happening only with dead code. I'd guess that without `pc-table` it gets eliminated and thus linked doesn't complain.

**Comment by Dor1s** [comment]
@morehouse Matt, is there any way we can ask you or someone else on your team to take a look into this issue? It's pretty bad as it doesn't let us to enable value profiling on Chromium fuzz targets.

**Comment by Dor1s** [comment]
Maybe Peter @pcc can help / give a hint, as it seems to be a linker issue rather than libFuzzer / sanitizer one.

**Comment by morehouse** [comment]
> Btw, it seems like issue is happening only with dead code. I'd guess that without pc-table it gets eliminated and thus linked doesn't complain.

This sounds like https://bugs.llvm.org/show_bug.cgi?id=34636.  I'll take a look.

**Comment by Dor1s** [comment]
Thanks, Matt! I'll give it a try.
