### ISSUE TITLE
question: my program needs to count malloc() calls from a 3rd-party library

### ISSUE THREAD

**Issue by basinilya** [google/sanitizers#975]
Due to a leak in some versions of the native Oracle driver I need to perform a runtime check and optionally do some additional cleanup. The leak only occurs when the allocated structure has an extra field. The driver's allocation function calls malloc() internally.

When I call the driver's allocate function I need to know whether malloc() was called with sz=96 or sz=104. Normally, I would use __malloc_hook in a single-threaded app, but these glibc hooks don't work when compiled with address sanitizer.

I've noticed that malloc_usable_size() behaves differently in the presence of Asan. With it the function returns the exact size that was passed to malloc(). Without Asan the function returns a value rounded up to 16 or something like that.

Will malloc_usable_size() always be precise when Asan is used?

**Comment by eugenis** [comment]
Try __sanitizer_malloc_hook, it should report original, user-requested size.

Sanitizer allocator uses size classes. It will allocate slightly more
memory than requested in most cases, and will correctly reflect this
overallocation in malloc_usable_size().

**Comment by basinilya** [comment]
This worked. Thanks a lot.
