### ISSUE TITLE
Is that sdllvm project can enable ASAN?

### ISSUE THREAD

**Issue by TyphoonWu** [google/sanitizers#983]
Some targets cannot be built with ASAN:
Statically linked executables.
LOCAL_CLANG:=false.
LOCAL_SANITIZE:=false

Does the make file with  flag of 'LOCAL_SDCLANG := false' can build with ASAN?

**Comment by kcc** [comment]
(sounds like something android-specific)

**Comment by TyphoonWu** [comment]
Yes, For android platform.

**Comment by TyphoonWu** [comment]
Thanks @eugenis we'll try it.
