### ISSUE TITLE
Leak sanitizer null pointer on start

### ISSUE THREAD

**Issue by artyomd** [google/sanitizers#986]
libclang_rt.asan-aarch64-android.so is crashing with null pointer when enabling leak detection

```sh 
#!/system/bin/sh
HERE="$(cd "$(dirname "$0")" && pwd)"
export ASAN_OPTIONS=log_to_syslog=false,allow_user_segv_handler=1,detect_leaks=1
export LD_PRELOAD=$HERE/libclang_rt.asan-aarch64-android.so
"$@"
```

Build fingerprint: 'google/angler/angler:8.1.0/OPM6.171019.030.E1/4805388:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 20120, tid: 20120, name: app_process64  >>> /system/bin/app_process64 <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    Cause: null pointer dereference
        x0   000000793c1f34b8  x1   0000000000000000  x2   00000055761c07f4  x3   0000000000000000
        x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
        x8   000000793eee2000  x9   0000007ff6f23a80  x10  0000007ff6f23a90  x11  0000000000000001
        x12  0000000000000000  x13  000000793e18c2dc  x14  000000000000001b  x15  0000000000000002
        x16  000000793c1ee4e0  x17  000000793e1d0038  x18  000000793eee21f8  x19  00000055761c4678
        x20  00000055761c07f4  x21  0000007ff6f23a88  x22  000000793fca8a40  x23  00000055761c4670
        x24  000000793eee21b0  x25  000000793eee21e4  x26  000000793eee21d8  x27  000000793eee21d0
        x28  000000793eee21c8  x29  0000007ff6f23a70  x30  000000793c1b4ee8
        sp   0000007ff6f23a40  pc   0000000000000000  pstate 0000000000000000
07-29 17:26:54.346 20127-20127/? A/DEBUG: backtrace:
        #00 pc 0000000000000000  <unknown>
        #01 pc 00000000000b8ee4  /system/lib64/libc++.so (std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))+40)
        #02 pc 0000000000003330  /system/bin/app_process64 (sigprocmask+100)
        #03 pc 000000000001d6e8  /system/lib64/libc.so (abort+76)
        #04 pc 0000000000033690  /data/app/com.example.artyomd.myapplication-HDYP3iVznde9f5l4UVLAIA==/lib/arm64/libclang_rt.asan-aarch64-android.so
        #05 pc 0000000000031250  /data/app/com.example.artyomd.myapplication-HDYP3iVznde9f5l4UVLAIA==/lib/arm64/libclang_rt.asan-aarch64-android.so
        #06 pc 000000000004ad6c  /data/app/com.example.artyomd.myapplication-HDYP3iVznde9f5l4UVLAIA==/lib/arm64/libclang_rt.asan-aarch64-android.so
        #07 pc 00000000000a3f28  /data/app/com.example.artyomd.myapplication-HDYP3iVznde9f5l4UVLAIA==/lib/arm64/libclang_rt.asan-aarch64-android.so
        #08 pc 0000000000070074  /data/app/com.example.artyomd.myapplication-HDYP3iVznde9f5l4UVLAIA==/lib/arm64/libclang_rt.asan-aarch64-android.so (pthread_mutex_lock+60)
        #09 pc 0000000000096280  /system/lib64/libc.so (jemalloc_constructor+116)
        #10 pc 000000000002087c  /system/bin/linker64 (__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_mbS5_+280)
        #11 pc 0000000000020aa8  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+396)
        #12 pc 00000000000209a0  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
        #13 pc 00000000000209a0  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
        #14 pc 000000000001c994  /system/bin/linker64 (__dl___linker_init+3188)
        #15 pc 0000000000023064  /system/bin/linker64 (_start+4)

**Comment by kcc** [comment]
I don't think we support lsan on android. @eugenis ?

**Comment by eugenis** [comment]
We don't. That could be the reason for the crash. Does it print anything to logcat before crashing?

**Comment by artyomd** [comment]
I saw the log that says that leak sanitizer is not supported. I am closing this issue
