### ISSUE TITLE
is it possible to completely disable asan at execution?

### ISSUE THREAD

**Issue by matthieu-nesme** [google/sanitizers#988]
Hi,  
on the same build, I'd like to run some executables w/ asan enabled and some other executables w/ asan disabled.  
Typically, the first ones are simple low level tests while the last ones are complex applications way too slow to be executed with asan on a regular basis.

Is it possible to completely turn off asan? Maybe a magical option in ASAN_OPTIONS? Or even a full set of options?

I cannot find anything on the doc. Thanks.

**Comment by kcc** [comment]
No, this is not possible with asan. 
You want a hardware-assisted tool like [memory tagging](https://arxiv.org/pdf/1802.09517.pdf), which doesn't exist yet except for SPARC.

**Comment by matthieu-nesme** [comment]
Thanks for you answer, it is clear!

Just to be sure, I was not meaning deactivating asan during the execution. Simply running an executable compiled with the asan options w/o performing the runtime tests.

**Comment by eugenis** [comment]
Right. ASan checks are spread throughout the code, there is no way to disable them after compilation.
