### ISSUE TITLE
android ASAN can not detect the memory leck

### ISSUE THREAD

**Issue by haolongzhangm** [google/sanitizers#991]
1: from the google site: https://source.android.com/devices/tech/debug/asan
android already support ASAN

2:same test code linux-x64 ASAN can success find the  memory leak,
but android ASAN can not find the memory leak

env:
host:ubuntu 16.04
android : ndk 16b create toolchain by command: make-standalone-toolchain.sh in NDK/build/tools

build.sh: build command
echo "test pc side============================================"
clang++ -fsanitize=address -O0 -fno-omit-frame-pointer -g main.cc
./a.out

echo "test android side======================================"
aarch64-linux-android-clang++ -fsanitize=address -O0 -fno-omit-frame-pointer -g -pie -fPIE main.cc
adb push a.out /system/bin/
adb shell a.out

test code:
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

class t
{
public:
t(){
char * k = (char )malloc(1024);
memset(k, 5, 1024);
k[100] = 0;
printf("%s:%d,%p\n", func, LINE, k);
};
~t(){
printf("%s:%d\n", func, LINE);
};
};
int main(int argc, char* argv) {
//int* a = new int[10];
for(int i = 0; i < 2; i++) {
t *m = new t();
delete m;
}

//int a[6];
//a[10] = 0;
//a[6] = 0;
//if (a[argc])
// printf("xx\n");
return 0;
}

test result:
test pc side============================================
t:13,0x61900000b480
~t:16
t:13,0x61900000aa80
~t:16

=================================================================
==7562==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2048 byte(s) in 2 object(s) allocated from:
#0 0x4b8bf8 in __interceptor_malloc (/home/zhl/shell_my/unexeshell/try_code/test_asan/a.out+0x4b8bf8)
#1 0x4ed08a in t::() /home/zhl/shell_my/unexeshell/try_code/test_asan/main.cc:10:26
#2 0x4ecf88 in main /home/zhl/shell_my/unexeshell/try_code/test_asan/main.cc:22:16
#3 0x7f185e12d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 2 allocation(s).
test android side======================================
1978 KB/s (479304 bytes in 0.236s)
WARNING: linker: a.out: unused DT entry: type 0xf arg 0x2e7
WARNING: linker: a.out: unsupported flags DT_FLAGS_1=0x8000000
t:13,0x4300000080
~t:16
t:13,0x4300000c80
~t:16

**Comment by haolongzhangm** [comment]
from the test result:
we can find linux-asan can find the class t do not release memory,which new by:
char * k = (char )malloc(1024);
memset(k, 5, 1024);

but android test result do not find this memory leak

**Comment by kcc** [comment]
I don't understand how is this a new issue. 
This is still about leak detection and in #990 I already explained that lsan is not supported.

**Comment by haolongzhangm** [comment]
OK , understand.
any plan to support this featrue,? same linux-asan aleady support this.

**Comment by kcc** [comment]
We've wanted to support lsan for android for a long time, just don't have enough hangs... :(
https://github.com/google/sanitizers/issues/379
