### ISSUE TITLE
Modify asan shadow offset doesn't works

### ISSUE THREAD

**Issue by BoringKen** [google/sanitizers#998]
Hi, I have used the sanitizers in my application on a x86_64 machine.

Because I mmap the address from 0x0000400 00000 ~ 0x0000A00 00000 in my C code, so I modified the shadow offset in asan_mapping.h 0x00007fff8000 to 0x80000 00000 to avoid shadow region. It works fine when I look the maps file in /proc dir, the LowShadow 、 ShadowGap andHighShadow all are above 0x80000 00000.

But when I accessed a pointer at 0x0000A00 00000, the sanitizers reports SEGV at address 0x000093FF8000.
Obviously 0x000093FF8000 = 0x0000A0000000/8 + 0x00007fff8000. But I have modified the shadow offset from 0x00007fff8000 to 0x80000 00000, why it's still 0x00007fff8000 when calculating the shadow region.

I can't figure out the reason, can you help me ? Thanks a lot.

**Comment by eugenis** [comment]
Did you change the offset in the compiler, too? There is a flag for that,
-mllvm -asan-mapping-offset.

**Comment by BoringKen** [comment]
Thanks a lot. But the '-mllvm -asan-mapping-offset' option is only used for 'kernel-address'. If we want to modify the asan shadow offset, we should modify the asan_mapping.h and the arch file(such as i386/i386.c in src dir). Thank you all the same. :-)
